### ISSUE TITLE
[Question] Tabline config question.

### ISSUE THREAD

**Issue by khalidchawtany** [itchyny/lightline.vim#100]
Hi,

How can I have a vim-airline like tabline that displays the buffers of the current tab. Is it possible to have such a tabline. If so, could you provide a sample vimscript to accomplish this. I know that I am asking a lot. However, I suck at vimscript and I tried but couldn't succeed :disappointed: 

Thanks :smiley:

**Comment by itchyny** [comment]
I'm sorry but you cannot do that with lightline. The `tabline` is a place where the tabs are displayed. Tabs can be switched by gt and gT. Displaying buffers in *tab*line is not a intended usage. Sorry.
