### ISSUE TITLE
Customizing lightline tab name by vim filetype

### ISSUE THREAD

**Issue by atweiden** [itchyny/lightline.vim#101]
I am trying to name Vimfiler tabs 'FV' instead of '[No Name]', and thought copying the `lightline#tab#filename` function into `MyTabname` would be a good place to start:

```vim
function! lightline#tab#filename(n) abort
  let buflist = tabpagebuflist(a:n)
  let winnr = tabpagewinnr(a:n)
  let _ = expand('#'.buflist[winnr - 1].':t')
  return strlen(_) ? _ : '[No Name]'
endfunction
```

```vim
function! MyTabname(n) abort
  let buflist = tabpagebuflist(a:n)
  let winnr = tabpagewinnr(a:n)
  let _ = expand('#'.buflist[winnr - 1].':t')
  if &ft == 'vimfiler'
    return 'FV'
  else
    return strlen(_) ? _ : '[No Name]'
  endif
endfunction
```

This is how I am using it (the `MyTabname` function):

```vim
let g:lightline.tab = {
      \ 'active': [ 'tabnum', 'mytabname', 'modified' ],
      \ 'inactive': [ 'tabnum', 'mytabname', 'modified' ] }

let g:lightline.tab_component_function = {
      \ 'mytabname': 'MyTabname',
      \ 'modified': 'lightline#tab#modified',
      \ 'readonly': 'lightline#tab#readonly',
      \ 'tabnum': 'lightline#tab#tabnum'
      \ }
```

It works, almost. When I switch to the Vimfiler tab, all tabs are renamed 'FV': https://i.imgur.com/avxztvE.png

When I switch back, I get this: https://i.imgur.com/0zLfbSU.png

Help would be much appreciated.

**Comment by itchyny** [comment]
How about using `gettabwinvar(a:n, winnr, '&ft')` instead of `&ft`?

**Comment by atweiden** [comment]
That did the trick. [Tyvm](https://github.com/atweiden/dotfiles/commit/d6073d96ded485d02a66594745809e37cd27c9a2)

https://i.imgur.com/uhHc68p.png
