### ISSUE TITLE
MacVim display issue when reloading .vimrc

### ISSUE THREAD

**Issue by PhilG** [itchyny/lightline.vim#102]
Hi,
I'm getting this issue on MacVim which should be resolved by using `set t_Co=256` . This only happens when I source the vimrc automatically after changing it. Normally starting MacVim displays lightline correctly!

Any ideas why this is happening or what I should investigate?

**Comment by itchyny** [comment]
Would you please paste your vimrc here?

**Comment by PhilG** [comment]
Sure thing! I also noticed this only happens when reloading the `.vimrc` via autocmd. If I `:source $MYVIMRC` by hand in commandmode everything is fine.

```vim
set nocompatible

" General
set number
set linebreak
set showbreak=+++
set textwidth=100
set showmatch
set visualbell
 
set hlsearch
set smartcase
set ignorecase
set incsearch
 
set autoindent
set shiftwidth=4
set smartindent
set smarttab
set softtabstop=4
 
" Advanced
set ruler
 
set undolevels=1000
set backspace=indent,eol,start
 
 
" Generated by VimConfig.com

syntax on

filetype plugin indent on

call plug#begin('~/.vim/plugged')

Plug 'itchyny/lightline.vim'
Plug 'tomasr/molokai'

call plug#end()

set encoding=utf-8
scriptencoding utf-8
set laststatus=2

let g:molokai_original = 1 
colorscheme molokai

augroup reload_vimrc " {
    autocmd!
    autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup END " }

let g:lightline = {
      \ 'component': {
      \   'readonly': '%{&readonly?"x":""}',
      \ },
      \ 'separator': { 'left': '', 'right': '' },
      \ 'subseparator': { 'left': '|', 'right': '|' }
      \ }

set guioptions-=T
set guioptions-=r
```

**Comment by itchyny** [comment]
What happens when you move the two commands `syntax on` and `filetype plugin indent on` after the end of your vimrc?

**Comment by PhilG** [comment]
Issue persists.

I can switch between it breaking and displaying correctly by saving my `vimrc` (it breaks) and then executing `:source $MYVIMRC` (changes to showing up fine) indefinitely..

**Comment by Shougo** [comment]
You should use `syntax enable` instead of `syntax on`.
`syntax on` resets current highlight config.

**Comment by PhilG** [comment]
Thank you!

So this looks to be an issue with `autocmd` since it's independent from how I source (using $MYVIMRC or "%").

**Comment by Shougo** [comment]
This problem is solved?  I think it is not lightline issue.

**Comment by PhilG** [comment]
It was not solved by changing to `syntax enable` but it is indeed not a lighten issue! I did some more digging around and found that Powerline kind of has the same issue just much more apparent on Stackoverflow.

You should always be using the `nested` flag for `autocmd` when sourcing your vimrc file! Using:

```vim
augroup reload_vimrc " {
    autocmd!
    autocmd BufWritePost $MYVIMRC nested source $MYVIMRC
augroup END " }
```

fixed this.

**Comment by Shougo** [comment]
Oh, I get it.

**Comment by itchyny** [comment]
Hmm looks weird but that would be the solution.
