### ISSUE TITLE
Problem with switching background in Solarized

### ISSUE THREAD

**Issue by HiPhish** [itchyny/lightline.vim#104]
Hi,

I'm using the Solarized theme and I occasionally switch the background from dark to light depending on the lighting in the room (`:set background=dark`). The problem is that if Lightline has been started with a light background it will keep that theme even after I flip the theme in Vim. Here is a comparison:

![Lightline](http://i60.tinypic.com/2e367g6.png)
![Airline](http://i62.tinypic.com/dde5h0.png)

The top one is Lightline, as you can see the surrounding colours are dark, but the line is still light. The bottom one is from Airline, the colours were all set properly.

Furthermore, I have set up Vim to set the background to dark automatically if the window is opened between 9PM and 8AM, and the theme settings are after the Lightline setting, so at night my settings are all messed up.

Is there a way to change the theme after Lightline has been started? Then I could override the default settings for the time being.

**Comment by itchyny** [comment]
As you know, the solarized theme of lightline does not update once it is loaded. There are `solarized_light` and `solarized_dark` themes in lightline and the `solarized` theme uses them based on the value of `&background`. Therefore, when you switch the theme after the startup of Vim, you have to call some functions.
```vim
" Firstly set the new colorscheme
let g:lightline.colorscheme = 'solarized_light' " or 'solarized_dark'

" Secondly tell the lightline to load the settings of `g:lightline`
call lightline#init()

" Thirdly generate the colors based on the value of g:lightline.colorscheme
call lightline#colorscheme()

" Lastly update all the statusline of the windows
call lightline#update()
```
If you want to make this work automatically on setting the option `&background`, refer to the example in the reference `:h lightline-problem-13`. Hope it help you.

**Comment by HiPhish** [comment]
Thanks, the manual steps do it, I'll take a look at the automatic steps later.
