### ISSUE TITLE
Arrow not alligned

### ISSUE THREAD

**Issue by shinokada** [itchyny/lightline.vim#106]
![image](https://cloud.githubusercontent.com/assets/147320/8146549/5816e2ae-127a-11e5-8126-9427655dbb2b.png)

As you can see in the above image, top part of arrow is off a bit. How can I fix this?

I use iTerm2 on OSX Yosemite with Solarized Dark, 18pt Inconsolata for Powerline for Regular and Non-ASCII font.

**Comment by itchyny** [comment]
How about setting `:set linespace=0`.

**Comment by shinokada** [comment]
Thank you for your reply but it doesn't change anything.

**Comment by itchyny** [comment]
Please use fontpatcher to create the font at hand. It will solve the problem. https://github.com/Lokaltog/vim-powerline/tree/develop/fontpatcher

**Comment by shinokada** [comment]
I have done it when I installed it.

**Comment by itchyny** [comment]
How about decreasing the size of Non-ASCII Font?

**Comment by shinokada** [comment]
That worked. I set it to 16pt. Thanks.
