### ISSUE TITLE
Gappless separators, no padding

### ISSUE THREAD

**Issue by noscript** [itchyny/lightline.vim#107]
I tried to remove separators but I still get two space characters inserted between tokens, and also there are padding spaces on left and right token sides. Lot of precious status line real estate gets wasted.

Would be great to be able to decide myself when to use space separators and / or padding:
```
let g:lightline.active.left = { [  'bufnum' , ' ', 'filename'  ] }
```

![line](https://cloud.githubusercontent.com/assets/717109/8305114/7de7122e-19b4-11e5-9427-55abc0e9e6da.png)

**Comment by itchyny** [comment]
I don't understand what you are saying... you want to insert? or remove? spaces... The right hand side of the screenshots are not preferable for you?

**Comment by noscript** [comment]
I want to remove spaces, the right side of the screenshot is the desired outlook.

**Comment by itchyny** [comment]
You can specify the component_type to raw
```vim
  'component_type': { 'bufnum': 'raw', 'filename': 'raw' }
```
But I found a bug with the logic, so pull the repository.

**Comment by noscript** [comment]
It works somehow strange. If I set empty separators, the gap disappears:

![1](https://cloud.githubusercontent.com/assets/717109/8307644/5312e604-19c8-11e5-8fc1-d7d41128275a.png)

Then I define my own separator and set it to raw:
```vimL
let g:lightline.component = { 'sep': ' '}
let g:lightline.component_type = { 'bufnum': 'raw', 'filename' : 'raw', 'sep' : 'raw' }
let g:lightline.active = { 'left': [ ['bufnum' , 'sep', 'filename'] ] }
```
but I get 3 spaces instead:
![2](https://cloud.githubusercontent.com/assets/717109/8307660/7c49b82c-19c8-11e5-9362-11a712643834.png)

**Comment by itchyny** [comment]
How about adding a space in the bufnum component? (g:lightline.component.bufnum = '%n ')

**Comment by noscript** [comment]
> How about adding a space in the bufnum component?

That works.

Also, I managed to get my separators working:
```
let g:lightline.component = { 'sep': '%{" "}'}
```
