### ISSUE TITLE
Truncate & collapse control

### ISSUE THREAD

**Issue by noscript** [itchyny/lightline.vim#108]
Vim status line supports `%<` token to control where to truncate if there is not enough space. I didn't find how to do that in lightline. The problem is that all items on the left side become obscured or completely hidden:

![line2](https://cloud.githubusercontent.com/assets/717109/8305320/84ae3d42-19b6-11e5-866e-1fc1ef1c0d78.png)

Would be great to be able to choose which components to truncate (e.g. file name only and not the entire left side) or collapse.

**Comment by itchyny** [comment]
Try using component_function. See the example at https://github.com/itchyny/lightline.vim#my-settings.

**Comment by noscript** [comment]
Thanks, I guess it will do. And I managed to get `%<` token working:
```
let g:lightline.component = { 'fname': '%<%f'}
```
