### ISSUE TITLE
Minimal text for status mode

### ISSUE THREAD

**Issue by krzkrzkrz** [itchyny/lightline.vim#113]
Would be nice if there was a way to shorten the status mode text. 

i.e. `Insert` would just be `I`, `Visual` would b `V`, `Normal` mode would be `N`. Which also allows a bit of extra residential space. (Especially handy when several buffers are opened).

**Comment by itchyny** [comment]
You can use the following configuration.
```vim
let g:lightline.mode_map = {
		\ 'n' : 'N',
		\ 'i' : 'I',
		\ 'R' : 'R',
		\ 'v' : 'V',
		\ 'V' : 'V',
		\ "\<C-v>": 'V',
		\ 's' : 'S',
		\ 'S' : 'S',
		\ "\<C-s>": 'S'
		\ }
```

**Comment by krzkrzkrz** [comment]
Ok works with:

```
let g:lightline = {
\ 'mode_map': {
\   'n' : 'N',
\   'i' : 'I',
\   'R' : 'R',
\   'v' : 'V',
\   'V' : 'V',
\   "\<C-v>": 'V',
\   's' : 'S',
\   'S' : 'S',
\   "\<C-s>": 'S'
\   }
\ }
```

Thanks
