### ISSUE TITLE
Possible to color Vimfiler?

### ISSUE THREAD

**Issue by krzkrzkrz** [itchyny/lightline.vim#114]
ctrlP has some nice colors:

     NORMAL  ControlP | - 

Possible for the same effect to be applied on https://github.com/Shougo/vimfiler.vim ?

**Comment by itchyny** [comment]
```vim
let g:vimfiler_force_overwrite_statusline = 0
```

**Comment by krzkrzkrz** [comment]
Thanks, this works!
