### ISSUE TITLE
Re-initializing colorscheme when switching background 'light' and 'dark'

### ISSUE THREAD

**Issue by sdothum** [itchyny/lightline.vim#116]
Is there a way to get lightline to reflect the current colorscheme when the background is switched between 'light' and 'dark'.

If I switch the background (light/dark) for solarized, lightline retains the initial colorscheme background colors. 

lightline#init, #colorscheme, #enable etc do not seem to have any affect.

**Comment by itchyny** [comment]
`:h lightline-problem-13`

**Comment by sdothum** [comment]
My fault.. didn't see problem report #104. The outlined procedure works perfectly.

Thanks for lightline! It rocks!
