### ISSUE TITLE
Remove any text information on the right side of the statusline

### ISSUE THREAD

**Issue by krzkrzkrz** [itchyny/lightline.vim#118]
In `.vimrc`, I have:

    let g:lightline = {
    \   'component_function': {
    \     'fileencoding': 'asdf',
    \     'fileformat': 'asdf',
    \     'filetype': 'asdf',
    \     'percent': 'asdf',
    \     'lineinfo': 'asdf'
    \   }
    \ }

Which seems to do the trick. Instead of `asdf`, I tried giving it a value of `''`. But it returned with an error:

    E129: Function name required
    Press ENTER or type command to continue

Am I doing this correctly?

**Comment by itchyny** [comment]
```vim
let g:lightline.active = {
		\ 'right': []
		\ }
let g:lightline.inactive = {
		\ 'right': []
		\ }
```

**Comment by krzkrzkrz** [comment]
Awesome! Thanks
