### ISSUE TITLE
Display directories as a single character

### ISSUE THREAD

**Issue by krzkrzkrz** [itchyny/lightline.vim#119]
@itchyny I'm not sure if you've done this before. Currently I have the following which shows the relative path just fine. In `.vimrc`:

    let g:lightline = {
    \   'component_function': {
    \     'filename': 'RelativePathToFilename'
    \   }
    \ }

    function! RelativePathToFilename()
      " %{pathshorten(fnamemodify(expand('%'),':~:.'))}
      " set stl+=%{substitute(fnamemodify(expand('%'),':~:.'),'\\([^/\\\\]\\)[^/\\\\]*[/\\\\]','\\1\\2/','g')}
      return expand('%')
    endfunction

Returns:

    app/pods/components/foo-bar/component.js

However, I'd like to make this even shorter, by representing each directory with a single character. So above would instead return:

    a/p/c/f-b/component.js

Note `f-b` because `foo-bar` is dasherized. Ideally, the same would apply for underscored directories. So `foo_bar`, would turn into `f_b`.

**Comment by itchyny** [comment]
What is the problem of `pathshorten(fnamemodify(expand('%'),':~:.'))`? I don't sure why you don't use it.

**Comment by krzkrzkrz** [comment]
Yea `return pathshorten(fnamemodify(expand('%'), ":."))` works
