### ISSUE TITLE
lightline#highlight()

### ISSUE THREAD

**Issue by pswit** [itchyny/lightline.vim#122]
I love your plugin. There's one issue though.

When I do :split ~/.vimrc, the status line goes black and white. Re-running lightline#highlight() fixes this. And it seems to happen only when I split and load .vimrc. 

So, for some reason this auto command doesn't fire when I split:

autocmd ColorScheme,SessionLoadPost *  call lightline#highlight()

Any idea why?

Thanks so much,
   Sergei

**Comment by itchyny** [comment]
I cannot reproduce the bug you report. Please paste the minimal vimrc to reproduce the bug.

```vim
set nocompatible
filetype off
set rtp+=/path/to/lightline
set laststatus=2
filetype plugin on
syntax enable
```
1. Open Vim with `vim -u /path/to/the/above/vimrc`.
2. `:split /path/to/the/above/vimrc` does work well with lightline.

**Comment by pswit** [comment]
Thanks for a quick reply.

Indeed when I minimize my config like that, it works.

I noticed that when I remove the :colo command in my .vimrc, it starts working too.

Not sure how to debug this. Any ideas?

**Comment by itchyny** [comment]
Can you provide a minimal vimrc like the above with one line `:colorscheme default` inserted somewhere? Or does it depend on the colorscheme; wombat or solarized or... what colorscheme do you use?

**Comment by pswit** [comment]
I use solarized. 

Here’s the minimum .vimrc when it stops working (after i do :split .vimrc)

 Globals {{{
let g:lightline = { 'colorscheme': 'solarized' }
" }}}
set laststatus=2
syntax on
colo Pablo
filetype on
filetype plugin on

Commenting "filetype plugin” out fixes it…

In my local ftpplugin folder I have this for “vim.vim”:

set keywordprg=:help
syntax on
set foldmethod=marker

And after I comment out syntax on, it works as well :)

Not sure what’s going on.

Thanks so much for responding so quickly!!

**Comment by itchyny** [comment]
I've been using vim for years but I've never seen `syntax on` in ftplugin files. It causes the bug and probably it shouldn't be there. You've already have enabled `syntax on` in your vimrc right? What's the purpose of setting syntax on in a ftplugin file?

**Comment by pswit** [comment]
Because for some reason when I edit vim script files, the syntax doesn’t turn on without that setting. I don’t have syntax on in my .vimrc

**Comment by itchyny** [comment]
Why don't you write `syntax on` in your vimrc? I don't understand...

**Comment by pswit** [comment]
I didn’t know I could have. Now I do. I didn’t have it all this time and syntax highlighting was never a problem :) But I’ve put it in. The problem seems to be solved.

Thanks again

**Comment by itchyny** [comment]
Fine.

**Comment by pswit** [comment]
There’s only question I have.

I love the themes. But I would like to highlight PASTE in a special way. What’s the best way to do it?

**Comment by itchyny** [comment]
Unfortunately, that's not that easy.
```vim

let g:lightline = {
      \ 'component_expand': {
      \   'paste': 'LightLinePaste'
      \ },
      \ 'component_type': {
      \   'paste': 'warning'
      \ }
      \ }

function! LightLinePaste()
  return &paste ? "PASTE" : ""
endfunction
```
With this configuration, the paste component is not updated instantly after `set paste`. There's no clean way but to call lightline#update after setting paste; `set paste | call lightline#update()`.

**Comment by pswit** [comment]
Cool, but I meant I would like to keep a theme (like ’Tomorrow_Night_Blue’) and change the color/background of the word ‘PASTE’ in the status line. I could make a copy of an existing colorscheme and change that there (?) or is there a better way?

**Comment by itchyny** [comment]
Please create a new colorscheme of lightline.

**Comment by pswit** [comment]
Cool, I will.

Do you know why setting g:lightline while vim is running is not taking effect immediately?

**Comment by itchyny** [comment]
That's by design. The function `lightline#init()` should be called to affect the value of `g:lightline`.

**Comment by pswit** [comment]
Good deal. Thanks!

**Comment by pswit** [comment]
I’m a little confused how to control the colors.

If I just have this in my .vimrc:

set g:lightline =  { 'colorscheme': 'solarized_darker’ }

Then I can go into solarized_darker and change the colors — and it works.

When however I do this:

let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'active': {
      \   'left': [ [ 'paste' ],
      \             [ 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component': {
      \   'readonly': '%{&filetype=="help"?"":&readonly?"⭤":""}',
      \   'modified': '%{&filetype=="help"?"":&modified?"+":&modifiable?"":"-"}'
      \ }
      \ }


… the colors in the color scheme don’t seem to have an effect.

Can I specify the colors as part of the structure above as well (along with [‘paste’], etc)?

**Comment by itchyny** [comment]
In the second configuration you are using the wombat colorscheme, right?

**Comment by pswit** [comment]
Oh man, how did I not notice that? All good now :)

Thanks!!
