### ISSUE TITLE
Show if unfocused file is saved

### ISSUE THREAD

**Issue by zyedidia** [itchyny/lightline.vim#123]
When I move to another split, the file I move from becomes unfocused and lightline no longer displays whether or not the file is saved by showing the `[+]` or not. I would like to be able to see the save status of all open splits even if they are unfocused.

**Comment by itchyny** [comment]
Please see the reference `h g:lightline.inactive`.
```vim
let g:lightline = {
      \ 'inactive': {
      \   'left': [ [ 'filename', 'modified' ] ],
      \   'right': [ [ 'lineinfo' ], [ 'percent' ] ]
      \ }
      \ }
```

**Comment by zyedidia** [comment]
Thank you very much.
