### ISSUE TITLE
List of buffers on top like with airline?

### ISSUE THREAD

**Issue by codingrogue** [itchyny/lightline.vim#125]
Hey guys,

first of all thanks for the great plugin! I was wondering if I can config a second bar on the top for all my open buffers like the tabline in airline?

![Airline](https://camo.githubusercontent.com/ba79534309330accd776a8d2a0712f7c4037d7f9/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3330363530322f313037323632332f34346332393261302d313439352d313165332d396365362d6463616461336631633533362e676966)

**Comment by itchyny** [comment]
Sorry but I will not support that feature in lightline.

**Comment by itchyny** [comment]
Please use https://github.com/mengelbrecht/lightline-bufferline for example. IMO the tabline is a place where tabs are displayed so I don't want to include the feature in this plugin. Also, lightline is extensible enough that users can display anything you want (buffer list is just one of them and the lightline-bufferline plugin proves it), and implementing everything users want is against the spirit of this plugin.
