### ISSUE TITLE
Colorscheme does not work with NeoVim in certain environments

### ISSUE THREAD

**Issue by xeno1991** [itchyny/lightline.vim#126]
# Problem

Colorscheme does not work with NeoVim in certain environments. It turns black as shown in the picture below.

![](https://i.gyazo.com/c5f31c9f979fe12b12171f878c1fc070.png)

# Envirionments

I tested some environments. In every case, [the latest commit:
5a195858657e1c494e77ea868073d2f3664cdb60](https://github.com/neovim/neovim/commit/5a195858657e1c494e77ea868073d2f3664cdb60) was cloned and compiled by myself.

Tested .nvimrc is [here](https://gist.github.com/xeno1991/7e5047db42825b1166d7)

| Envirionment             | on terminal | on tmux |
|--------------------------|-------------|---------|
| Max OS X 10.10.4         | o           | x       |
| ArchLinux                | o           | o       |
| Ubuntu 14.04 (on Docker) | x           | x       |
o: colored, x: black

**Comment by itchyny** [comment]
Close due to inactivity.

**Comment by dncnmcdougall** [comment]
I have also found this to be a problem. It makes using neovim or lightline mutually exclusive, and both are great.

**Comment by h-michael** [comment]
+1

**Comment by itchyny** [comment]
I tested on tmux 0.1.4, Mac OS X 10.11.5, the latest version of lightline with the following vimrc but all things seem to be working well. If you have problem on this, please describe your environment and configuration precisely so that I can reproduce the same environment.
```vim
set nocompatible
filetype off
set rtp+=~/path/to/lightline
let g:lightline = {}
set laststatus=2
filetype plugin indent on
syntax enable
```

**Comment by tannerli** [comment]
Sorry to reopen old issues:
On Ubuntu 17.04, using tmux 2.3, vim 8.0, and latest lightline, i have the same coloring issues:
Works well outside tmux
No colors inside tmux

My complete .vimrc:
```
execute pathogen#infect()

set nocompatible
filetype off
set rtp+=~/.vim/bundle/lightline.vim
let g:lightline = {}
set laststatus=2
filetype plugin indent on
syntax enable
```
lightline is currently the only plugin installed

**Comment by itchyny** [comment]
Please let me know the result of `:echo [&t_Co, $TERM]` in Vim.

**Comment by tannerli** [comment]
There we have the culprit:
Outside tmux:` ['256', 'xterm-256color']`
Inside tmux:` ['8', 'screen']`

Now, vim in  general doesn't seem to mind for syntax highlighting works inside tmux with all colors of the rainbow....

**Comment by itchyny** [comment]
There's a note for `$TERM` and `t_Co` in README.md.

**Comment by tannerli** [comment]
Ah... another case of RTFM. I actually followed the part above with laststatus=2 but then assumed the rest doesn't apply to me b/c its coloring by default... I was guessing in a completely different direction...

Sorry to bother you and thank you for your help

**Comment by itchyny** [comment]
Never mind, good luck.
