### ISSUE TITLE
The arrows in Lightline in Urxvt do not show up...

### ISSUE THREAD

**Issue by fingertap** [itchyny/lightline.vim#127]
I was using airline before I saw this, and I think lightline is more modifiable. However, I am currently using Arch linux with Urxvt terminal, and the arrows in vim just do not show up. It seems that the patched font fails in Urxvt because it works well in gvim (I am using patched Monaco). Is there any solution to this?

**Comment by itchyny** [comment]
Umm, I'm not familiar with Urxvt terminal... Please make sure that the command `:echo "\ue0b0"` in Vim shows the arrow.
