### ISSUE TITLE
How can I make lightline the bottom-most line in the vim window?

### ISSUE THREAD

**Issue by shikhanshu** [itchyny/lightline.vim#128]
First time using any status-line plugin. I have set noshowmode, so I don't see Vim's default mode indicator. But the lightline is still not the bottom-most line. The bottom-most line is reserved for the commands. How can I integrate both and make lightline the very last line? And when I have to type commands, they simply appear in the lightline line?

Is that even possible?

**Comment by itchyny** [comment]
No, that's impossible. There's no option in Vim to make the statusline at the bottom-most line.

**Comment by shikhanshu** [comment]
Thanks! I now know that the last line is "command bar" and it makes sense to reserve that line for it.

Can lightline (or airline for that matter) theme the command bar/line too? That would look neat and consistent with the themed status line.

On that note, can lightline (or airline) theme the wildmenu?

**Comment by itchyny** [comment]
No, the plugins do nothing with the command line.

Sorry but I don't understand your second question...

**Comment by shikhanshu** [comment]
There is a thing called "wildmenu" in Vim (set wildmenu). When typing any
command, filename etc. it lists the possible values in the form of a menu
just above the status line.

Can the plugins theme this line? It is an in-built vim feature (as far as I
know) and not a separate plugin.


Thanks,
Shikhanshu

**Comment by itchyny** [comment]
The answer is no. The colours of the candidates is not configurable and any plugin is not allowed to style the part.

**Comment by shikhanshu** [comment]
Alright, thanks for entertaining my questions! And great job on lightline!
Amazing and I will use it forever.


Thanks,
Shikhanshu

**Comment by strboul** [comment]
My comment will revive the old issue but this should now be possible with the floating window functionality in neovim, have a look floating window statusline at https://github.com/windwp/windline.nvim
