### ISSUE TITLE
Visibility of empty components

### ISSUE THREAD

**Issue by tbastos** [itchyny/lightline.vim#130]
The documentation suggests that if a `component_function` returns an empty string, the component is collapsed and there's no need to define a `component_visible_condition`, right? This sounds great.

However, I can still "see" these empty components because their separators are still added. Shouldn't the separators be omitted if the `component_function` returns empty? Otherwise it looks very ugly. And it's a lot of trouble to define `component_visible_condition` in addition to each `component_function`.

Thanks for the help!

**Comment by itchyny** [comment]
I don't understand what you mean by `separators are still added`. For example, with the following configuration, the hello component disappears when the filetype is vim.
```vim
let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ], [ 'filename', 'hello', 'filename' ] ],
      \ },
      \ 'component_function': {
      \   'hello': 'Hello',
      \ }
      \ }
function! Hello()
  return &ft ==# 'vim' ? '' : 'Hello'
endfunction
```
The statusline will looks like this: with vimrc (ft=vim)
![screenshot 2015-11-01 20 53 39](https://cloud.githubusercontent.com/assets/375258/10868727/ae187536-80da-11e5-96c9-de3565e43ba3.png)
and with zshrc
![screenshot 2015-11-01 20 53 48](https://cloud.githubusercontent.com/assets/375258/10868737/c3031e74-80da-11e5-8e9e-7e275000d72e.png)
They both look fine.

**Comment by tbastos** [comment]
I'm getting a different result. For example, I use VimFiler and want to remove the right-side components (ft, percent, line info, etc.). I do this by returning `''` if `&ft == 'vimfiler'`. And this is what I get:

<img width="257" alt="lightline" src="https://cloud.githubusercontent.com/assets/150480/10869105/013514ae-80a4-11e5-94cd-d4fdaabe9268.png">

You can clearly see the empty components with separators on the right. Am I missing something obvious? The code is here: https://github.com/tbastos/dotfiles/blob/master/vim/lightline.vim#L70

Thanks again!

**Comment by itchyny** [comment]
Unfortunately, hiding that part in lightline is technically impossible. The sub-separators can be controlled by lightline but it's too difficult to hide the whole component group including the separators.

By the way, there are three colours at most so if you use the following config, the inner most separator on the right hand side of your screenshot will disappear.
```
  \     'right': [ ['syntastic', 'cursor'], ['percent'], ['fugitive', 'filetype'] ]
```

**Comment by tbastos** [comment]
Ah ok, that wasn't clear to me. Indeed I tried to debug the code but it's too complex. Vim's statusline internals aren't pretty... Thanks anyway!

**Comment by jordwalke** [comment]
This is really unfortunate. There is no way to remove the ugly triangles?
