### ISSUE TITLE
solarized dark not display same as vim color

### ISSUE THREAD

**Issue by tthanh** [itchyny/lightline.vim#131]
My config
set background=dark       " enable for dark terminals
let g:solarized_termcolors=16
set t_Co=16
:silent! color solarized

gnome-terminal
xterm-256color
![screenshot from 2015-11-02 20-01-34](https://cloud.githubusercontent.com/assets/8962973/10882368/bdbe407a-819c-11e5-8bc5-d4c72f65b3d9.png)

**Comment by itchyny** [comment]
How about using `16color` theme? (g:lightline.colorscheme = '16color')

**Comment by tthanh** [comment]
I use your line but E121: Undefined variable: g:lightline
I change solarized to 16color in my array config but still same

**Comment by itchyny** [comment]
Your screenshot looks like the default theme, not the solarized. Could you please share the whole config?

**Comment by tthanh** [comment]
Here is my old vimrc: https://github.com/tthanh/dotfiles/blob/master/vim/vimrc 
It only different with current is lightline config line, everything else same.

**Comment by itchyny** [comment]
Can you paste the lightline config here? Where did you added in your vimrc?

**Comment by tthanh** [comment]
I added it under Plug 'itchyny/lightline'
" lightline
let g:lightline = {
            \'colorcheme': 'solarized',
            \ }

**Comment by itchyny** [comment]
colorscheme, not colorcheme.

**Comment by tthanh** [comment]
OMG my stupid mistake, sorry about wasting your time

**Comment by itchyny** [comment]
Fine.

**Comment by tthanh** [comment]
I have other problem, after start vim, my statusline not 
![screenshot from 2015-11-02 21-02-52](https://cloud.githubusercontent.com/assets/8962973/10883529/2b3594e8-81a5-11e5-8894-668cb73ed1fd.png)
