### ISSUE TITLE
How to install lightline.vim using vim-plug?

### ISSUE THREAD

**Issue by timfayz** [itchyny/lightline.vim#132]
Hello, can I install your plugin using `vim-plug`? I've already tried, but it seems that nothing changed..

**Comment by itchyny** [comment]
1. Add configuration to your vimrc.
```
Plug 'itchyny/lightline.vim
```

2. Restart Vim and install with `:PlugInstall`.

**Comment by timfayz** [comment]
I've already tried this, but `vim-plug` doesn't install it.. Look:

![screenshot from 2015-11-04 11 15 46](https://cloud.githubusercontent.com/assets/6209197/10932891/8ff0b106-82e5-11e5-9b5f-e8c78e4a4726.png)

As you can see at the screen there are only 2 installed plugins (but I have three ones with lightline). Saving `.vimrc` and running `:PlugInstall` nothing changes. It seems vim-plug doesn't see lightline. What's wrong?

**Comment by itchyny** [comment]
Did you restart Vim?

**Comment by timfayz** [comment]
Yes, of course! Whatever I try nothing changes(

**Comment by timfayz** [comment]
Strange, I've already tried this. But after you suggest it explicitly it miraculously has worked!)) Thank you)

**Comment by itchyny** [comment]
Fine.
