### ISSUE TITLE
It's the autocmd CursorMoved necessary?

### ISSUE THREAD

**Issue by adonis0147** [itchyny/lightline.vim#133]
Hi, itchyny. I really love the lightline.vim because of its lightweight and performance (loaded faster than powerline when vim starts up). However, when I use [ctrlp.vim](https://github.com/kien/ctrlp.vim), an issue happens. Here are steps:

1. open a file to edit
2. toggle ctrlp by command
3. lightline update the statusline of the buffer created by ctrlp
4. press `ctrl + c`, it will close the buffer created by ctrlp
5. lightline doesn't update the statusline of the original buffer

I tried to remove the autocmd CursorMoved in `plugin/lightline.vim` and the issue disappeared.

The modified code is 
 autocmd ~~CursorMoved,~~ BufUnload * call lightline#update_once()

Here is the question, it's the autocmd CursorMoved necessary? If so, which case need the autocmd to update the statusline?

**Comment by itchyny** [comment]
Without `CursorMoved`, it fails to overwrite the statusline of ctrlp.
![problem](https://cloud.githubusercontent.com/assets/375258/11049887/fe6d1630-8784-11e5-990a-1bbda1890e73.gif)

With `CursorMoved`, it works well with ctrlp.
![well](https://cloud.githubusercontent.com/assets/375258/11049912/239ea6a8-8785-11e5-9eb4-f9d10541aaa5.gif)

**Comment by adonis0147** [comment]
If you add the settings listed in [readme](https://github.com/itchyny/lightline.vim#for-power-users) to .vimrc, you will find the statusline of ctrlp works fine and the behavior is the same as powerline.

![](http://i.imgsafe.org/430089c.png)

**Comment by itchyny** [comment]
That screenshot does not seem that it works well; the statusline of the above window still looks like active.

**Comment by adonis0147** [comment]
I think it is acceptable, because ctrlp works as a fuzzyfinder and usually the buffer created by ctrlp will be closed in a short time. What's more, the behavior is consistent with powerline as the following screenshot shows.

![](http://i.imgsafe.org/2c403d4.png)

**Comment by itchyny** [comment]
lightline does not know which plugin is a finder and it should deal all the situation consistently.

**Comment by adonis0147** [comment]
It is `let g:ctrlp_match_window_reversed = 0` which causes the issue I described above. You can add this setting to .vimrc and you will find the issue. This setting makes the cursor focus on the top (default: bottom) of the buffer created by ctrlp.

Any ideas to solve it?

**Comment by itchyny** [comment]
I took for minutes to struggle against the problem but probably impossible to solve it. CtrlP uses `noautocmd` on opening and closing the buffer. It makes other plugins impossible to detect one window opened or closed.
