### ISSUE TITLE
combination of `component_expand` and `component_type:raw` does not work

### ISSUE THREAD

**Issue by Milly** [itchyny/lightline.vim#134]
Combination of `component_expand` and `component_type:raw` does not work.

How can I use expand with no-wrapped?

### In this config
```vim
let g:lightline = {
  \ 'active': { 'left': [ ['myex'] ], 'right': [] },
  \ 'component_expand': { 'myex': 'MyFunc' },
  \ 'component_type': { 'myex': 'raw' },
  \ }
function! MyFunc()
  return 'ABC'
endfunction
```

### Be expected
```vim
&statusline == '%{lightline#link()}%#LightLineLeft_active_0#ABC%#LightLineLeft_active_0_1#%#LightLineMiddle_active#%='
```

### But actual
```vim
&statusline == '%{lightline#link()}%#LightLineLeft_active_raw#%( ABC %)%#LightLineLeft_active_raw_1#%#LightLineMiddle_active#%='
```

**Comment by Milly** [comment]
処理順で先に expand されてるので raw 変換する箇所では既に component 名で判別できなくなってるのが原因ですが、仕様なのでしょうか。

**Comment by itchyny** [comment]
すみませんが、仕様です。component_typeに指定されるのはtabselとかwarningのように別の色付けされる (個人的にはcomponent groupに昇格すると呼んでいます) ことを想定していて、 `%(..)` で囲わないと見栄えが悪かろう、同時に使うことはなさそうということで raw type を `g:lightline.component_type` に入れてしまいました。若干設計をミスった感じは否めませんが、仕様ということにさせていただきます。

**Comment by Milly** [comment]
了解です。ありがとうございます。

component の中で状態によって色を変更したかったのですが、`component_expand` に指定した function 内で文字列展開してしまうと `%(...%)` の中に条件 `%{...}` がなくなって非表示になってしまうので raw にできないかと考えていました。
少し冗長ですが、条件 `%{...}` を出力するようにして実装いたしました。
