### ISSUE TITLE
Tabline

### ISSUE THREAD

**Issue by franklinchou** [itchyny/lightline.vim#140]
First off: Just changed from airline to lightline and IMHO lightline is vastly superior. Just in terms of its configuration options; great documentation and TRUE out-of-the-box functionality (without the need for patched fonts--I really like the xterm's standard monospaced font; why should I be forced to replace it just to get a statusline with cute arrows?).

That being said, I'm having some problems configuring the bufferline (or "tabline") to work. 

I've tried:

(A) Straight from the man pages:
```
let g:lightline.enable = {
		    \ 'statusline': 1,
		    \ 'tabline': 1
		    \ }
```
Unfortunately, this returns: `g:lightline is not a recognized variable.`

(B) I've also tried to incorporate the `enable` switch in the "super" lightline variable, e.g., 
```
let g:lightline = {
          \ 'enable': {
		    \ 'statusline': 1,
		    \ 'tabline': 1
		    \ }
         \ }
```
Vim accepts this easily enough; but the bufferline doesn't actually display.

**Comment by itchyny** [comment]
Try `:set showtabline=2`

**Comment by franklinchou** [comment]
Got it. Thanks.
