### ISSUE TITLE
Solarized light tabline issue

### ISSUE THREAD

**Issue by alexeyzab** [itchyny/lightline.vim#141]
Hi there!

I seem to be having some troubles with the tabline again. This time using the solarized light  colorscheme.
This is what it looks like for me now:

![before-fix-solarized-light](https://cloud.githubusercontent.com/assets/5606260/12058903/8cfd3b20-af1f-11e5-9c84-218afddf5ae3.png)

I believe the issue might be caused by reversing the colors in this block in solarized_light.vim:

```vimscript
let [s:base03, s:base3] = [s:base3, s:base03]
let [s:base02, s:base2] = [s:base2, s:base02]
let [s:base01, s:base1] = [s:base1, s:base01]
let [s:base00, s:base0] = [s:base0, s:base00]
```

I've edited the file and now my tabline looks like this:

![after-fix-solarized-light](https://cloud.githubusercontent.com/assets/5606260/12058917/cd5869d8-af1f-11e5-9bb2-711a0ca68062.png)

I'll submit a pull request with my fix. Let me know if it's an acceptable way of doing that.

Thank you!

**Comment by itchyny** [comment]
Thank you.
