### ISSUE TITLE
Spaces between tabs in tabline

### ISSUE THREAD

**Issue by nhooyr** [itchyny/lightline.vim#143]
This is my current setup with neovim + tmux.
<img width="1440" alt="screen shot 2016-01-19 at 4 55 10 pm" src="https://cloud.githubusercontent.com/assets/10180857/12433176/8c038b1c-becd-11e5-8cc2-14aba17b4a0f.png">

Notice how my tmux windows are listed at the bottom with spaces between them, and the unselected ones are coloured differently? I want to do the same with my tabline in lightline. Is this possible? It just looks really weird to me as I'm accustomed to my tmux status line.

**Comment by itchyny** [comment]
Seems to be difficult... probably not impossible, but requires lots of configuration of Vim script codes.

**Comment by nhooyr** [comment]
How would I go about it?

**Comment by itchyny** [comment]
1. See `:h g:lightline.component_expand` / `:h lightline-component-expansion`
2. Check what `lightline#tabs()` returns and what it means.
3. Write your `tabs` component and register it to `g:lightline.component_expand.tabs` in your configuration file.

**Comment by nhooyr** [comment]
Will do, thank you very much!

**Comment by nhooyr** [comment]
I think I'll just make my own function for the tabline. That seems to be much easier.
