### ISSUE TITLE
How to assign ctermbg 'none' color in colorscheme?

### ISSUE THREAD

**Issue by barwinko** [itchyny/lightline.vim#146]
First of all: thank you for fantastic plugin!

How to assign ctermbg 'none' color in colorscheme? There is no info about that in `:h lightline-colorscheme`.

This is available and works in vim colorschemes, very useful when you use vim in terminal with background transparency.
```viml
let s:p.normal.middle   = [ [ '#000000', '#000000',  4, 'none' ] ]
```
didn't work, lightline drops to color0 instead:
![](http://i.imgur.com/9m7CMEe.png)
```viml
let s:p.normal.middle   = [ [ '#000000', '#000000',  4, none ] ]
```
and without quotes lightline drops to default fallback theme with error.

Thanks.

**Comment by itchyny** [comment]
Thank you for your issue report. I've fixed the code. Please update the plugin and try `'none'`.

**Comment by barwinko** [comment]
Everything works! Thanks!

**Comment by itchyny** [comment]
You're welcome.
