### ISSUE TITLE
Idea: Special/Plugin buffers

### ISSUE THREAD

**Issue by critiqjo** [itchyny/lightline.vim#147]
Plugins like Undotree opens one or more split windows with the buffers unlisted *and* unmodifiable. The idea is to provide a new section/mode called 'special' or 'plugin' (similar to 'active') which will be used when that window is focused. ~~The default format could be as simple as~~:
*[deleted]*
What do you think?

**Comment by itchyny** [comment]
Thank you for your feature request. But your request is hard to implement.
- It's too difficult to judge the buffer is special or not. Some plugin allows the user to modify the contents; vimshell, unite, VimCalc and keep &modifiable true. Checking the value of &buflisted causes the same problem. Basically, these local options have nothing to do with whether the buffer is created by a plugin or not.
- The feature breaks the statusline of many users. Some configurations switches the appearance due to the value of &filetype to judge the plugin. If the components disappears suddenly, it will confuse many users.

**Comment by critiqjo** [comment]
> It's too difficult to judge the buffer is special or not.

We don't need to cover *all* cases. If the buffer is *both* `noma` and `nobuflisted`, then it's definitely created by a plugin (incl. vim help).

> The feature breaks the statusline of many users.

Oh, yeah! We can easily fix that by defaulting to `active` if `special` is not defined:
```vim
if !has_key(g:lightline, 'special')
  let g:lightline.special = g:lightline.active
endif
```

**Comment by critiqjo** [comment]
The motivation is:

![1](https://cloud.githubusercontent.com/assets/1436441/12886008/7f139406-ce90-11e5-84d0-a9414fe3b240.png)
![2](https://cloud.githubusercontent.com/assets/1436441/12886007/7f0fff1c-ce90-11e5-9461-3b83fbe79283.png)

Problems like these would be very easily solvable by setting the 'special' mode appropriately.

**Comment by critiqjo** [comment]
Wait a second... The problem above (protrusion of status line) does not exist in Vim -- it's only in Neovim! Nevertheless, it'd be neater to have this feature.

**Comment by itchyny** [comment]
I'm sorry but I'm not going to implement this feature anyway.

**Comment by critiqjo** [comment]
Fair enough! But if I implement it, will you be interested to merge it? Or do you think this will make things messy?

**Comment by itchyny** [comment]
Probably it'll not be merged...

**Comment by critiqjo** [comment]
Okay! Good to know -- saved time... By the way, it's a very nice plugin. Great work! :+1:  I've permanently moved from airline to lightline, because it was becoming heavier and heavier.

(The above issue was reported to Neovim repo, hope they fix it soon.)

**Comment by itchyny** [comment]
Thank you!

**Comment by critiqjo** [comment]
I'm just wondering (sorry for pestering)... Instead of `&buflisted` and `&ma` options, there is a much better option: `&buftype`. I just can't help but think that enabling users to customize based on `&buftype` will be really useful. Having each option be a component function and checking based on buftype seems to be a really tedious option for someone (me) wanting to customize things that fine-grained.

**Comment by itchyny** [comment]
The users are allowed to change the statusline based on `&buftype` by switching the logic *inside* the component functions. If you define some component function as follows, that component will shrink in plugin buffers.
```vim
function! Foo()
  if &buftype ==# 'nofile'
    return ''
  else
    return expand('%:p:t') " or something else
  endif
endfunction
```
There are many reasons that users want to change the appearance of statusline. Some people want to change the part of filename in some filetypes, others want to hide some components based on the width of the window. The buftype option might be a option some users want to change the appearance based on. Some people might use `has(feature)` to show something in the statusline, or switch the behaviour based on the existence of external command with `executable()`. There are many many wishes, but lightline lets users customize as they wish by allowing them to write the configuration by functions; the component function is the most important part of configurability of lightline.

**Comment by critiqjo** [comment]
> based on `&buftype` by switching the logic _inside_ the component functions.

Yes, but the problem with it is that, correct me if I am wrong, I can neither reuse the predefined components like `'lineinfo'`, nor can I return a pattern like `%l:%v`. The second problem is, for example, I want to change the position of `'filename'` (in the third list of `'left'` by default, but in the first list when special), now I have to modify/create two such functions with duplicated code.

Here's a generalized idea: let `'left'` and `'right'` keys _also_ accept a `Funcref`. This funcref will return the list based on custom logic (`buftype` or whatever).

**Comment by critiqjo** [comment]
On a related note, it would be nice if `'component_function'` accepted `Funcref`s too. This will enable passing in script-local functions.

**Comment by critiqjo** [comment]
> Here's a generalized idea: let `'left'` and `'right'` keys also accept a `Funcref`.

I meant it in a non-breaking manner. But if you are not interested at all, for the sake of keeping things simple, I understand.
