### ISSUE TITLE
undefined variable g:lightline

### ISSUE THREAD

**Issue by ranranking** [itchyny/lightline.vim#149]
I use neobundle and neovim. the plugin seems to be installed correctly. The statusline shows up, and the help file can be opened. But when I want to add configurations in my vimrc, it gives me error message: undefined variable g:lightine. I only added this:  let g:lightline.colorscheme='solarized'. I don't know what's wrong. When I try use commands, it shows "Not an editor command: lightline#...". And when I was using vim, I had the same problem. My vim is 7.4.1147

**Comment by itchyny** [comment]
```vim
let g:lightline = { 'colorscheme': 'solarized' }
```

**Comment by ranranking** [comment]
Thank you! I didn't read the readme file carefully. So I closed the issue. But I still think the informations in the help file is a little bit confusing. Hope you can just format so people like me won't make mistakes anymore.
