### ISSUE TITLE
lightline doesn't automatically show if a colourscheme is used.

### ISSUE THREAD

**Issue by TheReverend403** [itchyny/lightline.vim#151]
webm says it all really, if a colourscheme is used, lightline only shows on user input.

https://a.pste.pw/VPF.webm

Using vim 7.4.769 on Gentoo with USE="X acl lua luajit nls python -cscope -debug -gpm -minimal -perl -racket -ruby -selinux -tcl -vim-pager"

vimrc: http://ix.io/oDX

**Comment by itchyny** [comment]
I `curl`ed your vimrc but could not test the configuration; it seems to be a part of your vimrc. Please paste a minimal (under 50 lines) vimrc to reproduce the bug so that I can investigate.

**Comment by TheReverend403** [comment]
Alright, so after disabling plugins until lightline works, the culprit turned out to be vim-sensible. Further digging led me to https://github.com/tpope/vim-sensible/issues/78 and the last comment (https://github.com/tpope/vim-sensible/issues/78#issuecomment-185949649) solved the issue for me.

**Comment by itchyny** [comment]
Okay.
