### ISSUE TITLE
wrong width of statusline

### ISSUE THREAD

**Issue by genabug** [itchyny/lightline.vim#152]
Hi!

I've noticed that statusline is slightly cut at the bottom at one of my machine (see the screenshot). I doubt that this is somehow related to the plugin, more likely that the reason is in font config/video driver/... Can somebody give me a hint how to fix this?

![lightline_bottom_cut](https://cloud.githubusercontent.com/assets/13887572/13424914/9d783e26-dfb4-11e5-9d7a-105846906e32.png)

**Comment by itchyny** [comment]
What does it look like when you insert `M` character at the bottom of the screen with `100aM<ESC>` ?

**Comment by genabug** [comment]
Sorry, don't understand -- what does it mean "100aM<ESC>"?
![lightline_bottom_cut_mmm](https://cloud.githubusercontent.com/assets/13887572/13426330/c1fc701a-dfbd-11e5-9d2b-70fa35310ea7.png)

**Comment by itchyny** [comment]
The statusline is composed by characters so it cannot be rendered beyond the region where characters can be rendered.
![screenshot 2016-03-01 21 01 39](https://cloud.githubusercontent.com/assets/375258/13426466/e10b750e-dff0-11e5-8f2c-51c500ccf8d7.png)

**Comment by genabug** [comment]
So the problem is about fonts/characters? I noticed that when statusline doesn't containt pretty characters, than it looks better (not perfect, but better):
![lightline-bottom-cut2](https://cloud.githubusercontent.com/assets/13887572/13433049/3fa55810-dfe1-11e5-8465-c8ca87797b7e.png)
![lightline-bottom-cut3](https://cloud.githubusercontent.com/assets/13887572/13433055/46d8c36a-dfe1-11e5-8356-48a4c2f532af.png)

May be it's because I haven't installed patched fonts but took them from the repository? (debian testing, fonts-powerline package)

**Comment by genabug** [comment]
Yep, seems the problem is in used font (and its size). Switching from Noto Mono 11 to DejaVu Sans Mono 11 fixed the problem (however, DejaVu Sans Mono 10 doesn't fix it).

**Comment by itchyny** [comment]
The rendering problem cannot be solved by a plugin.

**Comment by genabug** [comment]
Yes, of course! I was hoping to find here someone with the same problem who fixed it:)
