### ISSUE TITLE
Error detected while processing function LightLineCWD

### ISSUE THREAD

**Issue by nickiesiva** [itchyny/lightline.vim#153]
I just installed `lightline` on my machine. I use `vim-plug`. But after install it, I don't get status line but some errors appears on my VIM. My VIM version is `7.4.52`.

`Error detected while processing function LightLineCWD:`

and 

`E117: Unknown function: env#Path`

Error screenshot :
![error1](https://cloud.githubusercontent.com/assets/9525894/13663929/03ce8814-e6d7-11e5-9e9f-73d779ffd6de.png)

Why I got this errors ? And how to fix it ? Thank's.

**Comment by itchyny** [comment]
Install this plugin: https://github.com/nhooyr/env.vim.

**Comment by nickiesiva** [comment]
I don't know how to call the function. I've read lightline documentation, but still didn't get it. Could you tell me how to fix it ? And after I installed `env.vim`, I got another errors. You can see the screenshot bellow

![error2](https://cloud.githubusercontent.com/assets/9525894/13666993/e9c7d000-e6e6-11e5-8ee9-497f0f19ef52.png)

Do I make a mistake while install it ? Oh ya, I use `fish-shell`, does it cause a trouble ?

**Comment by itchyny** [comment]
Where did you copied the lightline config from? Please paste your lightline config here.

**Comment by nickiesiva** [comment]
I use your config. 
```
let g:lightline = {
      \ 'colorscheme': 'landscape',
      \ 'mode_map': { 'c': 'NORMAL' },
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ], [ 'fugitive', 'filename' ] ]
      \ },
      \ 'component_function': {
      \   'modified': 'LightLineModified',
      \   'readonly': 'LightLineReadonly',
      \   'fugitive': 'LightLineFugitive',
      \   'filename': 'LightLineFilename',
      \   'fileformat': 'LightLineFileformat',
      \   'filetype': 'LightLineFiletype',
      \   'fileencoding': 'LightLineFileencoding',
      \   'mode': 'LightLineMode',
      \ },
      \ 'separator': { 'left': '⮀', 'right': '⮂' },
      \ 'subseparator': { 'left': '⮁', 'right': '⮃' }
      \ }

function! LightLineModified()
  return &ft =~ 'help\|vimfiler\|gundo' ? '' : &modified ? '+' : &modifiable ? '' : '-'
endfunction

function! LightLineReadonly()
  return &ft !~? 'help\|vimfiler\|gundo' && &readonly ? '⭤' : ''
endfunction

function! LightLineFilename()
  return ('' != LightLineReadonly() ? LightLineReadonly() . ' ' : '') .
        \ (&ft == 'vimfiler' ? vimfiler#get_status_string() :
        \  &ft == 'unite' ? unite#get_status_string() :
        \  &ft == 'vimshell' ? vimshell#get_status_string() :
        \ '' != expand('%:t') ? expand('%:t') : '[No Name]') .
        \ ('' != LightLineModified() ? ' ' . LightLineModified() : '')
endfunction

function! LightLineFugitive()
  if &ft !~? 'vimfiler\|gundo' && exists("*fugitive#head")
    let _ = fugitive#head()
    return strlen(_) ? '⭠ '._ : ''
  endif
  return ''
endfunction

function! LightLineFileformat()
  return winwidth(0) > 70 ? &fileformat : ''
endfunction

function! LightLineFiletype()
  return winwidth(0) > 70 ? (strlen(&filetype) ? &filetype : 'no ft') : ''
endfunction

function! LightLineFileencoding()
  return winwidth(0) > 70 ? (strlen(&fenc) ? &fenc : &enc) : ''
endfunction


function! LightLineMode()
  return winwidth(0) > 60 ? lightline#mode() : ''
endfunction
```

But errors still apear.

**Comment by itchyny** [comment]
Where do you define LightLineCWD?

**Comment by nickiesiva** [comment]
I not yet define it, I just install the plugin and copy your config to my `.vimrc`. I still searching for lightline tutorial from scratch.

**Comment by itchyny** [comment]
Please paste a minimal vimrc to reproduce the problem. The function LightLineCWD should exist in your vimrc or in one of the plugins you use.

**Comment by nickiesiva** [comment]
You see it here [https://github.com/nickiesiva/dotfiles/blob/master/.vimrc](url) .I comment the config and try to reinstall but nothing change. I thing I didn't have LightLineCWD on my vimrc.

**Comment by itchyny** [comment]
Please paste the output of `grep -r LightLineCWD ~/.vim/plugged`

**Comment by nickiesiva** [comment]
`/home/shad/.vim/plugged/elysian.vim/plugin/elysian_lightline.vim:      \   'cwd': 'LightLineCWD',
/home/shad/.vim/plugged/elysian.vim/plugin/elysian_lightline.vim:function! LightLineCWD()
`

**Comment by itchyny** [comment]
Uninstall the elysian plugin if you don't understand what it is.

**Comment by nickiesiva** [comment]
Thank's a lot for your help and fast response answering my question. Now, lightline work on my VIM. The amazing service ! Keep creating ! :dart:
