### ISSUE TITLE
Colorscheme change it self after saving

### ISSUE THREAD

**Issue by nickiesiva** [itchyny/lightline.vim#154]
Hello, sorry for asking you again. I've a trouble (actualy not a problem but it's inconvenience at appearance). I open VIM and `lightline` colorscheme didn't have problem in all mode, but after I make changes and save it, `lightline` colorscheme change it self. I try different default colorscheme like `PaperColor, jellybeans, solarized` but didn't solve it. What configuration for this problem ? 

Here the screenshot : 

when opening VIM : 
![good](https://cloud.githubusercontent.com/assets/9525894/13691613/f3ddf50c-e76c-11e5-9d08-003a5e175fc1.png)

after make changes, and saving it :
![jelek](https://cloud.githubusercontent.com/assets/9525894/13691742/afe9b39e-e76d-11e5-8864-bc158284a2af.png)

Colorscheme change only on `NORMAL MODE` and `INSERT MODE`. In `VISUAL` and `V-BLOCK MODE` it's still look good like when I open VIM for the first time.

in `VISUAL MODE` :
![visual](https://cloud.githubusercontent.com/assets/9525894/13691801/4db52b12-e76e-11e5-839c-515505c89be5.png)

Thank's for your help :)

**Comment by itchyny** [comment]
What happens if you move `colorscheme  lucius` after the lightline config?

**Comment by nickiesiva** [comment]
nothing happen. still change it self after saving.

**Comment by itchyny** [comment]
Comment out this line: https://github.com/nickiesiva/dotfiles/blob/f3c657d8c26f232f1096de6f7f378737c69a277d/.vimrc#L169

**Comment by nickiesiva** [comment]
Thank's a lot. It's work.
