### ISSUE TITLE
I'm making a custom colourscheme, but I can't seem to make some parts transparent in a transparent terminal.

### ISSUE THREAD

**Issue by krompus** [itchyny/lightline.vim#157]
I'd like to make the middle of the bottom bar transparent, and the empty space to the right of the tabs as well. I have tried setting these values to 'NONE', 'default', '0', 'black', and 'rgba(0, 0, 0, 0)' etc, but nothing has worked.

**Comment by itchyny** [comment]
How about this configuration?
```vim
let s:p.normal.middle = [ [ '#ffffff', 'NONE', 255, 'NONE' ] ]
let s:p.inactive.middle = [ [ '#ffffff', 'NONE', 255, 'NONE' ] ]
let s:p.tabline.middle = [ [ '#ffffff', 'NONE', 255, 'NONE' ] ]
```

**Comment by krompus** [comment]
You bet! Thanks a bunch! :)

**Comment by krompus** [comment]
Oh! One other thing: is there a way to remove the little vertical separators on the bottom right? `unix | utf-8 |` >>> `unix   utf-8 `

**Comment by itchyny** [comment]
Add the following configuration to your vimrc.
```vim
let g:lightline = { 'subseparator': { 'right': '' } }
```

**Comment by krompus** [comment]
Perfect! Thanks again!

**Comment by karambaq** [comment]
@itchyny I'm sorry, what I'm doing wrong?

I've pasted this in my .vimrc

```
let s:p.normal.middle = [ [ '#ffffff', 'NONE', 255, 'NONE' ] ]
let s:p.inactive.middle = [ [ '#ffffff', 'NONE', 255, 'NONE' ] ]
let s:p.tabline.middle = [ [ '#ffffff', 'NONE', 255, 'NONE' ] ]
```
and it says:

` Undefined variable: s:p`

**Comment by itchyny** [comment]
@karambaq Please create a new issue with your configuration and what you want.
