### ISSUE TITLE
'lineinfo' in a function

### ISSUE THREAD

**Issue by monkoose** [itchyny/lightline.vim#158]
How i can get `lineinfo` in some component_function? Is it possible?
I tried to make function that doesn't display lineinfo for particular files. I know you get this `%c`, `%3p%%` etc from vim statusline printf style items.
I tried to look in lightline.vim - but my expirience with vimscript is very small.

**Comment by itchyny** [comment]
```vim
function! LightLineLineInfo()
    return printf('%d:%-2d', line('.'), col('.'))
endfunction
```

**Comment by monkoose** [comment]
Thank you very much. Works perfectly. The most important thing that now i understand how vim gets current line and column info.
