### ISSUE TITLE
Status line color is not displayed in nomal mode...

### ISSUE THREAD

**Issue by ytac8** [itchyny/lightline.vim#163]
Thanks for this great plugin.
I'm not good at English, so I can't explain well.  I wanna talk in Japanese, if you don't mind.

I can't use this plugin as I expected.I use neovim and dein plugin manager.
In nomal mode, it doesn't display the color like this.
<img width="1280" alt="2016-05-09 11 18 30" src="https://cloud.githubusercontent.com/assets/11435694/15102234/e10c71bc-15d7-11e6-902a-3b8790a6387d.png">

I've wrote 
```
export TERM=xterm-256color
```
in my `.zshrc`.

And I wrote `set laststatus=2` and 
```  
augroup reload_vimrc
       autocmd!
       autocmd bufwritepost $MYVIMRC nested source $MYVIMRC
augroup END
```
in my `~/.config/dein/plugin.toml`.    
  
And my plugin.toml file are like this↓
```
[[plugins]]
    repo = 'itchyny/lightline.vim'
    hook_add = '''
        set laststatus=2
        
        augroup reload_vimrc
            autocmd!
            autocmd bufwritepost $MYVIMRC nested source $MYVIMRC
        augroup END

        let g:lightline = {
        \ 'colorscheme': 'wombat',
        \ 'mode_map': {'c': 'NORMAL'},
        \ 'active': {
        \   'left': [ [ 'mode', 'paste' ], [ 'fugitive', 'filename' ] ]
        \ },
        \ 'component_function': {
        \   'modified': 'LightLineModified',
        \   'readonly': 'LightLineReadonly',
        \   'fugitive': 'LightLineFugitive',
        \   'filename': 'LightLineFilename',
        \   'fileformat': 'LightLineFileformat',
        \   'filetype': 'LightLineFiletype',
        \   'fileencoding': 'LightLineFileencoding',
        \   'mode': 'LightLineMode'
        \ } ,
        \ 'component_expand': {
        \   'syntastic': 'SyntasticStatuslineFlag'
        \ },
        \ 'component_type': {
        \   'syntastic': 'error'
        \ }
        \ }

        let g:lightline.component_expand = {
        \ 'tabs': 'lightline#tabs' } 
        let g:lightline.component_type = {
        \ 'tabs': 'tabsel' } 

        let g:syntastic_mode_map = { 'mode': 'passive' }
        augroup AutoSyntastic
          autocmd!
          autocmd BufWritePost *.c,*.cpp call s:syntastic()
        augroup END
        function! s:syntastic()
          SyntasticCheck
          call lightline#update()
        endfunction

        function! LightLineModified()
          return &ft =~ 'help\|vimfiler\|gundo' ? '' : &modified ? '+' : &modifiable ? '' : '-'
        endfunction
        
        function! LightLineReadonly()
          return &ft !~? 'help\|vimfiler\|gundo' && &readonly ? 'x' : ''
        endfunction
        
        function! LightLineFilename()
          return ('' != LightLineReadonly() ? LightLineReadonly() . ' ' : '') .
                \ (&ft == 'vimfiler' ? vimfiler#get_status_string() :
                \  &ft == 'unite' ? unite#get_status_string() :
                \  &ft == 'vimshell' ? vimshell#get_status_string() :
                \ '' != expand('%:t') ? expand('%:t') : '[No Name]') .
                \ ('' != LightLineModified() ? ' ' . LightLineModified() : '')
        endfunction
        
        function! LightLineFugitive()
          try
            if &ft !~? 'vimfiler\|gundo' && exists('*fugitive#head')
              return fugitive#head()
            endif
          catch
          endtry
          return ''
        endfunction
        
        function! LightLineFileformat()
          return winwidth(0) > 70 ? &fileformat : ''
        endfunction
        
        function! LightLineFiletype()
          return winwidth(0) > 70 ? (strlen(&filetype) ? &filetype : 'no ft') : ''
        endfunction
        
        function! LightLineFileencoding()
          return winwidth(0) > 70 ? (strlen(&fenc) ? &fenc : &enc) : ''
        endfunction
        
        function! LightLineMode() 
            return winwidth(0) > 60 ? lightline#mode() : ''
        endfunction
    '''

```

I could display the lightline color when I start vim, typing `vim ~/.config`.
but I could not display the light line color  when I start vim, typing like `vim` or `vim ~/.config/dein/plugin.toml`.
I could display the lightline color in Insert mode, Visual mode.
Why I couldn't display the color well in Nomal mode?

**Comment by itchyny** [comment]
Can you test without dein?
Save the following code with `.vimrc.test` and open neovim with `nvim -u .vimrc.test`.
```vim
set nocompatible
filetype off
set rtp+=~/.vim/miv/lightline
filetype plugin indent on
syntax enable
set laststatus=2
let g:lightline = {
      \ " .... Your lightline config
```

**Comment by ytac8** [comment]
I could display well when open neovim with `nvim -u .vimrc.test`

I wrote what is like you said in my `~/.config/nvim/init.vim`, but it doesn't work well.....

mmmmmmm...
It seems that there are something wrong with dein setting...
but I couldn't understand...

**Comment by itchyny** [comment]
Can you show your complete configuration? Otherwise it's hard to find the solution because I cannot reproduce.

**Comment by ytac8** [comment]
Im sorry for my replying late.
When I  push my  vim files to github, I removed my vim files...
So I rewrite the files, and then, lightline.vim works well! 
Im so sorry for taking your time
Thank you

**Comment by itchyny** [comment]
Okay. Thanks.

**Comment by Hpixpoke** [comment]
Hello,
so I'm starting out with vim and got the same issue, here's my vimrc:
`
" vundle
set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'morhetz/gruvbox'
Plugin 'itchyny/lightline.vim'

call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

set number
syntax on

set background=dark
let g:gruvbox_constrast_dark = 'hard'
autocmd vimenter * colorscheme gruvbox

set laststatus=2 " enable lightline colors
set noshowmode " removes default mode indication
set ttimeout ttimeoutlen=50 " removes delay of switching modes
`

When I do `:source ~/.vimrc` the colors appear as intended.
Adding the TERM=xterm-256color variable to bashrc didn't help.

Thx for fast reply

**Comment by Hpixpoke** [comment]
Hello,
so I'm starting out with vim and got the same issue, here's my vimrc:
`" vundle
set nocompatible " be iMproved, required
filetype off " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'morhetz/gruvbox'
Plugin 'itchyny/lightline.vim'

call vundle#end() " required
filetype plugin indent on " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList - lists configured plugins
" :PluginInstall - installs plugins; append ! to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append ! to refresh local cache
" :PluginClean - confirms removal of unused plugins; append ! to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

set number
syntax on

set background=dark
let g:gruvbox_constrast_dark = 'hard'
autocmd vimenter * colorscheme gruvbox

set laststatus=2 " enable lightline colors
set noshowmode " removes default mode indication
set ttimeout ttimeoutlen=50 " removes delay of switching modes`

When I do :source ~/.vimrc the colors appear as intended.
Adding the TERM=xterm-256color variable to bashrc didn't help.

Thx for fast reply

**Comment by Hpixpoke** [comment]
Hello,
so I'm starting out with vim and got the same issue, here's my vimrc:

```
" vundle
set nocompatible " be iMproved, required
filetype off " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'morhetz/gruvbox'
Plugin 'itchyny/lightline.vim'

call vundle#end() " required
filetype plugin indent on " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList - lists configured plugins
" :PluginInstall - installs plugins; append ! to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append ! to refresh local cache
" :PluginClean - confirms removal of unused plugins; append ! to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

set number
syntax on

set background=dark
let g:gruvbox_constrast_dark = 'hard'
autocmd vimenter * colorscheme gruvbox

set laststatus=2 " enable lightline colors
set noshowmode " removes default mode indication
set ttimeout ttimeoutlen=50 " removes delay of switching modes
```

When I do `:source ~/.vimrc` the colors appear as intended.
Adding the TERM=xterm-256color variable to bashrc didn't help.

Thx for fast reply

**Comment by Hpixpoke** [comment]
Hello,
so I'm starting out with vim and got the same issue, here's my vimrc:
```
" vundle
set nocompatible " be iMproved, required
filetype off " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'morhetz/gruvbox'
Plugin 'itchyny/lightline.vim'

call vundle#end() " required
filetype plugin indent on " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList - lists configured plugins
" :PluginInstall - installs plugins; append ! to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append ! to refresh local cache
" :PluginClean - confirms removal of unused plugins; append ! to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

set number
syntax on

set background=dark
let g:gruvbox_constrast_dark = 'hard'
autocmd vimenter * colorscheme gruvbox

set laststatus=2 " enable lightline colors
set noshowmode " removes default mode indication
set ttimeout ttimeoutlen=50 " removes delay of switching modes
```

When I do `:source ~/.vimrc` the colors appear as intended.
Adding the `TERM=xterm-256color` variable to bashrc didn't help.

Thx for fast reply

**Comment by itchyny** [comment]
@Hpixpoke It doesn't  seem the exact same issue so please open a new issue.

**Comment by wongjiahau** [comment]
@Hpixpoke I had the same problem too, the problem is with `autocmd vimenter * colorscheme gruvbox`. Once I removed this line then the problem is solved.

**Comment by yhu266** [comment]
> @Hpixpoke I had the same problem too, the problem is with `autocmd vimenter * colorscheme gruvbox`. Once I removed this line then the problem is solved.

This is a known and solved issue. See https://github.com/itchyny/lightline.vim/issues/487#issuecomment-660380223 for details.
