### ISSUE TITLE
Undefined variable r

### ISSUE THREAD

**Issue by lmr3796** [itchyny/lightline.vim#166]
Hi, I'm getting this error message while doing `vundle`'s action `:PluginInstall`

## Error Message
```
Error detected while processing function lightline#update[9]..lightline#statusline[2]..lightline#highlight:
line   23:
E121: Undefined variable: r
E116: Invalid arguments for function printf('hi LightLine%s_%s_%s_%s guifg=%s guibg=%s ctermfg=%s ctermbg=%s', p, mode, i, j, r[1], q[1], r[3], q[3])
E15: Invalid expression: printf('hi LightLine%s_%s_%s_%s guifg=%s guibg=%s ctermfg=%s ctermbg=%s', p, mode, i, j, r[1], q[1], r[3], q[3])
```

## Version
`lightline` on lastest master (6803c2c)
`vundle` version [4984767](https://github.com/VundleVim/Vundle.vim/commit/4984767509e3d05ca051e253c8a8b37de784be45)

## Reproducing
To reproduce this:
1. Install lightline with vundle
2. Run command `:PluginInstall` in vim

My lightline setting https://github.com/lmr3796/.vim/blob/master/sub_vimrc/lightline.vimrc
Here's my vundle plugin setting:
```vimrc
filetype off

" Init vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" REQUIRED
Plugin 'gmarik/vundle'


Plugin 'itchyny/lightline.vim'

filetype plugin indent on
```

**Comment by itchyny** [comment]
Thank you for the issue report. I fixed the bug.
