### ISSUE TITLE
Integrate with Syntastic will cause the syntax checked twice

### ISSUE THREAD

**Issue by QMonkey** [itchyny/lightline.vim#167]
Thank you for building such wonderful plugin! I really love lightline, because it is very smart. But recently I find a problem may cause the lightline to be slow.
After save code, syntastic will check the syntax, and the command SyntasticCheck inside AutoSyntastic will check the syntax again! Sometime syntax check will be slow. Therefore, check syntax twice will be slower. If I remove the SyntasticCheck  command, I always have to save twice to let the syntastic error show. Is there any way to integrate with syntastic?

My config is like that:
https://github.com/itchyny/lightline.vim#for-power-users

**Comment by itchyny** [comment]
Let me know how do you configure syntastic.

**Comment by QMonkey** [comment]
My syntastic config is like that:

```vim
let g:syntastic_loc_list_height = 10
let g:syntastic_error_symbol = '✖'
let g:syntastic_style_error_symbol = '✖'
let g:syntastic_warning_symbol = '!'
let g:syntastic_style_warning_symbol = '!'
let g:syntastic_always_populate_loc_list = 0
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_enable_highlighting = 1
let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
let g:syntastic_mode_map = {'mode': 'active', 'passive_filetypes': ['go']}
```

**Comment by itchyny** [comment]
If the mode is active, syntastic checks the syntax and the configuration of lightline does the same check. If you set the mode to passive, the check will be executed once.

Reference: https://github.com/scrooloose/syntastic/blob/9ac3dbe2b907870a0fd8287ee8658c4619e6e97c/doc/syntastic.txt#L510-L543

**Comment by QMonkey** [comment]
Oh yeah! Nice! That it! Thank you very much! : )
