### ISSUE TITLE
fillchars stlnc ignores unicode characters

### ISSUE THREAD

**Issue by dessaya** [itchyny/lightline.vim#169]
Hi, love your plugin!

I use neovim and have this line in my `init.vim`: `set fillchars=vert:\│,stlnc:\─`

If I run without plugins I see: 

![screenshot from 2016-07-19 15-39-40](https://cloud.githubusercontent.com/assets/7060033/16962248/2b024c70-4dc7-11e6-8b97-23f8b850d955.png)

With lightline I see:

![screenshot from 2016-07-19 15-40-17](https://cloud.githubusercontent.com/assets/7060033/16962251/2ddd756e-4dc7-11e6-8194-333380d43e87.png)

Note that the `vert` setting works fine, but `stlnc` shows a standard ASCII dash `-` instead of the unicode char `─`.

Thanks!

**Comment by itchyny** [comment]
The document (:h 'fillchars') says that `for "stl" and "stlnc" only single-byte values are supported.`, so you cannot use multi-byte values. I confirmed that `set fillchars=stlnc:!` has effect with lightline enabled.
```vim
set fillchars=vert:\│,stlnc:\─
set statusline=%t\ %=\ %l:%c
```
without lightline can cause the same situation, please confirm.

**Comment by dessaya** [comment]
Too bad, that's right. I wonder what's the reason for limiting these values to single-byte chars.
Thanks!
