### ISSUE TITLE
tell iTerm2 users to not use a different font for non-ascii text

### ISSUE THREAD

**Issue by noahgamboa** [itchyny/lightline.vim#171]
in the readme when discussing how to use the arrows in lightline and installing powerline text i struggled for a while because i had the setting to use a different font for non-ascii text turned on iterm2. I didn't open a pr for it because it's as simple as:

"If you're using iTerm2, be sure that the font you use for non-ASCII text is the font that you want for the airline."

**Comment by itchyny** [comment]
I set Font `Inconsolata for Powerline` and Non-Ascii Font `Hiragino Kaku Gothic Pro W3` but it works well with the fancy arrows.
