### ISSUE TITLE
component_visible_condition with winwidth

### ISSUE THREAD

**Issue by ericbn** [itchyny/lightline.vim#173]
Why do we have to define:

    \ 'component_function': {
    \   'mode': 'LightLineMode',

and

    function! LightLineMode()
      return winwidth(0) > 60 ? lightline#mode() : ''
    endfunction

instead of just defining

    \ 'component_visible_condition': {
    \   'mode': '(winwidth(0) > 60)',

?

The second looks much simpler, but does not work...

**Comment by itchyny** [comment]
You cannot do that, please control the visibility of components inside component functions.

component_visible_condition is used for the clue to judge whether each components is empty or not. It is not used to control the visibility of the components. The lightline plugin cannot tell how the statusline components (e.x. `%{&paste?"PASTE":""}` and `%R`) look like actually and requires a clue to know that each components are empty or not (in order to hide the sub-separators). So, we have to give the visible conditions to the plugin to know that. On the other hand, component functions are easy to tell if they are empty or not; just compare the result of the functions to the empty string.

**Comment by ericbn** [comment]
Okay, so using the function renders a statusline with

    %( %{LightLineMode()} %)%{LightLineMode()!=#""&&((&paste))?"|":""}

and using component_visible_condition renders a status like with

    %( %{lightline#mode()} %)%{((winwidth(0) > 60))&&((&paste))?"|":""}

I'm getting it. I tried also setting the subseparators to `""` and saw that the second block was gone.

So component_visible_condition is all about the separators. Oh, it wasn't clear to me. Maybe the documentation should be more explicit about it.

Or shouldn't we have something like this

    %( %{((winwidth(0) > 60))?lightline#mode():""} %)%{((winwidth(0) > 60))&&((&paste))?"|":""}

?

Which is actually what the function does, just we would not need to write it for simple cases like this. I like the simplicity of having a one-liner component_visible_condition, instead of the component line plus three or four lines for the function...

This even puts me thinking: isn't there a better way? I don't have enough vim knowledge here, but can't we use variables inside the statusline code so things don't get called twice? Also, looking at the burden that subseparators give, I start to see them as "evil" now... And do they deserve so much attention as to be gifted with a special component_visible_condition feature just for them? 😄

**Comment by itchyny** [comment]
It's surely a confusing configuration so I'll update the document.

Supporting the visibility configuration is very difficult. For example, the default readonly component is `%R` and suppose a user want to hide the component based on the window width and in the help window. The new visibility configuration leads to `%{ (winwidth(0) > 60 && &ft !=# 'help') ? '%R' : ''}`, but it does not work. The user have to set the component `%{ winwidth(0) > 60 &ft !=? 'help' && &readonly ? 'RO' : '' }`. Then, how lightline can tell the visibility of this component? Should it parse the component configuration?

After all, the idea of component functions is simple enough to make it easy to write the configuration and let lightline control the sub-separators easily. Yes, the sub-separators is causing this difficult situation so probably the next X-line plugin should omit it to make the logic simple. But the fancy separators were attractive enough to move them use the X-line plugins.

**Comment by ericbn** [comment]
I would think the visibility configuration in that case would be `(winwidth(0) > 60 && &ft !=# 'help' && &readonly)`, and the component simply `'RO'`.

Separating visibility from the component visual form can even lead to optimizations if one submodule is besides another one that is always visible. In the case of mode always being visible, we would have something like

    %( %{LightLineMode()} %)%{((&paste))?"| "."PASTE"." ":""}

Given `(&paste)` is the visibility configuration of the component paste, whose visual form is `'PASTE'`.

Actually, by default most of the subcomponents are visible, so there's a lot of redundant testing regarding the separators. And having separate visibility configurations could better optimize the final statusline code. After all, the intent of the plugin is exactly to help with things like these, right? 😄

**Comment by itchyny** [comment]
Sorry but I close this issue. I'll look into the logic to find further optimization when I have time.

**Comment by ericbn** [comment]
Actually, just found that vim can hide separators if the group string is empty. No no need for a visibility configuration actually, we can just have a component `&paste ? 'PASTE' : ''` and if the subseparator is `|` then we can just render this in the statusline:

    %(\ \|\ %{&paste?'PASTE':''}%)

If the `%{...}` group results in an empty string, the ` | ` is not printed out either.
