### ISSUE TITLE
tweaking tabline separators

### ISSUE THREAD

**Issue by jarhat** [itchyny/lightline.vim#174]
I'm having this in my .vimrc:

`let g:lightline.tabline_separator = { 'left': ' ', 'right': '' }`

`let g:lightline.subseparator = { 'left': '', 'right': '' }`

That results in this

![img-2016-08-06-162702](https://cloud.githubusercontent.com/assets/13524127/17457336/739164d0-5bf5-11e6-97e5-27635b3d7771.png)

Now can I get this one

![img-2016-08-06-1627020](https://cloud.githubusercontent.com/assets/13524127/17457335/6d9ec6ee-5bf5-11e6-9919-b89d9f0035b8.png)

?

**Comment by itchyny** [comment]
How about this config?
```vim
let g:lightline.tabline_separator = { 'left': "\u2b80", 'right': "\u2b82" }
let g:lightline.tabline_subseparator = { 'left': "\u2b81", 'right': "\u2b83" }
```
