### ISSUE TITLE
Latest commits break solarized

### ISSUE THREAD

**Issue by danielbmarques** [itchyny/lightline.vim#176]
I don't know what's going on, but the latest commits broke the Solarized theme for me.

Now I get `lightline.vim: Could not load colorscheme solarized_light`.

If I revert a couple of commits it works fine again.

**Comment by itchyny** [comment]
Please use `solarized` colorscheme.

**Comment by danielbmarques** [comment]
Ah! I was using the `solarized` cholorscheme, but I also had that `s:lightline_update()` function in my `.vimrc` and I didn't notice you changed it in the documentation. Now I updated that and it's all good. Thanks!
