### ISSUE TITLE
Solarized dark does not work

### ISSUE THREAD

**Issue by ctnieves** [itchyny/lightline.vim#177]
'colorscheme': 'solarized' uses the solarized light colors even if background is set to dark.

**Comment by itchyny** [comment]
I cannot reproduce.
I started Vim by `vim -u ./.vimrc` with the following vimrc.
```vim
set nocompatible
filetype off
set background=dark
set runtimepath+=/Users/itchyny/.vim/miv/lightline
let g:lightline = { 'colorscheme': 'solarized' }
set laststatus=2
filetype plugin indent on
syntax enable
```

**Comment by patrickshan** [comment]
same problem here. solarized_dark doesn't work any more but solarized works.

**Comment by mentoc3000** [comment]
I'm having the same problem.  The .vimrc you provide works correctly and loads the dark solarized lightline.  However, when you include
```
set runtimepath+=/path/to/solarized
colorscheme solarized
```
The lightline reverts back to light.  If I remove the colorscheme definition from the .vimrc file and just set it once vim is open it works fine, though.

**Comment by mremond** [comment]
I have the same issue. Switching the global theme to solarized, switch lightline theme to light.

**Comment by itchyny** [comment]
I cannot reproduce this problem. I confirmed with the following configuration today and the lightline theme keeps dark. Changing the `&background` to light changes the both themes light.
```vim
set nocompatible
filetype off
set runtimepath+=/path/to/colors-solarized
set runtimepath+=/path/to/lightline
set background=dark
let g:lightline = { 'colorscheme': 'solarized' }
set laststatus=2
filetype plugin indent on
syntax enable
colorscheme solarized
```
Please upload a minimal vimrc to reproduce the behavior and I'll investigate then.

**Comment by emilhuseynli** [comment]
I can confirm that lightline doesn't switch to solarized light when background changes to light. This issue is related: https://github.com/itchyny/lightline.vim/issues/188

**Comment by itchyny** [comment]
Yes, lightline does not support changing the solarized highlight by switching background afterwards . I'm not sure this issue is related to it.

**Comment by emilhuseynli** [comment]
Sorry, this isssue is indeed is not related to mine. I've edited my post already. Regarding to my problem, I have to use "runtime autoload/lightline/colorscheme/solarized.vim" trick to get it work.

**Comment by mavam** [comment]
I'm also struggling to find a solution that makes it possible to switch from light to dark. I currently do it simply via `set bg=dark` and `set bg=light`. As noted, this doesn't update lightline. Is there a simple function one could write that facilitates switching? Or does it still involve some patching?
