### ISSUE TITLE
Statusline background missing in vertical split column

### ISSUE THREAD

**Issue by sstallion** [itchyny/lightline.vim#179]
I'm working on a new colorscheme for lightline and I've encountered something interesting. The underlying colorscheme is designed to work in all terminals with or without lightline. The default statusline highlight is set to blue, however when lightline is present, it uses a monochrome scheme to take advantage of 256 color terminals. This works great, however I've noticed that when the window has a vertical split, the default statusline background shows up where lightline should be:

![image](https://cloud.githubusercontent.com/assets/5983112/17649300/540ea52a-61f7-11e6-8d29-fcd786989adf.png)

I worked around this issue by adding support for a callback when `lightline#highlight` is called for the given mode, however this feels like the wrong approach. For the life of me, I can't figure out how lightline determines the width of the window. I'm happy to file a PR for this, but some help to pinpoint where this happens would be  much appreciated. It seems that lightline just needs to account for increasing the winwidth by one if a vertical split is present.

As an aside, would you be interested in a patch that adds support for this callback? It has some interesting side-effects, mainly that a colorscheme can react to changes in modes without having to muck about with nested autocommands. I could imagine this being used to affect other highlights apart from those that lightline defines (i.e. insert could change `Normal` to bold).

**Comment by sstallion** [comment]
With the callback hack applied, the active window correctly expands to cover the entire statusline:

![image](https://cloud.githubusercontent.com/assets/5983112/17649559/0ed9514c-61fe-11e6-8e4d-037faa9d6357.png)

The inactive window also expands correctly on the left side as well:

![image](https://cloud.githubusercontent.com/assets/5983112/17649564/2365acbe-61fe-11e6-9a12-11d19c0d8ace.png)

**Comment by itchyny** [comment]
What do you mean by *the callback hack*? Can you paste the configuration? I think this is a bug of Vim and is hard to fix.

**Comment by sstallion** [comment]
It might be easier to explain (and it sounds like this could end up being the only solution).

By adding a callback to `lightline#highlight`, I'm able to change the `StatusLine` and `StatusLineNC` highlights to match the colors used by lightline. Since these colors are different than the default statusline color, the callback ended up being necessary as it was the only way to really know when lightline loaded the colorscheme.

The change to the colorscheme script looks something like this:

    function! lightline#colorscheme#wtf#highlight(mode)
      if exists('s:loaded_highlight')
        return
      endif
      let s:loaded_highlight = 1

      call wtf#highlight({
            \ 'StatusLine': {
            \   'ctermfg': s:active_right[0][2], 'ctermbg': s:active_right[0][3],
            \   'guifg'  : s:active_right[0][0], 'guibg'  : s:active_right[0][1],
            \ },
            \ 'StatusLineNC': {
            \   'ctermfg': s:inactive_right[0][2], 'ctermbg': s:inactive_right[0][3],
            \   'guifg'  : s:inactive_right[0][0], 'guibg'  : s:inactive_right[0][1],
            \ },
            \ })
    endfunction

**Comment by sstallion** [comment]
I also verified behavior when lightline is not loaded. If you start vim with lightline disabled and create a vertical split, vim performs the correct highlighting between both windows, which is what led me to think that there could be a bug in lightline.

**Comment by itchyny** [comment]
Okay, I got it. This is not a bug, but a new feature. I think that overwriting the colours of StatusLine and StausLineNC on setup is enough. It should be a task of the colorschemes and I'm not sure lightline can overwrite them.

**Comment by sstallion** [comment]
Sounds good. I'll file a PR momentarily.

**Comment by sstallion** [comment]
Hi @itchyny, I've created PR #180. Please let me know if there is anything else I can do!

**Comment by itchyny** [comment]
I concluded that lightline should not support callbacks and should not overwrite StatusLine/StatusLineNC. I think that the following config will work well enough.
```vim
hi StatusLine ctermfg=0 ctermbg=237
hi StatusLineNC ctermfg=0 ctermbg=237
```

**Comment by sstallion** [comment]
The issue is that the statusline uses a different color when lightline is disabled. The above proposal forces users of the colorscheme to use a color that does not work well for the entire statusline.

**Comment by itchyny** [comment]
When I configured so that `StatusLine` has the same bg colours as `VertSplit`, it looked good for me.

**Comment by sstallion** [comment]
I think the issue is that this colorscheme in particular behaves differently depending on how many colors are available. Ideally, there could be some kind of a notification that a particular colorscheme is loaded for lightline - that would allow the author to update any highlight groups that might be needed.

If this doesn't sound like a reasonable feature, I can always add something to the documentation that the additional function call should be added to the lightline configuration. I was hoping that this could be avoided.

**Comment by itchyny** [comment]
A colorscheme should not depends on other plugins. A colorscheme should not change its behaviour based on other plugins. Such settings should be written in users' configuration files.

**Comment by sstallion** [comment]
This is a colorscheme specifically plugin for lightline.

**Comment by itchyny** [comment]
Oh sorry. This one? https://github.com/sstallion/lightline-wtf

**Comment by sstallion** [comment]
It is! It's still very new (I haven't taken the time to document it yet), but the idea behind the original colorscheme (vim-wtf) is to adapt to different terminal capabilities (mostly number of colors available). I've been working on a complementary colorscheme for lightline (lightline-wtf) in parallel. I realize this is a bit different than most colorschemes - I was hoping that configuring lightline for this colorscheme would be as seamless as it is for the ones provided.

**Comment by sstallion** [comment]
@itchyny I've finally gotten around to finishing lightline-wtf (https://github.com/sstallion/lightline-wtf). I've added a note that an additional function call is needed to work around this issue, though I hope you'll reconsider addressing this at some point in the future. Thanks again!
