### ISSUE TITLE
Unexpected subseparators in statusline

### ISSUE THREAD

**Issue by sstallion** [itchyny/lightline.vim#181]
I've recently converted to using toggles for certain behaviors in my `vimrc`. Similar to the existing `paste` and `spell` components, I've added one for `hlsearch`. I've noticed that when I add more than 3 elements to `g:lightline.left[0]`, A phantom subseparator appears when none of the toggles are enabled:
![screen shot 2016-08-15 at 12 08 04 pm](https://cloud.githubusercontent.com/assets/5983112/17672232/f0d75dd6-62e0-11e6-82de-1dcc62e6f6ee.png)
This works normally if I limit `g:lightline[0]` to 3 items or fewer.

My configuration is as follows:

    let g:lightline = {
          \ 'active': {
          \   'left': [['mode', 'paste', 'search', 'spell'], ['fugitive'], ['filename']],
          ...
          \ },
          \ 'component': {
          \   'paste': '%{&paste ? "PASTE" : ""}',
          \   'search': '%{&hlsearch ? "SEARCH" : ""}',
          \   'spell': '%{&spell ? "SPELL" : ""}',
          \   ...
          \ },
          ...

**Comment by itchyny** [comment]
Add the following config.
```vim
      \   'component_visible_condition': {
      \     'search': '&hlsearch'
      \   },
```

**Comment by sstallion** [comment]
Perfect. Thanks again!
