### ISSUE TITLE
vim-better-whitespace

### ISSUE THREAD

**Issue by jjo93sa** [itchyny/lightline.vim#184]
Is it possible to integrate https://github.com/ntpeters/vim-better-whitespace with lightline. The screen shots show some extra text on the right hand side of the status line when trailing white space is detected. I can't get this text to show with lightline.vim

**Comment by itchyny** [comment]
Please refer to the document (https://github.com/ntpeters/vim-better-whitespace/blob/master/doc/better-whitespace.txt). If the plugin exports some functions to get the information of this plugin, the answer is yes, otherwise no.
