### ISSUE TITLE
tabline.tabsel with dynamic background color.

### ISSUE THREAD

**Issue by Valdsonjr** [itchyny/lightline.vim#185]
Is there a way to set the `s:p.tabline.tabsel` to match the current mode for the (current) buffer on that tab?

![example](https://cloud.githubusercontent.com/assets/6580116/18403251/07bb14f6-76ba-11e6-973b-c251ea814eff.png)

For example: if init.vim is my selected tab/buffer and it is in Normal mode the background should be green (instead of maroon), if it is in Insert mode then the background should be blue and etc.

**Comment by itchyny** [comment]
I'm afraid the answer is no.
```
hi clear LightLineLeft_tabline_tabsel
hi link LightLineLeft_tabline_tabsel LightLineLeft_active_0
```
Linking the highlight group will affect the colour of the tabline, but the separator messes up.
