### ISSUE TITLE
Symbol for linecolumn separator not implemented

### ISSUE THREAD

**Issue by Aster89** [itchyny/lightline.vim#187]
I noticed that in the readme, there is a symbol () of  the patched font to use as the line-column separator (in place of the colon), but it is not implemented. I substituted it in the colon at the line 108 of lightline.vim.

**Comment by itchyny** [comment]
Not all the users install patched font, so the ascii colon is preferable for default configuration. If you want the symbol in the component, you can overwrite the component.

**Comment by Aster89** [comment]
Yes, of course, I'm not talking about changing the default configuration, I'm just wondering why that symbol is present in the "Cool characters for the patched fonts" table (with subseparators, readonly, ...), but it's the only one in the table that's not used in any part of the configuration tutorial.

**Comment by itchyny** [comment]
By the way, what is the code point of that character? Does it exist in the older vim-powerline font? The character in your comment looks like a square.

**Comment by Aster89** [comment]
It's the e0a1 symbol [here](https://github.com/ryanoasis/powerline-extra-symbols/blob/master/fontforge.png).

**Comment by itchyny** [comment]
Ah, ok. I got what you mean. I think setting the lineinfo component to `"\ue0a1%3l:%-2c"` will look nice. Talking of the configuration tutorial, I'm planning to remove the fancy characters from README because I noticed that many people does not want to install the fancy font for Vim plugin.
