### ISSUE TITLE
Using solarized dark with background=light

### ISSUE THREAD

**Issue by Bew78LesellB** [itchyny/lightline.vim#188]
Hello,

I'm using a light theme (so `background=light`). I was using the `solarized_dark` colorscheme which doesn't work anymore. As the new `solarized` lightline colorscheme depends on `background` value, how can I use the dark theme when `background=light` ?

Can you add a setting in the `g:lightline` dict to be able to change the `background` property before applying the lightline theme ?

thanks

**Comment by itchyny** [comment]
No, you cannot. The colorscheme depends on the value of `&backeround`, which is also what [vim-colors-solarized](https://github.com/altercation/vim-colors-solarized/blob/master/colors/solarized.vim) does. Set the option dark to use the dark colours. Sorry. #175
