### ISSUE TITLE
Can't override colorcheme colors in vimrc

### ISSUE THREAD

**Issue by bronzdoc** [itchyny/lightline.vim#190]
First, thank you for lightline is awesome!

My problem is:

I'm using the powerline colorscheme, by default it looks like:
![alt tag](http://i.imgur.com/JtFr3wO.png)

but I want it to look like this:
![alt tag](http://i.imgur.com/xez3HDB.png)

what I have done to accomplish this, is override the colors in the `powerline.vim` colorscheme, but that is not optimal, so I decided to instead of doing that just override the colors in my vimrc with the following:

`vimrc`

```
let g:lightline = {
      \ 'colorscheme': 'powerline',
      ...

let s:cuicolor = {
            \ 'darkestgreen'   : 22,
            \ 'brightgreen'    : 148,
            \ 'gray0'          : 233,
            \ 'gray1'          : 235,
            \ 'gray2'          : 236,
            \ 'gray3'          : 239,
            \ 'gray4'          : 240,
            \ 'gray5'          : 241,
            \ 'gray6'          : 244,
            \ 'gray7'          : 245,
            \ 'gray8'          : 247,
            \ 'gray9'          : 250,
            \ 'gray10'         : 252,
            \}

let s:palette = g:lightline#colorscheme#{g:lightline.colorscheme}#palette
let s:palette.normal.left = [ [s:cuicolor.darkestgreen, s:cuicolor.brightgreen, 'bold'], [s:cuicolor.gray4, s:cuicolor.gray1] ]
```
but this isn't working.

I'm getting the following error when I open vim with this configuration:
![alt tag](http://i.imgur.com/LCdubSW.png)

**Comment by itchyny** [comment]
The palette colours is:
```
let s:palette.{mode}.{where} = [ [ {guifg}, {guibg}, {cuifg}, {cuibg} ], ... ]
```
So  you can configure as:
```
let s:palette.normal.left = [ ['#005f00', '#afdf00', s:cuicolor.darkestgreen, s:cuicolor.brightgreen], ['#585858', '#121212', s:cuicolor.gray4, s:cuicolor.gray1] ]
```

**Comment by bronzdoc** [comment]
That works, thank you!
