### ISSUE TITLE
Highlights are broken at startup on Windows console

### ISSUE THREAD

**Issue by Bakudankun** [itchyny/lightline.vim#191]
![default](https://cloud.githubusercontent.com/assets/4504807/19088174/0238f9bc-8ab0-11e6-89f3-273fa7bcb990.png)
![2](https://cloud.githubusercontent.com/assets/4504807/19088178/07d349b8-8ab0-11e6-8e33-debe660ebd51.png)

Highlights seem broken on Windows command prompt at startup.
It returns to correct color after I `:call lightline#highlight()` manually.

As far as I researched, this bug comes from commit 7a2d853. This doesn't occur at the previous revision 757fa3d.

**Comment by itchyny** [comment]
Thanks for your detail report, I fixed the bug.
