### ISSUE TITLE
Lag of ESC key in Linux terminal

### ISSUE THREAD

**Issue by Bakudankun** [itchyny/lightline.vim#192]
Using in Linux console, lightline seems cause lag of ESC key (as if there is some key mapping starting with `<ESC>` or `<C-[>`).
This doesn't occur with gvim or `vim -u NORC -N` (even if `laststatus=2`), and it occurs with following `.vimrc`.

```vim
set runtimepath+=~/path/to/lightline.vim
set laststatus=2
" nothing else
```

When I `:set laststatus=0`, the lag disappears.

Could you fix this, please?

I confirmed this occur in xfce4-terminal, Guake terminal or LXTerminal on Ubuntu derivatives.

**Comment by itchyny** [comment]
How about adding `set ttimeout ttimeoutlen=30` to your configuration?

**Comment by Bakudankun** [comment]
oh it removed the lag. Thank you!
