### ISSUE TITLE
Question: Is there a way to disable lightline on NERDTree

### ISSUE THREAD

**Issue by RahulKatariya** [itchyny/lightline.vim#193]
First of all this is a great plugin with great customizations ❤️

So I want to disable the lightline inside the NerdTree view. is there any way to achieve it?

**Comment by RahulKatariya** [comment]
And one more thing I am using the agnoster [https://gist.github.com/agnoster/3712874] theme in zsh terminal with oh-my-zsh.

I was wondering if I could make the left side of the status bar exactly the same as agnoster with colors. I am very new to vim right now. Could you give me some direction or any help would be greatly appreciated.

Thanks

**Comment by itchyny** [comment]
There's no way to disable in specific plugin windows, I'm not planning to implement, sorry.

You can create your own colorscheme to change the colours. See `:h lightline-colorscheme` or look into some repositories https://github.com/search?q=lightline+colorscheme.
