### ISSUE TITLE
Lightline won't update after toggling background color?

### ISSUE THREAD

**Issue by dbmrq** [itchyny/lightline.vim#194]
When there were different colorschemes for solarized light and dark I was able to toggle the background color and call [the update function in the documentation](https://github.com/itchyny/lightline.vim/blob/master/doc/lightline.txt#L1218) and the status line would change accordingly. But now if I change the background from dark to light the status line will remain the same.

**Comment by itchyny** [comment]
I decided to drop the support for that when I merged #175. Sorry but restart Vim to see the appearance changes.

**Comment by dbmrq** [comment]
Ah, that's unfortunate. Ok then, thanks!

**Comment by interstellar716** [comment]
I faced this limitation a few hours ago too but my OCD couldn't let it go. My solution was to `source` (again) the file that contains the airline settings of the colorscheme that I've just selected. It is far from perfect and it may only work for the colorscheme that I use but I think it is worth sharing.
Anyway [this was what I did](https://github.com/interstellar716/dotfiles/blob/a2bef85beeb5639892fd19757792bc85c35282d8/init.vim#L43).

**Comment by 123subhadeep** [comment]
> Anyway this was what I did.
The link you posted isn't accessible anymore. 

@dbmrq Were you able to find a workaround ? I am facing the same issue: lightline doesn't change theme unless vim restarted.
@itchyny Is there any workaround without restart ?

**Comment by itchyny** [comment]
Source the colorscheme file and `call lightline#colorscheme()`, `call lightline#update()`.
Ref: https://github.com/itchyny/lightline.vim/issues/424#issuecomment-590058820.
