### ISSUE TITLE
Could not load colorscheme solarized_dark

### ISSUE THREAD

**Issue by ianwalter** [itchyny/lightline.vim#197]
I'm getting the following error on Ubuntu 16.04 (Docker) but not on MacOS Sierra:
```
lightline.vim: Could not load colorscheme solarized_dark.
```
Any ideas?

**Comment by itchyny** [comment]
Please use the `solarized` colorscheme. The `solarized_light` and `solarized_dark` colorschemes are merged into one colorscheme. #175.

**Comment by ianwalter** [comment]
I missed that, thank you!
