### ISSUE TITLE
How to get rid of placeholder if custom color is being used

### ISSUE THREAD

**Issue by fatih** [itchyny/lightline.vim#201]
Hi,

I've added statusline support for vim-go. This can be now integrated into statusline with native statusline support like:

```viml
" go command status (requires vim-go)
set statusline+=%#goStatuslineColor#
set statusline+=%{go#statusline#Show()}
set statusline+=%*
```

Here is a demo that shows it in action: https://twitter.com/fatih/status/800473735467847680

The demo uses native vim statusline.

I've tried to integrate it into `lightline` and made it work with the following setting (showing only important part):

```viml
let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste'],
      \             [ 'fugitive', 'filename', 'modified', 'ctrlpmark', 'go'] ],
      \   'right': [ [ 'lineinfo' ], 
      \              [ 'percent' ], 
      \              [ 'fileformat', 'fileencoding', 'filetype' ] ]
      \ },
      \ 'component': {
      \   'go': '%#goStatuslineColor#%{LightLineGo()}',
      \ },
      \ 'component_visible_condition': {
      \   'go': '(exists("*go#statusline#Show") && ""!=go#statusline#Show())'
      \ }
      \ }

function! LightLineGo()
  return exists('*go#statusline#Show') ? go#statusline#Show() : ''
endfunction

...
```

The whole lightline setup can be seen here: https://github.com/fatih/dotfiles/blob/master/vimrc#L498

Now when I just open a file this is what I've got:

![screen_shot_2016-11-23_at_11_45_01_am](https://cloud.githubusercontent.com/assets/438920/20555392/88d37c78-b16a-11e6-8db6-e0e682855405.png)

As you see there is a one character placeholder being showed in a completely different color. When `go#statusline#Show()` returns a non empty string, it can be shown like this (for example if you call `:GoBuild`, which is a vim-go command):

![screen_shot_2016-11-23_at_11_43_23_am](https://cloud.githubusercontent.com/assets/438920/20555412/a6541032-b16a-11e6-8047-1d99e91b2b90.png)

We clean status afterwards (after 60 seconds) and `go#statusline#Show()` then returns an empty string: `''`. But then it shows it like this:

![screen_shot_2016-11-23_at_11_47_52_am](https://cloud.githubusercontent.com/assets/438920/20555422/b36b3d18-b16a-11e6-95e6-5612bdb698d6.png)

So my problem is of how to get rid of this single character placeholder shown with arrows? 

Even If I set `component_visible_condition` or I use `g:lightline.inactive.left` and add `[ 'go' ]` it still show it. As seen in the first picture above, in case of an empty `go#statusline#Show()` there is still one character place colored differently.  Do you have an idea what the problem might be? I assume it's because `%#goStatuslineColor#`, but the component is being shown even if `go#statusline#Show()` is empty. If there is a way to hide the `go` component then maybe we can fix this.

I'm going to add instructions to `vim-go` Readme for this, so any help would be helpful for other lightline users.

Thanks

**Comment by itchyny** [comment]
Specifying `raw` type will get rid of that space character.
```vim
let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ], [ 'readonly', 'filename', 'modified' ], [ 'go' ] ]
      \ },
      \ 'component': {
      \   'go': '%#goStatuslineColor#%{LightlineGo()}',
      \ },
      \ 'component_type': {
      \   'go': 'raw',
      \ },
      \ }

function! LightlineGo()
  return exists('*go#statusline#Show') ? go#statusline#Show() : ''
endfunction
```

To be honest, customizing colors of components is very limited in lightline by design because it is a duty of colorschemes. Setting `go#statusline#Show` to `component_function` will satisfy many people in my opinion.

**Comment by fatih** [comment]
Thanks @itchyny, this works and fixes the problem. 

I agree that it will satisfy a lot of people, however I believe that color's improve the user experience a lot. For example this is how it looks for certain conditions if color is enabled:

Started: 
![screen shot 2016-11-23 at 1 58 53 pm](https://cloud.githubusercontent.com/assets/438920/20559388/dc329d6a-b17c-11e6-8846-5c035e5ccc12.png)


Success:
![screen shot 2016-11-23 at 1 59 15 pm](https://cloud.githubusercontent.com/assets/438920/20559392/e1a3aece-b17c-11e6-9cfb-89176022a3bf.png)


Failure:
![screen shot 2016-11-23 at 1 59 29 pm](https://cloud.githubusercontent.com/assets/438920/20559395/e3ec5f96-b17c-11e6-93ca-abb35db3db79.png)

Thanks again for the clue.
