### ISSUE TITLE
How can I change the separator between status lines in different panes?

### ISSUE THREAD

**Issue by flybayer** [itchyny/lightline.vim#202]
As you can see in the below screenshot, I have two vim panes open.

The problem is the small gray rectangle that doesn't match the pane divider.

![image](https://cloud.githubusercontent.com/assets/8813276/20576782/f3263128-b184-11e6-97e2-6e281f51a24b.png)

I can make it look like this:

![image](https://cloud.githubusercontent.com/assets/8813276/20576989/e75e4f3c-b185-11e6-9252-f85d95b1fe66.png)

by setting
```vim
highlight StatusLine cterm=NONE
highlight StatusLineNC cterm=NONE
```

But I'd really like it to match the pane divider. Any ideas on how I can do this?

Thanks!

P.S. This split UI is accomplished with;
```vim
set fillchars+=vert:│
highlight VertSplit ctermbg=NONE guibg=NONE
```

**Comment by itchyny** [comment]
I'm afraid this is impossible. Which color do you expect it to be equal to? How about this configuration? Be sure to update lightline because I changed the highlight group names recently (but will never, I guess...).
```vim
hi! link StatusLineNC LightlineRight_normal_0
hi! link StatusLine LightlineRight_normal_0
```

**Comment by flybayer** [comment]
Ok! The color in the first screenshot is correct, but it's not using the same divider character as the pane divider. So it's much wider. I want them to be the same width (skinny).

Closing. If anyone figures out a way, please let me know!
