### ISSUE TITLE
The abbreviation behavior of tabline should be configurable

### ISSUE THREAD

**Issue by ShikChen** [itchyny/lightline.vim#204]
Currently, the behavior is fixed in [autoload/lightline.vim#L453](https://github.com/itchyny/lightline.vim/blob/e46447e/autoload/lightline.vim#L453). But I think I am not the only one who want to customize this in vimrc 🐱

**Comment by itchyny** [comment]
I agree with you but I cannot imaging a nice api to fulfil configurability of this function. After all, anyone can customise as they wish by overwriting the component.
```vim
let g:lightline = {
...
      \   'component_expand': {
      \     'tabs': 'LightlineTabs'
      \   },
...

function! LightlineTabs()
  " whatever
endfunction
```
