### ISSUE TITLE
Refresh `tabs` component

### ISSUE THREAD

**Issue by pwntester** [itchyny/lightline.vim#205]
I have a custom `tabs` component that uses a custom function:
```
    \ 'component_expand': {
    \   'tabs': 'LightLineBufferTabs',
    \ },
```

This function is successfully called when a new window is created (eg: `tabnew`) but I need it to get called when entering a buffer instead. I saw in the code that when entering a new window `lightline#update()` gets called:

```
autocmd WinEnter,BufWinEnter,FileType,ColorScheme,SessionLoadPost * call lightline#update()
```

so I tried adding an autocmd for `BufEnter` to call it:

`autocmd BufEnter * call lightline#update()`

However the `tabs` component does not get refreshed. Not even when calling `lightline#update()` directly.

Any idea what Im missing?

Thanks!

**Comment by itchyny** [comment]
OK. This is actually an inconvenient behaviour so I fixed the logic. Please update this plugin and you may not need to call `lightline#update()` to see your component updated.

**Comment by pwntester** [comment]
Awesome, thanks!

Just in case it comes handy for someone, this is the function I use to use the tabline as a bufferline:

```
function! LightLineBufferTabs()
    let buflist = filter(range(1,bufnr('$')),'buflisted(v:val) && "quickfix" !=? getbufvar(v:val, "&buftype")') 
    let tabline_before = []
    let tabline_current = []
    let tabline_after = []
    let isBeforeCurrent = 1
    for buf_nr in buflist
        if buf_nr == winbufnr(0)
            let isBeforeCurrent = 0
            let tabline_current += [buf_nr]
        else
            if isBeforeCurrent
                let tabline_before += [buf_nr]
            else
                let tabline_after += [buf_nr]
            endif
        endif
    endfor
    let tabline_before = map(tabline_before, "fnamemodify(bufname(v:val), ':t') . (getbufvar(v:val, '&mod')?' *':'')")
    let tabline_current = map(tabline_current, "fnamemodify(bufname(v:val), ':t') . (getbufvar(v:val, '&mod')?' *':'')")
    let tabline_after = map(tabline_after, "fnamemodify(bufname(v:val), ':t') . (getbufvar(v:val, '&mod')?' *':'')")
    return [tabline_before, tabline_current, tabline_after]
endfunction
```

Maybe it could be added to lightline as an alternative to tabs

Thanks,
A
