### ISSUE TITLE
Is it possible disabled lightline.vim in specific buffer name.

### ISSUE THREAD

**Issue by pocari** [itchyny/lightline.vim#206]
I want to disable lightline.vim in specific buffer name.

Because I use [denite.nvim](https://github.com/Shougo/denite.nvim) plugin.
It create custom window and the window's statusline is rendered by denite itself (named "[denite]").

If buffer name is [denite], I wan to disable updating statusline by lightline.

**Comment by itchyny** [comment]
No, there's no way to disable in specific buffers.

**Comment by pocari** [comment]
Thanks!
It was able to solve by obtaining and displaying the information of denite from lightline configration.
