### ISSUE TITLE
Issues when splitting windows

### ISSUE THREAD

**Issue by n9code** [itchyny/lightline.vim#207]
When using startify with lightline.vim installed, an error occurs when splitting the window.

How to reproduce:
1. Start vim with startify and lightline enabled
2. Split the window (any of `sp` and `vsp`)

Error:

```
Error detected while processing function lightline#update[9]..lightline#statusline[2]..lightline#highlight:                                                                          
line   18:                                                                                                                                                                           
E254: Cannot allocate color guibg= 
```

**Comment by n9code** [comment]
Not sure where this bug belongs exactly, so duplicated for both plugins:
https://github.com/mhinz/vim-startify/issues/254

**Comment by itchyny** [comment]
I cannot reproduce this problem with following configuration.
```
set nocompatible
filetype off
set runtimepath+=/path/to/lightline
set runtimepath+=/path/to/startify
set background=dark
set laststatus=2
filetype plugin indent on
syntax enable
```
```sh
vim -u /path/to/the/above/vimrc
:vsp
```

**Comment by n9code** [comment]
Looks like this happens even without startify, but I really cannot track it down. My dotfiles are here: https://github.com/n9code/dotfiles

**Comment by itchyny** [comment]
https://github.com/n9code/dotfiles/blob/313cdf278654b33a08e2aed409615f44ed6eee8b/.vim/autoload/lightline/colorscheme/solarized_dark_n9code.vim#L60-L62
Here you have to specify gui colors. lightline does not accept abbreviation like this so that colorschemes should be available for both cui and gui environments.

**Comment by n9code** [comment]
Oh man, you saved my day, thanks a lot @itchyny!

*Off-topic:* After fixing this, I started to get the following (the `^`s instead of spaces):
<img width="263" alt="screen shot 2016-12-09 at 7 16 55 am" src="https://cloud.githubusercontent.com/assets/3033265/21036516/c631ed30-bddf-11e6-8ae7-32977e7dc72d.png">

**Comment by n9code** [comment]
Could this be because of `:help fillchars`?

> Any one that is omitted will fall back to the default.  For "stl" and
"stlnc" the space will be used when there is highlighting, '^' or '='
otherwise.

If so, what would be a workaround?

**Comment by itchyny** [comment]
Hmm, looks weird. You seem to be specify spaces [here](https://github.com/n9code/dotfiles/blob/003b87f36d327546d6555d209e64b0a8e96678d2/.vim/vimrc.d/settings.vim#L27). I'm not sure but the [highlight configuration here](https://github.com/n9code/dotfiles/blob/003b87f36d327546d6555d209e64b0a8e96678d2/.vim/vimrc.d/plugin_lightline.vim#L32-L33) can be related to it.

**Comment by n9code** [comment]
yep, that's what I'm concerned about. However, setting `ctermfg` and `ctermbg` colors to different values, does not help 😕

**Comment by itchyny** [comment]
Can you test what it looks like without lightline?

**Comment by n9code** [comment]
With bg and fg set to the same color:

<img width="554" alt="screen shot 2016-12-09 at 7 36 35 am" src="https://cloud.githubusercontent.com/assets/3033265/21036847/407e1efe-bde2-11e6-96bc-3aefe9b1ef1d.png">

**Comment by itchyny** [comment]
lightline specifies different colors for bg and fg so can you try with the different colors?

**Comment by n9code** [comment]
I explained it wrong. The screenshot I posted is with lighline turned off and with:

```
hi StatusLine ctermbg=10 ctermfg=10 cterm=NONE guibg=NONE guifg=NONE gui=NONE
hi StatusLineNC ctermbg=10 ctermfg=10 cterm=NONE guibg=NONE guifg=NONE gui=NONE
```

**Comment by n9code** [comment]
Actually, the original reason I touch `StatusLine` and `StatusLineNC` is this effect I want to avoid (see left to `NORMAL`):

<img width="298" alt="screen shot 2016-12-09 at 7 46 48 am" src="https://cloud.githubusercontent.com/assets/3033265/21037021/c995feae-bde3-11e6-9e68-7079e5d37574.png">

*The last character of inactive window status line (or first character of active status line) is highlithed with the default `StatusLine` group (or default `StatusLineNC` group).*

**Comment by itchyny** [comment]
Okay. How about using `cterm=bold` instead of `cterm=NONE` for `StatusLine` (only, not for `StatusLineNC`)? It will make no differences in the appearance.

**Comment by n9code** [comment]
@itchyny it worked with this config 👍 :
```
hi StatusLine ctermbg=10 ctermfg=10 cterm=bold guibg=NONE guifg=NONE gui=NONE
hi StatusLineNC ctermbg=10 ctermfg=10 cterm=NONE guibg=NONE guifg=NONE gui=NONE
```

**Comment by itchyny** [comment]
Thanks.
