### ISSUE TITLE
(sub)separator value mathing against lists

### ISSUE THREAD

**Issue by petervaro** [itchyny/lightline.vim#208]
*(This is a feature request to improve the configurability of this otherwise very flexible project)*

It would be very nice if both the `'separator'` and the `'subseparator'` keys' `'left'` and `'right'`  values in `g:lightline` would match againt lists instead of single values.

Eg.

```vim
let g:ligthline = {
    \ 'active': {
    \     'left': [
    \         ['mode', 'paste'],
    \         ['relativepath', 'modified']
    \         ]
    \     },
    \ 'subseparator': {
    \     'left': ['>', '']
    \     }
    \ }
 ```

This would put `'>'` between `'mode'` and `'paste'`, but nothing between `'relativepath'` and `'modified'`

**Comment by itchyny** [comment]
I don't think it is such useful and I'm afraid it is not worth implementing at the sacrifice of performance regression checking the type of subseparator, due to a function most of people would not use. You can create your own component to concatenate the two components.
```vim
let g:ligthline = {
    \ 'active': {
    \     'left': [
    \         ['mode', 'paste'],
    \         ['relativepath_modified']
    \         ]
    \     },
    \ 'component': {
    \     'relativepath_modified': '%f %M'
    \     },
    \ 'subseparator': {
    \     'left': '>'
    \     }
    \ }
```
The component functions are more flexible.

**Comment by petervaro** [comment]
👍 well, I guess you are right on this one.. anywho, thanks for you consideration and the workaround you posted! Keep up the good work, lightline is more than awesome ;)

**Comment by itchyny** [comment]
Thanks.
