### ISSUE TITLE
[question] about themes

### ISSUE THREAD

**Issue by lanox** [itchyny/lightline.vim#209]
Hi 

Just a question, I have customised the powerline theme as I didn't like the blue for INSERT to how I like it. What would be the best way to load a theme ? is it possible to store it outside ```~/.vim/bundle/lightline.vim/autoload/lightline/colorscheme``` and load it with colorscheme in vimrc ?

Thanks.

**Comment by itchyny** [comment]
Yes, please refer to `:h lightline-colorscheme`. You can add (and distribute) your lightline colorscheme.

**Comment by lanox** [comment]
sheesh i feel like idiot, I even read that ..

thanks.

**Comment by lanox** [comment]
@itchyny I have read that, but I am not sure if that answers my question, my new custom theme, can I save in in /tmp dir (for example) and load it from .vimrc

**Comment by itchyny** [comment]
You can use `:source {filename}` to read that file and specify the name of that colorscheme.
