### ISSUE TITLE
Lightline Syntax Group

### ISSUE THREAD

**Issue by 0phoff** [itchyny/lightline.vim#210]
Is it possible to create Syntax Groups for lightline?

I am asking this because I am using Vim-Devicons and wanted to color the icons. For that I created a Syntax group and they work inside any buffer (nerdtree, unite, and any file that uses them), but the highlighting doesnt seem to work for the lightline...

For every different color I have these 2 lines in my configs:
```vim
hi! deviconsBlue  guifg=#689FB6 ctermfg=73
autocmd Syntax * syntax match deviconsBlue /\v||/ containedin=ALL
```

I dont know whether lightline is considered as a buffer with a filetype, but reading through the docs I dont think thats the case?
I read the docs where you explain about colorschemes  and the error/warning component expansion, but I did not fully understand it...

It would be nice if lightline had support for Syntax/Highlight groups as this is the default way of handling text colors in any other part of VIM. I know the statusline is different and thus it might be difficult to implement that... Let me know if it is possible to add support for syntax highlighting, or how I should proceed to highlight my icons otherwise!

Also, these icons are part of my filename component and I would like to only color the icons and not the the text if that is possible! (if its not possible Im happy with the entire component being of one color)

Thanks for your time/answer!

Lightline Settings:
```vim
let g:lightline = {
    \ 'colorscheme' : 'gruvbox',
    \ 'active': {
    \   'left':     [ ['mode', 'paste'],
    \                 ['fileNameMod'] ],
    \   'right':    [ ['linenumber'],
    \                 [''],
    \                 ['filetype', 'projectPath', 'rootDir'] ]
    \ },
    \ 'component_function': {
    \   'projectPath': "LLpath",
    \   'fileNameMod': "LLfile",
    \   'rootDir': "LLroot",
    \   'linenumber': "LLline"
    \ },
    \ 'separator': { 'left': '', 'right': '' },
    \ 'subseparator': { 'left': '', 'right': '' }
    \ }

    function! LLfile()
        return ('' != expand('%:t') ? WebDevIconsGetFileTypeSymbol() . expand('%:t') : '[No Name]') .
            \ ('' != LLtype() ? ' '.LLtype() : '')
    endfunction

    function! LLtype()
        if &readonly || !&modifiable
            return ''
        elseif &modified
            return '+'
        else
            return ''
        endif
    endfunction
```

**Comment by itchyny** [comment]
The lightline is not inside the buffers, it just configures the statusline. If I am correct you're going to color the icons, and `:h lightline-problem-12` might help.

**Comment by 0phoff** [comment]
Thanks for the reply!
I got a basic version working, but I dont like the fact that I have to put it in lightline.component and that the Syntax group is thus fixed, requiring me to call highlight every time I change the file...

Is there a way to call a function that programatically expands the string
```vim
"%#SYNTAX_GROUP%#{fun()}"
``` 
That way I can construct the string myself and thus change what Syntax group I'm using.
I think thats what the component_expand is for, but I couldnt find any clear example on how to use that...

If this is not really possible, or not how lightline is supposed to be used, I'll accept my hacky way.. :clown_face:

**Comment by itchyny** [comment]
I'm not sure how you install the plugin but the following code might have some hints for using the palette in the configuration.
```
augroup lightline-init
  autocmd!
  autocmd VimEnter * call s:init()
augroup END
function! s:init()
  let palette = lightline#palette()
  " Do something with palette.
endfunction
```

**Comment by 0phoff** [comment]
I am using vim-plug as my plugin manager..

```vim
call plug#begin()
    ...
    Plug 'itchyny/lightline.vim'                    " Lightweight and customizable 
    ...
call plug#end()
...
let g:lightline = { ... }
...
function! ColDevicons_init()
    let colors = keys(g:coldevicons_colormap)
    let pal = lightline#palette()
    ...
endfunction
call ColDevicons_init()
```

The error I am getting when starting vim is:
```
Error detected while processing function ColDevicons_init[2]..lightline#palette:
line    1:
E121: Undefined variable: s:lightline
E15: Invalid expression: s:lightline.palette
Press ENTER or type command to continue
```

If i continue and then call ColDevicons_init() myself, it runs without errors!

**Comment by 0phoff** [comment]
OK tried it with the autocmd and it's working now...
I guess that autocmd delayed the execution enough for lightline to have been called or something?
(still don't fully understand why though..)

I guess you can close this issue now!
Thanks for your help!! :+1:

[Link to my dotfiles for people who want a similar setup](https://github.com/0phoff/DotFiles/tree/master/Vim)
