### ISSUE TITLE
Triangles are larger than the line area

### ISSUE THREAD

**Issue by jjcall** [itchyny/lightline.vim#211]
Been trying to figure out this one for a while. The triangles expand larger than the bar. I've tried messing with font sizing, but nothing. Ideas?

<img width="718" alt="screen shot 2017-01-30 at 11 49 45 am" src="https://cloud.githubusercontent.com/assets/12879/22432226/3b818458-e6e2-11e6-9cd2-bef77eac45e2.png">

**Comment by itchyny** [comment]
This is a problem of font rendering and this plugin cannot configure. I'm not sure it solves this problem, there're two types of fancy font and using the other might help.
