### ISSUE TITLE
[Feature request] Modify default theme so inactive third section doesn't have jetblack background.

### ISSUE THREAD

**Issue by trusktr** [itchyny/lightline.vim#212]
For example, in the screenshot, the inactive window show "master" with a dark black background:

![screen shot 2017-02-05 at 2 41 15 am](https://cloud.githubusercontent.com/assets/297678/22625481/0318b270-eb4d-11e6-878a-b317429635d0.png)

Can you change that so the background is the same color as the mid section of the statusline, similarly to how the active window's git branch section is the same color as the mid-section of the statusline?

**Comment by itchyny** [comment]
I cannot change the color of the default theme because too many people use the theme. The color of that part is not that bad, but you can create your own colorscheme if you wish.
