### ISSUE TITLE
[feature request] Fifth colormode for TERMINAL mode.

### ISSUE THREAD

**Issue by trusktr** [itchyny/lightline.vim#214]
Not sure if this needs any extra feature added for it to work, or maybe a colorscheme can currently be configured for it to work, but it'd be sweet to have a new color combination for when in Neovim's TERMINAL mode.

Lightline currently shows the INSERT colors in TERMINAL mode, which is already much nicer than airline which stays in NORMAL color when entering TERMINAL mode.

**Comment by itchyny** [comment]
Yes, you can specify the colors for terminal, but I don't have time to configure for the colorschemes, also I do not use neovim so I'm not going to implement this feature. You can create your own colorscheme so please refer to `:h lightline-colorscheme'`.
```diff
+let s:p.terminal.left = [ (you can specify colors for terminal here) ]
```
