### ISSUE TITLE
Is there a way to link have a custom colorscheme in a different directory?

### ISSUE THREAD

**Issue by db-ryan** [itchyny/lightline.vim#217]
It would be awesome to be able to put a custom colorscheme in a file outside of the repo (/.vim/bundle/etc...). Is it possible to do something like this?

let g:lightline = {
   \ 'colorscheme': '~/dotfiles/vimrc/frankelColorScheme.vim'
}

**Comment by itchyny** [comment]
Yes.
```vim
source ~/dotfiles/vimrc/frankelColorScheme.vim
let g:lightline = {
\ 'colorscheme': 'frankelColorScheme'
}
```

**Comment by db-ryan** [comment]
Awesome.  That worked for me.

**Comment by pabloaguirrenck** [comment]
Did as recommended, ended up with the following error when opening vim:

lightline.vim: Could not load colorscheme lumiere-lightline.
Error detected while processing function lightline#update[5]..lightline#colorscheme[18]..ligh
tline#highlight:
line    2:
E716: Key not present in Dictionary: normal.left), len(c.normal.right)]
E116: Invalid arguments for function len(c.normal.left), len(c.normal.right)]
Error detected while processing function lightline#update:
line    5:
E171: Missing :endif
Press ENTER or type command to continue
