### ISSUE TITLE
Unknown Characters in README

### ISSUE THREAD

**Issue by pankajpatel** [itchyny/lightline.vim#218]
Hello,
In the readme, there are many sections with information of different characters like this:
```vim
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'component': {
      \   'readonly': '%{&readonly?"⭤":""}',
      \ },
      \ 'separator': { 'left': '⮀', 'right': '⮂' },
      \ 'subseparator': { 'left': '⮁', 'right': '⮃' }
      \ }
```
Now these sections always have `⮀`, but no actual character; which makes it difficult to just copy and paste the configs to `vimrc`.

How can this be solved? Is it something README is lacking or the browser?

**Comment by mschilli87** [comment]
The box represents a character missing in the font.
The ones used by lightline will be provided by the patched fonts mentioned in the `README`.
You can see that they actually are different by copy-pasting them into a file and running `od -c < <file> | less`.

**Comment by pankajpatel** [comment]
Makes sense. This is what I got:
```
0000000    l   e   t       g   :   l   i   g   h   t   l   i   n   e
0000020    =       {  \n                           \       '   c   o   l
0000040    o   r   s   c   h   e   m   e   '   :       '   w   o   m   b
0000060    a   t   '   ,  \n                           \       '   c   o
0000100    m   p   o   n   e   n   t   '   :       {  \n
0000120            \               '   r   e   a   d   o   n   l   y   '
0000140    :       '   %   {   &   r   e   a   d   o   n   l   y   ?   "
0000160  342 255 244   "   :   "   "   }   '   ,  \n
0000200        \       }   ,  \n                           \       '   s
0000220    e   p   a   r   a   t   o   r   '   :       {       '   l   e
0000240    f   t   '   :       ' 342 256 200   '   ,       '   r   i   g
0000260    h   t   '   :       ' 342 256 202   '       }   ,  \n
0000300                    \       '   s   u   b   s   e   p   a   r   a
0000320    t   o   r   '   :       {       '   l   e   f   t   '   :
0000340    ' 342 256 201   '   ,       '   r   i   g   h   t   '   :
0000360    ' 342 256 203   '       }  \n                           \
0000400    }
0000401
(END)
```

Though, how can it be used in the lightline?

**Comment by itchyny** [comment]
You can skip the configuration if you don't use patched font.

I'm actually planning to remove the config based on the patched fonts from README because it sometimes make beginners confusing that lightline requires patched fonts. The style was cool years ago but I shouldn't have recommend a config which requires the special font, leading less portability.

**Comment by pankajpatel** [comment]
@itchyny it can go as a separate or Advanced README.

**Comment by pankajpatel** [comment]
But few things are really useful, like readonly character.
Separators can be dropped from main README as it will serve only being fancy.

I tried using the emoji keys and it looked fine (few background issues, but that's affordable):
<img width="96" src="https://cloud.githubusercontent.com/assets/251937/23790825/04ab8038-0581-11e7-8aeb-2c2dcd9e3960.png">
