### ISSUE TITLE
lightline doesn't load on vim startup

### ISSUE THREAD

**Issue by jonathaw** [itchyny/lightline.vim#219]
I installed lighline, but I have to run source .vimrc to get the status line to show as lightline. any ideas?

thanks

**Comment by itchyny** [comment]
I have no clue what's happening on your editor. Please describe the steps how to reproduce and what's in your vimrc.

**Comment by jonathaw** [comment]
I installed lightline (and all other plugins I use) with Vundle, and have PaperColor as the color scheme.
some vimrc stuff i have i think might be relevant are:

set laststatus=2
set t_Co=256  
set background=dark
colorscheme PaperColor

I realised that the status line does become lightline if I invoke any plugin, such as buufergator for instance. not sure how these are related.
thanks!
