### ISSUE TITLE
extend tabs in tabline to full width of app window

### ISSUE THREAD

**Issue by tap349** [itchyny/lightline.vim#220]
good day!

when I create many tabs I get ellipsis in the middle:

[screenshot](https://monosnap.com/file/iazE21n9uzdKDCxwAAX74wyO0Q9Hqo)

AFAIK in lightline both tabline and statusline are split in 3 parts: left, middle and right.
I specify `tabs` in left part in tabline configuration:

```vimscript
let g:lightline.tabline = { 'left': [['tabs']], 'right': [['close']] }
```

but it turns out that left part has maximum width that is approximately half the width of vim app window.
desirable behaviour is to have tabs that occupy full width of app window - with arrows on both sides that signify that there are more tabs on either left or right side.

is it possible to have such a behaviour? would vim-bufferline help in this case?

**Comment by itchyny** [comment]
The line below determines the truncate threshold.
https://github.com/itchyny/lightline.vim/blob/a63a00d548fd20457a4f31d31fb9c8fe8a7ebc2a/autoload/lightline.vim#L453
What does `:echo winwidth(0)` print? I think I can extend the threshold but the 80 items limit (see `:h E541`) is causing much pain for me.

**Comment by tap349** [comment]
@itchyny thanks for your reply.

my window width without splits (`:echo winwidth(0)`) is 158.
this 80 items limit for statusline means that it's possible to create max 80 tabs? for me it's not a problem - I never create that many tabs.

according to your formula tabs width is determined by `g:lightline.winwidth` and will be multiple of 40. by trial and error I've found out that the best `g:lightline.winwidth` for me is 240 - in this case tabs extend almost till close button in upper right corner. but I guess it would be better to have winwidth to be multiple of 20 so that I could set it to 220 - it would allow for longer filenames to fit in tabline without adding `<` on the left.

btw `g:lightline.winwidth` setting is not mentioned in your docs - is it a proper way to configure tabs width?

**Comment by itchyny** [comment]
> this 80 items limit for statusline means that it's possible to create max 80 tabs 

Vim counts the number of `'%' items`. For example, `:echo lightline#tabline()` will print something like `%( %3T%{lightline#onetab(3,0)} %)`, which has four items. Within the 80 items limit, I think about 15~16 tabs can be displayed to avoid the E541 error. That's why I wrote `min([ ..., 8])`.

> I've found out that the best g:lightline.winwidth for me is 240 - in this case tabs extend almost till close button in upper right corner.

I think it's very hard to find the general solution because each tab width varies due to the filenames. But I'm going to update the formula to show more tabs in various width of the terminals.

> g:lightline.winwidth setting is not mentioned in your docs

Oh, I think I did not suppose the field to be configured by users. I think I should tweak the formula to make tabs better.

**Comment by tap349** [comment]
@itchyny as for me I'm used to tabs with `<`, `>` on both sides of tabline when there are too many tabs (just like in vim-airline) - without ellipsis in the middle. but it's just my preference and I don't know if it's easy to implement this behavior or if it's suitable for other users.

so far I'm going to live with `g:lightline.winwidth` setting and will wait for your updates regarding tabs.

thanks )

**Comment by somini** [comment]
Any changes on this? I manually set the `winwidth` variable but I wasn't able to eliminate the ellipsis on my screen.

`winwidth(0)` returns 219 on my screen.
