### ISSUE TITLE
noshowemode showing

### ISSUE THREAD

**Issue by horak** [itchyny/lightline.vim#224]
The readme indicates that:
![image](https://cloud.githubusercontent.com/assets/1111424/24793917/f8ea660e-1bad-11e7-9ffe-7aba6b926fe5.png)

My .vimrc includes that and still has that gap...
![image](https://cloud.githubusercontent.com/assets/1111424/24793980/2da18fe4-1bae-11e7-8676-5a8c79e357c9.png)

What am I missing here?

**Comment by itchyny** [comment]
The README mentions the `-- INSERT --` message under the statusline.

**Comment by horak** [comment]
Sorry, I'm not sure where you mean. So is that screenshot just omitting that insert line? It's actually there?

**Comment by itchyny** [comment]
<img width="943" alt="screen shot 2017-04-08 at 1 48 50 am" src="https://cloud.githubusercontent.com/assets/375258/24810625/e1f5ea90-1bfd-11e7-9a61-c5c0fddffd21.png">
In the above screenshot, the information on the current mode is duplicatededly displayed. Configuring `set noshowmode` stop displaying the Vim's default mode information.

**Comment by horak** [comment]
Gotcha. Great, I'm no longer seeing that mode information twice. Is it possible, as my first screenshot indicates, to get rid of the line entirely?

**Comment by itchyny** [comment]
It's impossible in Vim. How do you input Vim commands?

**Comment by horak** [comment]
Yeah, makes sense. I was thinking maybe it could slide up next to the mode information. Thanks for the great work here!
