### ISSUE TITLE
component_expand not called on buffer edit

### ISSUE THREAD

**Issue by mgee** [itchyny/lightline.vim#225]
I have a function registered as `component_expand`. However, if the function is used in the `active.left` section it is not called when a buffer is edited. If it is used in the `tabline` section it works fine. It does also work fine in the `active.left` section if the function is registered as a `component_function`.

To illustrate the issue a little better I created a small vimrc example (lightline is installed via [vim-plug](https://github.com/junegunn/vim-plug)).
It displays the modified state of the current buffer. The `MyExpand` function in `active.left` does not get called as often as `MyFunction` in `active.left` or `MyExpand` in `tabline`.

```vim
call plug#begin()
Plug 'itchyny/lightline.vim'
call plug#end()

set nocompatible
set laststatus=2
set showtabline=2
set hidden
if has('gui_running')
  " Do not use gui tab apperance
  set guioptions-=e        
endif

let g:lightline = {}
let g:lightline.active = {'left': [['my_expand', 'my_function']]}
let g:lightline.tabline = {'left': [['my_expand']], 'right': [['close']]}
let g:lightline.component_expand = {'my_expand': 'MyExpand'}
let g:lightline.component_type = {'my_expand': 'tabsel'}
let g:lightline.component_function = {'my_function': 'MyFunction'}

function! MyExpand()
  let l:current_buffer = bufnr('%')
  let l:name = bufname(l:current_buffer)
  if getbufvar(l:current_buffer, '&mod')
    let l:name .= '+'
  endif
  return [[], [l:name], []]
endfunction

function! MyFunction()
  return join(MyExpand()[1])
endfunction
```

**Comment by itchyny** [comment]
You are right. The components in `component_expand` is called only after `lightline#update()`. It is an expected behaviour and I cannot change. You can use `component_function` for highly updated information or call `lightline#update()` explicitly for compilation errors like syntastic information.

**Comment by mgee** [comment]
Thanks for your quick answer. I am using the component_expand in the [lightline-bufferline](https://github.com/mgee/lightline-bufferline) plugin and need the component_type functionality for the expand function. Therefore I cannot switch to component_function.

If the expand function is used in the tabline it does get called when the buffer is edited but not if it used in active.left. Is this only solvable by triggering a lightline#update via an autocmd?
