### ISSUE TITLE
%f doesn't control statusline to show relative path

### ISSUE THREAD

**Issue by dayancn** [itchyny/lightline.vim#226]
Hi, relativepath doesn't work when use ctrl + ] to jump to another file.

**Comment by dayancn** [comment]
when I echo the statusline option, it's %f, but it does't work like it should be.

**Comment by dayancn** [comment]
You can use ctags or cscope jump to reproduce this issue.

**Comment by itchyny** [comment]
I cannot reproduce this issue by testing ctags. The relativepath is updated instantly after I jump.

**Comment by dayancn** [comment]
my platform is Ubuntu 14.04, version 7.4.52.

**Comment by itchyny** [comment]
Can you confirm without lightline? You can `set statusline=%f`.

**Comment by dayancn** [comment]
I have confirm with this method yesterday. It's ok without lightline.

**Comment by dayancn** [comment]
this is my configure of lightline:
let g:lightline = {
	\ 'colorscheme': 'wombat',
	\ 'active': {
		\   'left': [ ['mode', 'paste'],
		\             ['fugitive', 'readonly', 'filename', 'modified'] ]
			\ },
	\ 'component': {
		\   'filename': '%f'
			\ },
	\ 'separator': { 'left': '', 'right': '' },
	\ 'subseparator': { 'left': '|', 'right': '|' }
	\ }

**Comment by dayancn** [comment]
I also verified this with powerline, and it's ok.

**Comment by dayancn** [comment]
I have just configured a single plugin with your lightline. But it still doesn't work with %f. I can offer this to you with tarball.

**Comment by dayancn** [comment]
from the scenario, lightline changed %f preference to make it become %t or %F.

**Comment by itchyny** [comment]
lightline cannot modify the preference of statusline flags, if %f is set to &statusline, it should work as it is.
