### ISSUE TITLE
Show character code of character under cursor

### ISSUE THREAD

**Issue by isene** [itchyny/lightline.vim#228]
How do I add the character code of the caracter under the cursor on the right side of lightline?

**Comment by itchyny** [comment]
How about this configuration?

```vim

let g:lightline = {
      \ 'active': {
      \   'right': [ [ 'lineinfo' ],
      \              [ 'percent', 'charcode' ],
      \              [ 'fileformat', 'fileencoding', 'filetype' ] ] },
      \ 'component_function': {
      \   'charcode': 'LightlineCharcode'
      \ }
      \ }

function! LightlineCharcode() abort
  let line = getline('.')
  let col = col('.')
  return col - 1 < len(line) ? printf('\u%04x', char2nr(matchstr(line[(col - 1):], '^.'))) : ''
endfunction
```

**Comment by isene** [comment]
Yup. Incorporated it with what I have and it works fine:

let g:lightline = {
      \ 'colorscheme': 'wombat', 
      \ 'component': { 'readonly': '%{&readonly?"x":""}', },
      \ 'separator': { 'left': '', 'right': '' },
      \ 'subseparator': { 'left': '│', 'right': '│' },
      \ 'active': { 'right': [ [ 'lineinfo' ], [ 'percent', 'charcode' ], [ 'fileformat', 'fileencoding', 'filetype' ] ] },
      \ 'component_function': { 'charcode': 'LightlineCharcode' }
      \ }

**Comment by isene** [comment]
Why 4 digits for the charcode?

I changed it a bit to not have the right side "jump" when it comes to a blank line:

function! LightlineCharcode() abort
  let line = getline('.')
  let col = col('.')
  return col - 1 < len(line) ? printf('C:%02x', char2nr(matchstr(line[(col - 1):], '^.'))) : 'C:  '
endfunction

**Comment by itchyny** [comment]
OK. Configure as you like.
