### ISSUE TITLE
Is it possible to make remove the padding at the bottom?

### ISSUE THREAD

**Issue by Hund** [itchyny/lightline.vim#230]
It feels like there's a lot of wasted space at the bottom. Is it possible to make it more slim?

![vimairline](https://cloud.githubusercontent.com/assets/320498/26008495/5350f286-3745-11e7-8a7f-ba1405413c7a.png)

**Comment by Hund** [comment]
Hm, it seems like it's a issue with my terminal emulator itself. I've never noticed it before. :|

**Comment by lokesh-krishna** [comment]
@Hund I am using Gnome Terminal and have the same problem. Did you manage to solve it?

**Comment by GuijonGustavo** [comment]
Try with:

:set cmdheight=1
