### ISSUE TITLE
Dracula colorscheme transparency

### ISSUE THREAD

**Issue by LER0ever** [itchyny/lightline.vim#231]
Dracula Vim theme has enabled background transparency on terminal recently, but the arrows of lightline is still plain color, which looks a little bit inconsistent.

Like this...
![image](https://cloud.githubusercontent.com/assets/10568668/26518870/874a7b78-42eb-11e7-844e-6e55ecf2a26f.png)

**Comment by itchyny** [comment]
Unfortunately it is an limitation of iTerm2. The README.md of lightline.vim suggests to disable transparency and contrast configurations. Related issues: https://github.com/powerline/powerline/issues/65, https://github.com/gnachman/iTerm2/pull/277.

**Comment by LER0ever** [comment]
Sorry I missed that part in README. The color under VimR seems fine, and it works perfectly without transparency under iTerm2. So I'll close this issue since it's unrelated to lightline.vim.
