### ISSUE TITLE
Hello, how can I change the color of the '+' in the line?

### ISSUE THREAD

**Issue by Lovin0730** [itchyny/lightline.vim#232]
May be this way clear:
![image](https://cloud.githubusercontent.com/assets/10047788/26643198/23976278-4663-11e7-8dbd-8699b850c84d.png)
**look at the minus, the mark of modified files, It's red.**
How can I do this with lightline?

**Comment by itchyny** [comment]
See `:h lightline-problem-12`, it's surely possible, but I don't recommend this complicated configuration. Basically lightline.vim does not allow users to modify colours like this.

**Comment by Lovin0730** [comment]
@itchyny It works! Thank you.
