### ISSUE TITLE
Extraneous spaces when overloading a component

### ISSUE THREAD

**Issue by aldanor** [itchyny/lightline.vim#235]
I was trying to see if the example from `:h lightline-problem-12` works (#232), with a jellybeans scheme (this is a simplified version; the bg color is intentionally different so it's easier to see what happens):

```vim
let g:lightline = {
      \ 'colorscheme': 'jellybeans',
      \ 'component': {
      \   'modified': '%#ModifiedColor#%{LightlineModified()}',
      \ }
      \ }

function! LightlineModified()
  hi ModifiedColor ctermfg=167 guifg=#cf6a4c ctermbg=242 guibg=#666656 term=bold cterm=bold
  return &modified ? '+' : &modifiable ? '' : '-'
endfunction
```

The problem is that if I return `''`, then there are extra spaces in the previous section which, surprisingly, doesn't happen when the component is not overloaded.

When the returned string is non-empty, it works fine:
<img width="171" alt="screen shot 2017-07-02 at 13 18 04" src="https://user-images.githubusercontent.com/2418513/27769764-2bd3ac2e-5f29-11e7-8922-21a3065b62bc.png">

When it's empty though, note the extra spaces after `.vimrc`, both in the component and in the previous section:
<img width="154" alt="screen shot 2017-07-02 at 13 18 17" src="https://user-images.githubusercontent.com/2418513/27769765-35255908-5f29-11e7-85d6-b43bfee02ce4.png">

----

For comparison, here's default `jellybeans` without overloading the modified component:
<img width="139" alt="screen shot 2017-07-02 at 13 18 45" src="https://user-images.githubusercontent.com/2418513/27769766-39353662-5f29-11e7-8b4a-816c77807c8b.png">

**Comment by itchyny** [comment]
How about specifying `component_type` to `raw`?
```vim
let g:lightline = {
      \ 'colorscheme': 'jellybeans',
      \ 'component': {
      \   'modified': '%#ModifiedColor#%{LightlineModified()}',
      \ },
      \ 'component_type': {
      \   'modified': 'raw',
      \ }
      \ }
```
The raw type might be difficult until understanding the relation between the lightline configuration and `&statusline` deeply...

**Comment by aldanor** [comment]
@itchyny Thanks! That kind of seems to work if extra spaces are added to the return string:

```vim
  return &modified ? '  + ' : &modifiable ? '' : '  - '
```

I'm not sure whether it should be mentioned in the help (e.g. "try using the raw component type if things don't look the way you expect them to")?

**Comment by itchyny** [comment]
Configuring colors of the components has some troubles like this. Just debug `&statusline` to see what's happening. In your first config, it looks like `%( %#ModifiedColor#%{LightlineModified()} %)`, and the space after `%{LightlineModified()}` and `%)` is visible as your screenshot. The components of lightline are enclosed by `%(...%)` but by specifying raw type will allow them to escape from it.

**Comment by aldanor** [comment]
Yep indeed - thanks a lot for the explanation! I'll close this then for now.
