### ISSUE TITLE
How can I point to my own colorscheme or submit a new one?

### ISSUE THREAD

**Issue by vegangaro** [itchyny/lightline.vim#238]
Hi, 

At work, it bothers me all those shiny color in available colorscheme. 

There is a way to point to a scheme that I adapted to grayish colors?

Thanks! 

[My Colorscheme (PaperColor_Night adapted) ](https://raw.githubusercontent.com/vegangaro/dotfiles/master/Images/Terminalscreen/archi3tmuxvim.png)

**Comment by itchyny** [comment]
You can create your own colorscheme and publish to GitHub, managed as an independent colorscheme plugin for lightline. Please refer to `:h lightline-colorscheme`.

**Comment by vegangaro** [comment]
Oh, ok! Lemme try!

**Comment by itchyny** [comment]
Examples: https://github.com/popkirby/lightline-iceberg, https://github.com/felixjung/vim-base16-lightline

**Comment by vegangaro** [comment]
Wont work:

`lightline.vim: Could not load colorscheme graynito.`

**Comment by itchyny** [comment]
Did you add your plugin managed by vim plugin manager?

**Comment by vegangaro** [comment]
yes. Please try ourself! 

https://github.com/vegangaro/graynito

**Comment by vegangaro** [comment]
My vimrc:

`Plug 'vegangaro/graynito'
`

```
let g:lightline = {
      \ 'colorscheme': 'PaperColor',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'fugitive#head'
      \ },
      \ }



```

**Comment by itchyny** [comment]
I found a typo at the last line of graynito_light.vim, `graynito` not `graynit`.

**Comment by vegangaro** [comment]
I think there are more issues I will try everything again!

**Comment by vegangaro** [comment]
Done. All working! Could debug it through cause I was in a hurry! haha...

Thanks. 

Grayish ColorScheme: https://github.com/vegangaro/graynito

**Comment by itchyny** [comment]
Congrats!
