### ISSUE TITLE
reload lightline's config without having to quit/launch (n)vim

### ISSUE THREAD

**Issue by rotsix** [itchyny/lightline.vim#241]
Hi!

First thanks for this amazing bar.

Having a question: is there a way to reload the lightline's config without having to quit/launch (n)vim ?

**Comment by itchyny** [comment]
Calling the following three functions will reload the config.

- `lightline#init()`
- `lightline#colorscheme()`
- `lightline#update()`

For example:
```vim
command! LightlineReload call ReloadLightline()

function! ReloadLightline()
  call lightline#init()
  call lightline#colorscheme()
  call lightline#update()
endfunction
```

**Comment by rotsix** [comment]
Working, thanks!

**Comment by nikaro** [comment]
Hi,

These functions does not seem to reload "line's theme". If i change the `background` setting and/or the `colorscheme`, and then call `LightlineReload`, it does update its colors.

Am i missing something?

**Comment by itchyny** [comment]
@nikaro Refer to #424.
