### ISSUE TITLE
Limit of tabs in upper tabline

### ISSUE THREAD

**Issue by adam0z** [itchyny/lightline.vim#243]
Where could I change the limit of visible tabs in upper tabline?

When I open more than 5 tabs, I see only 5 file names and dots between them (| ... |).

**Comment by itchyny** [comment]
The tab truncation is calculated by window width; `winwidth(0)`. What does `:echo winwidth(0)` print? May I see some screenshot?

**Comment by elig0n** [comment]
I experience the same issue.  winwidth(0) returns varying values depending on the terminal/window size but the tab bar always truncate at 5 tabs.

**Comment by elig0n** [comment]
@itchyny 
can I get a reply regarding this ?
Here's a screenshot: https://ibb.co/h8JtqHL

**Comment by yhu266** [comment]
Number of tabs is limited as:
https://github.com/itchyny/lightline.vim/blob/1b412cf3af3dad79ee5807e6b151b8ac6aa4e2fc/autoload/lightline.vim#L468

And I don't see any issues here. For example, here's a window with 7 tabs:

<img width="470" alt="image" src="https://user-images.githubusercontent.com/56977205/91761282-7a1d2a00-eb89-11ea-9014-8e9f8b17a8dc.png">

**Comment by elig0n** [comment]
In the screenshot I posted above you can see that in my instance the maximum tabline width isn't used . 
My tabline also displays the 'X' close button and "hides" tabs of the middle range showing "..." instead while there is still many room to show more tabs.
Actually I would have prefered to just let the tabs grow naturally and not even hide them.

**Comment by yhu266** [comment]
What I meant, with "no issues", is that the number of tabs is not limited to 5.

As for the display of tabs, I think the upper limit of tabs (5 with your configurations) is determined by the line I referenced. So it is designed to have a maximal of 8 tabs, and to not fill the entire tabline, and use "..." to truncate tabs. We only have 10 number keys after all.

If you'd like to add features to allow more tabs, feel free to discuss more!
