### ISSUE TITLE
Component ellipsis in tabline

### ISSUE THREAD

**Issue by mildred** [itchyny/lightline.vim#244]
Hi,

I have as part of my MRU plugin a component that shows a list of buffers in the tabline. When there is more buffers that can fit in the window, however, the first elements of the tabline are not shown, only the right part of the tabline is shown.

How would it be possible to control the ellipsis? I have a few ideas:

- the component function could be given as argument the maximum width available for the component, and the component is responsible to return less characters so they can be shown
- the component could return multiple elements and given a weight on each of them for which can be hidden and which should not
- ...

**Comment by itchyny** [comment]
I haven't looked into your plugin code but you may try using `%<`.

**Comment by mildred** [comment]
I didn't know of that, but I don't think this is flexible enough for what I want. I want to be able to make ellipsis in the middle of the tabline.

I found a solution that works nicely for simple use cases: use `winwidth(0)` to get the current window width and substract a constant number (10 for example) that should be configurable that accounts for other components on the tabline. In .vimrc, when you configure lightline, you can in most cases know which place other components will take.
