### ISSUE TITLE
Display Current Working Directory In Tab Names

### ISSUE THREAD

**Issue by joshdick** [itchyny/lightline.vim#245]
I'm asking for something very similar to vim-airline/vim-airline#1357; I want working directories to display as tab names in my lightline.vim tab bar.

I have managed to hack something together that doesn't work quite right, and am hoping I can be pointed in a better direction.

First, I have configuration adapted from [Sane Vim Working Directories](http://inlehmansterms.net/2014/09/04/sane-vim-working-directories/) that looks like this, which attempts to store working directories in tab-scoped variables:

```vim
" follow symlinked file
function! FollowSymlink()
  let current_file = expand('%:p')
  " check if file type is a symlink
  if getftype(current_file) == 'link'
    " if it is a symlink resolve to the actual file path
    "   and open the actual file
    let actual_file = resolve(current_file)
    silent! execute 'file ' . actual_file
  end
endfunction

" set working directory to git project root
" or directory of current file if not git project
function! SetProjectRoot()
  " default to the current file's directory
  lcd %:p:h
  let git_dir = system("git rev-parse --show-toplevel")[:-2]
  " See if the command output starts with 'fatal' (if it does, not in a git repo)
  let is_not_git_dir = matchstr(git_dir, '^fatal:.*')
  " if git project, change local directory to git project root
  if empty(is_not_git_dir)
    lcd `=git_dir`
    let t:cwd = fnamemodify(git_dir, ':t') " <-- Stores the working directory in a tab-scoped variable
  endif
endfunction

" follow symlink and set working directory
autocmd BufRead *
  \ call FollowSymlink() |
  \ call SetProjectRoot()
```

I then have lightline.vim configuration that looks like this, which pulls the working directory out of the tab-scoped variable:

```vim
function! CustomTabname(n) abort
  let _ = gettabvar(a:n, 'cwd')
  return strlen(_) ? _ : '[No Name]'
endfunction

let g:lightline.tab_component_function = {
      \ 'custom_tabname': 'CustomTabname',
      \ 'modified': 'lightline#tab#modified',
      \ 'readonly': 'lightline#tab#readonly',
      \ 'tabnum': 'lightline#tab#tabnum'
      \ }

let g:lightline.tab = {
      \ 'active': [ 'tabnum', 'custom_tabname', 'modified' ],
      \ 'inactive': [ 'tabnum', 'custom_tabname', 'modified' ] }
```

Any time I try to use something like `getcwd()` directly in the `CustomTabname` function, even when passed window and tab number parameters, *all* tabs end up getting displayed with the name of the working directory of the selected tab. (In other words, every time I select a different tab, *all* tabs update to show/duplicate the selected tab's name, instead of keeping their own independent names.) So, I came up with the solution of using tab-scoped variables.

This code sort of works, but I'm wondering if there's something obvious I'm missing/a better way to do this?

Thanks!

**Comment by itchyny** [comment]
How about this configuration?
```vim
function! CustomTabname(n) abort
  return fnamemodify(getcwd(tabpagewinnr(a:n), a:n), ':t')
endfunction
```

**Comment by joshdick** [comment]
Works perfectly with the other code that manages changing the working directory, and no variable passing. 😄 

Thanks very much for your help and for all of your work on `lightline.vim`!

**Comment by itchyny** [comment]
Example configurations
```vim
let g:lightline = {
      \ 'tab_component_function': {
      \   'filename': 'LightlineTabname'
      \  }
      \  }

function! LightlineTabname(n) abort
  return fnamemodify(getcwd(tabpagewinnr(a:n), a:n), ':t')
endfunction
```

```vim
let g:lightline = {
      \ 'tab': {
      \   'active': [ 'tabnum', 'cwd', 'filename', 'modified' ],
      \   'inactive': [ 'tabnum', 'cwd', 'filename', 'modified' ]
      \  },
      \ 'tab_component_function': {
      \   'cwd': 'LightlineCurrentDirectory'
      \  }
      \  }

function! LightlineCurrentDirectory(n) abort
  return fnamemodify(getcwd(tabpagewinnr(a:n), a:n), ':t')
endfunction
```

**Comment by GaryFurash** [comment]
Here's what my status line looks like with the above configuration. I still don't see a cwd.

![image](https://user-images.githubusercontent.com/15006133/38096393-950f607a-3327-11e8-82b0-d05d5747349e.png)

**Comment by itchyny** [comment]
This issue is about tabs. If you want to show tab always, try `set showtabline=2` in vimrc. If you want to show the current working directory in statusline, use `'absolutepath'` or `'relativepath'` components.
