### ISSUE TITLE
Entering Command in Split Terminal Window

### ISSUE THREAD

**Issue by ichitera** [itchyny/lightline.vim#246]
I cannot enter commands after a terminal window is split.

### Procedure
This issue is reproduced by the following procedure:
1. run `gvim.exe -u vimrc -U NONE`
2. execute `:term`
3. split the terminal window by typing `<C-w>v`
4. (the issue occurs)

The vimrc in the above procedure is the following:
```VimL
set runtimepath+=~/.vim/itchyny/lightline.vim
```

![Animation](https://user-images.githubusercontent.com/31098747/29906083-8ad18446-8e4d-11e7-8346-b76679081c04.gif)

### Environment
OS: Windows 10 Home (64bit)
Vim: Version 1026 (obtained from [vim-win32-installer](https://github.com/vim/vim-win32-installer/releases/tag/v8.0.1026))

### NOTE
1. This issue does not occur in vim.exe

**Comment by itchyny** [comment]
Does it happens without lightline.vim or not?

**Comment by ichitera** [comment]
It does not happen without lightline.vim.
I can enter commands when I run `gvim.exe -u NONE -U NONE -N` at the first step in the above procedure.

**Comment by itchyny** [comment]
Hmm, I cannot reproduce the problem anyway (sorry I don't have Windows environment) and the terminal feature is still in its early stage, so I cannot judge if the problem exists in lightline.vim or the terminal feature.

**Comment by ichitera** [comment]
I found `lightline#link` was called infinitely often when this issue occurred, but I didn't know the cause. As you commented, the terminal feature is in progress, and it was too early to open the issue. I am sorry.

**Comment by ichitera** [comment]
This issue was caused by Vim and fixed at [patch 8.0.173](https://github.com/vim/vim/commit/ba2929b6afd2fc20479912a8dec789be26a38244). I am sorry for this wrong issue report.

**Comment by itchyny** [comment]
Okay, thank you for the information.
