### ISSUE TITLE
Trim lightline components based on winwidth()

### ISSUE THREAD

**Issue by her** [itchyny/lightline.vim#248]
Hi itchyny, 

I love your plugin and it's philosophy. Thank you for making this. 

I followed your guide here: https://github.com/itchyny/lightline.vim/issues/237 but I'm wondering if there's someway to make this a little more terse? 

```vim
function! LightlineFileformat()
  return winwidth(0) > 150 ? &fileformat : ''
endfunction
function! LightlineFiletype()
  return winwidth(0) > 150 ? (&filetype !=# '' ? &filetype : 'no ft') : ''
endfunction
function! LightlineFileencoding()
  return winwidth(0) > 150 ? (&fenc !=# '' ? &fenc : &enc) : ''
endfunction
```

Like some sort of setting where I can collapse the entire `right` or `left` active components in the status line? 

Ideally some function where I can say 

```vim 
function! LightLineActiveRight()
  return winwidth(0) > 150 ? &lightline.active.right : ""
endfunction
```

Thank you 🙏 ☺️

**Comment by itchyny** [comment]
There's no way to do that... I think truncation in each component functions can cover the use case.

**Comment by her** [comment]
Got it 😄 

Thank you for taking the time to reply. I hope you enjoy your day! 

I'll close this now 🙏

**Comment by her** [comment]
hi @itchyny 👋 

So I've been trying to convert my various component functions to accept a `winwidth()` check but I keep running into a few errors on these items: 

for `filepath`
```
function! LightLineFilepath()
  return winwidth(0) > 120 ? (&filepath : '' != expand('%:p') ? expand('%:p') : '[No Name]')
endfunction
```

for `percent`
```
function! LightLinePercent()
  return winwidth(0) > 120 ? : (100 * line('.') / line('$')) . '%'
endfunction
```

for `'gitbranch': 'fugitive#head'`
```
function! LightLineGitbranch()
  return windwidth(0) > 120 ? &fugitive#head : ''
endfunction
```

for `getcwd()`
```
function! LightLineGitbranch()
  return windwidth(0) > 120 ? &getcwd : ''
endfunction
```

For clarity here are my active and component functions:

```
  \ 'active': {
  \   'left': [ ['mode', 'paste'], ['gitbranch', 'readonly', 'filename', 'filepath', 'modified'] ],
  \   'right': [ ['percent', 'cwd'], ['lineinfo'], ['fileformat', 'fileencoding', 'filetype'] ]
  \ },
  \ 'component_function': { 'mode': 'LightLineMode', 'gitbranch': 'fugitive#head', 
  \   'filepath': 'LightLineFilepath', 'cwd': 'getcwd', 'fileformat': 'LightLineFileformat', 
  \   'filetype': 'LightLineFiletype', 'fileencoding': 'LightLineFileencoding', 
  \   'lineinfo': 'LightLineLineinfo'}
  \ }
```

For many of these like, filepath, mode, fileencoding, filetype, lineinfo, etc. I've been able to apply the API and get lightline to collapse these based on `winwidth()` but for the ones I've mentioned above I haven't had any luck 😢 

I've searched all the various issues and docs, including googling around and trying to search other's vimrc to see if they've come up with a solution but I haven't found anything 😞 

Can you please help me figure out how I should be formatting these component functions? 

Thanks again @itchyny 🙏

**Comment by itchyny** [comment]
I think there're some mistake in your scripts.

incorrect parenthesis
```vim
function! LightLineFilepath()
  return winwidth(0) > 120 ? &filepath : '' != expand('%:p') ? expand('%:p') : '[No Name]'
endfunction
```

missing the second value `''` for the ternary operator
```vim
function! LightLinePercent()
  return winwidth(0) > 120 ? '' : (100 * line('.') / line('$')) . '%'
endfunction
```

invalid invocation for the function:
```vim
function! LightLineGitbranch()
  return windwidth(0) > 120 ? fugitive#head() : ''
endfunction
```

same here:
```
function! LightLineGitbranch()
  return windwidth(0) > 120 ? getcwd() : ''
endfunction
```
(this prints the current directory instead of the git branch name though)

**Comment by her** [comment]
Hi, itchyny ! Thank you for the reply, hope your day is well. 

For percents you were totally right I guess, I was missing the ternary operator. It's interesting though because in order to make it work I had to reverse the comparator operator `>` to less than `<` 

```
function! LightLinePercent()
  return winwidth(0) < 120 ? '' : (100 * line('.') / line('$')) . '%'
endfunction
```

Though for `LightLineFilepath()` something breaks... 

I get this error message, any ideas?

<img width="1319" alt="screen shot 2017-10-03 at 11 22 28 pm" src="https://user-images.githubusercontent.com/10278096/31162370-d45532bc-a891-11e7-812d-87204724a123.png">

So these two are invalid... 

```
function! LightLineGitbranch()
  return windwidth(0) > 120 ? fugitive#head() : ''
endfunction
```

```
function! LightLineGetcwd()
  return windwidth(0) > 120 ? &getcwd : ''
endfunction
```

(sorry about my quick edit earlier, realized I had copied the wrong function name) 

I'm not sure how to really incorporate the `fugitive#head` and `getcwd` as when I was searching the docs + source code I couldn't find these properties defined. Like I know `getcwd()` is a vim function (and thanks to lightline actually) I was able to easily add that to my status line! But when trying to make it collapsable with `winwidth()` I fail  💥 😩 😭 

I'm still getting the hang of vim script, really. 🙃 

Thanks again for the fast reply itchyny 😄 I hope I'm not interrupting work 😅

**Comment by itchyny** [comment]
Ahh, sorry. My comment above still has some mistake.
```vim
function! LightLineFilepath()
  return winwidth(0) > 120 ? '' : ('' != expand('%:p') ? expand('%:p') : '[No Name]')
endfunction
```

```vim
function! LightLineCwd()
 return windwidth(0) > 120 ? '' : getcwd()
endfunction
```
And I think you may have to recheck the `cwd` component function name in `component_function`.

**Comment by her** [comment]
itchyny! I fell asleep last night after that last comment (West Coast/Seattle times....) it was late 😴 

So I got BOTH the `LightLineFilepath()` _and_ `LightLineCwd()` to work thanks to your help! 

With `LightLineCwd()` I was running into some errors at first


This blows up...
```
function! LightLineCwd()
 return winwidth(0) > 120 ? &getcwd() : ''
endfunction
```
This doesn't blow up... at first... but then once I make the window small it evaluates `winwidth` explodes and then I get a ton of errors :( 
```
function! LightLineCwd()
 return winwidth(0) > 120 ? '' : getcwd
endfunction
```

but THIS! after rechecking as you suggested

```
function! LightLineCwd()
 return winwidth(0) < 120 ? '' : getcwd()
endfunction
```

THIS WORKS! 🎉 💃 😄 amazing. 

Still a bit confused on how to set the gitbranch to a winwidth function but I will continue to play 🙂
