### ISSUE TITLE
Is it possible use different colorscheme for different buffer?

### ISSUE THREAD

**Issue by chenzhihuai1990** [itchyny/lightline.vim#249]
I would like to use different color for speical buffer like ctrp, nerdtree et al. Is it possible to use other color/component/layout/configuration according to buffer name? 
The only way I can figure out is to add buffer name matcher to visual_condition, but it is not very convenient.

**Comment by itchyny** [comment]
no, it's impossible.

**Comment by itchyny** [comment]
No, it's impossible.

**Comment by chenzhihuai1990** [comment]
Do you have any plan to add this feature?

**Comment by itchyny** [comment]
No.
