### ISSUE TITLE
statusline flickering

### ISSUE THREAD

**Issue by shihan9** [itchyny/lightline.vim#251]
i am using vim inside iterm2. every time I scroll down or up the completions of jedi-vim, the statusline of the doc preview windows will occasionally flicker between INSERT [SCRATCH] and [SCRATCH], basically the preview window flickers because the editing mode comes out. but in macvim, there is no such issue. thank you for any help.
![test](https://user-images.githubusercontent.com/9028490/31311687-b24a7f56-ab7f-11e7-9cb8-13070c70a78b.gif)

**Comment by itchyny** [comment]
I cannot reproduce the problem. Can you provide a minimal vimrc to reproduce the issue?

**Comment by shihan9** [comment]
```
call plug#begin('~/.vim/plugged')
Plug 'itchyny/lightline.vim'
Plug 'sstallion/vim-cursorline'
Plug 'davidhalter/jedi-vim', { 'for': 'python' }
call plug#end()
```
it is caused by vim-cursorline.

**Comment by itchyny** [comment]
Ok, then it's a problem of vim-cursorline. I think adding `if pumvisible() | return | endif` in `CursorLineHide` and `CursorLineShow` will fix the problem.
