### ISSUE TITLE
Horizontal aligment with custom linespace

### ISSUE THREAD

**Issue by fxn** [itchyny/lightline.vim#254]
Not sure this is fixable, but let me ask at least.

I have `linespace` set to 6 with font Menlo in MacVim, and the text is rendered at the bottom, I attach a screenshot.

Would it be possible to center it?

<img width="1163" alt="screen shot 2017-10-22 at 00 25 57" src="https://user-images.githubusercontent.com/3387/31856386-2abd3cf8-b6c0-11e7-8463-0c8520e74dec.png">

**Comment by itchyny** [comment]
That's impossible. See the related issue: https://github.com/macvim-dev/macvim/issues/493.

**Comment by fxn** [comment]
Makes sense, appreciate the prompt reply. Thanks!

**Comment by fxn** [comment]
Oh! For the archives. I just checked if by chance line spacing in iTerm2 (configured in the font dialog) behaved differently, it does!

<img width="1409" alt="screen shot 2017-10-22 at 01 18 16" src="https://user-images.githubusercontent.com/3387/31856684-5b74294a-b6c7-11e7-84b2-a587aa373159.png">
