### ISSUE TITLE
Empty components do not collapse after Vim 8.0.1208

### ISSUE THREAD

**Issue by dohq** [itchyny/lightline.vim#255]
日本語で申し訳ありません
いつも便利に使わせて頂いております。
タイトルのように、vimのv8.0.1208の修正よりコンポーネントが空の場合(例えばpasteモードOFFの場合のpasteコンポーネントなど)で、非アクティブである場合、空白(？)が入っているようです。

![statusline](https://user-images.githubusercontent.com/1639089/31928189-1a4d9d54-b8d2-11e7-9993-58004fd719c4.png)

vimrc
```
call plug#begin($VIM.'\vimfiles\plugins')
Plug 'itchyny/lightline.vim'
call plug#end()
filetype plugin indent on

set laststatus=2
```

修正方法などサッパリ分からずお力になれないのですが、修正可能でしょうか。

宜しくお願い致します。

**Comment by itchyny** [comment]
報告ありがとうございます。 https://github.com/vim/vim/pull/2228 ですね。調べてみます。

**Comment by itchyny** [comment]
Vim 8.0.1220で修正されたと思います。Vimを最新にしてご確認ください。
https://groups.google.com/d/msg/vim_dev/akSs0YX4f6Q/nj2-RhlwBQAJ

**Comment by dohq** [comment]
ありがとうございます！
最新版をビルドしたところ問題無く表示されました。
素早い対応ありがとうございます。
当issueはcloseさせて頂きます。

**Comment by itchyny** [comment]
ありがとうございました。
