### ISSUE TITLE
Changing lightline colorscheme on the fly

### ISSUE THREAD

**Issue by gbarta** [itchyny/lightline.vim#258]
Hi,
I was hoping to test out the different lightline colorschemes to see which I liked best, and in a wanton episode of yak-shaving ended up writing the following command to change colorscheme, including command-line completion for the colorscheme names.

```
fun! s:setLightlineColorscheme(name)
    let g:lightline.colorscheme = a:name
    call lightline#init()
    call lightline#colorscheme()
    call lightline#update()
endfun

fun! s:lightlineColorschemes(...)
    return join(map(
                \ globpath(&rtp,"autoload/lightline/colorscheme/*.vim",1,1),
                \ "fnamemodify(v:val,':t:r')"),
                \ "\n")
endfun

com! -nargs=1 -complete=custom,s:lightlineColorschemes LightlineColorscheme
            \ call s:setLightlineColorscheme(<q-args>)
```

I will never get that time back, but perhaps I can be redeemed if this command is made available to others.

I note that lightline does not currently define any commands - I am not sure if this was a deliberate choice.
If you are interested, I can submit a PR either with this code as a part of lightline, or alternatively as an extension to the help file sample code for "Problem 13" about changing colorscheme.

**Comment by itchyny** [comment]
I don't want to provide a command for this feature. Once users choose their favorite colorscheme, they will continue to use lightline with it and changing the colorscheme is not worth providing via a command for our daily use cases of this plugin.  To change the colorscheme, edit your vimrc and restart the editor, that's enough. But I will accept a patch for the help.

**Comment by gbarta** [comment]
I totally understand wanting to keep lightline light.  It's right there in the name!  Thanks for making it.
