### ISSUE TITLE
Undefined variable g:lightline

### ISSUE THREAD

**Issue by tuyenpm9** [itchyny/lightline.vim#261]
When trying to disable statusline and enable tabline, got this from doc:  
```
let g:lightline.enable = {
  \ 'statusline': 0,
  \ 'tabline': 1
  \ }
```  
but reload .vimrc I got the error as title. Any helps?

**Comment by itchyny** [comment]
Please add `let g:lightline = {}` before that configuration.

**Comment by tuyenpm9** [comment]
@itchyny : Thanks for quick reply, I enabled lightline but don't see tabline appear.  
Some options in vimrc may be concerned:  
```
set noshowmode
set shortmess+=c 
```

**Comment by itchyny** [comment]
`set showtabline=2` will help you.

**Comment by tuyenpm9** [comment]
It shows tab instead of buffertabline. I'm trying to get similar behavior of lightline as airline (airline restricts users from disable statusline), I can obtained with airline as below:  
```
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#tab_nr_type = 1 " tab number
let g:airline#extensions#tabline#show_tab_nr = 1
let g:airline#extensions#tabline#formatter = 'default'
let g:airline#extensions#tabline#buffer_nr_show = 1
let g:airline#extensions#tabline#fnametruncate = 16
let g:airline#extensions#tabline#fnamecollapse = 2

let mapleader = ","

let g:airline#extensions#tabline#buffer_idx_mode = 1

nmap <silent> <leader>1 <Plug>AirlineSelectTab1
nmap <silent> <leader>2 <Plug>AirlineSelectTab2
nmap <silent> <leader>3 <Plug>AirlineSelectTab3
nmap <silent> <leader>4 <Plug>AirlineSelectTab4
nmap <silent> <leader>5 <Plug>AirlineSelectTab5
nmap <silent> <leader>6 <Plug>AirlineSelectTab6
nmap <silent> <leader>7 <Plug>AirlineSelectTab7
nmap <silent> <leader>8 <Plug>AirlineSelectTab8
nmap <silent> <leader>9 <Plug>AirlineSelectTab9
```  
How can I have it in lightline?

**Comment by itchyny** [comment]
This plugin does not provide buffertabline integration. But users can configure the tabline components. See the related issues: #155, #36.
