### ISSUE TITLE
colorscheme not working in neovim

### ISSUE THREAD

**Issue by LaBatata101** [itchyny/lightline.vim#263]
the one theme is not working in neovim

**Comment by itchyny** [comment]
Let me see some screenshots and describe what do you expect.

**Comment by LaBatata101** [comment]
# Expected
![lightline.vim - one](https://raw.githubusercontent.com/wiki/itchyny/lightline.vim/image/one.png)

# Actual
![screen](https://imgur.com/QDM286y.png)

**Comment by tonylambiris** [comment]
Doesn't look like the vim-one theme has a lightline theme available for it
```
╰ tree       
.
├── autoload
│   └── airline
│       └── themes
│           └── one.vim
├── colors
│   ├── one-dark.vim
│   └── one.vim
├── CONTRIBUTING.md
├── estilo
│   ├── addons
│   │   └── nvim-term.yml
│   ├── palettes
│   │   └── vim-one-dark.yml
│   └── syntax
│       └── base.yml
├── estilo.yml
├── LICENSE
├── README.md
└── screenshots
    ├── new-logo.png
    └── Untitled.sketch

9 directories, 12 files
```

Try using [onedark.vim](https://github.com/joshdick/onedark.vim):
![screenshot-20171127200518-930x877](https://user-images.githubusercontent.com/14058972/33297348-74dde232-d3ae-11e7-909d-c4b52a16e3d2.png)

**Comment by itchyny** [comment]
I acknowledge this as a bug of lightline and I'll work on this in a few days.
