### ISSUE TITLE
Support including all buffers in the tabline, à la buftabline

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [itchyny/lightline.vim#264]
Exactly what the title says. See [vim-buftabline](https://github.com/ap/vim-buftabline).

Basically, I'd like Lightline to conform a little more to a classic-vim workflow, as opposed to a “file-per-vimtab” workflow. `(=`

Alternatively, simply integrate directly with buftabline, if installed? Override its styles and such? I'm not sure if that's possible, I suspect buftabline assumes it has full control of the tabline's content.

**Comment by itchyny** [comment]
See https://github.com/itchyny/lightline.vim/issues/155#issuecomment-196015726.

**Comment by ELLIOTTCABLE** [comment]
@itchyny That does indeed do exactly what I wanted! Thank you!
