### ISSUE TITLE
76e374 breaks background

### ISSUE THREAD

**Issue by nathanjordan** [itchyny/lightline.vim#267]
wasn't sure what an appropriate title for this would be, but https://github.com/itchyny/lightline.vim/commit/76e374334cd9f1cb7845757e9a1b35112d3e0f19 has changed the background color of lightline for the worse IMO. I'm not sure if this was intended as part of the change or if it's an unintended side effect.

Before
<img width="566" alt="screen shot 2017-11-28 at 4 48 10 pm" src="https://user-images.githubusercontent.com/1120611/33352168-7876759a-d45c-11e7-9e04-d86da81b3d17.png">

After
<img width="565" alt="screen shot 2017-11-28 at 4 47 02 pm" src="https://user-images.githubusercontent.com/1120611/33352169-788c2728-d45c-11e7-8d28-cb275926892b.png">

Using iTerm2 Build 3.1.5

vim version
```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/build/config -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/build/include
Compiled by brew@HighSierra-2.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2/share/nvim"

Run :checkhealth for more info
```

**Comment by itchyny** [comment]
What is the result of `:hi Normal`.

**Comment by nathanjordan** [comment]
`Normal         xxx ctermfg=12 ctermbg=8`

**Comment by itchyny** [comment]
Please let me know the result of `:echo [get(g:, 'solarized_termcolors'), &t_Co]`.

**Comment by nathanjordan** [comment]
`[16, '256']`

**Comment by itchyny** [comment]
I have fixed the problem. Thanks for the issue report.
