### ISSUE TITLE
How to change filename section?

### ISSUE THREAD

**Issue by milushov** [itchyny/lightline.vim#273]
![image](https://user-images.githubusercontent.com/424326/33985634-c6684d76-e0ed-11e7-964b-3f568ff28d51.png)
I have file: `~/projects/foo/src/components/my_component/index.cjsx`
I want to see "previous directory level/filename", eg: `my_component/index.cjsx` indead of `index.cjsx`

I will be very happy if someone help me to customize it, cz I'm too far from vim script

Thanks in advance

**Comment by itchyny** [comment]
Example configuration:
```vim
let g:lightline = {
      \ 'component_function': {
      \   'filename': 'LightlineFilename'
      \ }
      \ }

function! LightlineFilename()
  return expand('%:t') ==# '' ? '' : expand('%:p:h:t') . '/' . expand('%:t') 
endfunction
```

**Comment by milushov** [comment]
@itchyny thank u so much! :)
