### ISSUE TITLE
Left side disappears on small window width

### ISSUE THREAD

**Issue by aaschmid** [itchyny/lightline.vim#276]
Thanks for this nice plugin. Would it be possible to provide a possibility to adjust which side (left or right) will disappear / overlap the other?

Cheers,
Andreas

**Comment by itchyny** [comment]
Please refer to README.md, `Can I trim the file format and encoding information on narrow windows?`.

**Comment by aaschmid** [comment]
Hi @itchyny, thanks for the quick response. I have seen that yesterday scanning the `README.md` and `:help lightline` section. As I work a lot with diffs and prefer to have long file names shown, I would prefer a solutation that the right part would simple get smaller and smaller (now the left part does). But the left part contains the more important information for me, especially the `mode`.

Maybe this is not possible but maybe this is only a setting which things are drawn first and second. I haven't had a look into the code but the default statuslines behavior is exactly like that. 

It is ok, if you will mark this as "won't fix" but maybe you have a hint for me where to have a look into your code such that I can do some research ;-)

**Comment by itchyny** [comment]
Maybe you can hide the right components (line counts or the percentage) with a little extension with the example config.  A screenshot will help me figure out what's happening and how narrow your terminal is.

**Comment by aaschmid** [comment]
To create a customization which will hide some components is of course an option which I already considered doing but I think it is valuable to have a closer look to my problem as hiding would just be a workaround in my opinion.

However, I found the solution myself. Looking again to `:help statusline` I found the following on `item meaning` section:

```
	< -   Where to truncate line if too long.  Default is at the start.
	      No width fields allowed.
```

So the solution is adding and using following component: 
```
let g:lightline.component = { 'truncateEnd': '%<' }
``` 

Thanks anyway for listening and repsonding. You can close the issue if you don't need it anymore. Maybe this is a usecase for the documentation or even a provided option ;-)

**Comment by somini** [comment]
@aaschmid Thanks for that.

I added two other settings to make sure the component doesn't show until it's actually needed.
```vim
let g:lightline.component = {
			\ 'truncate_here': '%<',
			\ }
let g:lightline.component_visible_condition = {
			\ 'truncate_here': 0,
			\ }
let g:lightline.component_type = {
			\ 'truncate_here': 'raw',
			\ }
```
With `visible_condition` always false you can add that component in the regular configuration and it won't ever show a sub-separator. The `raw` type eliminates any extra spaces between that component and others.
