### ISSUE TITLE
Modified buffers in tabline

### ISSUE THREAD

**Issue by somini** [itchyny/lightline.vim#277]
This is a "configuration" issue, I don't think there's any issue with the plugin.

I'm trying to show symbols for each tab. I want to show a symbol if there is any `&modified` buffers inside, and another if there's only `&nomodifiable` buffers inside.
My first pass is the following function, but this doesn't work for some reason. Can you shed some light on this?

```vim
function! LightlineTablineModified(n)
	" TODO: Fix it
	" return lightline#tab#modified(a:n)
	let l:window_number = tabpagewinnr(a:n, '$')
	let l:modified = v:false
	let l:unmodifiable = v:true
	for winnr in range(1, l:window_number)
		let l:modified = l:modified || gettabwinvar(a:n, winnr, '&modified') ? v:true : v:false
		let l:unmodifiable = l:unmodifiable && gettabwinvar(a:n, winnr, '&modifiable') ? v:false : v:true
	endfor
	let l:string = ''
	if l:modified
		let l:string .= s:modified_glyph
	elseif l:unmodifiable
		let l:string .= s:unmodifiable_glyph
	endif
	return l:string
endfunction
```

**Comment by itchyny** [comment]
I think this is operator precedence problem.
```vim
    let l:modified = l:modified || (gettabwinvar(a:n, winnr, '&modified') ? v:true : v:false)
    let l:unmodifiable = l:unmodifiable && (gettabwinvar(a:n, winnr, '&modifiable') ? v:false : v:true)
```
The first line works as the same but the second line works different; `(x && y) ? false : true` and `x && (y ? false : true)` are different with `x = false`. BTW the first line can be abbreviated to `l:modified || gettabwinvar(...)`.

**Comment by somini** [comment]
Thank you very much, the abbreviations work perfectly.
And thanks for the plugin!

For completeness, here is the final working version:
```vim
function! LightlineTablineModified(n)
	let l:window_number = tabpagewinnr(a:n, '$')
	let l:modified = v:false
	let l:unmodifiable = v:true
	for winnr in range(1, l:window_number)
		let l:modified = l:modified || gettabwinvar(a:n, winnr, '&modified')
		let l:unmodifiable = l:unmodifiable && !gettabwinvar(a:n, winnr, '&modifiable')
	endfor
	let l:string = ''
	if l:modified
		let l:string .= s:modified_glyph
	elseif l:unmodifiable
		let l:string .= s:unmodifiable_glyph
	endif
	return l:string
endfunction
```
To use it, define the `s:modified_glyph` and `s:unmodifiable_glyph` at will. I like
```vim
let s:modified_glyph = '☢'
let s:unmodifiable_glyph = '⏚'
```
