### ISSUE TITLE
one theme is different from expected

### ISSUE THREAD

**Issue by Dcryfm** [itchyny/lightline.vim#280]
It's the same as this issue [#263](https://github.com/itchyny/lightline.vim/issues/263)

**Comment by itchyny** [comment]
Please upload some screenshot otherwise I cannot understand what's happening.

**Comment by Dcryfm** [comment]
@itchyny  I'm sorry to reply too late.
When I first used it, the color of the one theme looks the same as this, ![](https://camo.githubusercontent.com/a2e27bfaae710521e3ba6e7dd97036f3af7fbcf5/68747470733a2f2f696d6775722e636f6d2f51444d323836792e706e67) but it's right now.

**Comment by itchyny** [comment]
So it's working well now? You can close the issue.
