### ISSUE TITLE
Unicode characters not displaying correctly upon startup

### ISSUE THREAD

**Issue by parvus-mortalis** [itchyny/lightline.vim#281]
I defined a function that adds a unicode character to the git branch name.

```vim
function! Lightlinegit()
    let l:branch = fugitive#head()
    return l:branch ==# '' ? '' : 'Ψ ' . l:branch
endfunction
```

And this is my `g:lightline` list:

```vim
let g:lightline = {                                                              
      \ 'colorscheme': 'seoul256',                                               
      \ 'active': {                                                              
      \   'left': [ [ 'mode', 'paste' ],                                         
      \             [ 'branch', 'readonly', 'filename' ] ],                      
      \   'right': [ [ 'lineinfo' ], [ 'filetype' ] ]                            
      \ },                                                                       
      \ 'component_function': {                                                  
      \   'mode': 'Lightlinemode',                                               
      \   'filename': 'Lightlinename',                                           
      \   'branch' : 'Lightlinegit'                                              
      \ }                                                                        
      \ }
```

I get this output in the statusbar when I open vim:

```
<bf> master
```

Lightline (or vim) thinks that the `<bf>` is one character, which messes up the formatting. When I manually source `.vimrc` after opening vim, the unicode character shows up.

**Comment by itchyny** [comment]
Put `scriptencoding utf-8` at the top of your .vimrc.

**Comment by parvus-mortalis** [comment]
I already have, and I can't get it to display correctly on startup.

**Comment by itchyny** [comment]
I cannot reproduce the problem so please upload a minimal vimrc to investigate the problem. I think this is a kind of encoding problem.

**Comment by scholi** [comment]
Hi,
I have the same issue but in order to set listchars on gvim 8.1 (MS-Windows 64bit).
I'm not using the lightline.vim library, but as it's the same problem, maybe the previous user @parmort have a solution and it's the reason why I'm posting it here (I cannot find anyone else reporting this issue on the internet).

For my case I have the following .vimrc

```vim
scriptencoding utf-8
set termencoding=utf-8
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,latin1
set list listchars=tab:→_
```

when loaded vim reads the char "→" as <bf>, but it works fine if I do `:so %` from my .vimrc

**Comment by parmort** [comment]
@scholi I found that the You have to set the encoding of vim itself to utf-8 then set the script encoding to utf-8. If thats not clear (my apologies), it appears at the top of my [vimrc](https://github.com/parmort/dotfiles/blob/master/vimrc)

**Comment by scholi** [comment]
@parmort thanks a lot, that works great :+1:
