### ISSUE TITLE
status item changed but status bar is not redrawn until other changes

### ISSUE THREAD

**Issue by mckellyln** [itchyny/lightline.vim#283]
Hi.
I have a custom git-like status field I've added to lightline.
So instead of fugitive#head() or gitbranch#name() I have a g:gitstatus variable that is updated via a job channel.
But when this var changes the status line is not always redrawn with the new value.
I can echomsg the new value and see it changed but until I or vim redraws the statusline does not show the new value.
I can add a redraw, but just asking if there is a lighltline method to force an update of the statusline ?
Thx again for lightline.

**Comment by itchyny** [comment]
Try `call lightline#update()` explicitly.

**Comment by mckellyln** [comment]
Great thx so much.
