### ISSUE TITLE
Automatic truncation of segments in small windows

### ISSUE THREAD

**Issue by fabirovsky** [itchyny/lightline.vim#288]
How about to add this feature, like in Powerline?

![deepinscreenshot_select-area_20180208100307](https://user-images.githubusercontent.com/20482699/35961835-b898c7c0-0cb7-11e8-8b72-93b3f8d0c3ed.png)

**Comment by itchyny** [comment]
See https://github.com/itchyny/lightline.vim#can-i-trim-the-file-format-and-encoding-information-on-narrow-windows.

**Comment by fabirovsky** [comment]
Wow, thanks.
