### ISSUE TITLE
Separators without highlighting due to component_expand

### ISSUE THREAD

**Issue by dan-santana** [itchyny/lightline.vim#289]
Currently the expanding components (the ones declared in `component_expand`) can be hidden by returning  `''`, but the separators between the components around the hidden component won't be highlighted. 

As in the example below, there's an expanding component between the components showing "NORMAL" mode and "[No Name]" file name.

![screenshot-2018-02-12t23 45 31-0200](https://user-images.githubusercontent.com/6091633/36129685-8cd59348-104f-11e8-8b25-dd23399a7deb.png)

Here's the corresponding `&statusline` (broken into multiple lines):

```
%{lightline#link()}%#LightlineLeft_active_0#%( %{LightlineMode()} %)
%#LightlineLeft_active_0_2#%#LightlineLeft_active_2#%( %{LightlineFilename()} %)
%{LightlineFilename()!=#""&&(LightlineGitStatus()!=#"")?"":""}%( %{LightlineGitStatus()} %)
%#LightlineLeft_active_2_success#%#LightlineLeft_active_success#%(  OK %)
%#LightlineLeft_active_success_4#%#LightlineLeft_active_4#%( %{LightlineSearchMatches()} %)
%#LightlineLeft_active_4_5#%#LightlineMiddle_active#%=
%#LightlineRight_active_1_2#%#LightlineRight_active_1#%( %{LightlineFileformat()} %)
%{LightlineFileformat()!=#""&&(LightlineFileEncoding()!=#""||LightlineFiletype()!=#"")?"":""}
%( %{LightlineFileEncoding()} %)%{LightlineFileEncoding()!=#""&&(LightlineFiletype()!=#"")?"":""}
%( %{LightlineFiletype()} %)%#LightlineRight_active_0_1#
%#LightlineRight_active_0#%( %3p%% %)%{1?"":""}%( %3l:%-2v %)
```

In this example, the culprit is the `LightlineLeft_active_0_2` highlighting that doesn't exist.

**Comment by itchyny** [comment]
Please let me know how you configure lightline components.

**Comment by dan-santana** [comment]
Here's a minimal setup similar to what I'm using that can reproduce the issue:

```

let g:lightline = {
      \   'colorscheme': 'base16',
      \   'active': {
      \     'left': [
      \       [ 'mode' ],
      \       [ 'table_mode' ],
      \       [ 'file_name' ],
      \     ],
      \     'right': [],
      \   },
      \   'component_function': {
      \     'mode': 'lightline#mode',
      \     'file_name': 'LightlineFilename',
      \   },
      \   'component_expand': {
      \     'table_mode': 'LightlineTableModeModifier',
      \   },
      \   'separator': { 'left': '', 'right': '' },
      \   'subseparator': { 'left': '', 'right': '' },
      \ }

function! LightlineFilename()
  let fname = expand('%')
  return '' != fname ? fname : '[No Name]'
endfunction

function! LightlineTableModeModifier()
  return get(g:lightline, 'table_active') ? 'TABLE' : ''
endfunction
```

**Comment by itchyny** [comment]
Maybe following will resolve the issue? I'm afraid I didn't assume that all the components in the group are expanded.
```vim
      \   'active': {
      \     'left': [
      \       [ 'mode' ],
      \       [ 'table_mode', 'file_name' ],
      \     ],
      \     'right': [],
      \   },
```
It looks like not working as expected but I have to take more time to investigate your fix causes other problems or not.

**Comment by itchyny** [comment]
Hmm, your fix will cause much performance regression, I think I have to find another way...

**Comment by dan-santana** [comment]
Putting the expanding components together in another group solved the issue, but I had to change my colorscheme to not try setting the colors for their old position (as I'll have to use `component_type` due to the different color for these components).

Out of curiosity, how are you measuring the performance? I didn't notice much performance loss, so I believe you are talking about the extra time it will take to create these additional color combinations for the separators, right? 

If that's the case, I could just put some checking to avoid creating the combinations if both left and right groups aren't composed exclusively of expanding components.

**Comment by itchyny** [comment]
I firstly apologize for commenting without measuring and disobeying the don't-guess principle. And right, increasing the number of exec commands and highlights is surely what I want to avoid in this plugin. Adding more highlight groups will cause more time for linking the highlights on switching between modes, that's why I wrote the `i + 1 == j` condition. I think this is a kind of corner case which can be avoided by user's configuration, not worthing fixing with taking time from the others not affected by this case.

**Comment by dan-santana** [comment]
I took some time to understand the logic around creating highlights and links and came to the following formula to calculate how many `exec 'hi ...'` will be called on `lightline#link()` (and `lightline#highlight()` too, but this one doesn't matter for this discussion):

```python
# ls => quantity of groups in g:lightline.active.left
# rs => quantity of groups in g:lightline.active.right
# ts => quantity of distinct types in g:lightline.component_type
(ls + rs) * (ts + 2) + (ts + 1) * (ls + rs + 2 + (ts + 1) * 2)
```

And the #290  patch adds this amount of `exec`s:

```python
(ls ** 2 + rs ** 2 - ls - rs) / 2
```

Considering each `exec 'hi ...'` takes around 0.015\~0.025ms to execute (YMMV), I tried the extremely worst case scenario: 25 component groups on the left (Vim only allows 80 statusline items, including `%#` highlightings) each containing a single expanding component (without having the same component type sequentially in order to avoid subseparators), and each `lightline#link()` call averaged from 12\~25ms without the patch, and 18\~35ms after it. This difference matches the formula, where the increase would be around 4.5\~7.5ms (due to the added 300 `exec 'hi ...'` calls by the patch).

That's quite a lot considering it will run every time the user switches modes, but on a less extreme (and maybe more realistic) but still heavy setup with 10 component groups on each side (20 total) and 4 different component types they would add only 1.35\~2.25ms per call.

Now, on my real setup with 5 groups on the left and 3 on the right, with 4 different component types (`error`, `warning`, `info`, `success`) the patch would add more 13 `exec 'hi ...'` calls, increasing mere 0.195\~0.325ms per call (total: 2.415\~4.025ms), which I believe is a more common case.

I just thought it would be valuable to share these notes about the performance changes I could check by `:profile`ing lightline.vim functions before and after the patch, and while there are many other factors that could change these numbers, I don't know if the impact will be really too big or even noticeable on other setups. In any case, if you decide the performance degradation still is relevant, as an alternative can you note this quirk on the docs? So other users won't stumble upon this edge case.

_**NOTE:** These 3 cases were tested manually and although I didn't take a cautious scientific approach for measuring the timings, they were consistent enough with the formula, which I believe is more reliable for guesstimating the impact of this modification for other users._
