### ISSUE TITLE
How to config filename to show full path

### ISSUE THREAD

**Issue by zhouytforever** [itchyny/lightline.vim#293]
This may not be a problem, But I am confused about configuring full path of current file.
Could you please show me ?

**Comment by itchyny** [comment]
Use `absolutepath` component:
```vim
let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ], [ 'readonly', 'absolutepath', 'modified' ] ],
      \ }
      \ }
```

**Comment by AndreGeng** [comment]
Is there a configure that can show the file path relative to project root directory?

**Comment by itchyny** [comment]
Assuming you are working on git repositories, configure as follows
```vim
let g:lightline = {
      \ 'component_function': {
      \   'filename': 'LightlineFilename',
      \ }
      \ }

function! LightlineFilename()
  let root = fnamemodify(get(b:, 'git_dir'), ':h')
  let path = expand('%:p')
  if path[:len(root)-1] ==# root
    return path[len(root)+1:]
  endif
  return expand('%')
endfunction
```
Note that this configuration requires [vim-fugitive](https://github.com/tpope/vim-fugitive) plugin.

If you have [vim-gitbranch](https://github.com/itchyny/vim-gitbranch) plugin installed, replace the `let root` line with as follows.
```vim
  let root = fnamemodify(get(b:, 'gitbranch_path'), ':h:h')
```

**Comment by AndreGeng** [comment]
it works, awesome, @itchyny thanks for the quick reply

**Comment by Plotnus** [comment]
@itchyny my hero :)

**Comment by b3tchi** [comment]
Hi it's work great, thank you! Just have to made small adjustment on Windows that root variable was C:\...\... and path variable was C:/.../... at least with fugitive. Then It didn't match because of different file separator symbol.

**Comment by png261** [comment]
['relativepath']

**Comment by cnshsliu** [comment]
> ```viml
> function! LightlineFilename()
>   let root = fnamemodify(get(b:, 'git_dir'), ':h')
>   let path = expand('%:p')
>   if path[:len(root)-1] ==# root
>     return path[len(root)+1:]
>   endif
>   return expand('%')
> endfunction
> ```


Does not work for filename in tabline.
my tabline is defined as:
```viml
  \ 'tab' : {
        \ 'active': [ 'tabnum', 'filename', 'modified' ],
        \ 'inactive': [ 'tabnum', 'filename', 'modified' ] 
  \ },

```
The filenames in tabs  are still pure file name.

**Comment by strogonoff** [comment]
To make Lightline’s _tabline_ show Git-repo-root-relative path instead of filename (requires git-fugitive):

```vim
    let g:lightline = {
      ...
      \ 'tab_component_function': {
      \   'filename': 'LightlineTablineGitRelativePath',
      \ },
      ...
    \ }

    function! LightlineTablineGitRelativePath(n)
      let buflist = tabpagebuflist(a:n)
      let winnr = tabpagewinnr(a:n)
      let bufnum = buflist[winnr - 1]
      let bufname = expand('#'.bufnum.':t')
      let buffullname = expand('#'.bufnum.':p')
      let gitroot = fnamemodify(FugitiveGitDir(bufnum), ':h')
      if strlen(gitroot)
        if buffullname[:len(gitroot)-1] ==# gitroot
          return buffullname[len(gitroot)+1:]
        endif
      endif
      return bufname
    endfunction
```

This adapts itchyny’s snippet above for tab components. (Tab component function receives a tab number and AFAICT doesn’t have direct buffer access, so I resolve tab number to buffer according to the logic in the snippet from [itchyny’s another comment](https://github.com/itchyny/lightline.vim/issues/43#issuecomment-26041480).)

Love this plugin, very light!
