### ISSUE TITLE
Is it possible to put word count on lightline?

### ISSUE THREAD

**Issue by mrbig033** [itchyny/lightline.vim#295]

**Comment by itchyny** [comment]
I googled for `word count vim` and found a script https://gist.github.com/cormacrelf/d0bee254f5630b0e93c3. Example configuration using this function:

```vim
let g:lightline = {
      \ 'active': {
      \   'right': [ [ 'lineinfo' ], [ 'percent', 'wordcount' ], [ 'fileformat', 'fileencoding', 'filetype' ] ]
      \ },
      \ 'component_function': {
      \   'wordcount': 'WordCount',
      \ },
      \ }
```

**Comment by itchyny** [comment]
@andreas-bulling  It works for me. Please paste your configuration or link to your vimrc.

**Comment by KargJonas** [comment]
Worked like a charm!
If you are having trouble with a separate file, just put the function directly into .vimrc

**Comment by MariusSwane** [comment]
The above script (in the link) works well, but if you are on newer versions of vim/neovim you can now use the following script to get selected words count and words 'so far'.

```vim
"new in vim 7.4.1042
let g:word_count=wordcount().words
function WordCount()
    if has_key(wordcount(),'visual_words')
        let g:word_count=wordcount().visual_words."/".wordcount().words " count selected words
    else
        let g:word_count=wordcount().cursor_words."/".wordcount().words " or shows words 'so far'
    endif
    return g:word_count
endfunction
```
