### ISSUE TITLE
Not working in vim, works in neovim

### ISSUE THREAD

**Issue by arnsa** [itchyny/lightline.vim#296]
Hello,

I've just installed this plugin, it's working perfectly fine in nvim, but it doesn't seem to be working on vim8 at all (statusline isn't showing up). Any thoughts?

**Comment by itchyny** [comment]
I use this plugin in Vim 8, not neovim and it works well. Please paste a minimal vimrc to reproduce the problem so that I can investigate the problem.

**Comment by arnsa** [comment]
Here's my vimrc file:

`set nocompatible
set number

" Switch syntax highlighting on
syntax on
syntax enable

if (has("termguicolors"))
  set termguicolors
endif

" Enable file type detection and do language-dependent indenting.
filetype plugin indent on

call plug#begin('$HOME/.config/nvim/plugged')
autocmd vimenter * NERDTree

if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif

Plug 'kristijanhusak/vim-hybrid-material'
Plug 'vim-airline/vim-airline-themes'
Plug 'w0rp/ale'
Plug 'itchyny/lightline.vim'
Plug 'scrooloose/nerdtree'
Plug 'carlitux/deoplete-ternjs', { 'do': 'npm install -g tern' }

call plug#end()

colorscheme hybrid_material
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ }
set background=dark`

**Comment by itchyny** [comment]
It works for me with your configuration, it's weird. Can you give me information of Vim version? Also, can you test if

- setting `set laststatus=2` in your vimrc
- removing `set termguicolors` configuration
- moving `Switch syntax highlighting on` at the end of vimrc

**Comment by arnsa** [comment]
Yay, setting set laststatus=2 worked! I am pretty sure I've tried it before and it didn't work, but perhaps I am wrong... Thanks!

**Comment by itchyny** [comment]
OK.
