### ISSUE TITLE
Request to take Dracula responsibility

### ISSUE THREAD

**Issue by dsifford** [itchyny/lightline.vim#299]
Hello,

I'm one of the maintainers of the vim [Dracula theme](https://github.com/dracula/vim). I'm curious if I'd be able to take the Dracula theme off your hands here and implement it in the autoload directory of our plugin?

Reason is exclusively for uniformity between all UI elements (we currently maintain themes for airline as well).

Thanks, let me know! :+1:

**Comment by itchyny** [comment]
Okay. I think I'm a bit scary for the support cost but maybe ok. The theme will be dropped off from the support of this repo and the screenshot will be removed as well.
I have to mention  @adamalbrecht who contributed to the initial code of the theme in #195. What do you think?

**Comment by dsifford** [comment]
Great, thanks so much 😊 

I'll be sure to credit @adamalbrecht for his work... When I get around to commiting the changes over, I'll even do a shared commit so he gets credit in the git history as well.

I'll chime back here after that happens 👍

**Comment by adamalbrecht** [comment]
That all sounds good to me 👍

**Comment by dsifford** [comment]
@itchyny https://github.com/dracula/vim/pull/72

**Comment by dsifford** [comment]
Merged in dracula/vim@dc8073cd13d149be0578a5b5e36eaedef0a9ad5a

**Comment by itchyny** [comment]
I removed the theme from this repository. Please confirm.

**Comment by dsifford** [comment]
It's live in the vim theme: https://github.com/dracula/vim/blob/master/autoload/lightline/colorscheme/Dracula.vim

Great teamwork!

**Comment by itchyny** [comment]
Thank you.
