### ISSUE TITLE
Ability to specify separators to appear without spaces on either side, other dynamic width questions

### ISSUE THREAD

**Issue by unphased** [itchyny/lightline.vim#300]
I have a lot of things in the statusline, and would like to maximize visibility of items inside when i make my terms skinny.

1. is there a way to change the subcomponents so that they take up 2 fewer characters by eliminating the space around the separator bar? Yes it will be slightly uglier, but I want to at least evaluate what it looks like saving this space. It does seem a bit silly that in the default config the spacing between two components is 2 spaces while the space between two subcomponents is 3 spaces! 

2. I expect dynamic components to be expressly excluded from management by this plugin due to its design principles, but I wanted to just ask about what might be the best way to implement dynamic fields based on width, because I sort of need it for sane workflow on skinny terms. I expect that it will work well to just use window resize autocommand: `autocmd VimResized * noautocmd call AdjustStatusSections()`. Where that function can have inside it all the magic to decide which components to leave out, and munge `g:lightline:active` etc. accordingly. When I still used airline, there was something to help with this (`section_truncate_width`). It seems like it'd be very easy to re-create something like those thresholds used to decide when to remove sections, but how might I go about checking the extant size of the sections as they currently are rendered? It seems that I would need this in order to guarantee that certain components are always fully visible while still maximizing the use of the remaining space. Airline was a complete failure at facilitating this. Despite lightline being that much more configurable, it's unclear how i can get the data necessary to perform the optimal computation.

**Comment by itchyny** [comment]
How about using `g:lightline.component_raw`? It appends the components without wrapping within `%( ... %)`.

**Comment by kevinhwang91** [comment]
@itchyny How to remove the space between sub-components by config?  It's always more than two space between them.
I can make multiple sub-components to be one to avoid these spaces, but I think it isn't a long-term policy.

**Comment by kevinhwang91** [comment]
I'm sorry, I took a little time to read carefully and practice, It can specify the sub-components as a raw typ. `component_type'`
