### ISSUE TITLE
Tabline Configuration Issues

### ISSUE THREAD

**Issue by sirplatypos** [itchyny/lightline.vim#302]
I have added the ungodly combination of both buffers and tabs in my tabline.  The buffers behave properly, and will expand to both sides when necessary.  It is configured so that the buffers are on the right and the tabs are on the left.  My problem is that the tabs lack the functionality of the buffers. 

The buffers will expand out from the right, and when they run out of space will start a scrollable list, expanding to the left.  If you select a buffer that is on the leftmost side, the buffers will move so that they have expanded off to the right instead, thus allowing you to see your selected buffer on the left.  Furthermore, the bufferline will always move appropriately to show the current buffer.

Unfortunately, the tabline cannot do nearly as much.  It is positioned to the left, but overflows to the left as well.  This means that as soon as it runs out of space the tabinfo thing gets pushed off the screen.  Also, when you select a tab that has been moved off of the screen, the tabline does not adjust, so you cannot see it.  Is there a way to make the tabline act like the taohexxx/lightline-buffer plugin?

**Comment by itchyny** [comment]
I recommend you to create your own tabline component. For example:
```vim
let g:lightline = {
      \ 'component_expand': {
      \  'tabs': 'LightlineTabs'
      \ }
      \ }

function! LightlineTabs() abort
  let [x, y, z] = [[], [], []]
  let nr = tabpagenr()
  let cnt = tabpagenr('$')
  for i in range(1, cnt)
    call add(i < nr ? x : i == nr ? y : z,
          \ '%' . i . '%%{lightline#onetab(' . i . ',' . (i == nr) . ')}'
          \ . (i == cnt ? '%T' : ''))
  endfor
  if len(x) > 3
    let x = x[len(x)-3:]
    let x[0] = '<' . x[0]
  endif
  if len(z) > 3
    let z = z[:2]
    let z[len(z)-1] = z[len(z)-1] . '>'
  endif
  return [x, y, z]
endfunction
```
