### ISSUE TITLE
[Question] What is CUI?

### ISSUE THREAD

**Issue by ym1234** [itchyny/lightline.vim#304]
I'm making a port of airline's hybrid theme, the only problem I had so far is that I don't know what cuifg and cuibg are.
I set all of the cui fields to random numbers but I don't notice any difference, and searching for "cui vim"/searching issues here/help page for lightline doesn't bring up anything useful. (I know you can let lightline set them for you with `lightline#colorscheme#fill(s:p)`)

Thanks!

**Comment by itchyny** [comment]
CUI is the abbreviation of Character User Interface but I think I have to rewrite the doc to use `cterm`.
