### ISSUE TITLE
No highlights while in a tmux session

### ISSUE THREAD

**Issue by brainst0rm** [itchyny/lightline.vim#306]
As the title suggests, the plugin doesn't seem to have any effect on the status bar while using vim inside a tmux session. Is there any work around for this that I might not be aware of?

Thanks!

**Comment by itchyny** [comment]
Try `export TERM=xterm-256color` in your shell config.

**Comment by brainst0rm** [comment]
Unfortunately that doesn't help :(

**Comment by itchyny** [comment]
`:echo &t_Co` in Vim prints 256?

**Comment by brainst0rm** [comment]
My bad, I exported xterm outside of tmux when I should have done it in a session. Thanks for your help :)

**Comment by itchyny** [comment]
Ahh, maybe `set -g default-terminal screen-256color` in tmux.conf will help.

**Comment by brainst0rm** [comment]
I updated my bashrc and that fixed it for all future sessions :)

**Comment by itchyny** [comment]
OK, thanks.

**Comment by kdyhkdy** [comment]
@itchyny  i hava same issue . but i cant fix this .. help me bro!

**Comment by itchyny** [comment]
@kdyhkdy  Please create **a new issue** if there's some trouble with environment info, precise steps expected behavior and minimal vimrc if possible.
