### ISSUE TITLE
Place Tabs on Status Bar

### ISSUE THREAD

**Issue by starifly** [itchyny/lightline.vim#313]
Is there any way to place tabs in the status bar rather the actual tab bar?

I like having my buffers on top since I have more space and I always have more buffers than tabs.

Just like the image below:
![tabline](https://user-images.githubusercontent.com/2003879/43377473-7e757142-93f3-11e8-99e5-9341dc8eacaa.png)
Also, is there a way to add the powerline symbols to the tab as well? For example, from the image above, 'Tab1' is the current tab and should be highlighted. Basically I'd like it to look exactly like the buffers above.

**Comment by itchyny** [comment]
Example configuration:
```vim
let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ], [ 'readonly', 'filename', 'modified' ], [ 'statuslinetabs' ] ]
      \ },
      \ 'component_expand': {
      \   'statuslinetabs': 'LightlineStatuslineTabs',
      \ },
      \ }

function! LightlineStatuslineTabs() abort
  return map(range(1, tabpagenr('$')), 'lightline#tab#filename(v:val)')
endfunction
```

**Comment by itchyny** [comment]
Example configuration:
```vim
let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ], [ 'readonly', 'filename', 'modified' ], [ 'statuslinetabs' ] ]
      \ },
      \ 'component_expand': {
      \   'statuslinetabs': 'LightlineStatuslineTabs',
      \ },
      \ }

function! LightlineStatuslineTabs() abort
  return join(map(range(1, tabpagenr('$')),
        \ '(v:val == tabpagenr() ? "[*] " : "") . lightline#tab#filename(v:val)'), " \u2b81 ")
endfunction
```
Replace the `[*]` with your favorite characters.
