### ISSUE TITLE
Some questions/problems, thanks!

### ISSUE THREAD

**Issue by if2012** [itchyny/lightline.vim#314]
1. How to display function name on the statusline

2. fold file path instead of fold mode
![snipaste_20180813_201408](https://user-images.githubusercontent.com/2003879/44031122-949a67b4-9f35-11e8-8ac2-08da87694c98.jpg)

3.now i have two tabs, the tab 1 contains two buffers No.1 & No.2, the second tab 2 contains buffer No.3, 
![snipaste_20180813_201735](https://user-images.githubusercontent.com/2003879/44031470-b34859ea-9f36-11e8-9f95-e4bff88811fd.jpg)

then i close the tab 2, I want the buffer No.3 under the tab 2 to hide, but not:
![snipaste_20180813_202524](https://user-images.githubusercontent.com/2003879/44031647-34139ae4-9f37-11e8-877f-cdfc64651a5f.jpg)

i use the plug 'taohexxx/lightline-buffer'

**Comment by itchyny** [comment]
1. Function name in statusline: install https://github.com/tyru/current-func-info.vim and configure as follows.
```vim
let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ], [ 'readonly', 'filename', 'modified' ], [ 'funcname' ] ],
      \ },
      \ 'component': {
      \   'funcname': '%{cfi#format("%s", "")}',
      \ },
      \ }
```

2: Abbreviate file names.
```vim
let g:lightline = {
      \ 'component_function': {
      \   'filename': 'LightlineFilename',
      \ },
      \ }

function! LightlineFilename() abort
  let name = expand('%:p') !=# '' ? expand('%:p') : '[No Name]'
  return len(name) < 40 ? name : '<'.name[len(name)-40:]
endfunction
```

3: That looks like an issue of lightline-buffer, not lightline.

**Comment by if2012** [comment]
@itchyny Does not seem to work

1. just works in vim files, does not get the function name in c, cpp, etc

2.When splitting the screen, the mode is still folded.

**Comment by itchyny** [comment]
1. README.md of current-func-info.vim mentions C support so please contact the author of the plugin.
2. Please use the `winwidth(0)` to truncation threshold.

**Comment by if2012** [comment]
@itchyny 
2.how to do?

**Comment by itchyny** [comment]
Try `:h winwidth` to see what it means. It returns the width of the window, specifically the current window when 0 is given. What you want to archive is, when I understand correctly, truncate the filename not so that the total width of the components does not exceed the window width. Following is an example, while you can change the constants.
```vim
function! LightlineFilename() abort
  let name = expand('%:p') !=# '' ? expand('%:p') : '[No Name]'
  let threshold = winwidth(0) - 50
  return len(name) < threshold ? name : '<'.name[len(name)-threshold:]
endfunction
```

**Comment by itchyny** [comment]
OK, I found another solution.
```vim
let g:lightline = {
      \ 'component': {
      \   'filename': '%<%{LightlineFilename()}',
      \ },
      \ }

function! LightlineFilename() abort
  return expand('%:p') !=# '' ? expand('%:p') : '[No Name]'
endfunction
```

**Comment by if2012** [comment]
ok. i will try it tomorrow

**Comment by if2012** [comment]
@itchyny wonderful

**Comment by if2012** [comment]
@itchyny 
but a new question, when the number of windows exceeds 2, the mode is still folded
![snipaste_20180819_205158](https://user-images.githubusercontent.com/2003879/44309012-200df980-a3f2-11e8-8d93-bc0e213f78f7.jpg)

**Comment by itchyny** [comment]
That does not reproduce on my Vim. Can you paste the entier configuration?

**Comment by if2012** [comment]
@itchyny 
[conf](https://github.com/if2012/FlyVim/blob/master/mp/appearance/lightline.vim)

**Comment by itchyny** [comment]
That truncation is caused by the `LightlineMode` function. Please fix the last line to `\ lightline#mode()`.

**Comment by if2012** [comment]
@itchyny 
Worked, thanks very much
