### ISSUE TITLE
Extra Line When Creating a File

### ISSUE THREAD

**Issue by redreceipt** [itchyny/lightline.vim#319]
I'm seeing an extra line always below lightline. When I create a new file, it shows the file name. My `.vimrc` settings are:

```
set laststatus=2
set noshowmode
```

Screenshot attached. What am I doing wrong?

![screen shot 2018-09-17 at 10 35 44 am](https://user-images.githubusercontent.com/2659478/45630052-d868a500-ba65-11e8-93b0-b6289be5719c.png)

**Comment by itchyny** [comment]
That line is called command-line and we cannot configure to remove the line of Vim. Plugin is not allowed to change the behavior too.

**Comment by mschilli87** [comment]
Also see https://superuser.com/q/619765/240925.

**Comment by redreceipt** [comment]
Excellent, thank you.

**Comment by dr-peppa** [comment]
Can't we at least hide the name of the open buffers in the command line? I don't want to get rid of the line, just of the duplicate filenames...

**Comment by itchyny** [comment]
You cannot do that without changing the source code of Vim.
