### ISSUE TITLE
Add a disable variable or 8 color compatible scheme?

### ISSUE THREAD

**Issue by jayflo** [itchyny/lightline.vim#32]
Hello,
I think this status bar is very good.  However, I am on archlinux and the colorschemes do not work well on the TTY console.  Would it be possible to add a variable that allows me to disable lightline when using vim in the TTY console or, perhaps, add an 8 color compatible colorscheme?

Thanks!

**Comment by thiagowfx** [comment]
Sorry for the bump, but to help those that come here from search engines:

The `one` colorscheme works well (=looks good) in Arch Linux's Linux Console (TTY) out-of-the-box (unlike the default `powerline` theme):

```
let g:lightline = {
      \ 'colorscheme': 'one',
      \ }
```
