### ISSUE TITLE
lineline did not work 

### ISSUE THREAD

**Issue by JIAKanghao** [itchyny/lightline.vim#320]
I have install the lightline through the way:
1) add Plugin 'itchyny/lightline.vim' into .vimrc
2) execute :PluginInstall
But while I restart vim, the lightline did not show.

**Comment by itchyny** [comment]
1. Please read https://github.com/itchyny/lightline.vim#introduction again.
2. If it does not help, please paste the entire vimrc or the link to your configuration.

**Comment by JIAKanghao** [comment]
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
" add nerdtree
Plugin 'scrooloose/nerdtree'
" add lightline
Plugin 'itchyny/lightline.vim'
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ }





" All of your Plugins must be added before the following line
call vundle#end()            " required


above is my plugin config in vimrc. I am new to vim, so I need your precious suggestion about that. Thank you.

**Comment by itchyny** [comment]
How about adding `set laststatus=2` to your .vimrc?

**Comment by JIAKanghao** [comment]
cool!!! It works. Thank you so much. I miss this configuration.
