### ISSUE TITLE
Text color changes after entering insert mode in tmux session

### ISSUE THREAD

**Issue by BrandonClapp** [itchyny/lightline.vim#321]
Hi, 

I just installed lightline in vim and am having an issue that is specific to tmux. The plugin colors work great outside of tmux, however, when I start a new tmux session and go into vim I observe the following behavior...

While in tmux session...
1. Open file. I see the following colors. Everything looks great.

![before](https://user-images.githubusercontent.com/2096746/46260928-2a6fe880-c4b2-11e8-8368-99727b98e872.PNG)

2. I go into insert mode. The text turns white and the word INSERT isn't visible.

![after](https://user-images.githubusercontent.com/2096746/46260934-3b205e80-c4b2-11e8-943f-fc8fa178919c.PNG)

3. I go back to normal mode and notice that the text is still white (as opposed to the first image)

![after-exit-insert](https://user-images.githubusercontent.com/2096746/46260938-4ecbc500-c4b2-11e8-8919-09cbad2edc1b.PNG)

This only happens in tmux, so I'm thinking it has something to do with tmux colors. Upon checking `:echo &t_Co` in vim (while in the tmux session), I see 256.

What I've tried:
- Setting `export TERM=xterm-256colors` in my `.bashrc` file. Once again, however, colors work fine outside of tmux.
- Creating a `.tmux.conf` file and trying the following settings 
  - `set -g default-terminal "screen-256color"` - Didn't seem to change anything
  - `set -g default-terminal "xterm-256color"`  - Also didn't change anything

Any thoughts on what could be affecting this?

**Comment by itchyny** [comment]
Looks weird and needs some debugging. Please check the output of `:hi LightlineLeft_active_0` and `:hi LightlineLeft_normal_0`.

**Comment by BrandonClapp** [comment]
I'm going to go ahead and close this because I'm almost certainly sure that it's an issue with 256 color support with Windows WSL.
