### ISSUE TITLE
How to dynamically control stuff based on width that uses modeline expansions?

### ISSUE THREAD

**Issue by unphased** [itchyny/lightline.vim#322]
I am trying to make my `charvaluehex` disappear when window is less than 50 columns. 

    fun CharValueHex()
      return winwidth(0) > 50 ? '0x%02B' : ''
    endfun

and referencing this from component_function for `charvaluehex` or using component as `'charvaluehex': '%{CharValueHex()}',`, the literal string `0x%02B` gets placed into the component instead of the expanded value of the char the cursor is on. It does disappear cleanly at 50 cols width though.

This technique works for other stuff that shows settings and other dynamic content, but here I just want to send it in literally and non-escaped, and have the modeline expand it for me. Can this be done?

BTW I also want to do this for `lineinfo`.

**Comment by unphased** [comment]
https://github.com/itchyny/lightline.vim/issues/314 seems to hint that a fully dynamic function may need to be used to have this level of control. I worry about the performance implications, and about the possibility of dynamically retrieving several of these quantities (char under cursor `%B`, cursor column range `%V`).

**Comment by unphased** [comment]
if this is not possible I really think some lightline specific config should exist that lets us control width expansion better: decide on the priority of the visibility of the different components, modularly.

**Comment by itchyny** [comment]
Example configuration
```vim
let g:lightline = {
      \ 'active': {
      \   'right': [ [ 'lineinfo' ], [ 'percent' ], [ 'fileformat', 'fileencoding', 'filetype', 'charvaluehex' ] ]
      \ },
      \ 'component_function': {
      \   'charvaluehex': 'LightlineCharValueHex',
      \   'lineinfo': 'LightlineLineInfo',
      \ },
      \ }

function! LightlineCharValueHex()
  return winwidth(0) > 50 ? printf('%02x', char2nr(getline('.')[col('.')-1])) : ''
endfunction

function! LightlineLineInfo()
    return winwidth(0) > 50 ? printf('%d:%-2d', line('.'), col('.')) : ''
endfunction
```

**Comment by unphased** [comment]
You have been able to address all the actual concerns I've outlined in that dynamic way there, so I will close the issue. Thank you. 

I do hope we can think about how to implement priority based collapsing, however, so that this can be controlled more elegantly. Thanks!
