### ISSUE TITLE
Awkward Spacing on Statusbar between split tabs

### ISSUE THREAD

**Issue by tusharsrivastava** [itchyny/lightline.vim#323]
![screen shot 2018-10-05 at 1 22 09 pm](https://user-images.githubusercontent.com/8246875/46522958-e578f700-c8a1-11e8-986c-f66d430c7ea0.png)

As we can see an awkward space between the two status bar. Is there any solution to this issue?

Thank you.

**Comment by itchyny** [comment]
The `StatusLine` highlight is related to the color of that space. Try `highlight StatusLine ctermfg=0 ctermbg=243` (if you are using GVim, set `guifg` and `guibg`).

**Comment by tusharsrivastava** [comment]
Tried with no luck. Using vim8 on iTerm2.

**Comment by itchyny** [comment]
What's the output of `:hi StatusLine`?

**Comment by tusharsrivastava** [comment]
This is the output
`StatusLine     xxx term=bold,reverse ctermfg=15 ctermbg=8 guifg=#FCE8C3 guibg=#2D2C29`

**Comment by itchyny** [comment]
OK, that contains the reverse property. Try changing the value of ctermfg.

**Comment by tusharsrivastava** [comment]
Ok since I have NerdTree opened automatically on opening Vim, the command in vimrc only runs on the first window and so it is not effective on other windows. Is there a way to do this when any new window is opened? Sorry I'm bit new to this.

**Comment by itchyny** [comment]
The color of StatusLine is global and not related to the window layout. Can you try `highlight StatusLine ctermfg=243 ctermbg=243 term=none cterm=none`?

**Comment by tusharsrivastava** [comment]
Hi finally found `236` to be working

**Comment by itchyny** [comment]
I don't get what you mean by no solution. Whatever the color you like, setting both ctermbg and ctermfg to it does not help?

**Comment by tusharsrivastava** [comment]
Found it working with `236` but is there a way to do it automatically based on theme I use? For example with `sublime-monokai` `236` works but with `srcery` it doesn't.

**Comment by itchyny** [comment]
1. Use the `ColorScheme` event to detect the colorscheme change.
2. To get some color from colorscheme, use `redir` to get the output of highlight command.
3. Use the value to construct a `highlight` command and `execute` it.

I close this issue, this is not related to the plugin.

**Comment by tusharsrivastava** [comment]
Thanks. You were very helpful.
