### ISSUE TITLE
NERDTree Tab Setting

### ISSUE THREAD

**Issue by prabjot-singh** [itchyny/lightline.vim#324]
Hey, 
I came across this cool setting for the status bar with respect to NERDTree

![Imgur](http://i.imgur.com/jSCwGjU.gif?1)
Credit: https://github.com/Xuyuanp/nerdtree-git-plugin 

Can this be done in lightline? I think the above used status bar is vim-airline. 
I want NERDTree tab should only show NERDTree and nothing else.

I tried using the solution you mention this issue #297, but it didn't work as expected.

**Comment by itchyny** [comment]
Please follow the README.md, the document describes how to use component functions, for example see https://github.com/itchyny/lightline.vim#can-i-display-the-plugin-name-at-the-mode-component.

**Comment by prabjot-singh** [comment]
Hi @itchyny, I tried that it still does not work. Maybe I am doing something wrong. Please check the below image
![Imgur](https://i.imgur.com/ArYpPo6.png)

I am using this function,
```
let g:lightline = {
      \ 'component_function': {
      \   'mode': 'LightlineMode',
      \ },
      \ }

function! LightlineMode()
  return expand('%:t') ==# 'NERD_tree' ? 'NERD':
        \ lightline#mode()
endfunction

```

**Comment by itchyny** [comment]
Right components should also be written in the function form, please refer to  https://github.com/itchyny/lightline.vim/issues/322#issuecomment-426545894.

**Comment by itchyny** [comment]
Also there're some hints in `:h lightline-powerful-example` how to write down the component functions.

**Comment by prabjot-singh** [comment]
I got it. Had to write functions for all the components in order to hide them. 

Is there an easier way? Like hiding the complete right column, instead of hiding each component individually
Or there is a scope for auto truncation in future?

**Comment by itchyny** [comment]
No, there's no easy way to do that in this plugin and there's no plan to support it. That would require complete rewrite and will be a new plugin.
