### ISSUE TITLE
Simple question, great job !

### ISSUE THREAD

**Issue by doums** [itchyny/lightline.vim#325]
Hi, I'm new in vim. I tested your status line. It's really nice, thank ! But I would like to know how to get rid of this:
![vim](https://user-images.githubusercontent.com/6359431/47177828-cd7d8a80-d319-11e8-9079-81e6da3d3f50.png)

Like you can see there is always this useless and duplicate details on the bottom of vim when I open a file. Sometimes there is just a blank line. I would like just to have the status line at the bottom.

It's possible ?

[EDIT] Ok after more search it seems to be impossible and it's normal because it's the command line. However I fixed the verbose with : `set shortmess=FaWc`

**Comment by itchyny** [comment]
It seems you have resolved by yourself so I close the issue, thanks.
