### ISSUE TITLE
Custom color for characters inside segment

### ISSUE THREAD

**Issue by oblitum** [itchyny/lightline.vim#329]
Hi, thanks for this plugin!

There's just one thing I'm missing which seems would require me to do a hard-coded patch. I want a single character in one segment of my lightline to be red, like in my tmux bar:

![20 13 29_17-11-18](https://user-images.githubusercontent.com/1269815/48666287-d642b700-eaa5-11e8-8736-96268368f45b.png)

Possible?

**Comment by itchyny** [comment]
Basically lightline does not support different color in one component. See `:h lightline-problem-12` for reference.

**Comment by oblitum** [comment]
:(

ok, I'll have to patch it.

Thanks.

**Comment by oblitum** [comment]
Ah OK, `:h  lightline-problem-12` shows a hack.

**Comment by leesmith** [comment]
Unrelated question...is it possible to add the arrow characters to the lightline segments like in the screenshot? Thanks!

**Comment by oblitum** [comment]
@leesmith you need a patched font with those characters, they're generally referred to as powerline symbols, then you set lightline separators, I think that is shown in README/docs. The [Nerd Fonts](http://nerdfonts.com/) provides them and several others for devs. Back to the topic, [putting my red star was not difficult at all](https://github.com/oblitum/dotfiles/blob/c2675bde6d82d88004f42195cb20c3b544b18eb8/.vimrc#L602).

**Comment by leesmith** [comment]
Thanks @oblitum!
