### ISSUE TITLE
Colorscheme "one" not working as expected

### ISSUE THREAD

**Issue by Lubits** [itchyny/lightline.vim#330]
I'm having the exact same issue as #263 and #280 

#280 doesn't talk about how they fixed it. Other colorschemes seem to work fine for me though.
I just installed the plugin using Vim Plug, I've also tried to run an update (PlugUpdate) but to no avail.

The colours now look like this:
<img width="682" alt="screenshot 2018-11-20 at 13 57 09" src="https://user-images.githubusercontent.com/3738747/48775044-2e5b0280-eccc-11e8-9496-dff61a610236.png">

**Comment by Lubits** [comment]
After looking at the code for "one" a bit, it seems to be a problem with the selection of the Light or Dark theme?

It seems to be selecting the light theme, while I expect it to select the dark theme.

**Comment by itchyny** [comment]
Please check the output of `:hi Normal` and `:echo lightline#colorscheme#background()`.

**Comment by Lubits** [comment]
`:echo lightline#colorscheme#background()` returns Light
`:hi Normal` returns `Normal    xxx cleared`

**Comment by itchyny** [comment]
So `:echo &background` echos `light` too, right? Then you are using the light colorscheme and lightline selects the light colors. Please set background=dark if you prefer the dark colorscheme.

**Comment by Lubits** [comment]
So adding `set background=dark` which worked to switch to the dark timeline. Thanks!

However, it seems that the colours I get is different from the colours in the readme. Is this due to the fact that the screenshot is not correct? Or are the colours I'm getting not correct?

<img width="920" alt="one" src="https://user-images.githubusercontent.com/3738747/48805440-b31f3e00-ed17-11e8-8056-1421afe8e0b4.png">
<img width="566" alt="screenshot 2018-11-20 at 22 44 32" src="https://user-images.githubusercontent.com/3738747/48805468-bfa39680-ed17-11e8-90bb-501910768b04.png">
<img width="564" alt="screenshot 2018-11-20 at 22 44 50" src="https://user-images.githubusercontent.com/3738747/48805469-bfa39680-ed17-11e8-9803-7a79508b1bc4.png">
<img width="564" alt="screenshot 2018-11-20 at 22 46 13" src="https://user-images.githubusercontent.com/3738747/48805472-c29e8700-ed17-11e8-9835-2e89c3093a4d.png">
<img width="565" alt="screenshot 2018-11-20 at 22 45 17" src="https://user-images.githubusercontent.com/3738747/48805482-c6caa480-ed17-11e8-9580-4225f3825dc8.png">

**Comment by itchyny** [comment]
Are you using Vim in a terminal? The screenshots in README.md are captured with GVim so terminal colors are different. But if your Vim supports termguicolors (check `:echo has('termguicolors')` to be 1), `set termguicolors` will help.

**Comment by Lubits** [comment]
@itchyny Ahh, that's it then. Thanks for the help and the quick responses. I'll close this now.

**Comment by jef** [comment]
> So `:echo &background` echos `light` too, right? Then you are using the light colorscheme and lightline selects the light colors. Please set background=dark if you prefer the dark colorscheme.

Interesting enough, For both `:echo &background` and `:echo lightline#colorscheme#background()` I get light, yet I still don't get a light color theme?

![image](https://user-images.githubusercontent.com/12074633/103911709-58522780-50d4-11eb-9404-0f2d1beedaa9.png)

Thanks!

**Comment by itchyny** [comment]
You seem to use the default colorscheme which does not have the light variant.

**Comment by jef** [comment]
> You seem to use the default colorscheme which does not have the light variant.

Ah! Makes sense. Unfortunately, I tried with `one` and `PaperColor`. Still the same results 😞 

![image](https://user-images.githubusercontent.com/12074633/103912719-a4519c00-50d5-11eb-983a-615fb0c6241e.png)


Thanks for your help ☺️

**Comment by itchyny** [comment]
Move the config before call plug#end() might fix it.

**Comment by jef** [comment]
Unfortunately, it didn't 😢 I'm using kitty (default `TERM=xterm-kitty`) as well, not sure if that's relevant. I tried exporting `TERM=xterm-256color` and setting the colors in `.vimrc` like you in the `README`, but no luck.

Perhaps it's something on my end, but can't seem to figure it out. I'll keep on playing with it. Let me know if any solution pops up! Thanks for your time.
