### ISSUE TITLE
Unsaved changes in unfocused split lose '+' indicator

### ISSUE THREAD

**Issue by Qix-** [itchyny/lightline.vim#331]
![kapture 2018-11-20 at 16 48 02](https://user-images.githubusercontent.com/885648/48785764-aa157900-ece5-11e8-9d23-f3b28527f94d.gif)

It'd be great if the unsaved indicator (the `+`) would still show up for unsaved panes in a split-paned session.

**Comment by itchyny** [comment]
Please add the modified component to g:lightline.inactive.left. See README.md for further details.

**Comment by Qix-** [comment]
What do you mean "modified component"?

**Comment by itchyny** [comment]
```vim
let g:lightline = {
      \ 'inactive': {
      \   'left': [ [ 'filename', 'modified' ] ],
      \ }
      \ }
```

**Comment by Qix-** [comment]
That did it! Thank you
