### ISSUE TITLE
lightline#update() reenables lightline

### ISSUE THREAD

**Issue by oblitum** [itchyny/lightline.vim#332]
If I do `call lightline#disable()`, lightline is turned off, but `call lightline#update()` brings it back. I wish and was expecting it to come back solely on `call lightline#enable()`.

**Comment by itchyny** [comment]
I think I can fix this but please let me ask, where `lightline#update` is called while the lightline is disabled. `lightline#disable` removes all the autocmd `lightline`  so `lightline#update` should not be called from the source code of lightline.

**Comment by oblitum** [comment]
It can be called from callbacks from diagnostic plugins. Currently at my conf I've put some checks to avoid this issue, but I think it would be best that lightline.vim itself woudn't show up on update when it's disabled. My case specifically, two plugins, one does diagnostic and calls `lightline#update()` anytime it has a new diagnostic, I do that from configured call back, the other is my fork of Goyo, which provides Zen mode for Vim, problem is that when on Zen mode the statusline shouldn't be visible, but if diagnostics is still enabled, callbacks calls `lightline#update()` and brings the statusline back when in Zen mode, I've then applied a fix checking if I'm in Zen mode or not before calling `update()`.

**Comment by itchyny** [comment]
It should be fixed for now, thanks for issue report.

**Comment by oblitum** [comment]
Thanks for the fixed, just tried, made my setup cleaner.
