### ISSUE TITLE
Is there a way to show BOM info?

### ISSUE THREAD

**Issue by KorvinSilver** [itchyny/lightline.vim#333]
I'm trying to figure out if it's possible to show BOM info in lightline but so far I couldn't.
The easiest way to add it to the statusline is:

    set statusline+=\ %{&bomb?'BOM':''}

I don't really understand how this line works though and everything else I've found is way too complex to decipher without a deeper understanding of what's going on. Can you turn this into something that works here as well or is there a built-in way that's not documented?

**Comment by itchyny** [comment]
Example configuration:
```vim

let g:lightline = {
      \ 'active': {
      \   'right': [ [ 'lineinfo' ], [ 'percent' ], [ 'fileformat', 'fileencoding', 'filetype', 'bomb' ] ],
      \ },
      \ 'component': {
      \   'bomb': '%{&bomb?"BOM":""}',
      \ },
      \ 'component_visible_condition': {
      \   'bomb': '&bomb',
      \ },
      \ }
```
Or alternatively,
```vim
let g:lightline = {
      \ 'active': {
      \   'right': [ [ 'lineinfo' ], [ 'percent' ], [ 'fileformat', 'fileencoding', 'filetype', 'bomb' ] ],
      \ },
      \ 'component_function': {
      \   'bomb': 'LightlineBomb',
      \ }
      \ }

function! LightlineBomb()
  return &bomb ? "BOM" : ""
endfunction
```

**Comment by KorvinSilver** [comment]
Thanks, the first one did the trick
