### ISSUE TITLE
Lightline config to hide fzf lengthy description

### ISSUE THREAD

**Issue by luongvo209** [itchyny/lightline.vim#334]
![image](https://user-images.githubusercontent.com/15828926/49343374-5ec27980-f69a-11e8-9547-083c08abc7a9.png)
As much as I tried, I cannot hide this lengthy path of some unknown thing whenever I enter fzf to find file or search for something. I clearly know that you may not be aware of what is fzf but if you happen to, please help. If you feel like this is not your problem, feel free to close this issue. 
Thank you.

Here's my super simple config which I use to find files with fzf (and also the one being used in the picture above) 
```vimscript
map <c-p> <ESC>:call fzf#vim#files('.', {'options': g:fzf_preview_source})<CR>
```

**Comment by itchyny** [comment]
How about the configuration in https://github.com/junegunn/fzf.vim#hide-statusline.

**Comment by luongvo209** [comment]
Thank you so much for such lightning reply @itchyny. This is actually my bad. 
Initially i want to get filepath relative to current working dir. So I copy paste your code here
https://github.com/itchyny/lightline.vim/issues/293#issuecomment-373710096
The problem is that when returning 
```
return expand('%')
``` 
it will show the full path to the temporary buffer of terminal mode of fzf (not sure if I am using the right terminology for this).

How I customized it so that it works fine now  : 
```vimscript
let g:tcd_blacklist = '\v(cheat40|denite|gundo|help|nerdtree|netrw|peekaboo|quickmenu|startify|tagbar|undotree|unite|vimfiler|vimshell|fzf)'

function! LightlineFilename()
  let root = fnamemodify(get(b:, 'git_dir'), ':h')
  let path = expand('%:p')
  if path[:len(root)-1] ==# root
    return &filetype !~# g:tcd_blacklist && winwidth(0) > 70 ? Devicon().' '.path[len(root)+1:] : ''
  endif
  return &filetype !~# g:tcd_blacklist && winwidth(0) > 70 ? Devicon().' '.expand('%') : &filetype
endfunction
```
![image](https://user-images.githubusercontent.com/15828926/49390743-56327780-f75c-11e8-8d28-55e16aacb824.png)
