### ISSUE TITLE
Feature request - Set CursorLine colour = Lightline color?

### ISSUE THREAD

**Issue by bradwood** [itchyny/lightline.vim#335]
It would be nice to set the cursorline to the same color as the lightline bar.  Is there a function I can call to get the color to pass into cursorline? 

thanks

**Comment by itchyny** [comment]
The function `lightline#palette()` provides the ligthline colors and please use it to set the `CursorLine` highlight.

**Comment by bradwood** [comment]
thanks. but I'm not clear how to invoke the function on the `CursorLine` entry.

something like
```:hi CursorLine   cterm=lightline#palette()```
does not work.

Can you provide an example pls, as `lightline#palette() ` returns a whole dictionary of stuff..

**Comment by itchyny** [comment]
```vim
function! SetCursorLineFromLightline() abort
  let palette = lightline#palette()
  let colors = palette.normal.middle[0]
  execute printf(
        \ 'highlight CursorLine guifg=%s guibg=%s ctermfg=%s ctermbg=%s',
        \ colors[0], colors[1], colors[2], colors[3])
endfunction
```
and invoke as `call SetCursorLineFromLightline()`.

**Comment by bradwood** [comment]
thanks! works a treat!

**Comment by itchyny** [comment]
Then please use the global palette variable instead of `lightline#palette()`,
```vim
  let palette = g:lightline#colorscheme#{g:lightline.colorscheme}#palette
```

**Comment by bradwood** [comment]
fixed... Thanks!
