### ISSUE TITLE
Incompatibility with taboo.vim and can't fully disable tabline

### ISSUE THREAD

**Issue by bedax** [itchyny/lightline.vim#337]
I usually have various tabs open at one time that are usually renamed with `:TabooRename` from [taboo.vim](https://github.com/gcmt/taboo.vim).

lightline doesn't seem to like taboo.vim as when taboo is installed lightline's tabline doesn't activate at startup, so I never noticed lightline had a tabline feature. That is until I used [`:Goyo`](https://github.com/junegunn/goyo.vim) then `:Goyo!`, then `lightline#link` gets called, the tabline activates, and it then messes up all the tabs. I assume it does this because of its misinteraction with taboo but I'm not sure.

Either way, to stop lightline from messing up the tabs I disabled the tabline feature using the normal method, but it doesn't seem to fully work, as now when I repeat the goyo thing, it doesn't enable anymore, it just mixes up the tabs without enabling the tabline feature.

I'm not sure if the two misinteractions mentioned are with taboo or lightline, if it's with lightline it would be nice if it was fixed, but the main issue here is the inability to fully disable lightline's tabline feature.

Thanks a lot for lightline though, besides this small point it's excellent.

**Comment by itchyny** [comment]
To disable tabline of lightline, try following configuration.
```vim
let g:lightline.enable = {
      \ 'tabline': 0
      \ }
```

**Comment by itchyny** [comment]
To disable tabline of lightline, try the following configuration.
```vim
let g:lightline = {
      \ 'enable': { 'tabline': 0 },
      \ }
```

**Comment by bedax** [comment]
Hi @itchyny, thanks for the reply. I tried disabling the tabline with that method and it didn't work, the problem still remains as described above.

**Comment by itchyny** [comment]
It should disable the tabline of lightline, please reconfirm that `:echo g:lightline.enable.tabline` should print 0.
