### ISSUE TITLE
modeset for tab collapsing

### ISSUE THREAD

**Issue by bitshiftnetau** [itchyny/lightline.vim#348]
First up: GREAT plugin... love it!!!

Second, is there a way to modeset the tabs collapsing? I use vim-workspace and would like to have my tabs span across the top as opposed to being collapsed into one square display on the left. 

Is this a bug? Should the tabs span anyway? I uninstalled vim-workspace but no change, just lose tab navigation functionality. 

Thanks

**Comment by itchyny** [comment]
Sorry but I'm not sure what you're talking about... You're talking about the tabline behavior of lightline.vim? I still don't know what you mean by modeset. Please describe your expected behavior and actual behavior with some screenshots if possible.

**Comment by bitshiftnetau** [comment]
Ah sorry about that, he only recently changed the name.

Perfect!! Disabling the tabline in your plugin was all I needed :) thanks a bunch!!
