### ISSUE TITLE
Display cocstatus when nvim start

### ISSUE THREAD

**Issue by taigacute** [itchyny/lightline.vim#349]
@itchyny  Hi !  I added coc to the lightline, it is always displayed in the lightline, I don't need to see it when I open vim, I hope it will only appear when I open the file and there is a problem. By default it always exists，like this
open the nvim
![11323](https://user-images.githubusercontent.com/41671631/52175779-0451b080-27e4-11e9-9d55-dd54da7729e2.png)
open a file
![134](https://user-images.githubusercontent.com/41671631/52175782-103d7280-27e4-11e9-940c-607cd7097d54.png)

i set a function ，but it has problem，how do i fix it
```
function! LightLineCoc()
    if  exists("*coc#status")
        \ || get(g:,'coc_status',0)
        let msg = coc#status()
            return msg
    elseif exists("*coc#status")
        \ || !get(g:,'coc_status',0)
        return ""
    else 
        return ""
    endif
endfunction

```
but its wrong,it still exists when i open vim.I am not learn vimscript, modified according to other examples, cocstatus returns a string? hoping to get your help，this is `coc#status` function
```
function! coc#status()
  let info = get(b:, 'coc_diagnostic_info', {})
  let msgs = []
  if get(info, 'error', 0)
    call add(msgs, s:error_sign . info['error'])
  endif
  if get(info, 'warning', 0)
    call add(msgs, s:warning_sign . info['warning'])
  endif
  return join(msgs, ' ') . ' ' . get(g:, 'coc_status', '')
endfunction
```

**Comment by itchyny** [comment]
How about this configuration?
```vim
function! LightLineCoc()
  if empty(get(g:, 'coc_status', '')) && empty(get(b:, 'coc_diagnostic_info', {}))
    return ''
  endif
  return trim(coc#status())
endfunction
```

**Comment by taigacute** [comment]
> How about this configuration?
> 
> ```viml
> function! LightLineCoc()
>   if empty(get(g:, 'coc_status', '')) && empty(get(b:, 'coc_diagnostic_info', {}))
>     return ''
>   endif
>   return trim(coc#status())
> endfunction
> ```

its works well tanks。Can I ask for a demand?

**Comment by itchyny** [comment]
Sorry, what do you mean by demand? Some feature request?

**Comment by taigacute** [comment]
hmm  sorry，i want display the buffer number in mode position。this is my lightline， i hope there is `Home +number` like  `Home ①`， i  use lightline with bufferline
![2321](https://user-images.githubusercontent.com/41671631/52267754-d94a9680-2974-11e9-9133-64176f037465.png)

**Comment by itchyny** [comment]
Just append `bufnr('')` to the mode function.
```vim
let g:lightline = {
      \ 'component_function': {
      \   'mode': 'LightlineMode',
      \ },
      \ }

function! LightlineMode()
  return lightline#mode() . ' ' . bufnr('')
endfunction
```

**Comment by itchyny** [comment]
Not sure what `Home` is (buffer name?), but use `bufnr('')` to get the current buffer number.
```vim
function! LightlineFilename()
  return (expand('%:t') !=# '' ? expand('%:t') : '[No Name]') . ' ' . bufnr('')
endfunction
```

**Comment by taigacute** [comment]
> Not sure what `Home` is (buffer name?), but use `bufnr('')` to get the current buffer number.
> 
> ```viml
> function! LightlineFilename()
>   return (expand('%:t') !=# '' ? expand('%:t') : '[No Name]') . ' ' . bufnr('')
> endfunction
> ```

`Home` is string. i think `bufnr('')` is wrong? you see this pic .my number is 2 but i got 4
![1334](https://user-images.githubusercontent.com/41671631/52271750-89bd9800-297f-11e9-8154-3730aaabe3c7.png)

**Comment by itchyny** [comment]
You have `let g:lightline#bufferline#show_number  = 2` in your config?

**Comment by taigacute** [comment]
> You have `let g:lightline#bufferline#show_number = 2` in your config?

yes  i set this. this is my min config
```
let g:lightline = {
            \ 'colorscheme': 'space',
            \ 'active': {
            \   'left': [  ['homemode' ],
            \             [ 'fugitive','gitgutter', 'filename','cocstatus' ] ]
            \ },
				\   'component': {
				\     'lineinfo': ' %3l:%-2v',
				\   },
            \ 'component_function': {
            \   'homemode'    : 'LightlineMode',
            \   'fugitive': 'LightLineFugitive',
            \   'gitgutter': 'LightLineGitGutter',
            \   'readonly': 'LightLineReadonly',
            \   'modified': 'LightLineModified',
            \   'filename': 'LightLineFilename',
            \   'cocstatus': 'LightLineCoc',
            \   'filetype': 'LightLineFiletype',
            \   'fileformat': 'LightLineFileformat',
            \ },
            \ 'separator': { 'left': "\ue0b0", 'right': "\ue0b2"},
            \ 'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3"}
            \ }

function! LightlineMode()
    let num = bufnr('')
    return num
endfunction

function! LightLineModified()
    if &filetype == "help"
        return ""
    elseif &modified
        return "+"
    elseif &modifiable
        return ""
    else
        return ""
    endif
endfunction

function! LightLineReadonly()
    if &filetype == "help"
        return ""
    elseif &readonly
        return ""
    else
        return ""
    endif
endfunction

function! LightLineFugitive()
    if exists("*fugitive#head")
        let _ = fugitive#head()
        return strlen(_) ? ''._ : ''
    endif
    return ''
endfunction

function! LightLineCoc() 
    if empty(get(g:, 'coc_status', '')) && empty(get(b:, 'coc_diagnostic_info', {})) 
        return ''
    endif 
    return trim(coc#status())
endfunction

function! LightLineGitGutter()
  if ! exists('*GitGutterGetHunkSummary')
        \ || ! get(g:, 'gitgutter_enabled', 0)
        \ || winwidth('.') <= 90
    return ''
  endif
  let symbols = ['+','~','-']
  let hunks = GitGutterGetHunkSummary()
  let ret = []
  for i in [0, 1, 2]
    if hunks[i] > 0
      call add(ret, symbols[i] . hunks[i])
    endif
  endfor
  return join(ret, ' ')
endfunction

function! LightLineFilename()
    return ('' != LightLineReadonly() ? LightLineReadonly() . ' ' : '') .
                \ ('' != expand('%:t') ? expand('%:t') : '') .
                \ ('' != LightLineModified() ? ' ' . LightLineModified() : '')
endfunction

function! LightLineFiletype()
  return winwidth(0) > 70 ? (strlen(&filetype) ? &filetype . ' ' . WebDevIconsGetFileTypeSymbol() : 'no ft') : ''
endfunction

function! LightLineFileformat()
  return winwidth(0) > 70 ? ( WebDevIconsGetFileFormatSymbol()) : ''
endfunction
let g:lightline.tabline          = {'left': [['buffers']], 'right': [['close']]}
let g:lightline.component_expand = {'buffers': 'lightline#bufferline#buffers'}
let g:lightline.component_type   = {'buffers': 'tabsel'}
let g:lightline#bufferline#show_number  = 2
let g:lightline#bufferline#shorten_path = 1
let g:lightline#bufferline#filename_modifier = ':t'
let g:lightline#bufferline#unnamed      = '[No Name]'
let g:lightline#bufferline#number_map = {
\ 0: '➓ ', 1: '❶ ', 2: '❷ ', 3: '❸ ', 4: '❹ ',
\ 5: '❺ ', 6: '❻ ', 7: '❼ ', 8: '❽ ', 9: '❾ '}


nmap <Leader>1 <Plug>lightline#bufferline#go(1)
nmap <Leader>2 <Plug>lightline#bufferline#go(2)
nmap <Leader>3 <Plug>lightline#bufferline#go(3)
nmap <Leader>4 <Plug>lightline#bufferline#go(4)
nmap <Leader>5 <Plug>lightline#bufferline#go(5)
nmap <Leader>6 <Plug>lightline#bufferline#go(6)
nmap <Leader>7 <Plug>lightline#bufferline#go(7)
nmap <Leader>8 <Plug>lightline#bufferline#go(8)
nmap <Leader>9 <Plug>lightline#bufferline#go(9)
nmap <Leader>0 <Plug>lightline#bufferline#go(10)

```

**Comment by itchyny** [comment]
To get the number, use
```vim
function! s:get_buffer_number()
  let i = 0
  for nr in filter(range(1, bufnr('$')) 'bufexists(v:val) && buflisted(v:val)')
    let i += 1
    if nr == bufnr('')
      return i
    endif
  endfor
  return ''
endfunction
```

**Comment by taigacute** [comment]
> To get the number, use
> 
> ```viml
> function! s:get_buffer_number()
>   let i = 0
>   for nr in filter(range(1, bufnr('$')) 'bufexists(v:val) && buflisted(v:val)')
>     let i += 1
>     if nr == bufnr('')
>       return i
>     endif
>   endfor
>   return ''
> endfunction
> ```

this is bufferline function. How to put it in linglinemode i set this ，but its wrong
```
function! LightlineMode()
    let num = get_buffer_number()
    return num
endfunction
function! s:get_buffer_number() 
    let i = 0
    for nr in filter(range(1, bufnr('$')) 'bufexists(v:val) && buflisted(v:val)') 
        let i += 1
        if nr == bufnr('') 
            return i 
        endif 
    endfor 
    return '' 
endfunction

```

**Comment by itchyny** [comment]
Don't forget to prepend `s:` when you call the function.
```
function! LightlineMode()
  let num = s:get_buffer_number()
  return num
endfunction
```

**Comment by taigacute** [comment]
sorry  i got these 
```
Error detected while processing function LightlineMode[1]..<SNR>13_get_buffer_number:
line    2:
E15: Invalid expression: filter(range(1, bufnr('$')) 'bufexists(v:val) && buflisted(v:val)')
```

**Comment by taigacute** [comment]
> Ah, sorry, comma is missing; `filter(range(1, bufnr('$')), 'bufexists(v:val) && buflisted(v:val)')`.

thanks , i learn a lot. by the way . a feature.
Is it possible to have each component on the left have its own separator 。the same as right has own subseparator？

**Comment by taigacute** [comment]
i set this 
```
function! LightlineMode() 
    let nr = s:get_buffer_number() 
    let nmap = [ '➓ ',  '❶ ',  '❷ ',  '❸ ', '❹ ','❺ ',  '❻ ',  '❼ ',  '❽ ',  '❾ ']
    let num = nmap[nr]
    if nr == 0
        return ''
    endif
    return num 
endfunction
```
this is my linghtline now. thanks very much .
![line](https://user-images.githubusercontent.com/41671631/52277846-9dbdc580-2990-11e9-8009-f9e1a8f506f1.gif)

**Comment by taigacute** [comment]
How could setting coc error sign is red  coc warn sign is blue？
![23124](https://user-images.githubusercontent.com/41671631/52322275-6f34fe80-2a13-11e9-962b-41cefdcc376e.png)
like this
![1321](https://user-images.githubusercontent.com/41671631/52322294-91c71780-2a13-11e9-9c99-95028bedda6b.png)

**Comment by itchyny** [comment]
> Is it possible to have each component on the left have its own separator the same as right has own subseparator？

You can configure the subseparator with `g:lightline.subseparator` (please refer to `:h g:lightline.subseparator`). There's no difference in configuration between left and right.

> How could setting coc error sign is red coc warn sign is blue？

Sorry but this is impossible in lightline.vim. (Precisely speaking it's not impossible but difficult so I don't recommend. The api of lightline.vim is not designed to configure the color of specific character inside one component. See `:h lightline-problem-12` for further details.)

**Comment by taigacute** [comment]
> > 是否可以让左边的每个组件都有自己的分隔符，就像右边有自己的子分隔符一样？
> 
> 您可以配置子分隔符`g:lightline.subseparator`（请参阅`:h g:lightline.subseparator`）。左右之间的配置没有区别。
> 
> > 如何设置coc错误标志是红色coc警告标志是蓝色？
> 
> 抱歉，这在lightline.vim中是不可能的。（确切地说，这不是不可能，但很难，所以我不推荐.lightline.vim的api不是为了配置一个组件内特定字符的颜色而设计的。有关`:h lightline-problem-12`详细信息，请参阅。）

all right, thanks a lot. close

**Comment by taigacute** [comment]
@itchyny   how to config ale?
