### ISSUE TITLE
Unable to display special characters in patch font

### ISSUE THREAD

**Issue by paullemmens** [itchyny/lightline.vim#35]
Having downloaded and installed the patched inconsolata font for powerline and updated the lightline settings to use the special characters, I cannot get them to display in the statusline. The characters do display correctly in the separator settings, they do display correctly in Word and the Special Character app but just not in the status line. There they are display as inverted question marks (see image below). I am working on Win7 with gvim (portable; but that should be irrelevant I think).

My `.vimrc` section that covers lightline and color schemes:

```
let g:lightline = {
    \ 'colorscheme': 'solarized',
        \ 'active': {
        \   'left': [ [ 'mode', 'paste' ],
        \             [ 'readonly', 'filename', 'modified' ] ]
        \ },
    \ 'component': {
        \   'readonly': '%{&filetype=="help"?"":&readonly?"":""}',
        \   'modified': '%{&filetype=="help"?"":&modified?"+":&modifiable?"":"-"}'
    \ },
    \ 'component_visible_condition': {
        \   'readonly': '(&filetype!="help"&& &readonly)',
        \   'modified': '(&filetype!="help"&&(&modified||!&modifiable))'
        \ },
    \ 'separator': { 'left': '', 'right': '' },
    \ 'subseparator': { 'left': '', 'right': '' }
    \ }

set background=dark
"color ps_color
colorscheme solarized
let g:solarized_italic=0
let g:solarized_bold=0
```

Screenshot:

![image](https://f.cloud.github.com/assets/5063702/1120763/53e5cd78-1aae-11e3-855d-a4b43c2f14e3.png)

I would appreciate any help!

**Comment by her** [comment]
hey @itchyny 

I really love lightline so far thanks for all the hard work. your suggestions about ue0bx fixed my glyph issues 

I'm just wondering though: how did you know this would fix the glyph issue? is there a place where I can find these codes associated with these glyphs? 

thanks again :smile:

**Comment by itchyny** [comment]
Try `:h lightline-problem-9`.
