### ISSUE TITLE
Gruvbox term

### ISSUE THREAD

**Issue by soullivaneuh** [itchyny/lightline.vim#351]
What do you think about adding a [gruvbox](https://github.com/morhetz/gruvbox) term support?

**Comment by soullivaneuh** [comment]
Didn't see it's already supported by gruvbox itself: https://github.com/morhetz/gruvbox/tree/master/autoload/lightline/colorscheme

**Comment by Azza292** [comment]
@soullivaneuh, Thanks for posting the solution - What did you have to configure for this to work?

**Comment by oakszyjrnrdy** [comment]
@Azza292 If your have `colorscheme gruvbox` in your .vimrc (or init.vim), just add `let g:lightline = {'colorscheme': 'gruvbox'}`.

**Comment by Fakecrafter** [comment]
it doesnt work if you just have treesitter
and even if you install gruvbox you need to set gruvbox colorscheme to get lightline with gruvbox
i am really struggling with that
