### ISSUE TITLE
command mode on remapped key

### ISSUE THREAD

**Issue by Sparki2002** [itchyny/lightline.vim#357]
Hi,

i remapped the `:` key to `;`
```
nnoremap ; :
vnoremap ; :
```

How can I get the mode indicator working for `;`?
PS: On `:` it works just fine

**Comment by Sparki2002** [comment]
Maybe I should have mentioned that I'm using NeoVIM.
So the command does not work (nvim does not have an `--clean` argument)

**Comment by itchyny** [comment]
How about this `nvim -u NONE -N  -c 'set statusline=%{mode()} laststatus=2' -c 'nnoremap ; :'`.

**Comment by Sparki2002** [comment]
yeah, the mode indicator is not changing

**Comment by itchyny** [comment]
Then this is the current behavior of mode() and the mode indicator of lightline behaves as the same.
