### ISSUE TITLE
One colorscheme pattern different from the others

### ISSUE THREAD

**Issue by edgard** [itchyny/lightline.vim#359]
Seems the One colorscheme is using a double 'green' on the right site of the bar. From what I've seen on the others, it looks like it should be gray/green.

https://github.com/itchyny/lightline.vim/blob/78b1cc9e715f509a7e9f157e0d7a0e02b7e5125e/autoload/lightline/colorscheme/one.vim#L53

**Comment by itchyny** [comment]
Patches welcome.

**Comment by edgard** [comment]
Sorry, there you go. :) #360
