### ISSUE TITLE
vim-bufferline integration

### ISSUE THREAD

**Issue by timss** [itchyny/lightline.vim#36]
How would I go about integrating [vim-bufferline](https://github.com/bling/vim-bufferline) to my statusline, somewhat similar to what is done in [vim-airline](https://github.com/bling/vim-airline)? 

I found a part about [statusline integration](https://github.com/bling/vim-bufferline/blob/master/doc/bufferline.txt#L89), but not really sure how to do this for lightline so it updates when needed etc. 

It doesn't have to change the background if selected and all that jazz, but being able to change the frontground and/or background color of the chosen buffer would definitely be a bonus. 

I'd like to note that I like idea with lightline where usage of other plugins should be defined by the user instead letting the plugin do the "magic" or "hiding" it all in the plugin as is done in (vim-)powerline and airline. However adding things like the bufferline seems to be a bit tricky unless you're quite comfortable in vimscript.

**Comment by taohex** [comment]
https://github.com/taohex/lightline-buffer
You should use this.

**Comment by itchyny** [comment]
Ref: https://github.com/itchyny/lightline.vim/issues/155#issuecomment-196015726
