### ISSUE TITLE
:helptags probably necessary upon install

### ISSUE THREAD

**Issue by bitwombat** [itchyny/lightline.vim#362]
Amazing documentation for this plugin! Seriously, this should be the standard for any software docs. Thanks for that.

Small problem. I found it necessary to run:

```
:helptags ~/.vim/bundle/lightline.vim/doc/
```
Post-installation (git clone & Pathogen). Not sure if that should be automatic and one of my settings or plugins prevented it.

**Comment by itchyny** [comment]
So adding `:Helptags` (the command is defined in vim-pathogen) to the installation instruction in the document will solve the issue right?

**Comment by bitwombat** [comment]
I believe so. Other plugins mention it:
https://github.com/vim-airline/vim-airline#installation
https://github.com/chrisbra/csv.vim#using-a-plugin-manager
