### ISSUE TITLE
Mode indicator relies on delayed event... native is quicker

### ISSUE THREAD

**Issue by bitwombat** [itchyny/lightline.vim#363]
Vim's own --INSERT-- mode indicator instantly goes away on Esc, no matter the `ttimeout` and `ttimeoutlen` settings.

Lightline seems to rely on the Vim events (possibly InsertLeave?), which is delayed until `ttimeout` times out.

This means the user experience not as good as with the native mode indicator. Minor issue, of course.

The fix is to `set noesckeys` (make sure it's after your `set nocompatible`, if you set that). This has a side-effect of making arrow keys not work while in Insert mode (though they can be mapped to recreate the functionality).

With `esckeys` unset, lightline's mode indicator is instantaneous.

Is there an instantaneous way to detect when Insert mode has been left, like Vim's built-in indicator seems to do? Would this be desirable?

Note this isn't a duplicate of #192.

(I can't help but gush at HOW GOOD lightline is! Customizing is logical and organised. I've finally got the modeline I've always wanted!)

**Comment by itchyny** [comment]
Can you investigate the redrawing statusline lag without lightline plugin? Disable the lightline plugin and `set statusline=%{mode()}`. Basically lightline does the same things with `%{mode()}` so if it delays then it would be difficult to fix. Note that lightline does not rely on the InsertLeave event.

**Comment by bitwombat** [comment]
Yeah, mode() has the same delay...

**Comment by itchyny** [comment]
This is not a bug of lightline. Please report to vim dev if the delay without lightline is a bug.
