### ISSUE TITLE
How to change the color of tabsel in insert mode

### ISSUE THREAD

**Issue by taigacute** [itchyny/lightline.vim#366]
hi  i want to change the tabsel color when i in insertmod. i try to write function by `mode()` and use autocmd to call it  but failed.

**Comment by itchyny** [comment]
The plugin does not provide a neat way to do this, sorry. Ignoring the separators, `LightlineLeft_tabline_tabsel` is the matching highlight group.

**Comment by taigacute** [comment]
ok   i got it
