### ISSUE TITLE
How to show current function in right side of tabline

### ISSUE THREAD

**Issue by ppnman** [itchyny/lightline.vim#367]
Hello everyone, I want to show current function in right side of tabline.
I have tried this, but it does not work, can anyone help me?
```
let g:lightline = {
      \ 'tabline': {
      \   'right': [['CurrentFunction']]
      \ },
      \ 'component_function': {
      \   'CurrentFunction': 'CocCurrentFunction'
      \ },
      \ 'component_type': {'buffers': 'tabsel'},
      \ 'separator':      {'left': "\ue0b0", 'right': "\ue0b2"},
      \ 'subseparator':   {'left': "\ue0b1", 'right': "\ue0b3"}
      \ }

function! CocCurrentFunction()
    return get(b:, 'coc_current_function', '')
endfunction

```

**Comment by itchyny** [comment]
Can you confirm `echo b:coc_current_function` prints the current function name you want?

**Comment by itchyny** [comment]
Can you confirm `:echo b:coc_current_function` prints the current function name you want?

**Comment by ppnman** [comment]
yes，but the variable will be refreshed automatically by coc.nvim.
If CocCurrentFunction returns a const string, such as "Hello lightline", then the configuration works well.
But when CocCurrentfunction returns an variable    like this situation, it does not work!

**Comment by ppnman** [comment]
> Can you confirm `:echo b:coc_current_function` prints the current function name you want?

It seems the right side of tabline can only show a constant string. I have accepted the fact.

Can we define the font color? I notice the font color of all colorscheme displayed in README is black.

**Comment by itchyny** [comment]
Sorry what do you mean by font color? Foreground color?

**Comment by ppnman** [comment]
I take back what I said. I have knew how to set font color.
Is it true that the right side of tabline can only show constant string?

**Comment by itchyny** [comment]
I don't check the behavior of coc plugin, but for me it changes the contents when I `let b:coc_current_function = "foo"` . I'm afraid you install very old version of lightline...

**Comment by ppnman** [comment]
> Hello everyone, I want to show current function in right side of tabline.
> I have tried this, but it does not work, can anyone help me?
> 
> ```
> let g:lightline = {
>       \ 'tabline': {
>       \   'right': [['CurrentFunction']]
>       \ },
>       \ 'component_function': {
>       \   'CurrentFunction': 'CocCurrentFunction'
>       \ },
>       \ 'component_type': {'buffers': 'tabsel'},
>       \ 'separator':      {'left': "\ue0b0", 'right': "\ue0b2"},
>       \ 'subseparator':   {'left': "\ue0b1", 'right': "\ue0b3"}
>       \ }
> 
> function! CocCurrentFunction()
>     return get(b:, 'coc_current_function', '')
> endfunction
> ```

@itchyny  Thanks for your response. I just find the configuration is right all along.
But there is a problem, the tabline seems not to update automatically even through I  call lightline#update().
The only method I have found is entering into insert mode and come out.
Is there a function to update tabline?

**Comment by itchyny** [comment]
lightline specifies tabline by `%!lightline#tabline()` and Vim recalculates the value automatically; on cursor moves, mode changes, window switching.  But there are some cases the editor skips updating tabline. You can use `set tabline=%!lightline#tabline()` to force recalculation of tabline. `lightline#update` updates only statusline and is not related to tabline but, I noticed that it sounds weird that `lightline#update` does not update tabline.

**Comment by ppnman** [comment]
It really works that `set tabline=%!lightline#tabline()`.
Well, It really sounds weird that `lightline#update` does not update tabline.
