### ISSUE TITLE
Disable a component if it shows nothing

### ISSUE THREAD

**Issue by ppnman** [itchyny/lightline.vim#368]
My lightline is like this.
![image](https://user-images.githubusercontent.com/39628662/60385854-a8eccb80-9ac0-11e9-9e1a-00b3b48e5932.png)
But sometimes, the second component on the left whose duty is to show git message does not have any message. Like this.
![image](https://user-images.githubusercontent.com/39628662/60385873-0a149f00-9ac1-11e9-8360-b86c292797ae.png)
In this situation, can we disable the component?
In brief, I want to show a component **ONLY IF** it can show something.

**Comment by itchyny** [comment]
This is an expected behavior in lightline, component group never collapse. It is a trade off of performance (creating O(n^2) number of highlight comes with costs). If you still want to hide it, set empty string to the separators. Thanks.

**Comment by ppnman** [comment]
Thanks very much!
