### ISSUE TITLE
Strange gap on the right side 

### ISSUE THREAD

**Issue by ppnman** [itchyny/lightline.vim#369]
When I enter vim, there is a strange gap on the right side.
![image](https://user-images.githubusercontent.com/39628662/60392841-5225d700-9b3e-11e9-9579-f2d7019ab464.png)
But afterI enter into insert mode and come back, the gap is gone!
![image](https://user-images.githubusercontent.com/39628662/60392850-708bd280-9b3e-11e9-8f75-a54d57e0a450.png)
Can anyone help me on this? I will be very grateful!

**Comment by itchyny** [comment]
Would you paste your lightline config or link to your vimrc?

**Comment by ppnman** [comment]
This is the link to my configuration of lightline.vim.
https://github.com/ppnman/dotfiles/blob/master/vim/config/plugins/lightline.vim
Could you help me to find why the gap exists.
Thank you very much.

**Comment by itchyny** [comment]
That's a weird observation because there's no relation between lightline and startify (I believe). Can you test with no multi-byte characters (especially emoji) in lightline config? I think there's less possibility that this is a bug of lightline, but in the editor.

**Comment by ppnman** [comment]
@itchyny 
Wow, it really is caused by the emoji character. The gap has gone after I change to another character.
Thank you very much, Have a nice day!

**Comment by ppnman** [comment]
@itchyny 
Can I ask the last question?
1. What is subseparator ? It seems we need only separator, because all setting about subseparator does not influence lightline.
2. How can I achieve this statusline?
![image](https://user-images.githubusercontent.com/39628662/60592553-74845280-9dd3-11e9-9a78-11a03e53f205.png)
It seems that separator consists of both arc and flame. I don't know how to do it.
https://github.com/ryanoasis/powerline-extra-symbols/issues

**Comment by itchyny** [comment]
When you configure as 
```vim
let g:lightline = {
      \ 'active': {
      \   'left':  [['HomeMode'],['GitInfo','Filename']],
      \ },
      \ }
```
you will see the subseparator between GitInfo and Filename (when both have some information).

I can't see what you mean by _arc_ but maybe the following config will achieve the separators in that screenshot (with the font with extra symbols installed).
```vim
let g:lightline = {
      \ 'separator': { 'left': "\ue0c0", 'right': "\ue0c2" },
      \ 'subseparator': { 'left': "\ue0c1", 'right': "\ue0c3" },
      \ }
```

**Comment by ppnman** [comment]
> When you configure as
> 
> ```viml
> let g:lightline = {
>       \ 'active': {
>       \   'left':  [['HomeMode'],['GitInfo','Filename']],
>       \ },
>       \ }
> ```
> 
> you will see the subseparator between GitInfo and Filename (when both have some information).
> 
> I can't see what you mean by _arc_ but maybe the following config will achieve the separators in that screenshot (with the font with extra symbols installed).
> 
> ```viml
> let g:lightline = {
>       \ 'separator': { 'left': "\ue0c0", 'right': "\ue0c2" },
>       \ 'subseparator': { 'left': "\ue0c1", 'right': "\ue0c3" },
>       \ }
> ```

Thanks for your patience. It does work.
