### ISSUE TITLE
Fit into window size

### ISSUE THREAD

**Issue by LongChampion** [itchyny/lightline.vim#370]
Hello @itchyny ,
I am very enjoy to use `lightline`: it is light, simple, and easy to config. But i have a small disapointed about your plugin: it can't "shrink" itself to fix with the window size (like vim-airline). In particular, when the size of window become small enough, `lightline' show incorrect infomation:
![image](https://user-images.githubusercontent.com/47727306/60986094-ee36b600-a368-11e9-9bde-fa2fca85a731.png)

Loot at the screenshot above, `lightline' show "<AL", which is apart of "NORMAL" (character '<' belong to NERDTree). This is too ugly for me :)
Can you improve this feature in the next release? I think you should shrink it or make it disappear when the window size become too small.
Looking forward your answer. Regard.

**Comment by itchyny** [comment]
Automatic shrinking is too complex feature to implement by default. Instead, if you configure by component functions, you can check the window width. Please refer to https://github.com/itchyny/lightline.vim#can-i-trim-the-file-format-and-encoding-information-on-narrow-windows.
