### ISSUE TITLE
Trim "character under the cursor" on narrow windows?

### ISSUE THREAD

**Issue by sooqua** [itchyny/lightline.vim#377]
I was following [this example](https://github.com/itchyny/lightline.vim#can-i-trim-the-file-format-and-encoding-information-on-narrow-windows) after adding "value of character under the cursor in hexadecimal" and was wondering if I can hide it on narrow windows. I tried creating a function
```
function! CharValueHex()
  return winwidth(0) > 70 ? '0x%B' : ''
endfunction
```
But it's just displaying "0x%B". I tried escaping the `%` with backslash but that didn't work. Is there a way to use `'statusline'` syntax in `component_function` or I must re-write the function to display the character under the cursor? If it's the latter, how can I do so? I'm very new to vimscript.
Thanks.

**Comment by itchyny** [comment]
There's no way to use `'statusline'` syntax in `component_function`. Try
```vim
function! CharValueHex()
  return winwidth(0) > 70 ? printf('%02x', char2nr(getline('.')[col('.')-1])) : ''
endfunction
```

**Comment by sooqua** [comment]
That worked. Thanks!
