### ISSUE TITLE
Separators showing even when component ignored

### ISSUE THREAD

**Issue by sethen** [itchyny/lightline.vim#379]
It seems that even when I am returning an empty string in `component_function` and set the `separators` like so:

```
\ 'separator': { 'left': '▒░', 'right': '░▒' },
```
I still get separators on the left for things I've ignored:

![Screenshot from 2019-08-12 18-28-24](https://user-images.githubusercontent.com/1493530/62903038-7674f600-bd2f-11e9-81d9-cd518d8111c4.png)

This is from the `mode`, but I don't show the `mode` in things like startify yet the separators are still there.  Is there anyway to fix this??

**Comment by itchyny** [comment]
This is an expected behavior of lightline; the separators never collapse (while the subseparators are hided). There's no plan to change this behavior.

**Comment by sethen** [comment]
> This is an expected behavior of lightline; the separators never collapse (while the subseparators are hided). There's no plan to change this behavior.

Bummer.
