### ISSUE TITLE
[feature request] tabline color, <C-w> prompt, <Leader> prompt

### ISSUE THREAD

**Issue by z-huabao** [itchyny/lightline.vim#382]
Love this plugin, thank for your work!

I use vim tab instend of tmux recently, the origin tabline looks terrible, your plugin tabline better but seem not colorful enough in addition to `one, PaperColor` colorschemes.

Secend, `<C-w>` often be used for navigating windows, can you make a colorful prompt of this key on tabline? or statueline, like a new mode? 
(ps. I map `<Esc>` as `<C-w>`, so sometime I will confuse whether in normal mode or 'C-w' mode)

Third, `<Leader>` often be used too, can you prompt for it?

**Comment by itchyny** [comment]
1. If you don't like the default colors, you can overwrite the colors of tabline.

```vim
autocmd VimEnter * call SetupLightlineColors()
function SetupLightlineColors() abort
  let l:pallete = lightline#palette()
  let l:pallete.tabline.left = l:pallete.normal.left[1:] " or what ever
  call lightline#colorscheme()
endfunction
```

2, 3. We can't detect `<C-w>` or `<Leader>` and this is not a mode. I can't implement this technically. Instead, `:set showcmd` will prompt the key code under the statusline.

**Comment by z-huabao** [comment]
ok, thanks a lot ! I will try it.
