### ISSUE TITLE
Wrong background detection when using `16color` theme with the `Noctu` theme

### ISSUE THREAD

**Issue by nunocastromartins** [itchyny/lightline.vim#385]
Theme in question: https://github.com/noahfrederick/vim-noctu (works similarly to `16color`, by using the terminal's 16 colours).

Although I'm using the dark version of the theme, Lightline's `16color` is displaying its light version.

Going through the source, this is the line at fault: https://github.com/itchyny/lightline.vim/blob/master/autoload/lightline/colorscheme.vim#L246 together with, I believe, this setting: https://github.com/noahfrederick/vim-noctu/blob/master/colors/noctu.vim#L19.

Any way to override Lightline's background to the dark version?

Thank you!

**Comment by itchyny** [comment]
What's the value of `&background`?

**Comment by nunocastromartins** [comment]
Not sure if this is what you're asking, but I have `set background=dark` in my init script.

I'm not very well versed in Vim and don't have access to my computer right now, but hope that's what you're asking.

**Comment by itchyny** [comment]
`:echo &background` prints `dark`, right?

**Comment by nunocastromartins** [comment]
I apologise, I opened this issue **just** before my holiday. I don't have access to my computer to confirm but I believe that yes, it will echo `dark`.

I believe that if you simply install the mentioned theme (Noctu) and activate the 16color Lightline theme with `background` set to `dark` you will right away notice the issue: Lightline's 16color theme will display its light variant.

**Comment by itchyny** [comment]
This should be fixed for now.
