### ISSUE TITLE
View full file path all time instead of 1<C-g>

### ISSUE THREAD

**Issue by chinmaychhajed** [itchyny/lightline.vim#386]
Hi,
Is there any way I can view my full file path (from my home, '`~`' directory) and not relative path all the time at bottom of screen, maybe in place where default `----INSERT----` is present. It is very tedious to press 1<C-g> every time to see full path. 

I found that using `set statusline+=%F` shows full path but then it hides vim's mode (normal, insert, etc.) setup by this plugin.

Please help. Thanks for support.

**Comment by itchyny** [comment]
Configure as follows.
```vim
let g:lightline = {
      \ 'component': {
      \   'filename': '%F',
      \ }
      \ }
```

**Comment by chinmaychhajed** [comment]
Thanks, this helped!
