### ISSUE TITLE
Bad contrast for light background using the colorscheme 'one'

### ISSUE THREAD

**Issue by acatton** [itchyny/lightline.vim#388]
Hi there,

I open an issue instead of a pull request because I'm not sure what is the correct solution here...

Let me start by giving you a screenshot of what it looks like to me:

![Screenshot](https://user-images.githubusercontent.com/3966553/64490557-654fd400-d25e-11e9-9446-f93980618d63.png)

As you can see the inactive tabs have a very bad contrast. Also the position in the file (`100%` at the bottom right) has the same colors as the inactive tabs.

I'm using gnome-terminal 3.30 with the palette "Tango", here's my lightline configuration (my vim colorscheme is `default`):

    " Lightline
    let g:lightline = {
    \   'colorscheme': 'one',
    \   'active': {
    \       'left': [ [ 'mode', 'paste' ], [ 'charvaluehex', 'readonly', 'modified', 'filename' ] ],
    \       'right': [ [ 'lineinfo' ], [ 'percent' ], [ 'fileformat', 'fileencoding', 'filetype' ] ],
    \   },
    \   'component': {
    \       'charvaluehex': '0x%04B',
    \   },
    \   'component_function': {
    \       'filename': 'LightlineFullFilename',
    \   }
    \}

Looking at `autoload/lightline/colorscheme/one.vim` it looks like `s:gray2` is too light to put on `s:gray3` (for `s:p.tabline.middle`). I'm not sure how to change that since it would also impact dark colorschemes.

**Comment by itchyny** [comment]
I fixed this, please confirm.

**Comment by acatton** [comment]
@itchyny, it is fixed :) . Thank you very much, that's awesome.
