### ISSUE TITLE
Delay when switching to normal mode

### ISSUE THREAD

**Issue by linus345** [itchyny/lightline.vim#389]
## Description
When I switch **from** normal mode to other modes(insert, visual etc.) the label and color in the _mode component_ switches instantly but when I switch **back to** normal mode there's about a 500ms delay before the label and color changes in the _mode component_. Is this a bug or is it intentional?

**Comment by itchyny** [comment]
Try `set ttimeout ttimeoutlen=50` if it improves.

**Comment by mckellyln** [comment]
Yea, probably a delay after an <Esc>, waiting to see if there any any more keystrokes arriving ?
As @itchyny said above you can adjust that some in vim.

**Comment by linus345** [comment]
yes that improved it, thank you.
