### ISSUE TITLE
lightline status bar goes away after write or after some time

### ISSUE THREAD

**Issue by amit-raut** [itchyny/lightline.vim#391]
Hi there,

I hope you're doing well. Thank you building this amazing vim plugin. When I tried to use it in my linux system (xubuntu 19.04) it gave me trouble using it.

The status bar appears when I open a document but it goes away after writing of file/ after some time (around 20 seconds). Now if I split `:vsp` then it reappears for both new and already open file.

Status bar after opening file 
```
 NORMAL  test             unix | utf-8 | no ft    3%    1:1  
```

status bar changes to following after file write `:w<CR>`
```
(1) test [none] [unix/en_US.UTF-8]  2019-09-20 15:13:04     0x2D   1/32:1       (3%)
```
I tried adding `set laststatus=2` to `.vimrc` as mentioned in readme but it didn't fix this issue :(

I tried to figure out what is causing this behavior by disabling other configs from `.vimrc` but still the issue persists. Not sure what is causing it so I created this issue. Please let me know if you need more info

Thank you,
Amit

**Comment by itchyny** [comment]
Please paste the entire .vimrc or link to your .vimrc so that I can see the whole config, thanks.
