### ISSUE TITLE
Solarize broken

### ISSUE THREAD

**Issue by eNlinxed** [itchyny/lightline.vim#396]
Had to update system so and it seems the solarize theme got broken : 

Here is an example 

local box : 

https://imgur.com/6ehPZLE

remote box :  

https://imgur.com/Q9qU1T7

**Comment by itchyny** [comment]
Please make sure `:echo &background` prints `dark`. Also, I'd appreciate if you can use `git bisect` onto the lightline.vim repository.

**Comment by eNlinxed** [comment]
specifically setting the background to light on my local machine fixed the issue. Could you explain why ? From what I could see while I experimented with color schemes the plugin was not affected.

**Comment by itchyny** [comment]
There're two variants for solarized theme, dark and light. The background is automatically detected by the value of `&background`. So if you change the value, the solarized theme changes its appearance.
