### ISSUE TITLE
The embeded darcula colorscheme is just wrong

### ISSUE THREAD

**Issue by doums** [itchyny/lightline.vim#397]
Hi,

I'm the author of a vim color scheme project, that is a faithful reproduction of the original JetBrains IDE's theme -> [darcula](https://github.com/doums/darcula)
My goal is to reproduce as accurately as possible the color scheme and apply it to vim.
Also I created a lightline color scheme that I find much more faithful to the original JetBrains UI (I picked the same colors) that the one already present in your color scheme list. It is bundled with my color scheme plugin and can be used through the lightline configuration ie.
 ```
let g:lightline = {
      \ 'colorscheme': 'darcula'
      \ }
```
The problem is that the name of my color scheme and the one already present ie. "darcula" conflict each other.
Can you please change the name of the existing one ?

**Comment by itchyny** [comment]
Name conflict always give us headache. There are some users of the darcula theme in lightline repository so renaming would cause loading error so I can't easily do that. I would like to respect the author of the theme who give me the pull request at #216 where he says `It is also compliant with vim's blueshirts/darcula theme.`. It seems that there's already a Vim colorscheme https://github.com/blueshirts/darcula, the lightline theme is based on it and it is you created the name conflict so it's not reasonable for me to change the name of the theme.

**Comment by doums** [comment]
Hi,

So I guess it is useless to propose a PR to replace the existing theme by the one I created (as you want to preserve the work of the author of the existing one)?
If yes, too bad.. I'll rename my color scheme.

**Comment by itchyny** [comment]
Yes, I would like to maintain the appearance as possible. I'd like to accept a patch to tweak a few colors to match the original colorscheme but drastic change is difficult.

**Comment by metalelf0** [comment]
@doums, how about renaming your colorscheme to `darcula2`, `trueDarcula`, `darculaOriginal` or anything like that? Or maybe, you can contact the author of the other colorscheme and collaborate with him/her to create a better one.
