### ISSUE TITLE
Failed to set locale category

### ISSUE THREAD

**Issue by urw7rseeh8fr** [itchyny/lightline.vim#401]
macOS Catalina 10.15.1 on MacBook Pro

After installing lightline with vim-plug, I get this warning:

> Warning: Failed to set locale category LC_NUMERIC to en_KR.
Warning: Failed to set locale category LC_TIME to en_KR.
Warning: Failed to set locale category LC_COLLATE to en_KR.
Warning: Failed to set locale category LC_MONETARY to en_KR.
Warning: Failed to set locale category LC_MESSAGES to en_KR.

After adding export LC_ALL=en_KR.UTF-8 to .zshrc, I get the same warning twice. If I remove that line from .zshrc, I get one from lightline.

**Comment by itchyny** [comment]
Adding `export LC_ALL=en_US.UTF-8` to .zshrc fixes the issue (see [this](https://discourse.brew.sh/t/failed-to-set-locale-category-lc-numeric-to-en-ru/5092/2))? I believe the warning has nothing to do with this plugin. Please write the precise steps to reproduce the warnings. When you get the messages from what command? While starting Vim or Neovim?

**Comment by urw7rseeh8fr** [comment]
Sorry I checked again and it was a different plugin.
