### ISSUE TITLE
status line truncation when splits narrow width

### ISSUE THREAD

**Issue by mckellyln** [itchyny/lightline.vim#402]
Hi, thank you for awesome lightline!
NOTE: this is really a question and not an issue.
When I split windows vertically obviously the width is redcued by half.
Sometimes there is not enough space for all statusline parts and it seems the left-side mode gets truncated before other right-side parts.
Is there a way to have the truncation be from the right ?
I am reading this now:
```
https://github.com/itchyny/lightline.vim#can-i-trim-the-file-format-and-encoding-information-on-narrow-windows
```
Do I need to adjust the width of each part manually to try and make it fit better ?
thx,
-m

**Comment by mckellyln** [comment]
Can I make NORMAL -> N, INSERT -> I, REPLACE -> R, VISUAL -> V, etc. to make more room ?

**Comment by mckellyln** [comment]
This does help:
```
function! MyLightlineFilename()
    ....
    if winwidth(0) < 90
      return filename[-16:]
    else
      return filename
    endif
```
But am still curious about using a shorter mode word always.

**Comment by itchyny** [comment]
To truncate from right hand side, include `%<` in some of the component on the right (a little bit hacky but it works).

```vim
let g:lightline = {
      \ 'component': {
      \   'lineinfo': '%3l:%-2v%<',
      \ },
      \ }
```

To use shorter mode names, specify the `mode_map` (see `:h g:lightline.mode_map`).

```vim

let g:lightline = {
      \ 'mode_map': {
        \ 'n' : 'N',
        \ 'i' : 'I',
        \ 'R' : 'R',
        \ 'v' : 'V',
        \ 'V' : 'VL',
        \ "\<C-v>": 'VB',
        \ 'c' : 'C',
        \ 's' : 'S',
        \ 'S' : 'SL',
        \ "\<C-s>": 'SB',
        \ 't': 'T',
        \ },
      \ }
```

**Comment by mckellyln** [comment]
@itchyny thanks always so much for your help and work.

**Comment by mckellyln** [comment]
@itchyny one more ques - if I have a split then the mode seems to not be displayed for the window that is not the current window.  Is there a way to have the mode still be there ?  I just want to keep the statusline spacing and display unchanged except for its brightness when switching windows.
thx again as always for awesome lightline. -m

**Comment by mckellyln** [comment]
I figured it out.  I had to make inactive the same as active:
```
    \ 'active': {
    \   'left': [ [ 'mymode', 'paste' ], 
    \             [ 'gitbranch', 'myfilename', 'mymodified', 'mycolonkeyword' ] ]
    \ },
    \ 'inactive': {
    \   'left': [ [ 'mymode', 'paste' ], 
    \             [ 'gitbranch', 'myfilename', 'mymodified', 'mycolonkeyword' ] ]
    \ },
```
thx again.
