### ISSUE TITLE
lightline.vim: Could not load colorscheme

### ISSUE THREAD

**Issue by Maselko** [itchyny/lightline.vim#407]
I have added the colorscheme file in the wrong place and since that it stopped recognising all colorschemes. I have tried to reinstall the plugin but unfortunately it did not work. I have noticed the colorscheme manual too late, sorry. Any ideas how to fix? 
I am using Plugged for plugin manager.
And my plugin file looks like below.
<img width="643" alt="Zrzut ekranu 2020-01-3 o 12 17 36" src="https://user-images.githubusercontent.com/47721906/71720709-e725c780-2e22-11ea-807e-0b7e5473076f.png">

Thank you

**Comment by itchyny** [comment]
I cannot understand what you mean, please describe

- can you see the default colorsheme of lightline?
- can you change the lightline colorsheme to another preset (ex. wombat)?
- where exactly do you put your colorsheme file and how do you load it with vim-plug?
