### ISSUE TITLE
ligtline disabled when do :LspHover,   after popup windows

### ISSUE THREAD

**Issue by leoatchina** [itchyny/lightline.vim#409]
Vim version: vim with `popup` windows(not neovim)
OS : Windows , linux , macOS .   The screenshots is done in gvim8.2 on windows.

I use [vim-lsp](https://github.com/prabirshrestha/vim-lsp) for vim-completion, and when I do `LspHover` to get the information of a function, 
the popup windows appeard,   and lightline disabled
One more thing,  the complete_engine is [asyncomplete.vim](https://github.com/prabirshrestha/asyncomplete.vim) or [ncm2](https://github.com/ncm2/ncm2)

![图片](https://user-images.githubusercontent.com/4470821/72675215-eeec9980-3abb-11ea-836a-0218fb2e119a.png)

I reload  my `.vimrc` without quiting vim ,  lightline came back, and then do `LspHover` for  manytimes, lightline keeped normal
![图片](https://user-images.githubusercontent.com/4470821/72675245-38d57f80-3abc-11ea-82a7-403047437858.png)

If I use `neovim` or vim without `popup`, this issue not happen

Maybe it is related with this line
https://github.com/itchyny/lightline.vim/blob/8b3aa1632c08784928458b2b85faf5c89feefccf/autoload/lightline.vim#L14

**Comment by itchyny** [comment]
I use vim-lsp and popup but can't reproduce the issue. Please write the precise steps and your vimrc.

**Comment by leoatchina** [comment]
OK,  I will try to get a mimic vimrc to reproduce the issue

**Comment by leoatchina** [comment]
Hm, I have set a smaller .vimrc from my main hug config , and found lightline not disabled when LspHover.
So, the cause is with some lines in my config , I will try to find it out.

![图片](https://user-images.githubusercontent.com/4470821/72692966-c8853780-3b69-11ea-82aa-e75c545e6f55.png)

**Comment by leoatchina** [comment]
This  is not caused by any settings of lightline,  since I have masked almost all internal settings of lightline, only keep  let g:lightline = {}

**Comment by itchyny** [comment]
Can you give me the output of `:au WinEnter` and `:au BufWinEnter`?

**Comment by leoatchina** [comment]
The screenshot , it is hard to copy in Gvim
![图片](https://user-images.githubusercontent.com/4470821/72694848-64ff0800-3b71-11ea-98bc-a0cb88b7ec08.png)

**Comment by itchyny** [comment]
While lightline is disabled, try `:verbose set stl` to check which script sets the value.

**Comment by leoatchina** [comment]
line 65 of lightline.vim ?
![图片](https://user-images.githubusercontent.com/4470821/72695088-4fd6a900-3b72-11ea-96ce-cf00dcf6e239.png)

**Comment by itchyny** [comment]
The problem is you (or some plugin you are using) call `lightline#disable` or `lightline#toggle` somewhere.

**Comment by itchyny** [comment]
Hmm, https://github.com/prabirshrestha/vim-lsp/pull/395/files#diff-d00b51414572c34757f8c53315949ee6R133 is cause? Can you confirm that deleting these lines (maybe in `~/.gvim/plug/vim-lsp/autoload/lsp/ui/vim/output.vim`) solves the issue?

**Comment by leoatchina** [comment]
Oh,  in my config , it is cause by` Plug 'gorodinskiy/vim-coloresque'`
I have done `half plugins mask`, and finnaly found it !

**Comment by itchyny** [comment]
I sent a p/r to vim-lsp to stop toggling lightline (https://github.com/prabirshrestha/vim-lsp/pull/677). Maybe vim-coloresque throws some exceptions on setting the filetype (at https://github.com/prabirshrestha/vim-lsp/blob/fef60795ecef2b83cff89770fdf41d56acd0c72e/autoload/lsp/ui/vim/output.vim#L159) and the function aborts so `lightline#enable` is not called. Stop toggling lightline should fix this (but there might be some bugs in vim-coloresuque as well).
