### ISSUE TITLE
Missing statusline after changing buffer

### ISSUE THREAD

**Issue by riser88** [itchyny/lightline.vim#410]
Hello,

I was searching doc and tickets, but I was not able to find answer.
For some reason lightline is not visible when I switch buffer even with:
> set	laststatus=2

I'm observing this when I'm editing more than one file with vim (no tabs, no split windows).
How can I fix it ?

**Comment by itchyny** [comment]
Please describe the precise steps and your complete vimrc to reproduce the issue.

**Comment by riser88** [comment]
My vimrc file:
[vimrc.txt](https://github.com/itchyny/lightline.vim/files/4088043/vimrc.txt)

1. Launch vim with two files
> /depot/Vim/vim8.1.527/bin/vim common.aim xorg.conf
![statusline_after_opening](https://user-images.githubusercontent.com/12039554/72760072-f903ba80-3bd7-11ea-904d-c35527652c66.PNG)

2. Switching to buffer 2
> :b 2
![statusline_after_buffer_change](https://user-images.githubusercontent.com/12039554/72760108-10db3e80-3bd8-11ea-9a6e-fbfb01566320.PNG)

3. Switching to buffer 1
> :b 1
![statusline_after_second_buffer_change](https://user-images.githubusercontent.com/12039554/72760136-23ee0e80-3bd8-11ea-8f80-ac5212a2d773.PNG)

As you can see after loading buffer 2 lightline is not visible and It's back when I change back to buffer  1.

**Comment by itchyny** [comment]
Please remove the `autocmd BufEnter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree())` line. This is a broken syntax configuration.

**Comment by riser88** [comment]
After removing mentioned line it's working fine.
Thanks a lot !
