### ISSUE TITLE
tab colors based on vim mode?

### ISSUE THREAD

**Issue by joe23rep** [itchyny/lightline.vim#412]
is it possible to have the tabline color changed based upon the vim mode i am in?

so that when im in insert mode for example not only the bottom bar changes its background color but also the tabline?

i tried the following:
`let s:p.tabline.insert.left = [ [ '#7cffb7', '#292c33' ], [ '#d6f4fd', '#3e4452' ], [ '#7cffb7', '#292c33' ] ]`

but this gives me an error

**Comment by itchyny** [comment]
This is impossible in lightline.

**Comment by joe23rep** [comment]
ok. thank you for your fast answer
