### ISSUE TITLE
Fresh lightline install doesn't work as expected

### ISSUE THREAD

**Issue by cpkio** [itchyny/lightline.vim#413]
Today (23.01.2020) made a `git clone` to `\vim\pack\user\start`. Added `let g:lightline = { 'colorscheme': 'gruvbox' }` to `.vimrc`. Vim run in terminal, get an error.

```
Error detected while processing function lightline#update[5]..lightline#colorscheme[18]..lightline#highlight:
line   18:
E254: Cannot allocate color guibg=
Error detected while processing function lightline#update:
line    5:
E171: Missing :endif
Press ENTER or type command to continue
```

In gvim starts just fine.

**Comment by itchyny** [comment]
What's the Vim version?

**Comment by itchyny** [comment]
Note that there's no colorscheme `gruvbox` in lightline's preset. Please change to one of [colorscheme.md](https://github.com/itchyny/lightline.vim/blob/master/colorscheme.md).

**Comment by cpkio** [comment]
Vim version is 8.2 latest:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 21 2020 23:03:36)
MS-Windows 64-bit console version
Included patches: 1-140
```
It turns out gruvbox lightline theme, taken from [here](https://github.com/rafi/awesome-vim-colorschemes/tree/master/autoload/lightline/colorscheme), has some bugs which prevent from using it now.

Would love to see automatic loading of lightline color schemes with same name as the main one, this would simplify different color vim setups a lot.
