### ISSUE TITLE
filetype not working correctly

### ISSUE THREAD

**Issue by joe23rep** [itchyny/lightline.vim#416]
i have a filename function which ads a matching nerd font icon for the file and an icon for letting me know if there are unchanged changes. 

it works great. this is the function:

`
function! FileNameWithIcon() abort
  let filename_with_icon = expand('%:t') !=# '' ? expand('%:t') : '[No Name]'
  let modified = &modified ? '   ' : ''
return winwidth(0) >  70  ?  WebDevIconsGetFileTypeSymbol() . ' ' .  modified . expand('%:t') : ' '
       endfunction
`

i wanted to use the same for filetype (add an icon and one for letting me know if ive unsaved changes. 

looking threw `h:g:lightlinecomponent` i saw that ive to use `'%{&ft!=#""?&ft:"no ft"}'` instead of `'%:t'`

so my new function is:
`
function! FileTypeWithIcon() abort
  let filetype_with_icon = expand('%{&ft!=#""?&ft:"no ft"}') !=# '' ? expand('%{&ft!=#""?&ft:"no ft"}') : '[No Name]'
  let modified = &modified ? '   ' : ''
return winwidth(0) >  70  ?  WebDevIconsGetFileTypeSymbol() . ' ' .  modified . expand('%{&ft!=#""?&ft:"no ft"}') : ' '
       endfunction
`
to get the function running i use the following:
`let g:lightline.component = {
        \ 'vim_logo': "\ue7c5 ",
        \ 'unix_logo': "  ",
        \ 'filename_with_parent': '%t',
        \ 'buffer': 'buffers %n',
        \ 'gitbranch': 'fugitive#head',
        \ 'filename_with_icon': '%{FileNameWithIcon()}',
        \'filetype': '%{FileTypeWithIcon()}',
        \}
`
but this doesnt show me the filetype with icons but also the file name. 
do u know whats the error here? why does `('%{&ft!=#""?&ft:"no ft"}')` not show the filetype but the filename?

when i comment the function out the standart filetype option shows the filetype correctly

**Comment by itchyny** [comment]
The `expand()` function does not accept an arguments like `%{...}`. This brace syntax is for `'statusline'`. You can get the filetype with just `&ft` (this is an abbreviation of `&filetype`).

```vim
function! FileTypeWithIcon() abort
  let filetype_with_icon = &filetype !=# '' ? &filetype : 'no ft'
  let modified = &modified ? '  ' : ''
  return winwidth(0) > 70 ? WebDevIconsGetFileTypeSymbol() . ' ' . modified . &filetype : ' '
endfunction
```

For more reference, please look into `:h expand()`.

**Comment by joe23rep** [comment]
ahh ok. thanks. got it working
