### ISSUE TITLE
vim-fugitive has changed APIs

### ISSUE THREAD

**Issue by minusf** [itchyny/lightline.vim#417]
i noticed that my branch wasn't shown all the time.  seems like fugitive has started using `FugitiveHead`.  i know lightline is not tightly integrated with it, however the documentation needs to be updated i think.

thanks for the great plugin!

**Comment by itchyny** [comment]
I believe `fugitive#head` is still available (https://github.com/tpope/vim-fugitive/blob/268a9c1b8f80480b105c60ff52e7a752ef22d385/autoload/fugitive.vim#L6120). Is there a plan to deprecate this function?

**Comment by minusf** [comment]
while it is mentioned in the docs, the instructions are to use the new one, at least as i read it.

https://github.com/tpope/vim-fugitive/blob/master/doc/fugitive.txt#L625

**Comment by minusf** [comment]
in any case, when i change it manually to the new one, i see branches again. not sure what is happening there tbh.

**Comment by minusf** [comment]
and yes, i think it will be deprecated as other plugins i use (gv.vim) are also switching to "public" APIs..

**Comment by itchyny** [comment]
Thanks for you report.
