### ISSUE TITLE
lightline works only when sudo vim

### ISSUE THREAD

**Issue by s0m3OnE47** [itchyny/lightline.vim#419]
lightline works only when i do sudo vim <filename> It does not show colors when regular vim.
I have almost blank vimrc.

[Image Link](https://imgur.com/a/QMO1QqM)

**Comment by itchyny** [comment]
Please move the configuration to "$HOME/.vimrc" and try again.

**Comment by s0m3OnE47** [comment]
I moved the config file of vim from /etc/vimrc to ~/.vimrc
Now when using sudo, default vim behavior is seen. Without sudo, its same as before (as in the pic)
