### ISSUE TITLE
Show in what method and class I'm in

### ISSUE THREAD

**Issue by daGrevis** [itchyny/lightline.vim#42]
It would be really cool if I could see in what method and class I'm in. It could use Ctags.

What do you think? :)

**Comment by kkanungo17** [comment]
Sorry for reviving a closed thread, but the tag shown using the current solution persists even after the cursor has left the function and has not entered another function. Is there a way to fix this?

**Comment by itchyny** [comment]
@kkanungo17 That's not a issue of lightline but tagbar. Please submit a issue to the tagbar repository. I recommend to describe the issue without lightline, with samlpe code and the results of `:echo tagbar#currenttag("[%s]", "", "f")`, line numbers and what you expect.
