### ISSUE TITLE
Coloring in cterm and gui modes

### ISSUE THREAD

**Issue by cpkio** [itchyny/lightline.vim#420]
It seems to me Lightline is somehow messing around with colors. I'm mostly using Vim in a ConEmu terminal with the appropriate color scheme, so _my terminal colors 0-15 are the colors of a Nord scheme_, and I expect a Vim colorscheme to use those colors by number.

This is what I get when using Lightline with Lightline Nord scheme in Vim (the .vimrc is identical in both cases):
![Vim](https://user-images.githubusercontent.com/1917113/73678093-a7275e00-46c8-11ea-82ff-e7c1bd23e736.png)
and GVim:
![GVim](https://user-images.githubusercontent.com/1917113/73678095-a989b800-46c8-11ea-983a-7df4f1268cd2.png)

The question is _what Lightline uses to limit the available colors in Vim cterm mode_? Why are the colors for this INSERT/ REPLACE modes are not available in cterm Vim and what can I do to stop it doing so?

**Comment by itchyny** [comment]
Currently the [nord colors](https://github.com/itchyny/lightline.vim/blob/master/autoload/lightline/colorscheme/nord.vim) are defined by 0-15 so it is very natural that cterm colors are different from gui colors. The contributors (@arcticicestudio) would think that it is more important to follow the 0-15 colors instead of reproducing the nearest colors in 16-256. Some schemes are using `lightline#colorscheme#fill` which tries to calculate the nearest 256 colors, some schemes defines the colors directly. I think it's a matter of preference of the colorscheme author. You can use `:set termguicolors`.

**Comment by cpkio** [comment]
Does Lightline use system palette colors (by number, for example) in its' colorscheme or it uses colors provided by current Vim colorscheme?

**Comment by itchyny** [comment]
No, the color definition of lightline is not coupled with the colorscheme.

**Comment by cpkio** [comment]
Sorry, I just don't understand how this is working. If I **copy** `nord.vim` from `\lightline.vim\autoload\lightline\colorscheme` to `nordic.vim` and set `let g:lightline={'colorscheme':'nordic'}`, I will get errors on loading:
```
lightline.vim: Could not load colorscheme nordic.                                                            
Error detected while processing function lightline#update[5]..lightline#colorscheme[18]..lightline#highlight:
line    2:                                                                                                   
E716: Key not present in Dictionary: normal.left), len(c.normal.right)]                                      
E116: Invalid arguments for function len(c.normal.left), len(c.normal.right)]                                
Error detected while processing function lightline#update:                                                   
line    5:                                                                                                   
E171: Missing :endif                                                                                         
lightline.vim: Could not load colorscheme nordic.                                                            
Error detected while processing function lightline#update[5]..lightline#colorscheme[18]..lightline#highlight:
line    2:                                                                                                   
E716: Key not present in Dictionary: normal.left), len(c.normal.right)]                                      
E116: Invalid arguments for function len(c.normal.left), len(c.normal.right)]                                
Error detected while processing function lightline#update:                                                   
line    5:                                                                                                   
E171: Missing :endif
```
It should load the colorscheme fine, since it's a full copy.

**Comment by itchyny** [comment]
Did you replace the last line to `g:lightline#colorscheme#nordic#palette`?

**Comment by cpkio** [comment]
Thanks, now it's loading fine. I found out the reason of my problems was in the tricky Vim coloring settings, here is the [solution](https://www.reddit.com/r/vim/comments/b9t1zc/is_there_a_way_to_make_vim_use_the_16_defined): `set notermguicolors t_Co=256`.

**Comment by PyGamer0** [comment]
> 
> 
> Thanks, now it's loading fine. I found out the reason of my problems was in the tricky Vim coloring settings, here is the [solution](https://www.reddit.com/r/vim/comments/b9t1zc/is_there_a_way_to_make_vim_use_the_16_defined): `set notermguicolors t_Co=256`.

Yep this works for me. (I am using Cmder and Vim with Lightline, now it shows the colors properly)
