### ISSUE TITLE
Feature request: Clock

### ISSUE THREAD

**Issue by aemonge** [itchyny/lightline.vim#423]
I bet you can just relay on a set of configuration in the vimrc to accomplish the same functionality as 'enricobacis/vim-airline-clock'. Which simply displays a clock in airline.

Since I work with my browser full screen, and vim-terminal as well.... I need a clock on vim :)

**Comment by itchyny** [comment]
Here it is.
```vim
let g:lightline = {
      \ 'active': {
      \   'right': [['clock'], ['lineinfo'], ['percent'], ['fileformat', 'fileencoding', 'filetype']],
      \  },
      \  'component': {
      \    'clock': '%{strftime("%H:%M")}'
      \  },
      \ }
```
