### ISSUE TITLE
Changing 'background' has no effect on status bar.

### ISSUE THREAD

**Issue by kalekundert** [itchyny/lightline.vim#424]
The solarized color scheme reads the `background` setting when it is first loaded, but does not react when the setting is changed.  This specifically causes problems for me because I set the background for GUI windows in `~/.config/ginit.vim` (I use neovim), which is not loaded until after lightline has been initialized.  I also cannot find any way to manually trigger lightline to reevaluate the color scheme, which would make it pretty easy to work around this issue.

**Comment by itchyny** [comment]
Here is an example for solving this issue.
```vim
autocmd OptionSet background
      \ execute 'source' globpath(&rtp, 'autoload/lightline/colorscheme/solarized.vim')
      \ | call lightline#colorscheme() | call lightline#update()
```

**Comment by polyzen** [comment]
https://gitlab.com/polyzen/togglebg.vim/-/commit/d49706794221af0cb6bb707602e792b12b3d0119
