### ISSUE TITLE
Weird character in statuslinne

### ISSUE THREAD

**Issue by hnnazm** [itchyny/lightline.vim#427]
There seems a box after the filename and if I change it to something else (i.e filetype etc.) it turn out okay. It just happen recently. I use seoul256 theme.

This one is with 'filename'
<img width="1680" alt="weird character" src="https://user-images.githubusercontent.com/39019341/76043830-9c940900-5f93-11ea-92c1-89e3973aa742.png">

This one is with 'filetype'
<img width="1680" alt="without filename" src="https://user-images.githubusercontent.com/39019341/76043873-b7667d80-5f93-11ea-8324-b2db73c7bf3e.png">

Here is my lightline setting in init
<img width="755" alt="Screenshot 2020-03-06 at 10 11 21 AM" src="https://user-images.githubusercontent.com/39019341/76043939-e2e96800-5f93-11ea-8a74-869000c52da1.png">

**Comment by itchyny** [comment]
Please paste the result of `:echo &stl`

**Comment by hnnazm** [comment]
`:echo &stl` result:
%{lightline#link()}%#LightlineLeft_active_0#%( %{lightline#mode()} %)%{(&paste)?" ":""}%( %{&paste?"PASTE":""} %)%#LightlineLeft_active_0_1#%#LightlineLeft_active_1#%( %R %)%{(&readon
ly)&&(1)?" ":""}%( %<%F %)%#LightlineLeft_active_1_2#%#LightlineMiddle_active#%=%#LightlineRight_active_2_3#%#LightlineRight_active_2#%( %{&ff} %)%{1||1?"":""}%( %{&fenc!=#""?&fenc:
&enc} %)%{1?"":""}%( %{&ft!=#""?&ft:"no ft"} %)%#LightlineRight_active_1_2#%#LightlineRight_active_1#%( %3p%% %)%#LightlineRight_active_0_1#%#LightlineRight_active_0#%( %3l:%-2v %)

**Comment by itchyny** [comment]
You configure the filename component at
```vim
    \ 'filename': '%<%F%* ',
```
but fix this as
```vim
    \ 'filename': '%<%F',
```

**Comment by hnnazm** [comment]
Thank you. This solve the issue. Wasn't expecting this could be the problem because there was no problem before with this config
