### ISSUE TITLE
Trying to disable line/column numbers from show? help

### ISSUE THREAD

**Issue by dseeni** [itchyny/lightline.vim#429]
Hey itchyny, 
how can I disable the line:column numbers from showing?
inside of init.vim
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""Statusline  lightline
let g:lightline = {
\       'active': {
\         'left': [[ 'errors', 'warnings'],
\                   [  'filename', 'gitbranch', 'readonly', 'modified']]},
\       'inactive': {
\       'right': [ [ 'lineinfo' ],[ 'percent' ] ]},
\       'component_function': {
\         'errors': 'CocErrors',
\         'warnings': 'CocWarnings',
\         'gitbranch': 'gitbranch#name'}}

"""""""""""""""""""""""""""""""""""""""" Load these last to override any Plugins
set noruler
set noshowmode

This code results in 
![image](https://user-images.githubusercontent.com/6591429/76698174-15165c00-665d-11ea-8ebb-6cba1ca53959.png)

**Comment by itchyny** [comment]
That's called `lineinfo` component so remove them from the component list.
```vim
let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ], [ 'readonly', 'filename', 'modified' ] ],
      \   'right': [ [ 'percent' ], [ 'fileformat', 'fileencoding', 'filetype' ] ] },
      \ 'inactive': {
      \   'left': [ [ 'filename' ] ],
      \   'right': [ [ 'percent' ] ] },
      \ }
```

**Comment by dseeni** [comment]
Thanks itchyny, got it working! I didn't understand the format, very new to vimscript. Much appreciated.
