### ISSUE TITLE
BufWritePost / BufRead にて mkview および loadview を実施するようにしていると W11 発生時のファイル読込にてステータスラインが表示されなくなる

### ISSUE THREAD

**Issue by ansanloms** [itchyny/lightline.vim#430]
ファイル書き込み、読み込み時に mkview および loadview を実施するようにしています。
そのうえで、開いているファイルが別の箇所で更新された際に vim 上で再読み込みを行うと、ステータスラインが消えてしまいます。
こちら、ステータスラインが消えないようにするにはどうすればいいか、ご教示いただきたいです。

何卒宜しくお願い致します。

## 環境

+ Windows 10
+ vim 8.2.390

## 再現手順

1. lightline.vim を導入する

```
mkdir %UserProfile%\.vim-test\pack\test\start
git clone https://github.com/itchyny/lightline.vim.git %UserProfile%\.vim-test\pack\test\start\lightline.vim
```

2. 以下の通り .vimrc.test を用意する

```
set packpath^=~/.vim-test
set laststatus=2
" https://vim-jp.org/vim-users-jp/2009/10/08/Hack-84.html
autocmd BufWritePost * if expand('%') != '' && &buftype !~ 'nofile' | mkview | endif
autocmd BufRead * if expand('%') != '' && &buftype !~ 'nofile' | silent loadview | endif
set viewoptions-=options
```

3. あらかじめ test.txt を用意する (空ではないファイルを用意する)

~~copy nul test.txt~~
```
echo hoge >> test.txt
```

4. vim を起動し test.txt を開く

```
vim -u .vimrc.test -N
:e test.txt
```

![4](https://user-images.githubusercontent.com/16961622/76743969-d3012d80-67b6-11ea-80e6-c2e3defd3d9c.png)

5. vim 以外の所で test.txt を更新する

```
echo hoge >> test.txt
```

6. vim 上で W11 が発生しているはずなのでファイル再読込を実施する

```
W11: 警告: ファイル "test.txt" は編集開始後に変更されました
詳細は ":help W11" を参照してください
[O]K, ファイル読込((L)):
```
--> L を押下

![6](https://user-images.githubusercontent.com/16961622/76743980-d7c5e180-67b6-11ea-8fb9-4b6d353eea41.png)

## 実行結果

ステータスラインが消えている。

## 実現したいこと

ステータスラインが消えないようにしたい。

**Comment by itchyny** [comment]
「ステータスラインが消えた」状態のもらえますか

**Comment by itchyny** [comment]
「ステータスラインが消えた」状態のスクショもらえますか

**Comment by ansanloms** [comment]
当該、上記再現手順にキャプチャを貼り付けました。

---

すみません、再現手順に不備がありました。
上記「3. あらかじめ test.txt を用意する」の箇所を変更しております。
空のファイルに追記し、W11後の再読み込み時にはステータスラインが消えませんでした。
空ではないファイルに追記した際に、当issueの事象が発生致します。
大変失礼いたしました。

**Comment by itchyny** [comment]
修正したのでプラグインを更新してください

**Comment by ansanloms** [comment]
当該修正されていることを確認できました！
ご対応いただき、ありがとうございました。
