### ISSUE TITLE
How to set the colors of tabline?

### ISSUE THREAD

**Issue by Photonico** [itchyny/lightline.vim#431]
the tabline colors are a little dark, i want to customize it.

**Comment by itchyny** [comment]
Officially I recommend to create a new colorscheme of lightline (see `:h lightline-colorscheme`). But you can overwrite some colors by updating the palette.
```vim
let s:palette = g:lightline#colorscheme#landscape#palette
let s:palette.tabline.tabsel = [['#ff0000', '#121212', 196, 233]]
call lightline#highlight('tabline')
```

**Comment by unphased** [comment]
Thanks for the tip. If you do this in your vimrc make sure it is after the plugin loads, e.g. after `call plug#end()`.

**Comment by unphased** [comment]
Actually @itchyny this does not work: 
```
Error detected while processing function lightline#highlight:
line    1:
E121: Undefined variable: s:lightline
E15: Invalid expression: [s:lightline.palette, s:lightline.mode_fallback]
```

**Comment by yhu266** [comment]
Just use
```vim
let s:palette = g:lightline#colorscheme#landscape#palette
let s:palette.tabline.tabsel = [['#ff0000', '#121212', 196, 233]]
```
and ignore the third line.

**Comment by yhu266** [comment]
Also, make sure you overwrite the correct colorscheme. The example here assumes you're using `landscape`.

**Comment by unphased** [comment]
Ah, it was my mistake. this does work. I tried it two times. the first time i updated the colorscheme name. when i went to double check it just now, it was back to "landscape". OK! Thank you!
