### ISSUE TITLE
:gui commands starts gvim with discolored lightline

### ISSUE THREAD

**Issue by unInstance** [itchyny/lightline.vim#432]
I have laststatus=2 set in .vimrc
The plugin works [fine](https://i.imgur.com/2O5XUT5.jpg).

**Problem:** If I use vim from a terminal window and start gvim within vim with :gui command, then I can see a discolored lightline like [this](https://i.imgur.com/A2plMk2.jpg). It gets solved if I run :source ~/.vimrc in gvim.

**Comment by itchyny** [comment]
This looks like a problem of dotfiles. What happens when you copy ~/.vimrc to ~/.gvimrc?

**Comment by unInstance** [comment]
It works fine then.

**Comment by itchyny** [comment]
The configuration file of GVim is .gvimrc, so without this file the plugin cannot be enabled.
