### ISSUE TITLE
Missing "mode" when used with Syntastic

### ISSUE THREAD

**Issue by ichirou2910** [itchyny/lightline.vim#433]
Firstly thanks for this plugin. It's really lightweight for a minimalist like me.
I code Python, and I started using Syntastic for syntax checking recently. And i just found out something. Let me describe it in details below.
1. Open a python file, no problem
![image](https://user-images.githubusercontent.com/51302893/77560100-925c8f00-6eef-11ea-80d8-ff64a160e85b.png)
2. Make some errors, try saving it, and Syntastic would report the errors
![image](https://user-images.githubusercontent.com/51302893/77560172-ab654000-6eef-11ea-8583-83028e020ce1.png)
3. At first, it looked like nothing is wrong
![image](https://user-images.githubusercontent.com/51302893/77560292-d9e31b00-6eef-11ea-99d8-7c6a5368fb45.png)
4. But then when I fixed and saved, Syntastic window closed and....somehow "mode" disappeared too
![image](https://user-images.githubusercontent.com/51302893/77560396-026b1500-6ef0-11ea-9902-b6f2a75d7cda.png)
[Here](https://pastebin.com/eNAgXnDf) is my config of those 2 plugins. I hope I explained clearly what happened. I can still see the mode below the line, but just that I don't feel comfortable losing the mode part on the lightline. Do you have any idea?

**Comment by itchyny** [comment]
How about configuring `SyntasticCheckHook`?
```vim
function! SyntasticCheckHook(errors)
  call lightline#update()
endfunction
```

**Comment by ichirou2910** [comment]
Hi, thanks for your reply. After a few test, I found that lightline won't be updated when the error window appeared, and when I fixed the errors then saved, I had to save once more for the lightline to be updated. Tried both SyntasticCheckHook and g:SyntasticCheckHook. Do you have any idea?

**Comment by ichirou2910** [comment]
Okay so I inserted an echo command after the update call to check if it's called, and it turned out to be called any time I save (which triggers syntastic check). So I'm just confused how lightline#update() didn't work.

**Comment by itchyny** [comment]
Try `:call lightline#update()` manually does not work too?

**Comment by ichirou2910** [comment]
No, calling manually actually worked. That's what is confusing.

**Comment by itchyny** [comment]
I still cannot reproduce the issue, please write the precise steps to reproduce with the following vimrc. (I couldn't make syntastic check with Python works so I use Go)
```vim
set nocompatible
set rtp+=/path/to/lightline.vim
set rtp+=/path/to/syntastic
set laststatus=2

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 1
let g:syntastic_enable_highlighting = 0

filetype plugin indent on
syntax enable
```
test.go
```go
ackage main
```
```sh
 % vim -u ./.vimrc test.go
:SyntasticCheck go # location list opens
ip<ESC> # correct the syntax
:w # lightline looks still normal
```

**Comment by ichirou2910** [comment]
Ok. Here it is
test.py
```
rint("Hello World")
```
```
% vim -u ./.vimrc test.py
:w #location list opened
ip<ESC> # fix it
:w # location list disappeared but lightline lost the mode part
:w # lightline back to normal
```
Additional info: So I played around a bit, and I found something like this.
Basically syntastic error report is a window, and test.py is another window. If I run `:call lightline#update()` right after error window apppeared (in which test.py window is being focused), lightline on test.py window will become normal while syntastic's will lose mode (image below). After that if I change focus to syntastic window, its lightline came back to normal while test.py window will lose mode part until another `:call lightline#update()` or fixing the error followed by 2x `:w`
I'm really sorry if I bothered you too much with this issue.
![image](https://user-images.githubusercontent.com/51302893/77829108-69880400-7152-11ea-9270-28a76209a979.png)

**Comment by itchyny** [comment]
Hmm, still I cannot reproduce the issue.
![syntastic](https://user-images.githubusercontent.com/375258/77837929-f0b49680-71a9-11ea-8edd-a9d9f4cb40de.gif)

- I use Vim 8.2.450. What's your version of Vim?
- I use latest versions of lightline.vim and syntastic. Do you?
- Can you try `timer_start` solution?

```vim
function! SyntasticCheckHook(errors)
  call timer_start(10, {_->lightline#update()})
endfunction
```

**Comment by ichirou2910** [comment]
I use Nvim v0.4.3 with :PluginUpdate
OMG that timer worked like charm! Can you give me a brief explanation? My guess is that lightline#update() try to be executed before syntastic check, though looking at the code it's nearly impossible.

**Comment by itchyny** [comment]
Okay, I could reproduce with NeoVim. I would expect `SyntasticCheckHook` is called **after** closing the location list (in Vim it works like this) but something seems to be different in NeoVim (I don't want to take time to trace the root cause though). Just using the timer to delay the call of `lightline#update` works.

**Comment by ichirou2910** [comment]
Okay thanks for that. I will close this issue :+1:
