### ISSUE TITLE
Set tabline color for modified file

### ISSUE THREAD

**Issue by ffs97** [itchyny/lightline.vim#434]
Hi @itchyny,

Thanks so much for this awesome plugin. I have been considering shifting from airline to lightline because this is so lightweight and fast. There is one feature that I think is lacking from lightline and I was wondering if it possible to add it (in my .vimrc or in the plugin itself). How would I set the color of the tabline to something else if the file is modified (and not saved yet)? Any hints would be appreciated.

Thanks

**Comment by itchyny** [comment]
This is not basically supported feature but there's a hint in `:h lightline-problem-12`.

**Comment by ffs97** [comment]
Thanks for the quick reply. I did take a look at the problem and although it's not obvious to me how I will go about doing that, I will give it a try. Thanks :)

**Comment by itchyny** [comment]
You can change the modified color of some components in statusline, but you cannot change the colors in tabline. This is a limitation of this plugin and will not be changed.
