### ISSUE TITLE
Wrong active status line after restoring session

### ISSUE THREAD

**Issue by Isos9** [itchyny/lightline.vim#435]
Hi,
I'm using the plugin vim-session to manage my sessions, and when I open one of my sessions,
the status line is not active on the right buffer, if I have splitted/tabbed buffers.

![image](https://user-images.githubusercontent.com/16087932/77945254-a245eb80-72c0-11ea-9435-30948721d066.png)
for example on this one, I'm editing the left one, but the status line is active on the right.

I need to command :e or just change the buffer to get it work correctly.

so if anyone knows why, I would like some help please.
Thanks.

**Comment by itchyny** [comment]
Would you provide the minimal reproduction steps?

.vimrc
```
set nocompatible
set rtp+=/path/to/lightline.vim
set rtp+=/path/to/vim-misc
set rtp+=/path/to/vim-session
set laststatus=2

filetype plugin indent on
syntax enable
```

- Open Vim with `vim -u ./.vimrc`
- Do what?

**Comment by Isos9** [comment]
`:OpenSession mySession`

`mySession` should be a session with splitted or tabbed buffers, to reproduce this bug.

**Comment by itchyny** [comment]
What happens when you patch vim-session as follows?
```diff
diff --git a/autoload/xolox/session.vim b/autoload/xolox/session.vim
index 1f58004..a2aeea6 100644
--- a/autoload/xolox/session.vim
+++ b/autoload/xolox/session.vim
@@ -55,7 +55,7 @@ function! xolox#session#save_session(commands, filename) " {{{2
   call xolox#session#save_state(a:commands)
   if is_all_tabs
     call xolox#session#save_fullscreen(a:commands)
-    call add(a:commands, 'doautoall SessionLoadPost')
+    call add(a:commands, 'doautocmd SessionLoadPost')
   else
     call add(a:commands, 'let s:winrestcmd = winrestcmd()')
     call add(a:commands, 'windo doautocmd SessionLoadPost')
```

**Comment by Isos9** [comment]
Well, I don't even find the function save_session in it.

**Comment by itchyny** [comment]
Don't you using https://github.com/xolox/vim-session?

**Comment by itchyny** [comment]
Which vim-session plugin are you using? I assume https://github.com/xolox/vim-session.

**Comment by Isos9** [comment]
Yes this one

**Comment by itchyny** [comment]
https://github.com/xolox/vim-session/blob/master/autoload/xolox/session.vim#L11-L58

**Comment by Isos9** [comment]
Oh ok, my bad I was on the wrong file

**Comment by Isos9** [comment]
Still the same with this patch

**Comment by itchyny** [comment]
Please recreate the session and try again.

**Comment by Isos9** [comment]
Alright it works !, Thanks for your help and I like your simple status line.
