### ISSUE TITLE
How to set filename of inactive windows equals to active windows?

### ISSUE THREAD

**Issue by lucaspeixotot** [itchyny/lightline.vim#436]
Hello everyone, the colorscheme that I use is palenight and I would like to make filename of inactive windows the same colour that active windows? How can I do that?

**Comment by itchyny** [comment]
Here it is.
```vim
let s:palette = g:lightline#colorscheme#palenight#palette
let s:palette.inactive.left = s:palette.normal.left
call lightline#highlight('inactive')
unlet s:palette
```

**Comment by lucaspeixotot** [comment]
> Here it is.
> 
> ```viml
> let s:palette = g:lightline#colorscheme#palenight#palette
> let s:palette.inactive.left = s:palette.normal.left
> call lightline#highlight('inactive')
> unlet s:palette
> ```

I got this error 
```
Error detected while processing function lightline#highlight:
line    1:
E121: Undefined variable: s:lightline
E15: Invalid expression: [s:lightline.palette, s:lightline.mode_fallback]
Press ENTER or type command to continue
```

Apparently, inside of highlight function, there is something missing. Is it the problem? I liked your confidency, probably this is the right way.

**Comment by itchyny** [comment]
Can you try without the `call lightline#highlight` line?

**Comment by lucaspeixotot** [comment]
> Can you try without the `call lightline#highlight` line?

Nice, thanks. I supposed that this line was important, so didn't think in remove it. This worked.
