### ISSUE TITLE
now bar showing when there is only one window

### ISSUE THREAD

**Issue by mealsd** [itchyny/lightline.vim#438]
there is nothing when there is only one window left.
when there are more than one window, it works well.
as shown in the attached figures.
<img width="1856" alt="屏幕截图 2020-04-02 02 33 43" src="https://user-images.githubusercontent.com/17028231/78217676-868e4100-748a-11ea-8c77-ae3bd8df314d.png">
<img width="1857" alt="屏幕截图 2020-04-02 02 33 57" src="https://user-images.githubusercontent.com/17028231/78217693-8beb8b80-748a-11ea-8615-c972b1e42afa.png">

**Comment by itchyny** [comment]
Please configure `set laststatus=2` in vimrc.
