### ISSUE TITLE
Current tab not highlighted when displayed on right

### ISSUE THREAD

**Issue by nwaywood** [itchyny/lightline.vim#439]
When I have this:

```
      \ 'tabline': {
      \   'left': [ ['tabs'] ],
      \   'right': [ ['close'] ]
      \ },
```

The current tab is highlighted a different color so that you can tell what the current tab is, as shown below:

![image](https://user-images.githubusercontent.com/3773641/78541543-22c49900-7839-11ea-8620-9df487a84dd8.png)

However, if I display the tabs on the `right` instead of on the `left`:

```
      \ 'tabline': {
      \   'left': [ ['close'] ],
      \   'right': [ ['tabs'] ]
      \ },
```

The current tab is no longer highlighted:

![image](https://user-images.githubusercontent.com/3773641/78541668-57d0eb80-7839-11ea-85cc-a9f9ca0abd7f.png)

**Comment by itchyny** [comment]
I tweaked the tabline colors of the solarized theme, please confirm.

**Comment by nwaywood** [comment]
@itchyny yes it is working now. Thank you!
