### ISSUE TITLE
Just show tab numbers in tab component

### ISSUE THREAD

**Issue by nwaywood** [itchyny/lightline.vim#441]
I am trying to modify the `tabs` component to just show the tab number, like how [this plugin](https://github.com/pacha/vem-tabline) does it.

![image](https://user-images.githubusercontent.com/3773641/78736110-b7d9a600-798f-11ea-9d60-51a0c0afbae8.png)

From your documentation I have figured out that I need to override the `tabs` function in `component_expand` (at least I think that's what I need to do?). So I had a look at your [source code](https://github.com/itchyny/lightline.vim/blob/master/autoload/lightline.vim#L457-L489) but my vimscript isn't good enough to understand what is going on in those two functions.

Is this the correct way to do what I am trying to do?

**Comment by itchyny** [comment]
```vim
let g:lightline = {
      \ 'tab': {
      \   'active': [ 'tabnum' ],
      \   'inactive': [ 'tabnum' ],
      \ },
      \ }
```

**Comment by nwaywood** [comment]
Oh I was overcomplicating that a lot... thank you!

Is it possible to also make it preserve the same order? Atm it rearranges the order depending on which tab is selected.

![image](https://user-images.githubusercontent.com/3773641/78737135-27e92b80-7992-11ea-96de-955a55f1896a.png)

![image](https://user-images.githubusercontent.com/3773641/78737147-320b2a00-7992-11ea-8c42-e0dec74433f3.png)

![image](https://user-images.githubusercontent.com/3773641/78737169-3e8f8280-7992-11ea-83dc-6b7ea01b56c8.png)

**Comment by itchyny** [comment]
This is the same problem of #440. Currently there's a workaround using `reverse()`.

**Comment by nwaywood** [comment]
Perfect, it's working exactly how I want it now :)

Thanks again for this awesome plugin and your help!
