### ISSUE TITLE
Active window has statusline of inactive window on initial load

### ISSUE THREAD

**Issue by jackcogdill** [itchyny/lightline.vim#444]
I think this [workspace plugin](https://github.com/thaerkh/vim-workspace) might be causing it. The plugin restores saved layout (in my case, about five tabs). When I delete the workspace and load default vim (no tabs), lightline looks fine. Also, when I have the first tab selected, lightline looks fine. It's only when it's restoring a tab with index >1 that lightline looks inactive.

So maybe it has to do with how that plugin is switching tabs?

I can manually fix it like this:
```
:call lightline#update()
:e
:tabn
:tabp
```

_Originally posted by @jackcogdill in https://github.com/itchyny/lightline.vim/issues/443#issuecomment-611710427_

**Comment by jackcogdill** [comment]
Found steps to reproduce!

0. Install vim-workspace and lightline
1. Open 3 files in separate tabs.
2. Go to the 2nd tab
3. Quit vim
4. Reopen vim (and the workspace reloads)
5. The status bar looks as if it's an inactive window

**Comment by itchyny** [comment]
I opened a new issue #448 and closing. This is not just about the workspace plugin, nor just about the session. Please subscribe #448 for updates.

**Comment by jackcogdill** [comment]
Wow, great debugging. Thanks!

**Comment by itchyny** [comment]
This has been fixed for Vim 8.2.0996 or later.
