### ISSUE TITLE
Make work with wal.vim?

### ISSUE THREAD

**Issue by bradwood** [itchyny/lightline.vim#445]
I use [wal.vim](https://github.com/dylanaraps/wal.vim) which dynamically sets a vim colorscheme from the tool `pywal`.

I'm trying to get lightline to inherit (some) colours from the `pywal` config via `wal.vim`.

Is there an easy way to make these work together?

See: https://github.com/dylanaraps/wal.vim/issues/5
And https://github.com/dylanaraps/wal.vim/issues/19

**Comment by itchyny** [comment]
It seems that [wal.vim does not specify the gui colors](https://github.com/dylanaraps/wal.vim/blob/fb6ce53632f93c31cad66398636bfb383ad64d52/autoload/lightline/colorscheme/wal.vim#L8-L17) which can cause some problems. Please ask the author of wal.vim or send a pull request to support the gui colors.
