### ISSUE TITLE
lightline not loading properly when I load a Session with tabs

### ISSUE THREAD

**Issue by gbihtas** [itchyny/lightline.vim#447]
Steps to reproduce:

1. open vim from console:
> vim

2. Activate Startify and open a Session that contains tabs. The issue is also present when I load the session with SLoad without going through the Startify interface

3. lightline does not work properly. Statusline does not render correctly

![DSC_2883](https://user-images.githubusercontent.com/22296510/79427812-2dabc600-7fbd-11ea-8a9d-70315221f34b.JPG)

![DSC_2885](https://user-images.githubusercontent.com/22296510/79427833-343a3d80-7fbd-11ea-8d88-0ea8b86bb0f2.JPG)

4.  I have to reload the buffer with :e or move to a new tab in order statusline to reload again correctly

![DSC_2886](https://user-images.githubusercontent.com/22296510/79427855-3c927880-7fbd-11ea-8c07-76df097b64af.JPG)

![DSC_2887](https://user-images.githubusercontent.com/22296510/79427862-3f8d6900-7fbd-11ea-8822-d4abcadd14e6.JPG)

This issue is not present if I open a single buffer (no tabs)

**Comment by itchyny** [comment]
I opened a new issue #448 and closing. This is not just about the workspace plugin, nor just about the session. Please subscribe #448 for updates.

**Comment by itchyny** [comment]
This has been fixed for Vim 8.2.0996 or later.

**Comment by lesar** [comment]
I have installed:  
VIM - Vi IMproved 8.2 (2019 Dec 12, compilato Jan 08 2021 14:00:27)                                                                                                                                                
Patch incluse: 1-2311                                                                                                                                                                                              

but lightline is not show well after a session load.
