### ISSUE TITLE
Statusline is inactive on doautoall command (specifically on session loads)

### ISSUE THREAD

**Issue by itchyny** [itchyny/lightline.vim#448]
The `doautoall` command causes lightline to misbehave. Specifically the session file contains [doautoall SessionLoadPost](https://github.com/vim/vim/blob/8a7d6542b33e5d2b352262305c3bfdb2d14e1cf8/src/session.c#L1253) so this line causes #444, #447. The command `doautoall WinEnter` also causes the same problem. This is basically caused by the [hidden window](https://github.com/vim/vim/blob/aeea72151c31d686bcbb7b06d895006d7363585c/src/autocmd.c#L1421-L1428), lightline should not react to the event of the hidden window. But still I can't find the correct solution because all functions (winnr, bufwinnr, etc) go wrong.

**Comment by teoh** [comment]
Any updates on this?

**Comment by itchyny** [comment]
This needs a fix in Vim because Vim script can't tell the difference of normal windows and the autocmd window (I wrote hidden window in the above comment). One solution is exposing the [`aucmd_win_used` variable](https://github.com/vim/vim/blob/aeea72151c31d686bcbb7b06d895006d7363585c/src/autocmd.c#L1452) to Vim script, something like `v:aucmd_win_used` or `expand('<awinused>')`. Another solution is exposing the [`win_unlisted` function](https://github.com/vim/vim/blob/03a9f848175b182372fb33403998059724a8bf31/src/window.c#L5037-L5045) to Vim script. In any case, we have to write down the reasonable explanation for what we need here.

**Comment by sbromberger** [comment]
I don't know whether this is helpful, but I'm seeing the same behavior as described in https://github.com/haorenW1025/diagnostic-nvim/issues/32 with two different language servers: Julia and Rust. For me, it's happening with the latest version of neovim master (currently `NVIMv0.5.0-554-gdcd6cf5f3`).

**Comment by itchyny** [comment]
Vim finally implemented a way to detect the autocmd window at [8.2.0991](https://github.com/vim/vim/commit/0fe937fd8616fcd24b1b1ef2ab9f1657615dd22c), followed by [8.2.0996](https://github.com/vim/vim/commit/40a019f157c549dcdc17c33f082975485567bb06). So this issue has been closed for **Vim 8.2.0996** or later. Please update the version of Vim. We cannot fix for older versions of Vim because there's no way out to detect the autocmd window. For NeoVim users, please wait for the patch to be included to NeoVim or submit the patch yourself. If you still have the issue even if you update both lightline and Vim, that's another problem so please submit a new issue.

**Comment by lesar** [comment]
I have installed:  
VIM - Vi IMproved 8.2 (2019 Dec 12, compilato Jan 08 2021 14:00:27)                                                                                                                                                
Patch incluse: 1-2311                                                                                                                                                                                              

but lightline is not show well after a session load.

there is any workaround?

best regards
Leonardo
