### ISSUE TITLE
Status line does not update properly when fzf in popup window

### ISSUE THREAD

**Issue by halkn** [itchyny/lightline.vim#449]
## Overview

Thank you your plugin.
lightline.vim does not update properly when using fzf.vim in a popup window.
It doesn't seem to happen for normal windows, not popup windows.

![reproduction](https://user-images.githubusercontent.com/41255229/79743865-51b23300-8340-11ea-89f8-4b014002ca56.gif)

As shown below, the status line is not updated after selecting with fzf in popup window.

<img width="564" alt="actual" src="https://user-images.githubusercontent.com/41255229/79744253-fdf41980-8340-11ea-9f48-c32d46dd2dfb.png">

## Expected

<img width="563" alt="expected" src="https://user-images.githubusercontent.com/41255229/79744041-a35abd80-8340-11ea-9b64-b77faf6a2060.png">

## Environmental information

* OS : macOS
* vim version : 8.2.550 (install by homebrew)
* Minimum vimrc (with vim-plug)
```vim
set laststatus=2 
call plug#begin(expand('$XDG_DATA_HOME/vim/plugged'))
" global
Plug 'itchyny/lightline.vim'
Plug 'junegunn/fzf'
call plug#end()

let g:fzf_layout = { 'window': { 'width': 0.95, 'height': 0.9 } }
```

**Comment by ichizok** [comment]
I sent PR to fzf, will fix this issue.
https://github.com/junegunn/fzf/pull/2000

**Comment by itchyny** [comment]
@ichizok Wow, fix confirmed. This is such a great job, thank you.

**Comment by halkn** [comment]
Thank you.
I also confirmed the fix.

This was not a lightline issue. 
[junegunn/fzf#2000](https://github.com/junegunn/fzf/pull/2000) seems to be under discussion yet, but I think this issue may be closed.

**Comment by itchyny** [comment]
There's nothing to do in this plugin so closing.
