### ISSUE TITLE
q: how can i display full path name of file like how vim by default does

### ISSUE THREAD

**Issue by vired** [itchyny/lightline.vim#450]
why you have changed that feature.
it is very confusing not to seeing the full pathname of a file.

**Comment by itchyny** [comment]
Use `absolutepath` component.
```vim
let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'readonly', 'absolutepath', 'modified' ] ],
      \ },
      \ 'inactive': {
      \   'left': [ [ 'absolutepath' ] ],
      \ },
      \ }
```

**Comment by vired** [comment]
i think you should make this default

**Comment by itchyny** [comment]
Users can configure the behavior and I can't change the default behavior which is  used for years.

**Comment by vired** [comment]
ok, can you please explain what  `%F` in  `'absolutepath': '%F'`  does? 
how can i get the path in that format in normal mode?
i know that `echo @%` print the file path relative to the working dir.

**Comment by itchyny** [comment]
Please refer to `:h 'statusline'` and search by `/F S`.
