### ISSUE TITLE
Current working directory component

### ISSUE THREAD

**Issue by lifeBalance** [itchyny/lightline.vim#453]
I decided to dip my toes in Vimscript, and configuring this plugin sounds like a good start. I want to show the **current working directory** in a component, but it doesn't update when I change directory. How should I go about that?
```
let g:lightline = {
\ 'active': {
\   'left': [ ['mode', 'paste'],
\           ['readonly', 'filename', 'modified', 'cwd'] ]
\ },
\ 'component': {
\   'cwd': getcwd()
\ }
\ }
```
Is there a way of coloring the component?
Thanks

**Comment by itchyny** [comment]
Close, please specify `'%{getcwd()}'`.

**Comment by lifeBalance** [comment]
Wow, that was easy, I thought I was gonna have to create a function or something ). 

How about **coloring the component**? I've been reading *lightline-component-expansion* but can't really understand what to do. I've changed ``component`` to ``component_expand``:

```
let g:lightline = {
\ 'active': {
\   'left': [ ['mode', 'paste'],
\           ['readonly', 'filename', 'modified'],
\           ['cwd'] ]
\ },
\ 'component_expand': {
\   'cwd': '%{getcwd()}'
\ }
\ }
let s:p.active.left[2] = ['gray8', 'gray2']
```
I put the ``cwd`` component in ``lightline.active.left[2]``, correct? Then chose a random couple of colors for fg and bg, but I get the error:
**E121: Undefined variable: s:p**

**Comment by itchyny** [comment]
Displaying specific components in arbitrary colors is **not supported** in lightline except for components for error/warning messages. This is because the colors should be controlled only by the lightline colorschemes. If I allow the user to color the components freely, the roles go uncontrollable.

**Comment by lifeBalance** [comment]
I see, so the way to do it, it's in the colourscheme. I tried to copy a colorscheme to customize it, but I get the **﻿﻿﻿﻿lightline.vim: Could not load colorscheme customized_powerline.** error:
```
source $HOME/.config/nvim/customized_powerline.vim
let g:lightline = {
\ 'colorscheme': 'customized_powerline',
...
```

**Comment by itchyny** [comment]
Please refer to `:h lightline-colorscheme`. `customized_powerline.vim` should be placed at `{one of the paths in &rtp}/autoload/lightline/colorscheme/customized_powerline.vim`.

**Comment by lifeBalance** [comment]
Well, my runtimepath starts with ```runtimepath=~/.config/nvim, ...`` but:
```
source $HOME/.config/nvim/autoload/lightline/colorscheme/customized_powerline.vim 
let g:lightline = {                                                                   │
\ 'colorscheme': 'customized_powerline',
```
Still get the error

**Comment by itchyny** [comment]
Did you edit the file? It should define `g:lightline#colorscheme#customized_powerline#palette` at the bottom of the file.

**Comment by lifeBalance** [comment]
No sir, I had forgotten that. I did, and now I'm getting this:
```
line   28:
E117: Unknown function: lightline#colorscheme#fill
E15: Invalid expression: lightline#colorscheme#fill(s:p)
```
But I feel we're getting closer, right? :-)

**Comment by itchyny** [comment]
Maybe you want to add an element to `s:p.normal.left`.
```vim
let s:p.normal.left = [ ['darkestgreen', 'brightgreen', 'bold'], ['white', 'gray4'], ['gray8', 'gray2'] ]
```

**Comment by lifeBalance** [comment]
Yeah, I tried that, but I wanted to understand why. Anyways, I ended up adding an empty item:
```
let s:p.normal.left = [ ['darkestgreen', 'brightgreen', 'bold'], ['white', 'gray4'], [] ]
...
let s:p.normal.left[2] = ['white', 'darkestblue']
```
Thanks man.
