### ISSUE TITLE
Is there a way to change the colorscheme after it's been set?

### ISSUE THREAD

**Issue by nburns** [itchyny/lightline.vim#454]
In my vimrc I'll set the colorscheme:
```vim
let g:lightline = { 'colorscheme': 'solarized' }
```
then depending on the light or dark mode of the os the colorscheme may be updated:
```vim
let g:lightline = { 'colorscheme': 'PaperColor' }
```
lightlines colors don't change even when it updates information displayed.

Could you advise or suggest a way to trigger lightline to update its colors?

**Comment by itchyny** [comment]
Please call `call lightline#init()` and then `call lightline#colorscheme()`.

**Comment by nburns** [comment]
Thanks, that works!
