### ISSUE TITLE
How to show FugitiveHead on the tabline

### ISSUE THREAD

**Issue by lifeBalance** [itchyny/lightline.vim#456]
Hi itchyny, I'm trying to show the FugitiveHead on the tabline:
```
let g:lightline.tabline = {
\ 'left': [ [ 'tabs' ] ],
\ 'right': [ [ 'gitbranch'] ],
\ 'component_function': {
\   'gitbranch': 'FugitiveHead'
\ }
\}
```
I can see the **tabline** with the tabs, but not the ``gitbranch``. What am I doing wrong? (I have installed fugitive.vim)

**Comment by itchyny** [comment]
Please register the function to `tab_component_function`.

**Comment by lifeBalance** [comment]
Hmm, that didn't work. Do I have to create a function too, or ``FugitiveHead`` is included by **vim-fugitive**?

**Comment by itchyny** [comment]
Sorry, tab_component_function was incorrect. And I confirmed that YOUR configuration works.

**Comment by lifeBalance** [comment]
You mean the original I posted? Yeah, I don't know what could be wrong. When I run:
```
:echo FugitiveHead()
``` 
I get ``master``, meaning the fugitive plugin works.

**Comment by itchyny** [comment]
Please try the following configuration.
```vim
let g:lightline = {
      \ 'tabline': {
      \   'left': [ [ 'tabs' ] ],
      \   'right': [ [ 'gitbranch'] ],
      \ },
      \ 'component_function': {
      \   'gitbranch': 'FugitiveHead'
      \ },
      \ }
```

**Comment by lifeBalance** [comment]
Yes, that works. Thank you itchyny
