### ISSUE TITLE
conflict with vim-which-key.

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [itchyny/lightline.vim#459]
hello, sorry to submit this issue, maybe this plugin can help me to solve the problem.
i use vim-which-key with lightline. the mini-vim config is 
```vim
call plug#begin()

Plug 'liuchengxu/vim-which-key'
Plug 'itchyny/lightline.vim'

call plug#end()

set updatetime=200
let g:mapleader = "\<Space>"
let g:maplocalleader = ','
nnoremap <silent> <leader>      :<c-u>WhichKey '<Space>'<CR>
nnoremap <silent> <localleader> :<c-u>WhichKey  ','<CR>
call which_key#register('<Space>', "g:which_key_map")
set timeoutlen=50
let g:which_key_use_floating_win=0
let g:which_key_map =  {}

let g:which_key_map.w = {
      \ 'name' : '+windows' ,
      \ 'H' : ['<C-W>8<'    , 'expand-window-left']    ,
      \ 'J' : ['resize +5'  , 'expand-window-below']   ,
      \ 'L' : ['<C-W>8>'    , 'expand-window-right']   ,
      \ 'K' : ['resize -5'  , 'expand-window-up']      ,
      \ }

set termguicolors
```
 the problem is when i press <Space> to trigger vim-which-key, lightline was broken.
before
<img width="714" alt="iShot2020-04-3018 22 31" src="https://user-images.githubusercontent.com/2133400/80700058-a22f4a80-8b0f-11ea-85b2-b169d5c29a20.png">
after
<img width="719" alt="iShot2020-04-3018 22 47" src="https://user-images.githubusercontent.com/2133400/80700070-a9565880-8b0f-11ea-8fa3-13cce5afcd73.png">

the airline plugin works with vim-which-key very well.  so i think some implementation is different.

**Comment by itchyny** [comment]
It's responsible for plugins to emit WinEnter event on switching the windows. But on closing the which-key window, the WinEnter event is not fired (tested with `au WinEnter * echom 'WinEnter'`). This is not a bug of lightline. The airline plugin updates the statusline on BufUnload event but this is incorrect implementation because qall emits too many updates.

**Comment by FinallyFinancialFreedom** [comment]
thank you for reply, now the author of vim-which-key solved this problem by call lightline#update().
