### ISSUE TITLE
The showmode cannot displayed - font/background color are the same.

### ISSUE THREAD

**Issue by sihunqu123** [itchyny/lightline.vim#462]
![image](https://user-images.githubusercontent.com/22839917/81475716-7b27f580-9240-11ea-8408-65c76f92a68e.png)

See this is what I have experienced. And I have tried the below 2 solution, none of them works.

`set laststatus=2`

```
export TERM=xterm-256color
if !has('gui_running')
  set t_Co=256
endif
```

**Comment by itchyny** [comment]
Which colorscheme do you use?

**Comment by sihunqu123** [comment]
I've tried `molokai`, `desert`, `evening` and so on. BTW, I am using tty mode vim via putty(on windows) to ssh into centos.

**Comment by itchyny** [comment]
Your terminal might not support 256 colors. How about `16color` theme?

**Comment by sihunqu123** [comment]
Sorry, my Linux is broken for days. There are many available themes, and after iterating every theme, I finally found one, in which theme, all items in statueline are visible, thanks.
