### ISSUE TITLE
Lightline git status icons

### ISSUE THREAD

**Issue by hsheikhali** [itchyny/lightline.vim#463]
This is more so a question rather than an issue since I cant find any documentation on how to do this but airline allows you to display git icons for how many files have been modified, deleted, and added and also displays an branch icon. Is this doable with lightline?

Below is an example of how my airline looks like right now
<img width="1591" alt="Screen Shot 2020-05-10 at 4 41 28 PM" src="https://user-images.githubusercontent.com/35124039/81510061-1cfd2000-92dd-11ea-85aa-ab64ecdcd38c.png">

**Comment by polyzen** [comment]
https://github.com/itchyny/lightline.vim/blob/d77c94f2152cca6f8ce461150936d8456088a3f4/doc/lightline.txt#L306-L326
