### ISSUE TITLE
lightline not working after sourcing vimrc

### ISSUE THREAD

**Issue by chrischenubc** [itchyny/lightline.vim#464]
The lightline is not working after I source my vimrc.
I have to call :PlugInstall to re-enable this plugin

**Comment by itchyny** [comment]
Please describe the issue with your complete vimrc and precise steps to reproduce.

**Comment by chrischenubc** [comment]
I used Vim-Plugged to install the lightline.
```
call plug#begin('~/.vim/plugged')
Plug 'itchyny/lightline.vim'
call plug#end()
```
When I ran :source $MYVIMRC, the lightline stoped working.

**Comment by itchyny** [comment]
Please comment out the line `set statusline=\ ....`.

**Comment by chrischenubc** [comment]
Commenting out this line solve the problem.
Thanks!
