### ISSUE TITLE
lightline doesn't show up in Vim 8.2.510

### ISSUE THREAD

**Issue by ambushed** [itchyny/lightline.vim#465]
I am having issues with getting this plugin to work on the Vim version 8.2.510.   On start up, even though vim-plug shows that the plugin has been installed correctly, the lightline is not visible.  When I run the :PlugInstall, the status line appears, to disappear again when the split window is closed.  

:PlugSnapshot gives the the following commit sha:
`silent! let g:plugs['lightline.vim'].commit = '865c5c3'`

Any thoughts on how i can debug this?

**Comment by itchyny** [comment]
Please describe the issue with your entire vimrc and precise steps to reproduce the issue.

**Comment by ambushed** [comment]
My .vimrc is as follows:
`set runtimepath=~/.vim_lightline

call plug#begin('~/.vim_lightline/plugged')
Plug 'itchyny/lightline.vim'
call plug#end()
`
I have meanwhile solved the issue by adding `set laststatus=2` to the .vimrc.

**Comment by itchyny** [comment]
The README.md suggest adding `set laststatus=2` to your vimrc.
