### ISSUE TITLE
Styling based on "inactive" highlight groups in .vimrc

### ISSUE THREAD

**Issue by chrisnovakovic** [itchyny/lightline.vim#467]
I'm trying to make the style of the `VertSplit`, `StatusLine` and `StatusLineNC` highlight groups rely partially on the style of the current lightline theme, so instead of this:

![vim-no](https://user-images.githubusercontent.com/2261519/82158418-aed9cf80-987f-11ea-8096-f26c611f150d.png)

I get this:

![vim-yes](https://user-images.githubusercontent.com/2261519/82158433-b7320a80-987f-11ea-8862-1c6ffa72c269.png)

* The vertical divider has a background that matches the window's and a foreground that matches the background of the "main" part of the lightline bar, making the vertical divider look like a thin continuation of the status bar.
* The no-man's-land between the two lightline bars in the status bar has a (back|fore)ground that matches the "main" part of the lightline bar, so it all appears to be one continuous bar. (Without the latter, the no-man's-land is coloured white when either of the top windows is active, which looks even worse.)

Here's how I'm doing this in my `.vimrc`:

```vim
function Fixcolours()
    execute printf('highlight VertSplit ctermbg=%s ctermfg=%s',
        \ synIDattr(synIDtrans(hlID('Normal')), 'bg'),
        \ synIDattr(synIDtrans(hlID('LightlineMiddle_inactive')), 'bg'))

    execute printf('highlight StatusLine guifg=red ctermbg=%s ctermfg=%s',
        \ synIDattr(synIDtrans(hlID('LightlineMiddle_inactive')), 'bg'),
        \ synIDattr(synIDtrans(hlID('LightlineMiddle_inactive')), 'bg'))

    execute printf('highlight StatusLineNC guifg=blue ctermbg=%s ctermfg=%s',
        \ synIDattr(synIDtrans(hlID('LightlineMiddle_inactive')), 'bg'),
        \ synIDattr(synIDtrans(hlID('LightlineMiddle_inactive')), 'bg'))
endfunction

augroup LightlineColourfixes
    autocmd!
    autocmd VimEnter * call Fixcolours()
    autocmd ColorScheme * call Fixcolours()
augroup END
```

It makes heavy use of the `LightlineMiddle_inactive` highlight group, which unfortunately only exists after the first horizontal or vertical split has been performed, so I can't call `Fixcolours()` when Vim starts. Is there any way around this? Could lightline create the "inactive" highlight groups as soon as the palette is loaded, so they're available to code in `.vimrc` that wants to use them?

**Comment by chrisnovakovic** [comment]
I don't know if this has any adverse effects, but adding

```vim
call lightline#highlight('inactive')
```

after line 202 of `autoload/lightline.vim` fixes my problem. Is this sensible? Should I create a PR?

**Comment by itchyny** [comment]
Please use `lightline#palette()` for getting the palette colors. The colors are set lazily for performance reason so we can't change it.

**Comment by chrisnovakovic** [comment]
Thanks for the hint about `lightline#palette()` - in case anyone else has the same need in future, this is how I solved it:

```vim
" Partially link some highlight groups to highlight groups found in lightline,
" for overall consistency:
augroup LightlinePartiallink
    autocmd!
    autocmd VimEnter * call s:lightline_partiallink()
    autocmd ColorScheme * call s:lightline_partiallink()
augroup END
function s:lightline_partiallink()
    let l:palette = lightline#palette().inactive.middle[0]

    let l:targets = has('gui_running') ?
        \ { 'real': 'gui',   'dummy': 'cterm', 'bgindex': 1 } :
        \ { 'real': 'cterm', 'dummy': 'gui',   'bgindex': 3 }

    " Make the column separating vertically-split windows the same colour as the
    " empty part of an inactive lightline bar
    execute printf('highlight VertSplit ctermbg=%s ctermfg=%s',
        \ synIDattr(synIDtrans(hlID('Normal')), 'bg'),
        \ l:palette[l:targets.bgindex])

    " Make the status line the same colour as the empty part of an inactive
    " lightline bar, so the status bar appears unbroken when it contains
    " multiple lightline bars
    for group in ['StatusLine', 'StatusLineNC']
        execute printf('highlight %s %sfg=red %sbg=%s %sfg=%s',
            \ group, l:targets['dummy'],
            \ l:targets['real'], l:palette[l:targets.bgindex],
            \ l:targets['real'], l:palette[l:targets.bgindex])
    endfor
endfunction
```

It assumes there'll always be at least one element in the palette's `inactive.middle` list, but this seems like a safe assumption for any sensible colorscheme (@itchyny: is it? 🙂).

**Comment by itchyny** [comment]
Note that `inactive.middle` does not always exist, it fallbacks to `normal.middle`. So something like `has_key(l:palette, 'inactive') && has_key(l:palette.inactive, 'middle') ? l:palette.inactive.middle[0] : l:palette.normal.middle[0]`.

**Comment by chrisnovakovic** [comment]
Thanks for the clarification - in that case, for posterity, here's the final version:

```vim
" Partially link some highlight groups to highlight groups found in lightline,
" for overall consistency:
augroup LightlinePartiallink
    autocmd!
    autocmd VimEnter * call s:lightline_partiallink()
    autocmd ColorScheme * call s:lightline_partiallink()
augroup END
function s:lightline_partiallink()
    let l:palette = lightline#palette()

    " The inactive.middle group doesn't always exist, in which case lightline
    " falls back on the normal.middle group
    let l:colours = has_key(l:palette, 'inactive') && has_key(l:palette.inactive, 'middle') ?
        \ l:palette.inactive.middle[0] :
        \ l:palette.normal.middle[0]

    let l:targets = has('gui_running') ?
        \ { 'real': 'gui',   'dummy': 'cterm', 'bgindex': 1 } :
        \ { 'real': 'cterm', 'dummy': 'gui',   'bgindex': 3 }

    " Make the column separating vertically-split windows the same colour as the
    " empty part of an inactive lightline bar
    execute printf('highlight VertSplit ctermbg=%s ctermfg=%s',
        \ synIDattr(synIDtrans(hlID('Normal')), 'bg'),
        \ l:colours[l:targets.bgindex])

    " Make the status line the same colour as the empty part of an inactive
    " lightline bar, so the status bar appears unbroken when it contains
    " multiple lightline bars
    for group in ['StatusLine', 'StatusLineNC']
        execute printf('highlight %s %sfg=red %sbg=%s %sfg=%s',
            \ group, l:targets['dummy'],
            \ l:targets['real'], l:colours[l:targets.bgindex],
            \ l:targets['real'], l:colours[l:targets.bgindex])
    endfor
endfunction
```
