### ISSUE TITLE
Vim version 8.2.814 - "set nocompatible" messes with colors

### ISSUE THREAD

**Issue by ambushed** [itchyny/lightline.vim#471]
I have recently upgraded my Arch linux system and got the version of vim 8.2.814 with it.  The first thing i noticed was that the colorscheme of the lightline plugin have been affected.  I narrowed it down to "set nocompatible" in the following .vimrc
```
set packpath+=.
"set nocompatible

if empty(glob('.vim/autoload/plug.vim'))
  silent !curl -fLo .vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('.vim/plugged')

Plug 'gruvbox-community/gruvbox'
Plug 'itchyny/lightline.vim'

Plug 'dense-analysis/ale'

call plug#end()

set laststatus=2
set autowrite

let g:lightline = {'colorscheme': 'wombat'}
```
If i don't set `nocompatible`, vim chokes on multiline definitions in ALE (and many other plugins), if i do, the colors of lightline are reset to basic (non 256 ones).

Is there a way to have "nocompatible" set and have the nice colorschemes for lightline?

**Comment by itchyny** [comment]
I can't reproduce the issue with your vimrc. It works fine for me even with `set nocompatible`. Anyway adding `set nocompatible` to vimrc (or gvimrc) is totally nonsense because Vim automatically does this for you (see `:h compatible-default`). It is even dangerous because it truncates your command history.

**Comment by ambushed** [comment]
ah, ok, thank you for pointing me to the help file.  what i think is going on for me is in line with what is being said in the documentation: 
```
When Vim starts, the 'compatible' option is on.  This will be used when Vim
starts its initializations.  But as soon as:
- a user vimrc file is found, or
...
then the option will be set to 'nocompatible'.

Note that this does NOT happen when a system-wide vimrc file was found.
```
when i tried to illustrate the problem with colors, i created a custom .vimrc in a test directory while the global .vimrc was still in my HOME.  Thus, unless i explicitely set nocompatible, vim assumes "compatible" to be default.  Or am I misreading it?

**Comment by ambushed** [comment]
However, when I do :PlugInstall and then close the split, the lightline springs back to life showing correct colors.

**Comment by itchyny** [comment]
So you mean it works normal without doing :PlugInstall (that's not mentioned in the first comment)? I'm not an expert of vim-plug but it might reset all the colors after this command or resourcing vimrc. I suggest restarting Vim after installing the plugins and .

**Comment by itchyny** [comment]
Oops, it seems that I misunderstood but... anyway, there’s nothing to do that I can fix in the plugin. I would help if you could explain in more details, some screenshots, precise steps, &rtp, or Dockerfile.

**Comment by ambushed** [comment]
Let me get something ready, thanks!

**Comment by ambushed** [comment]
Thanks for the idea of reproducing the issue in a docker container.  I couldn't!  I guess it must be something really messed up in my config.  Sorry for confusion.
