### ISSUE TITLE
What I should do to change lightline's theme when changing different colorschemes?

### ISSUE THREAD

**Issue by dalu98** [itchyny/lightline.vim#473]
This is my current lightline's config
```vim
let g:lightline = {
            \ 'active': {
            \   'left': [[ 'mode', 'paste' ], [ 'cocstatus', 'readonly', 'filename', 'git' ]]
            \ },
            \ 'component_function': {
            \   'cocstatus': 'coc#status',
            \   'filename': 'LightlineFilename',
            \   'git': 'FugitiveHead',
            \ },
            \ }

if colors_name ==# 'gruvbox'
    let g:lightline = {
                \ 'colorscheme': 'gruvbox',
                \ }
    autocmd OptionSet background
                \ execute 'source' globpath(&rtp, 'autoload/lightline/colorscheme/gruvbox.vim')
                \ | call lightline#colorscheme() | call lightline#update()
else        
    let g:lightline = {
                \ 'colorscheme': 'minimal',
                \ }
endif
```
This config is behind setting `colorscheme`, and the `minimal` is a lightline's theme for my own use. By the way, I'm putting `minimal` in `~/.vim/pack/self/start/colorscheme/autoload/lightline/colorscheme`, is there some more convient place I can put?

I want to make `if-else-endif` judge which lightline's theme I should use. But thing doesn't goes as I thought. I met with two problems:

1.
- When I am using `colorscheme gruvbox` when starting vim
the lightline's theme can be toggled correctly when I toggled the background. But errors will happen when I try to change the `colorscheme`
```
Error detected while processing function lightline#colorscheme[18]..lightline#highlight:
line   18:
E254: Cannot allocate color guibg=
E421: Color name or number not recognized: ctermfg= ctermbg= term=bold cterm=bold gui=bold
```
Could this be my own colorscheme's problem?

- When I am not using `colorscheme gruvbox` when starting vim
The lightline's theme can't change to `gruvbox` and keeps `minimal`.

2. 
the `component_function` not work. Does the `if-else-endif` overwrite the first `g:lightline`, and the lightline keeps default except the `colorscheme`?

Thanks!

**Comment by dalu98** [comment]
And do you know which value I should set to `{mode}.middle` to make it equal to default statusline? The default statusline's background can be changed according to the colorscheme. If I'm using a light theme, the lightline's background can be changed with the colorscheme, so I set it to `NONE` currently. Is there a more convenient way?

**Comment by dalu98** [comment]
> @dalu98 have you checked `:h lightline-problem-13`?
@CarbonChauvinist yes. 

It can change lightline's colorscheme according to vim's colorscheme. But I want to change the lightline's colorscheme with the background change also.

```
autocmd OptionSet background
        \ execute 'source' globpath(&rtp, 'autoload/lightline/colorscheme/gruvbox.vim')
              \ | call lightline#colorscheme() | call lightline#update()
```
Use this only can change relative colorschemes. So I wonder whether there are some more convient ways.

**Comment by itchyny** [comment]
- When you `let g:lightline = { ... }`, it overwrites the entire dictionary (like as JavaScript). Consider `let g:lightline.colorscheme = '...'`.
- Use `ColorScheme` event to detect the change of the colorscheme. And when you want to change the colorscheme on the fly, you have to `call lightline#init()`, `call lightline#colorscheme()` and `call lightline#update()`.
- The `Cannot allocate color guibg=` error is caused by the `minimal` colorscheme problem which I can't find the source.

**Comment by dalu98** [comment]
>     * When you `let g:lightline = { ... }`, it overwrites the entire dictionary (like as JavaScript). Consider `let g:lightline.colorscheme = '...'`.

Thanks for answering

>     * Use `ColorScheme` event to detect the change of the colorscheme. And when you want to change the colorscheme on the fly, you have to `call lightline#init()`, `call lightline#colorscheme()` and `call lightline#update()`.

I got it. So if I want to set my `minimal` colorscheme to the default lightline's colorscheme, I need to write as this?
```vim
function! s:lightline_update()
    if !exists('g:loaded_lightline')
        return
    endif
    try
        if g:colors_name =~? 'wombat\|solarized\|jellybeans\|landscape\|seoul256\|Tomorrow\|gruvbox'
            let g:lightline.colorscheme =
                        \ substitute(substitute(g:colors_name, '-', '_', 'g'), '256.*', '', '')
            call lightline#init()
            call lightline#colorscheme()
            call lightline#update()
        else
            let g:lightline.colorscheme = 'minimal'
            call lightline#init()
            call lightline#colorscheme()
            call lightline#update()
        endif
    catch
    endtry
endfunction
```
 
>     * The `Cannot allocate color guibg=` error is caused by the `minimal` colorscheme problem which I can't find the source.

OK, I will find the reason.

**Comment by itchyny** [comment]
> So if I want to set my minimal colorscheme to the default lightline's colorscheme, I need to write as this?

It depends. If you want to switch between `gruvbox` and `minimal`,

```vim
let g:lightline.colorscheme = g:colors_name ==# 'gruvbox' ? 'grubox' : 'minimal'
call lightline#init()
call lightline#colorscheme()
call lightline#update()
```

**Comment by dalu98** [comment]
I see...

Thanks for your patience!
