### ISSUE TITLE
Color scheming for 16-bit ANSI schemes

### ISSUE THREAD

**Issue by jackno** [itchyny/lightline.vim#475]
I'm trying to port [`vim-dim`](https://github.com/jeffkreeftmeijer/vim-dim) to the colorschemes in lightline, but it looks like all the color schemes  in this repo are using hex codes. I'm not exactly sure how to create a new scheme using ANSI colors.

Any pointers would be helpful. Thanks.

**Comment by itchyny** [comment]
Please refer to [16color.vim](https://github.com/itchyny/lightline.vim/blob/master/autoload/lightline/colorscheme/16color.vim), which uses the 16 colors. The hex codes are required for GVim users.

**Comment by itchyny** [comment]
If you have configured the terminal color pallets, using `16color` for lightline colorscheme will work.
