### ISSUE TITLE
Set custom text color

### ISSUE THREAD

**Issue by Shatur95** [itchyny/lightline.vim#476]
Is it possible to set a specific text color for a specific text?
I using [Asyncrun](https://github.com/skywind3000/asyncrun.vim) and displaying last run status in lightline. But I would like to display `success` in green color and `failed` in red. Is it possible to achieve?

**Comment by itchyny** [comment]
This is not impossible in lightline.vim.

**Comment by itchyny** [comment]
Sorry, this is impossible in lightline.vim.

**Comment by Shatur95** [comment]
Bad to hear, but thanks for the answer!
