### ISSUE TITLE
Unable to install the 'one dark' theme

### ISSUE THREAD

**Issue by Joe23232** [itchyny/lightline.vim#477]
So in my code

```
let g:lightline {
/ 'colorscheme':'one dark'
/ }
```
Its unable to find this theme but it can find other themes without a space between the two words. I am not too sure why this is happening, how do I fix this, is there another name for this?

**Comment by itchyny** [comment]
Just use `one`. When `&background` is dark, it switches to the dark theme of one.

**Comment by Joe23232** [comment]
Thanks for that.

![image](https://user-images.githubusercontent.com/34926497/85136060-677d9f00-b282-11ea-9236-d5267d8be248.png)

It seems to work but why does it look different on my terminal? Is it cause of the terminal's configuration that has the ability to override the colors set or something?

**Comment by itchyny** [comment]
The screen shot is taken with GUI version (16777216 colors). We can't emulate the appearance using 256 colors.

**Comment by Joe23232** [comment]
@itchyny Ah I see, so I guess I can still edit one dark theme then?

**Comment by itchyny** [comment]
```vim
autocmd VimEnter * call s:setLightlineColors()

function s:setupLightlineColors() abort
  let l:pallete = lightline#palette()
  let l:pallete.normal.middle = [[ something ]]
  call lightline#colorscheme()
endfunction
```

**Comment by Joe23232** [comment]
@itchyny THanks then.
