### ISSUE TITLE
Solarized Dark theme is missing?

### ISSUE THREAD

**Issue by lkadalski** [itchyny/lightline.vim#481]
Hello, outstanding plugin !
I'm just trying to set solarized dark theme and I think that is missing actually. There is no configuration for `solarized dark` only for `solarized` which is light theme. Am I wrong?
Thanks in advance!

**Comment by itchyny** [comment]
When `set background=dark`, it selects the dark variant.

**Comment by lkadalski** [comment]
Thanks! :+1:
