### ISSUE TITLE
Vim crashed with lightline if a file in another tabpage is modified by external command 

### ISSUE THREAD

**Issue by skywind3000** [itchyny/lightline.vim#482]
## Environment

- Vim: GVim 8.2.1114
- OS: Windows 10
- Plugins: only `lightline` is enabled (all the others has been disabled to verify this).

## Reproduce

1. pre-create `1.txt` and `2.txt` with some random lines:

```bash
echo 12345 > d:\1.txt
echo 67890 > d:\2.txt
```

2. open them in two tabpages with GVim:

```
:tabe d:/1.txt
:tabe d:/2.txt
```

Now current tabpage is `2.txt`, previous tabpage is `1.txt`.

3. modify the file in the previous tabpage from external command:

```
:!echo 6666 >> d:/1.txt
```

(using another cmd.exe window to type this command equals to this).

4. reload `1.txt`:

![图片](https://user-images.githubusercontent.com/3035071/86893798-c2454080-c134-11ea-98e4-a855d78b96ca.png)

Press "Load File"

## Crash

And GVim becomes unresponsive for a few seconds

![图片](https://user-images.githubusercontent.com/3035071/86894011-06d0dc00-c135-11ea-8111-934b931343b7.png)

Then it crashed without any message.

## Summary

This often happens after a `git pull` if you have a lot files open in different tabpages. 

I have temporarily switch to airline, because it works well with multiple tabpages (vim never crash with airline).

**Comment by itchyny** [comment]
Is this reproducible with `let g:lightline = { 'enable': { 'tabline': 0 } }` or `let g:lightline = { 'enable': { 'statusline': 0 } }` ?

**Comment by skywind3000** [comment]
Yes, my configuration is:

```VimL
let g:lightline.enable = {'statusline':1, 'tabline':0}
```

My entire lightline setup is [here](https://github.com/skywind3000/vim/blob/master/site/bundle/lightline.vim)

I am using native vim gui tabline:

![图片](https://user-images.githubusercontent.com/3035071/86896069-01c15c00-c138-11ea-9200-9e15ac9e5c47.png)

So I never used the `tabline` feature in lightline.

**Comment by skywind3000** [comment]
FYI,

- `let g:lightline = { 'enable': { 'tabline': 0 } }` : reproducible  !!
- `let g:lightline = { 'enable': { 'statusline': 0 } }`: unreproducible

**Comment by itchyny** [comment]
Can you debug the trace or some system log? I don't have Windows environment and for now I can only say that crash caused by pure Vim script is a bug of Vim, unlikely due to the bug in this plugin.

**Comment by skywind3000** [comment]
Sorry, I don't know how to strace GVim on windows, and there isn't any core file after crash.

**Comment by itchyny** [comment]
Disabling tabline feature causes the tabline problem, that's very wired. Are you testing with lightline only, right? `let g:airline#extensions#tabline#enabled = 0` doesn't fix the problem?

**Comment by skywind3000** [comment]
I am testing with lightline only , other plugins have been completed disabled.

    let g:airline#extensions#tabline#enabled = 0

This doesn't help.

**Comment by itchyny** [comment]
Just curious, what does `:echo &tabline` print in GVim?

**Comment by skywind3000** [comment]
That's my own customized function:

![图片](https://user-images.githubusercontent.com/3035071/86901257-f32a7300-c13e-11ea-9c7e-a73a6d5e26d9.png)

It will not work in GVim because `guitablable` is enabled and overshadow `tabline` in GVim.

btw: why did you say it is a "tabline problem" ?? is it possible that statusline caused the problem ??

for example, 1.txt is reloaded in the previous tabpage which will trigger a autocmd, in which lightline will try to update something in 1.txt's buffer or its statusline, which is definitely not existing in the current tabpage, and that leads to the crash ??

**Comment by itchyny** [comment]
Let me confirm, `let g:lightline.enable = {'statusline':0, 'tabline':0}` stops the issue, right?

**Comment by skywind3000** [comment]
exactly, `let g:lightline.enable = {'statusline':0, 'tabline':0}` stops the issue.

**Comment by itchyny** [comment]
How about `augroup lightline | autocmd! FileChangedShellPost | augroup END` ?

**Comment by skywind3000** [comment]
That will not clear FileChangedShellPost in `lightline` augroup, I redefined the `lightline` augroup in a separate script and source it manually after starting vim:

- original `eventmap.vim` (copied from `plugin/lightline.vim`):

```VimL
augroup lightline
  autocmd!
  autocmd WinEnter,BufEnter,BufDelete,SessionLoadPost,FileChangedShellPost * call lightline#update()
augroup END
```

problem is still reproducible.

- remove `FileChangedShellPost`:

```VimL
augroup lightline
  autocmd!
  autocmd WinEnter,BufEnter,BufDelete,SessionLoadPost * call lightline#update()
augroup END
```

problem is still reproducible.

- remove `SessionLoadPost`:

```VimL
augroup lightline
  autocmd!
  autocmd WinEnter,BufEnter,BufDelete,FileChangedShellPost * call lightline#update()
augroup END
```

UNREPRODUCIBLE !!

**Comment by skywind3000** [comment]
in addition, when I leave only `SessionLoadPost` in the lightline augroup:

```VimL
augroup lightline
  autocmd!
  autocmd SessionLoadPost * call lightline#update()
augroup END
```

The problem is still reproducible, it appears that `SessionLoadPost` caused the issue.

**Comment by skywind3000** [comment]
![图片](https://user-images.githubusercontent.com/3035071/86906293-eb220180-c145-11ea-9185-114ff35dbdcc.png)

`SessionLoadPost` has been called 4-times when `1.txt` is modified:

![图片](https://user-images.githubusercontent.com/3035071/86906316-f5dc9680-c145-11ea-8d59-cdaa58d42604.png)

**Comment by skywind3000** [comment]
But airline is listening on SessionLoadPost too, and it will not crash:

![图片](https://user-images.githubusercontent.com/3035071/86907222-4c96a000-c147-11ea-9f87-9b4728922db7.png)

**Comment by skywind3000** [comment]
And I found a temporary work-around:

```VimL
function! s:override_event()
	augroup lightline
		autocmd!
		autocmd WinEnter,BufEnter,BufDelete,FileChangedShellPost * call lightline#update()
	augroup END
endfunc

autocmd! VimEnter * call s:override_event()
```

**Comment by itchyny** [comment]
Please check the following script causes the crash.
```vim
autocmd SessionLoadPost * F()
function! F()
  if win_gettype() ==# 'autocmd'
    return
  endif
  for n in range(1, winnr('$'))
    call setwinvar(n, '&statusline', 'X')
  endfor
endfunction
```

**Comment by skywind3000** [comment]
The script will not crash.

**Comment by itchyny** [comment]
Oops, `call F()` is correct.

**Comment by skywind3000** [comment]
I corrected `F()` to `call F()`, both of them can't cause the crash.

**Comment by itchyny** [comment]
In any case there's nothing to take action in this plugin. When Vim script can crash the editor, that's a bug of the editor. If you can create a minimal reproduction, you can report to the Vim dev.

**Comment by skywind3000** [comment]
Certainly, vim is accountable for this. But most of time, plugins can avoid such things by scripting in the right way, for example, prevent accessing window/buffer local variables which don't exist in the current tabpage.

I am not familiar with the lightline codebase, so impossible to minimal the issue without your help.
