### ISSUE TITLE
Lightline remains greyed out when switching buffers

### ISSUE THREAD

**Issue by francescoboc** [itchyny/lightline.vim#484]
When I switch between buffers, lightline remains greyed out, like if the window was not focused.
Gif for clarification:
![ezgif-1-0e62b6e914e9](https://user-images.githubusercontent.com/33369475/87060496-e5422400-c20a-11ea-82fa-9ba7025401df.gif)
As you can see, when I switch back to the buffer "analyse_pi_T.py", lightline remains grey.

I tried to disable lightline, and the problem disappears (the default vim line gets highlighted correctly), and I also tried with airline, and the problem is not there.

Finally, I tried to disable all the other plugins I am using, except for lightline, but the problem persists! (So it's not a conflict-related issue, I guess...). AND I tried to run vim outside tmux, just in a plain terminal, and this did not solve the issue... I am running out of ideas!

**Comment by francescoboc** [comment]
Ok, I think I spotted which one is the line in my .vimrc that is causing the issue:
```
" Save folds and cursor position when leaving buffer, reload them when re-entering                                                                                                                              
set viewoptions=folds,cursor                                                                                                                                                                                 
autocmd BufWinLeave *.* mkview                                                                                                                                                                               
autocmd BufWinEnter *.* silent loadview 
```
And in particular, is the last line (the one with `BufWinEnter`). If I comment it out, that the problem disappears.
Is there any way to fix the problem without having to comment out that line (I like that a lot!). Thanks!

**Comment by itchyny** [comment]
This looks like the nested event problem so try adding `++nested` attribute (see `:h autocmd-nested`). If it doesn't solve, try `loadview | call lightline#update()`.

**Comment by francescoboc** [comment]
Hello and thanks for your quick answer!
I tried straight away your second solution and it fixed the issue. :)
