### ISSUE TITLE
Neovim tabline crash on resize

### ISSUE THREAD

**Issue by antoinemadec** [itchyny/lightline.vim#486]
## Env
  - Neovim: compiled from source to latest version (NVIM v0.5.0-593-g1ca67a73c)
  - OS: Debian testing up to date
  - lightline.vim: up to date

## How to Reproduce
  1. ```nvim -u vimrc -p vimrc vimrc```
  2. resize window
  3. neovim crashes with this error message: ```double free or corruption (!prev)```

where **vimrc** is: 
```vim
call plug#begin('~/.vim/plugins')
Plug 'itchyny/lightline.vim'
call plug#end()

let g:lightline = {
  \ 'tab' : {
  \   'active': [ 'mytabname' ],
  \   'inactive': [ 'mytabname' ]
  \ },
  \ 'tab_component_function' : {
  \   'mytabname': 'MyTabname'
  \ },
  \ 'separator': { 'left': '', 'right': '' },
  \ 'subseparator': { 'left': '', 'right': '' },
  \ }

function! MyTabname(n)
  return ""
endfunction
```

## Observations
  - this is a **neovim** bug, as **vim** works OK
  - this bug only happens when we have an **empty tab name** and **exotic seprators**

## Question
Do you know which section in **lightline.vim** code triggers this bug?
I tried to create a minimal testcase to open an issue in Neovim unsuccessfully.

Thanks in advance and thanks for the great plugin!
Antoine

**Comment by itchyny** [comment]
I’m not sure. I recommend you to debug with gdb.

**Comment by antoinemadec** [comment]
@itchyny , got it.
I was just wondering if we could have come with a minimal ```tabline``` to reproduce this error, preferably without invoking **lightline**.

FYI, I created a bug on **neovim**: https://github.com/neovim/neovim/issues/12644

**Comment by itchyny** [comment]
No action in this plugin, closing.
