### ISSUE TITLE
Lightline will not load

### ISSUE THREAD

**Issue by DanielBarton446** [itchyny/lightline.vim#487]
I am running into what is most likely a configuration problem.
I am using "set statusline=2"

The problem I am running into is that Lightline will not be open on the file I edit until I re-edit it. Specifically I do this by 
":e" on the current vim file.

Note: I am using gruvbox as my general colorscheme and I have noticed this particular issue not being directly tied to this.

My vimrc is a little messy as I am still pretty new to vim and plugins, but here is what it is as follows:
```
set statusline=2
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" " alternatively, pass a path where Vundle should install plugins
" "call vundle#begin('~/some/path/here')
"
" " let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'scrooloose/nerdtree'
Plugin 'morhetz/gruvbox'
Plugin 'itchyny/lightline.vim'

"" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

:command RunPy !/mnt/c/Python3.7/python.exe '%:p'

" Open nerdtree on vim startup
autocmd vimenter * NERDTree
" Set to right side position
let g:NERDTreeWinPos = "right"
" Unfocus nerdtree
autocmd vimenter * wincmd p 
set mouse=a
set number
set relativenumber
set background=dark
" Makes movement between splits easier
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
" Makes nice closing braces
inoremap " ""<left>
inoremap ' ''<left>
inoremap ( ()<left>
inoremap [ []<left>
inoremap { {}<left>
inoremap {<CR> {<CR>}<ESC>O
inoremap {;<CR> {<CR>};<ESC>O
" Set tab size
:set tabstop=4
:set shiftwidth=4
:set expandtab
highlight ColorColumn ctermbg=DarkGray guibg=lightgray
set colorcolumn=80
syntax on
" Start Lightline status bar
let g:lightline = {}
let g:lightline.colorscheme='powerline'
"gruvbox color scheme config
let g:gruvbox_contrast_dark = 'hard'
:colorscheme gruvbox
```

**Comment by itchyny** [comment]
`set laststatus=2` is correct instead of `set statusline=2`.

**Comment by DanielBarton446** [comment]
> `set laststatus=2` is correct instead of `set statusline=2`.

Upon fixing that mistake I still am running into the same issue -- here is some visuals to help out
Before using ":e"
![image](https://user-images.githubusercontent.com/47621061/87836553-0c75a280-c856-11ea-921c-049b60556929.png)
After using ":e"
![image](https://user-images.githubusercontent.com/47621061/87836586-23b49000-c856-11ea-97e0-6ffe1d7668bf.png)


I tried to bodge it together in a way earlier by having vim run  the command ":e" after any time I open a file but was unsuccessful at this.

**Comment by yhu266** [comment]
Could you remove the line "autocmd vimenter * NERDTree" and see if it'll fix the issue?

**Comment by DanielBarton446** [comment]
AH -- I see -- this was something I thought might be the case. It appears to me that upon "autocmd vimenter * NERDTree" it loads the lightline information on the NERDTree split*(I think its technically a split) before the current file split. 

Is there anything you would suggest doing to allow for me to continue haveing "autocmd vimenter * NERDTree" while having lightline be based on the current file that I am editing?

**Comment by itchyny** [comment]
Try `autocmd VimEnter * ++nested NERDTree` .

**Comment by yhu266** [comment]
Could you try with:
```vim
augroup NERD
     au!
     autocmd VimEnter * NERDTree
     autocmd VimEnter * wincmd p
     autocmd VimEnter * call lightline#update()
augroup END
```

**Comment by DanielBarton446** [comment]
yhu266's response worked for me whereas itchyny's response did not for those who might be in a similar situation as I am. Make sure to recall his statement of potential performance issue.

**Comment by 3301n** [comment]
> Try `autocmd VimEnter * ++nested NERDTree` .

It really worked for me . For those who want the cursor in the other window rather than on the nerdtree try this 
`autocmd VimEnter * ++nested NERDTree | wincmd p`
I think this command will not affect performace rather than the other command suggested by yhu266
