### ISSUE TITLE
lightline.vim: Could not load colorscheme nord

### ISSUE THREAD

**Issue by pbartyik** [itchyny/lightline.vim#488]
```vim
let g:lightline = {
        \ 'colorscheme': 'nord',
        \ 'active': {
        \       'left': [ [ 'mode', 'paste' ],
        \                 [ 'readonly', 'filename', 'modified' ] ],
        \       'right': [ [ 'lineinfo','filetype' ] ]
        \ },
        \ 'inactive': {
        \       'right': [ [ 'lineinfo','filetype' ] ]
        \ },
        \ }
```

Yields error `lightline.vim: Could not load colorscheme nord`

**Comment by yhu266** [comment]
I wasn't able to reproduce this error.

Could you remove your `lightline.vim` plugin and reinstall it, and see if it'll fix it?

**Comment by pbartyik** [comment]
Removed it, reloaded nvim, added again, same error.
`~/.config/nvim/plugged/lightline.vim/autoload/lightline/colorscheme/nord.vim` is present

**Comment by yhu266** [comment]
Could you shared the part of your `init.vim` where the plugins are loaded? It's possible that some plugin manager does not load `nord.vim` correctly.

**Comment by pbartyik** [comment]
sure, here you go.

```vim
call plug#begin()
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'scrooloose/nerdtree'
Plug 'NLKNguyen/papercolor-theme'
Plug 'rust-lang/rust.vim'
Plug 'JamshedVesuna/vim-markdown-preview'
Plug 'tpope/vim-fugitive'
Plug 'rhysd/rust-doc.vim'
Plug 'Chiel92/vim-autoformat'
Plug 'ervandew/supertab'


Plug 'cespare/vim-toml'
Plug 'stephpy/vim-yaml'

" Theme
" use with ':colors nord'
Plug 'arcticicestudio/nord-vim'

" GUI stuff
Plug 'itchyny/lightline.vim'
Plug 'andymass/vim-matchup'

" tmux integration
Plug 'christoomey/vim-tmux-navigator'

" Fuzzy finder
Plug 'airblade/vim-rooter'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

"Plug 'ayu-theme/ayu-vim'
"Plug 'neoclide/coc.nvim', {'branch': 'release'}
if has('nvim')
        Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
        Plug 'Shougo/deoplete.nvim'
        "  Plug 'roxma/nvim-yarp'
        "  Plug 'roxma/vim-hug-neovim-rpc'
endif
Plug 'neovim/nvim-lsp'
Plug 'Shougo/deoplete-lsp'

call plug#end()

**Comment by pbartyik** [comment]
Commenting out `Plug 'articicestudio/nord-vim' resolves this. Conflicting names?

**Comment by yhu266** [comment]
Yes I got the same results. It's possible that the file `autoload/lightline/colorscheme/nord.vim` in `nord-vim` causes some strange issue.

**Comment by yhu266** [comment]
Could you remove it and see if it'll fix it?

**Comment by yhu266** [comment]
BTW, I tested with `vim` instead of `nvim` and there was no conflict. So it may be a `neovim` issue.

**Comment by pbartyik** [comment]
I did, commenting out `nord-vim` resolves this. I don't need `nord-vim`, was just a testing thing. Strange, as it should be possible to use nord syntaxt higlights with nord airline. Thanks for the help :)
