### ISSUE TITLE
Lightline theme doesn't load on startup

### ISSUE THREAD

**Issue by Shrimpram** [itchyny/lightline.vim#490]
I want to use Lightline with the wombat theme but the theme doesn't load on vim startup. I have to source my vimrc for the theme to load, otherwise it uses Lightline default theme. To be clear, Lightline itself still works on startup, but it only loads the default theme, _not_ the wombat theme.
Photo of what I mean:
![image](https://user-images.githubusercontent.com/67710369/88101420-cd479a00-cb52-11ea-9aa3-8acc901b6b53.png)
### ^^ gVim on startup
![image](https://user-images.githubusercontent.com/67710369/88101473-e2bcc400-cb52-11ea-8f89-75b4828430a5.png)
### My setup:
Windows 10 64 bit 
Vim 8.2 

### My vimrc:
```vim
set clipboard=unnamed	" vim uses windows clipboard

set backspace=indent,eol,start	" backspace works in insert mode

set spelllang=en_us	" adds english spellcheck

set number	" adds number lines

set noshowmode	" disables the --INSERT-- display since I use lightline

syntax on	" enables syntax highlighting 

set guifont=JetBrains_Mono:h12	" JetBrains Mono font with 12 height 

set pythonthreehome=C:\Python36-32\
set pythonthreedll=C:\Python36-32\python36.dll

" Makes j and k move using visual lines
nnoremap <expr> j v:count ? 'j' : 'gj'
nnoremap <expr> k v:count ? 'k' : 'gk'



" vim 8 native package manager
packloadall

" Lightline
set laststatus=2

let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ }



" gruvbox load

" dark mode
set bg=dark
" soft contrast
let g:gruvbox_contrast_dark = 'hard'
" comments are not italicized
let g:gruvbox_italicize_comments = '0'

autocmd vimenter * colorscheme gruvbox


" Writemode for writing prose
" Followed this reddit thread https://www.reddit.com/r/vim/comments/ckyspu/heres_how_to_create_custom_workspaces_to_switch/

:command Writemode setlocal spell | Goyo 120 | set showmode

:command Codemode set nospell | Goyo! | set noshowmode
```

Sorry if this is a basic question, I'm completely new to vim. Thanks :)

**Comment by yhu266** [comment]
It's probably the same `VimEnter` issue. See #487 for a temporary fix.

**Comment by yhu266** [comment]
Also, maybe it's better to set up colorscheme without the `VimEnter` command:

```vim
colorscheme gruvbox
```

**Comment by Shrimpram** [comment]
> Also, maybe it's better to set up colorscheme without the `VimEnter` command:
> 
> ```viml
> colorscheme gruvbox
> ```

That did the trick. I replaced the `autocmd VimEnter` with just `colorscheme gruvbox`

Now Lightline and gruvbox load at startup. Thanks so much :)
