### ISSUE TITLE
Second row / line break

### ISSUE THREAD

**Issue by scrouthtv** [itchyny/lightline.vim#491]
Hello,

I want to display a second line below lightline in my vim to display some tooltips to remember commands and keyboard shortcuts I only use rarely.

I tried to add a line break to my lightline:
```
let g:lightline = {
			\ 'colorscheme': 'solarized',
			\ 'active': {
			\   'left': [ [ 'mode', 'paste' ],
			\             [ 'readonly', 'filename', 'modified' ] ],
			\		'right': [ [ 'lineinfo', 'percent' ],
			\              [ 'fileformat', 'fileencoding', 'filetype', 'helloworld' ] ]
			\ },
			\ 'component': {
			\		'helloworld': '\nasdf'
			\ }
```

Which resulted in the `\n` being simply printed out. 

Is there any other way how I could accomplish this?
Thanks for any help in advance

**Comment by yhu266** [comment]
`lightline` sets statusline in vim. However, https://stackoverflow.com/questions/7986884/can-i-have-multiline-statusline-in-vim

So I guess it's better to display tooltips without newlines.

**Comment by itchyny** [comment]
We can't do this due to the limitation of Vim; statusline is one line.
