### ISSUE TITLE
"source init.vim" messes up lightline in neovim

### ISSUE THREAD

**Issue by j0ker70** [itchyny/lightline.vim#492]
Lightline works completely fine when I open any file. But whenever I source my init.vim file, lightline loses all its colors. This is when I open a file. 
![Screenshot from 2020-07-31 19-07-34](https://user-images.githubusercontent.com/28401403/89038261-d4945200-d361-11ea-9833-ef673fe12114.png)

And after sourcing init.vim file it looks like this.
![Screenshot from 2020-07-31 19-13-34](https://user-images.githubusercontent.com/28401403/89038316-f097f380-d361-11ea-8635-57176207991c.png)

This is my [init.vim](https://paste.ubuntu.com/p/TSkStZC2CR/) file.

**Comment by itchyny** [comment]
Please paste your entire configuration or link to init.vim.

**Comment by j0ker70** [comment]
> Please paste your entire configuration or link to init.vim.

I have edited it.

**Comment by itchyny** [comment]
Removing L110-L119 will fix the issue.

**Comment by j0ker70** [comment]
> Removing L110-L119 will fix the issue.

It's still not working. This is the modified [init.vim](https://paste.ubuntu.com/p/P6bH9GR5c2/)

**Comment by j0ker70** [comment]
And I have noticed that this problem only occurs when I am in editing the init.vim file. On every other files, it works now.

**Comment by yhu266** [comment]
Could you try with a new init.vim file that only sets up lightline, without other plugins and configurations?

Also, I do experience this exact "sourcing init.vim, losing color" issue, bur I suspect it's a bug in vim-plug.

**Comment by j0ker70** [comment]
That wouldn't solve the issue I think. I have noticed another thing. If I remove the first line of my init.vim file and then manually sourcing the init.vim file via command mode, that doesn't create any issue. So the problem seems to be in the first line only.

**Comment by itchyny** [comment]
Use nested attribute. `autocmd! BufWritePost init.vim ++nested source %`

**Comment by j0ker70** [comment]
That worked. I don't know about that attribute. Can you please share what that attribute does?

**Comment by itchyny** [comment]
With the nested attribute the event fires autocmd events recursively. Please refer to `:h autocmd-nested` for details.
