### ISSUE TITLE
filename is not getting modified but lightline#tab#filename returns it

### ISSUE THREAD

**Issue by Avishayy** [itchyny/lightline.vim#494]
Hey, I'm having a really weird issue. I can't configure the filename (trying to make it print `w:quickfix_title` instead of `Location List`), but it seems like my custom function is never called. Here's my configration:
```
" Statusline
let g:lightline = { 
    \ 'active': {
    \   'left': [ [ 'mode', 'paste' ],
    \             [ 'readonly', 'filename' ] ],
    \ },
    \ 'tab_component_function': {
    \     'filename': 'LightlineTabFilename'
    \ },
    \ 'colorscheme': 'base16'
\ }

function! LightlineTabFilename(n)
    return "AAA"
endfunction

```
The `"AAA"` string just never gets placed in the filename column and I tried everything. I even went as far as editing the function in `lightline/tab.vim`, as such:
```
function! lightline#tab#filename(n) abort
  return '[RANDOM NAME]'
endfunction
```

But the name never changes.

However, if I call the function `:echo lightline#tab#filename(0)`, `[RANDOM NAME]` gets printed as expected, but the status line still uses the original name (such as `[No Name]` or the actual file name).

I'm using neovim 0.4.3

Any help is appreciated, thank you.

**Comment by yhu266** [comment]
I think you are supposed to use `component_function` instead of `tab_component_function`.

**Comment by Avishayy** [comment]
@yhu266 It seems like this does work, though all examples I've seen so far use `tab_component_function` (#297 for example).

```VimL
" Statusline
let g:lightline = { 
    \ 'active': {
    \   'left': [ [ 'mode', 'paste' ],
    \             [ 'readonly', 'filename' ] ],
    \ },
    \ 'component_function': {
    \     'filename': 'LightlineTabFilename'
    \ },
    \ 'colorscheme': 'base16'
\ }

function! LightlineTabFilename()
    if &buftype ==# 'quickfix'
        return w:quickfix_title
    endif
    return expand('%:t')
endfunction
```

Though I am not sure if this is the idiomatic way. I want to be selective only for quickfix windows and let the default run if that's not the case, I don't see a way to call the default function if I'm using `component_function`.

And I still don't understand why `[No Name]` gets displayed after I overwrote `lightline#tab#filename`, where does this string come from? I couldn't find more occurrences in lightline.

**Comment by Avishayy** [comment]
Oh, it seems like I completely misunderstood the purpose of the tab components, my bad. I understand now that it affects the tab name. Whoops.

Sorry for the spam :)

**Comment by Avishayy** [comment]
Just documenting in case anyone wants to see what I ended up using:
```VimL
" Statusline
let g:lightline = { 
    \ 'active': {
    \   'left': [ [ 'mode', 'paste' ],
    \             [ 'readonly', 'filename' ] ],
    \ },
    \ 'component_function': {
    \     'filename': 'LightlineTabFilename'
    \ },
    \ 'colorscheme': 'base16'
\ }

function! LightlineTabFilename()
    if &buftype ==# 'quickfix'
        return w:quickfix_title
    endif
    
    let filename = expand('%:t')
    return !empty(filename) ? filename : "[No Name]"
endfunction
```

I guess `[No Name]` comes from `statusline`'s `%t` flag, but I couldn't find a way to make the substitution happen inside the function so I ended up checking if the name is empty, and returning instead `[No Name]`.
