### ISSUE TITLE
Latency in switching from Insert to Normal mode.

### ISSUE THREAD

**Issue by hakanohi** [itchyny/lightline.vim#499]
Lightline takes a while to switch to normal on pressing Esc. 

![latency](https://user-images.githubusercontent.com/51394064/90787954-feb7af00-e324-11ea-81ee-08748d99bf97.gif)

**Comment by itchyny** [comment]
This is not a problem of lightline, looks like the timeout configuration. Please try `set ttimeout ttimeoutlen=50`.
