### ISSUE TITLE
Lightline in normal mode doesn't show colors. (again)

### ISSUE THREAD

**Issue by SmashMineGame** [itchyny/lightline.vim#502]
I switched it to the onedark color scheme and it's doing the same issue again.
my new .vimrc
```
set nocompatible              " be iMproved, required
filetype off                  " required
set number
syntax on
set tabstop=4
set shiftwidth=4
set backspace=indent,eol,start

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

Plugin 'preservim/nerdtree'
let NERDTreeAutoDeleteBuffer = 1
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

Plugin 'joshdick/onedark.vim'

Plugin 'itchyny/lightline.vim'
let g:lightline = {'colorscheme': 'onedark'}
if !has('gui_running')
  set t_Co=256
endif
set noshowmode
set laststatus=2

" Plugin 'ycm-core/YouCompleteMe'
Plugin 'SirVer/ultisnips'
let g:UltiSnipsSnippetDirectories=["mycoolsnippets"]

" Snippets are separated from the engine. Add this if you want them:
Plugin 'epilande/vim-react-snippets'

" Trigger configuration.
let g:UltiSnipsExpandTrigger="<C-l>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" Put your non-Plugin stuff after this line

autocmd VimEnter * :colorscheme onedark
```
Images of it working in insert mode and not in normal.
![Screen Shot 2020-08-28 at 12 30 11 AM](https://user-images.githubusercontent.com/32280917/91533989-a9037980-e8c5-11ea-9154-f5ddb7f18977.png)
![Screen Shot 2020-08-28 at 12 30 04 AM](https://user-images.githubusercontent.com/32280917/91533998-abfe6a00-e8c5-11ea-8145-e86c0da3e7e3.png)

**Comment by itchyny** [comment]
Change the last line `autocmd VimEnter * :colorscheme onedark`  to `colorscheme onedark`, as I said at https://github.com/itchyny/lightline.vim/issues/501#issuecomment-682365590.

**Comment by mcthomas** [comment]
If you want to retain your autocmds to set filetype-specific color schemes, as I have, a workaround is to append the following to your .vimrc:
```
autocmd BufReadPre,FileReadPre * :call lightline#toggle()
autocmd BufReadPre,FileReadPre * :call lightline#toggle() 
```
By toggling Lightline off and back on, you should be able to avoid having your Lightline colors (mainly in normal mode) cleared as a result of opening a new file buffer (having a different color scheme) with Vim already previously opened.
