### ISSUE TITLE
Status bar is not showing up

### ISSUE THREAD

**Issue by Sumanth9Nandamuri** [itchyny/lightline.vim#506]
Hi, I am using terminal vim from WSL for windows.
My issue is very wierd. Status bar will show up only if I have two splits open else no status bar is visible. Here is my vimrc. Please help me in resolving this issue. Thanks

set laststatus=2
syntax on
set number      "show line numbers
set relativenumber      "show relative line numbers
set laststatus=1
set backspace=indent,eol,start
set hidden
set ignorecase
set smartcase
set incsearch
set clipboard=unnamed
set guioptions+=a

nmap Q <Nop> " 'Q' in normal mode enters Ex mode. You almost never want this.
" Prevent bad habit of using arrow keys
" Do this in normal mode...
nnoremap <Left>  :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up>    :echoe "Use k"<CR>
nnoremap <Down>  :echoe "Use j"<CR>
"" ...and in insert mode
inoremap <Left>  <ESC>:echoe "Use h"<CR>
inoremap <Right> <ESC>:echoe "Use l"<CR>
inoremap <Up>    <ESC>:echoe "Use k"<CR>
inoremap <Down>  <ESC>:echoe "Use j"<CR>

call plug#begin()

" Search
Plug 'romainl/vim-cool'               " Disables highlight when search is done
Plug 'haya14busa/incsearch.vim'       " Better incremental search
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }  " FZF plugin, makes Ctrl-P unnecessary
Plug 'junegunn/fzf.vim'

" Text Manipulation
Plug 'terryma/vim-multiple-cursors'   " Multiple cursors like sublime

" GUI enhancements
Plug 'itchyny/lightline.vim'          " Better Status Bar
Plug 'mhinz/vim-startify'             " Better start screen
Plug 'scrooloose/nerdtree'            " File explorer
Plug 'machakann/vim-highlightedyank'  " Highlight yanks
Plug 'andymass/vim-matchup'           " Highlight corresponding blocks e.g. if - fi in bash
Plug 'yggdroot/indentline'            " Shows indentation levels
" Git GUI
Plug 'tpope/vim-fugitive'             " Git interface
Plug 'xuyuanp/nerdtree-git-plugin'    " Show status of files in NerdTree

" Syntactic language support
Plug 'elzr/vim-json'                   " Better JSON support
" Plug 'lervag/vimtex'                   " Latex support
" Plug 'mechatroner/rainbow_csv'         " CSV color coding
Plug 'frazrepo/vim-rainbow'                " Rainbow parentheses
" Plug 'chrisbra/colorizer'              " Colorize color codes
Plug 'vim-python/python-syntax'

" Colorschemes
Plug 'morhetz/gruvbox'
Plug 'chriskempson/base16-vim'         " Base16 themes

" Writing
Plug 'junegunn/goyo.vim'               " Distraction free mode
Plug 'junegunn/limelight.vim'          " Focus on current paragraph
call plug#end()

set background=dark
colorscheme base16-gruvbox-dark-hard
set termguicolors

let g:lightline = {
     \ 'active': {
     \   'left': [ [ 'mode', 'paste' ],
     \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
     \ },
     \ 'component_function': {
     \   'filename': 'LightlineFilename',
     \   'gitbranch': 'FugitiveHead'
     \ },
     \ }
function! LightlineFilename()
  return expand('%:t') !=# '' ? @% : '[No Name]'
endfunction

![ss1_vim](https://user-images.githubusercontent.com/56218882/92320041-12108d00-f03c-11ea-809b-6fdba09b41ea.PNG)
![ss2_nvim](https://user-images.githubusercontent.com/56218882/92320044-1472e700-f03c-11ea-9580-7c3ba621e2ff.PNG)

**Comment by yhu266** [comment]
You have a `set laststatus=1` in your config file.

**Comment by Sumanth9Nandamuri** [comment]
@yhu266 Thanks for prompt reply, removing `set laststatus=2` or changing it to` set laststatus=1` couldn't make the status bar show up.

**Comment by yhu266** [comment]
According to [Introduction](https://github.com/itchyny/lightline.vim#introduction), `set laststatus=2` is needed for `vim` config file. However, in your config file, you have both `set laststatus=2` and `set laststatus=1`.

So, could you remove the line `set laststatus=1`?

**Comment by Sumanth9Nandamuri** [comment]
Thanks man, my bad, I overlooked it. Status bar is now appearing

This is status bar with neovim on my local WSL terminal
![nvim](https://user-images.githubusercontent.com/56218882/92320567-f9a27180-f03f-11ea-9324-f6e7cd3fbf8b.PNG)


This is status bar with vim on remote server connected with ssh 
![vim](https://user-images.githubusercontent.com/56218882/92320583-1f2f7b00-f040-11ea-9dc2-a678c127e858.PNG)
any idea on how I can remove this inconsistency ?

Thanks.

**Comment by yhu266** [comment]
You have different vim/nvim colorschemes and/or terminal colorschemes.

**Comment by Sumanth9Nandamuri** [comment]
I have gruvbox color scheme on both machines, may be different terminal color schemes.
Closing this now. Thanks.
