### ISSUE TITLE
How to change the Status Line and Tab Line background color without creating a new colorscheme.

### ISSUE THREAD

**Issue by blackCauldron7** [itchyny/lightline.vim#508]
I want to change the status line and tabline background color to #000ff0 but can't find a way to do so.

**Comment by itchyny** [comment]
You can change the entries of the colorscheme palette.
```vim
let s:palette = g:lightline#colorscheme#{g:lightline.colorscheme}#palette
let s:palette.normal.middle = [['#000000', '#000ff0', 0, 21]]
let s:palette.tabline.middle = [['#000000', '#000ff0', 0, 21]]
call lightline#colorscheme()
```

**Comment by blackCauldron7** [comment]
That does it

**Comment by blackCauldron7** [comment]
```
vim.g.lightline.colorscheme = color
vim.fn["lightline#init"]()
vim.fn["lightline#colorscheme"]()
vim.fn["lightline#update"]()
```

I was trying to change my vimrc to lua in neovim and this is not working. Any Suggestions?

**Comment by yhu266** [comment]
Any particular reason for lua configuration file? As far as I know lightline documentations do not mention this method.

**Comment by blackCauldron7** [comment]
This is the same method you suggested above simply in lua.

**Comment by yhu266** [comment]
I would recommend following the vimscript syntax when it comes to lightline configurations. If the author decided to add support for lua config files, I'm sure the documentations will be updated to let us know.

**Comment by itchyny** [comment]
I don’t officially support configuring lightline with Lua so closing. Sharing your Lua config is welcome so that others can find the solution.

**Comment by yochem** [comment]
For anyone who wants to switch to lua config in neovim and has problems with the lightline configuration, try this:

1. Put the whole config on one line,  removing the `\` character and `let g:lightline = `:
```vim
" from this:
let g:lightline = {
    \ 'colorscheme': 'onedark',
    \ 'active': {
    \ 'left': [['mode', 'paste'],
    \ ['readonly', 'filename', 'gitbranch', 'modified']],
    \ 'right': [['lineinfo'], ['percent'], ['filetype']]
    \ },
    \ 'component_function': {
    \   'gitbranch': 'FugitiveHead'
    \ }
    \ }

" to this:
{'colorscheme':'onedark','active':{'left':[['mode','paste'],['readonly','filename','gitbranch','modified']],'right':[['lineinfo'],['percent'],['filetype']]},'component_function':{'gitbranch':'FugitiveHead'}}
```

2. Run this command: `:lua print(vim.inspect(vim.api.nvim_eval("THE LONG LINE FROM ABOVE HERE")))`.
3. Copy the result and paste it in one of your lua config files like this:
```lua
vim.g.lightline = <<PASTE HERE>>
```
4. Result:
```lua
vim.g.lightline = {
  active = {
    left = { { "mode", "paste" }, { "readonly", "filename", "gitbranch", "modified" } },
    right = { { "lineinfo" }, { "percent" }, { "filetype" } }
  },
  colorscheme = "onedark",
  component_function = {
    gitbranch = "FugitiveHead"
  }
}
```
It will work fine now!

**Comment by Sawrz** [comment]
> You can change the entries of the colorscheme palette.
> 
> ```viml
> let s:palette = g:lightline#colorscheme#{g:lightline.colorscheme}#palette
> let s:palette.normal.middle = [['#000000', '#000ff0', 0, 21]]
> let s:palette.tabline.middle = [['#000000', '#000ff0', 0, 21]]
> call lightline#colorscheme()
> ```

In my case `call lightline#colorscheme()` lead to an error in my `init.vim`. Don't know if it's Neovim specific. However, The colors changed without the call anyway.

**Comment by stevensonmt** [comment]
What is the actual syntax for setting colors on various parts of the status line?
`s:palette.normal.middle = [[ color1, color2, A, B ]]`
The colorscheme I'm looking at only has two entries for `palette.normal.middle`, neither of which affects the background. They appear to set the color of the leader and the text of that section. Adding entries to that section does not seem to affect the background.

**Comment by blackCauldron7** [comment]
@stevensonmt i believe its [[guifg, guibg, termfg, termbg]]
