### ISSUE TITLE
share some good looking separators

### ISSUE THREAD

**Issue by elig0n** [itchyny/lightline.vim#509]
besides the default. 
maybe later when we collect a bunch of 'em they can be shown up in the README for users to make it easy to customize them

here's a subseparator i like : ┊

**Comment by yhu266** [comment]
The symbol in the above comment is U+250A.

However, I'd argue we leave customization settings out of the project README. In fact, I think it's best to have a separate file that describes customization options, while the project README includes basic settings and installation instructions only.

**Comment by itchyny** [comment]
I would not write the separator list in the README, but sharing your config to this thread is welcome.
