### ISSUE TITLE
Component to display number of words in a specific filetype

### ISSUE THREAD

**Issue by paniash** [itchyny/lightline.vim#510]
Hello!

I was wondering if there is functionality to display the number of words in a specific filetype.

Thanks!

**Comment by yhu266** [comment]
To count words, see https://unix.stackexchange.com/questions/145289/how-can-i-count-the-number-of-words-in-a-file-whilst-editing-the-file-in-vim

To make a component function, see the project README.

**Comment by itchyny** [comment]
You can use `wordcount().words`.

**Comment by paniash** [comment]
@itchyny @yhu266 Thank you for the inputs. I've been able to implement it in my `.vimrc` but I'd like it to only display the number of words in certain filetype like `tex`, `markdown` instead of all the filetypes. How do I do that?

**Comment by yhu266** [comment]
What's your implementation?

**Comment by paniash** [comment]
> What's your implementation?
```vim
let g:lightline = {
      \ 'colorscheme': 'gruvbox',
      \ 'active': {
      \   'right': [ [ 'lineinfo' ],
      \              [ 'percent' ],
      \              [ 'fileformat', 'fileencoding', 'filetype', 'wordcount' ] ]
      \ },
      \ 'component': {
      \   'wordcount': '%{wordcount().words} words'
      \ },
      \ }
```

**Comment by itchyny** [comment]
Here it is.
```vim
let g:lightline = {
      \ 'active': {
      \   'right': [ [ 'lineinfo' ],
      \              [ 'percent' ],
      \              [ 'fileformat', 'fileencoding', 'filetype', 'wordcount' ] ]
      \ },
      \ 'component_function': {
      \   'wordcount': 'LightlineWordCount'
      \ },
      \ }

function! LightlineWordCount() abort
  return &filetype =~# '\vtex|markdown' ? '' : wordcount().words . ' words'
endfunction
```

**Comment by paniash** [comment]
@itchyny Thank you very much! :)
