### ISSUE TITLE
Lightline disapears after :source % command

### ISSUE THREAD

**Issue by Manas02** [itchyny/lightline.vim#513]
Lightline works perfectly fine till I have to `source %` command.
To get it back i have to open that file again
my [.vimrc](github.com/manas02/vimrc) has :
`set laststatus=2`

**Comment by itchyny** [comment]
Remove the `set statusline=...` line from vimrc.

**Comment by Manas02** [comment]
It didn't work 
here's what it looks like before `source %`:
![image](https://user-images.githubusercontent.com/36999652/94358437-a2cc0d00-00be-11eb-8918-a52b47aebc8d.png)
and after the command : 
![image](https://user-images.githubusercontent.com/36999652/94358480-f6d6f180-00be-11eb-8797-36f39779eba1.png)

**Comment by zbraniecki** [comment]
for me it disappears when LSP kicks in in neovim 0.5 with https://sharksforarms.dev/posts/neovim-rust/ config. It works well for non-rust files, but in rust it shows and then disappears.
