### ISSUE TITLE
cant change icon for modified buffers

### ISSUE THREAD

**Issue by joe23rep** [itchyny/lightline.vim#515]
i tried to change the "+" symbol into a little icon to indicate that modifications have been made to the file. 

i did it the following way:

```
" Show icon and change the /+ for unsaved changes to be within the same block with diff icon
function! FileNameWithIcon() abort
  let filename_with_icon = expand('%:t') !=# '' ? expand('%:t') : 'Txt'
  let modified = &modified ? '  ' : ''
  return WebDevIconsGetFileTypeSymbol() . ' ' . filename_with_icon . modified
endfunction

```

and than added that to the statusbar via:

```
let g:lightline.active = {
        \ 'left': [ ['mode'], [ 'filename_with_icon' ], ['git_branch'] ],
        \ 'right': [ ['lineinfo'],[ 'percent' ], [ 'unix_logo' ] ],
        \ }
```

it worked for a bit but then i changed something else in my lightline config (tried to integrate github a bit more) and it stopped working. tried the exact same version where it worked again and it still doesnt work anymore. can u spot a mistake or give me an idea what else i could try?

or is it possible a different plugin or command is intefering with the function?

**Comment by yhu266** [comment]
What method did you use to integrate GitHub features? Or are they Git features instead?

**Comment by itchyny** [comment]
Do you have config in `component_function`? Please describe the issue with your entire config.

**Comment by joe23rep** [comment]
i tried to integrate github into lightline via vim fugitive. it didnt work in the end the way i wanted it to work so i went back to my old config.

heres my complete lightline config (but theres a little bit of config for lightline-bufferline inbetween).

```
" Lightline -------------------------------------------------------------------------------------
"       _       _     _   _ _
"| |   (_) __ _| |__ | |_| (_)_ __   ___
"| |   | |/ _` | '_ \| __| | | '_ \ / _ \
"| |___| | (_| | | | | |_| | | | | |  __/
"|_____|_|\__, |_| |_|\__|_|_|_| |_|\___|
"         |___/

" Lightline shows the mode -> get rid of vim's default
set noshowmode

" Show second tabline on top
set showtabline=2

let g:lightline = {
        \ 'colorscheme': 'deus',
        \ }

" Custom Functions-----------------------------------------------------------------

" Show icon and change the /+ for unsaved changes to be within the same block with diff icon
function! FileNameWithIcon() abort
  let filename_with_icon = expand('%:t') !=# '' ? expand('%:t') : 'Txt'
  let modified = &modified ? '  ' : ''
  return WebDevIconsGetFileTypeSymbol() . ' ' . filename_with_icon . modified
endfunction


" Show filetype with icon and display an icon for unsaved changes
function! FileTypeWithIcon() abort
  let filetype_with_icon = expand(&ft) !=# '' ? expand(&ft) : 'Txt'
  let modified = &modified ? '   ' : ''
  return WebDevIconsGetFileTypeSymbol() . ' '
endfunction
" return WebDevIconsGetFileTypeSymbol() . ' '  . filetype_with_icon  . modified


" Fugitive Integration
function! Git_branch() abort
  if fugitive#head() !=# ''
    " return  fugitive#head() . "  "
    " return  fugitive#head() . "  "
    return  fugitive#head() . "  "
  else
    return " "
  endif
endfunction



" Define lightline look-----------------------------------------------------------

let g:lightline.active = {
        \ 'left': [ ['mode'], [ 'filetype_with_icon' ], ['git_branch'] ],
        \ 'right': [ ['lineinfo'],[ 'percent' ], [ 'unix_logo' ] ],
        \ }



let g:lightline.separator = { 'left': " ", 'right': " " }
let g:lightline.subseparator = { 'left': " ", 'right': " " }
let g:lightline.tabline_separator = { 'left': " ", 'right': " " }
let g:lightline.tabline_subseparator = { 'left': " ", 'right': " " }
" let g:lightline.tabline_subseparator = { 'left': " ", 'right': " " }
" let g:lightline.subseparator = { 'left': " ", 'right': " " }

" let g:lightline.separator = { 'left': " ", 'right': " " }
" let g:lightline.subseparator = { 'left': " ", 'right': " " }
" let g:lightline.tabline_separator = { 'left': " ", 'right': " " }
" let g:lightline.tabline_subseparator = { 'left': " ", 'right': " " }
"


" Tabline-------------------------------------------------------------------------

let g:lightline.tabline = {
        \ 'left': [ [ 'vim_logo'], [ 'buffers' ] ],
        \ 'right': [ [ 'buffer' ], [ 'fileencoding' ] ]
        \ }


let g:lightline.tab = {
        \ 'active': ['filename_with_icon'],
        \ 'inactive': ['filename_with_icon']
        \ }


" Custom lightline components-----------------------------------------------------

let g:lightline.tab_component = {}
let g:lightline.tab_component_function = {
        \ 'artify_filename': 'lightline_tab_filename',
        \ 'filename': 'lightline#tab#filename',
        \ 'modified': 'lightline#tab#modified',
        \ 'readonly': 'lightline#tab#readonly',
        \ 'tabnum': 'lightline#tab#tabnum',
        \ 'filename_with_parent': 'FileNameWithParent'
        \ }


let g:lightline.component = {
        \ 'filename_with_icon': '%{FileNameWithIcon()}',
        \ 'filetype_with_icon': '%{FileTypeWithIcon()}',
        \ 'vim_logo': "\ue7c5 ",
        \ 'unix_logo': "  ",
        \ 'filename_with_parent': '%t',
        \ 'buffer': 'buffers %n',
        \ 'git_branch': '%{Git_branch()}',
        \}


" Tabline Settings-------------------------------------------------------------------

" Enable bufferline
let g:lightline.component_expand = {'buffers': 'lightline#bufferline#buffers'}
let g:lightline.component_type   = {'buffers': 'tabsel'}

" Tabline Icons
let g:lightline#bufferline#enable_devicons = 0
let g:lightline#bufferline#filename_modifier = ':t'

" Tabline colors
let s:palette = g:lightline#colorscheme#deus#palette
let s:palette.tabline.tabsel = [ [ '#d6f4fd', '#3e4452', 252, 66, ] ]
" let s:palette.tabline.tabsel = [ [ '#d6f4fd', '#3e4452', 252, 66, 'bold' ] ]

unlet s:palette



```

**Comment by yhu266** [comment]
You did not have put functions in `component_function`.

**Comment by itchyny** [comment]
Adding to `g:lightline.component` instead of `component_function` is fine. But you're trying to show the component in tabs? You're `FileNameWithIcon()` implementation does not work within tabs. Please consider `g:lightline.tab_component_function`, and the function accepts one argument; the tab number.

**Comment by joe23rep** [comment]
yes. i basically have the normal statusbar which shows the mode, the filetype etc and then above a have the lightline bufferline which shows on the right side the number of buffers and on the left side it has tabs with the filenames which are currently open which also shows if a buffer has unsafed changes. 

i know for fact that it once worked with the icon cuz ive seen it with my own eyes. only after i changed something else it stopped working. 

so if i understand u correct its not supposed to work but if i switch basically the filetype with icon and filename with icon places it should work (filename with icon being in the normal statusbar)?

**Comment by joe23rep** [comment]
yes. i basically have the normal statusbar which shows the mode, the filetype etc and then above a have the lightline bufferline which shows on the right side the number of buffers and on the left side it has tabs with the filenames which are currently open which also shows if a buffer has unsafed changes. 

heres a picture to better understand what i mean:

[](https://ibb.co/kKmym2J)

i know for fact that it once worked with the icon cuz ive seen it with my own eyes. only after i changed something else it stopped working. 

so if i understand u correct its not supposed to work but if i switch basically the filetype with icon and filename with icon places it should work (filename with icon being in the normal statusbar)?

**Comment by itchyny** [comment]
If I'm correct you're using [lightline-bufferline](https://github.com/mengelbrecht/lightline-bufferline) plugin. Please read the [Integration](https://github.com/mengelbrecht/lightline-bufferline#integration) which mentions on the modified indicator.

**Comment by joe23rep** [comment]
correct. its that plugin. i found the answer how to do it. thanks
