### ISSUE TITLE
Using things like %l and %c in a component_function

### ISSUE THREAD

**Issue by Magicrafter13** [itchyny/lightline.vim#516]
I'm moved the lineinfo text `%3l:%-2c` from a component, into a component function, because I wanted to hide this component in things like NERDTree.

When inside a component function, the % things aren't evaluated, they're just printed literally
![image](https://user-images.githubusercontent.com/29127566/95273519-2640d900-07f8-11eb-834a-2e16016d3baa.png)
After looking at stuff, I tried placing my function in the `component_expand` section instead of `component_function`, which actually gave me the results I wanted:
![image](https://user-images.githubusercontent.com/29127566/95273637-6902b100-07f8-11eb-94ab-ce053beac6cc.png)

But there's one problem with this method.
In all windows that aren't the active window, it shows up, including NERDTree.

Here's my function:
```
function! Lineinfo()
  let fname = expand('%:t')
  return fname =~# '^__Tagbar__\|NERD_tree' ? '' : ' %3l:%-2c'
endfunction
```
(I suppose this could just be one line, I don't really need to set fname if I only use it once...)

I won't ask why `component_expand` has this behavior, I'm sure it's supposed to do... whatever it is that it's doing, so that's why I want to know how to get `%3l:%-2c` to evaluate when it's a `component_function`.

**Comment by yhu266** [comment]
Did you try `line(".")` to show the current line number in `component_function`?

**Comment by Magicrafter13** [comment]
> Did you try `line(".")` to show the current line number in `component_function`?

Saw that at some point - how would I set aside 3 character spaces for it like `%3l` ?

**Comment by yhu266** [comment]
On second thought, maybe it's supposed to be in `component`, just like `lineinfo`:

https://github.com/itchyny/lightline.vim/blob/2afc3ab4dda191c75764d3239d1cf56356759dd4/autoload/lightline.vim#L113

**Comment by Magicrafter13** [comment]
But the thing is, I'm trying to have it in a function so I can check if I'm in a NERDTree (or Tagbar) Window, and if I am, then I return an empty string.

But for the record, yes it displays fine in the default location of `component`.

**Comment by yhu266** [comment]
If your issue is about the display of numbers, check https://vi.stackexchange.com/questions/12287/what-is-the-vimscript-version-of-sprintf and it'll help.

**Comment by itchyny** [comment]
See https://github.com/itchyny/lightline.vim/issues/80#issuecomment-57115482

**Comment by Magicrafter13** [comment]
Thank you this solves my issue.
Sorry I didn't respond sooner, I got pretty busy last night.
