### ISSUE TITLE
Error with colorschemes

### ISSUE THREAD

**Issue by lag00n** [itchyny/lightline.vim#517]
Hi, 
I'm actually having some problems with all lightline colorschemes. All of them looks strange as if their colors were changed (I'm uploading a example with selenized light) I've term colors enabled as well.
![example](https://user-images.githubusercontent.com/65380127/95663225-d0c83d00-0b13-11eb-9501-bb26bf6581d7.png)
Am I doing something wrong?

**Comment by yhu266** [comment]
Most likely your issue is related to your terminal (simulator) color settings. What terminal (simulator) do you use?

**Comment by lag00n** [comment]
I'm using urxvt, and I've compiled it (on gentoo) with 256color support.

**Comment by yhu266** [comment]
Could you remove all settings in your .Xdefaults file and see how that'll affect the lightline colorschemes?

**Comment by lag00n** [comment]
Unafortunally, nothing changes... I've removed everything and anything happened :(

**Comment by yhu266** [comment]
Well, if all lightline colorschems look strange (blue replaced by magenta for example), I doubt it's a lightline issue. Switch to a terminal simulator other than rxvt-unicode may be of help.

Also, note that neovim has `set background=dark` by default.

**Comment by lag00n** [comment]
On gnome-terminal it's the same thing... that's weird.

**Comment by itchyny** [comment]
What's your `$TERM` environment value? The [README.md](https://github.com/itchyny/lightline.vim#introduction) suggests to setting `$TERM` to `xterm-256color`. Also confirm that `&t_Co` is 256.

**Comment by lag00n** [comment]
My $TERM is `rxvt-unicode-256color` but when i set it to `xterm-256color`...
I already have `t_Co` set as `256`... Is there anything else I can do?

Sorry for the delay in responding

**Comment by itchyny** [comment]
Make sure `&termguicolors` is 0.

**Comment by lag00n** [comment]
it's already set like that, i've check it out with `echo &termguicolors` the output is 0.

When i try to set it as 1, my bar looks like that 

![termguicolors](https://user-images.githubusercontent.com/65380127/96464383-1f559580-11fe-11eb-96f1-4b60d65d96ff.png)

**Comment by itchyny** [comment]
Can you provide screenshot of `:XtermColorTable` command output? The plugin is available at https://github.com/guns/xterm-color-table.vim

**Comment by lag00n** [comment]
Sure!
   
  `0 #000000    1 #800000    2 #008000    3 #808000    4 #000080    5 #800080    6 #008080    7 #c0c0c0
   8 #808080    9 #ff0000   10 #00ff00   11 #ffff00   12 #0000ff   13 #ff00ff   14 #00ffff   15 #ffffff
  16 #000000   17 #00005f   18 #000087   19 #0000af   20 #0000df   21 #0000ff
  22 #005f00   23 #005f5f   24 #005f87   25 #005faf   26 #005fdf   27 #005fff
  28 #008700   29 #00875f   30 #008787   31 #0087af   32 #0087df   33 #0087ff
  34 #00af00   35 #00af5f   36 #00af87   37 #00afaf   38 #00afdf   39 #00afff
  40 #00df00   41 #00df5f   42 #00df87   43 #00dfaf   44 #00dfdf   45 #00dfff
  46 #00ff00   47 #00ff5f   48 #00ff87   49 #00ffaf   50 #00ffdf   51 #00ffff
  52 #5f0000   53 #5f005f   54 #5f0087   55 #5f00af   56 #5f00df   57 #5f00ff
  58 #5f5f00   59 #5f5f5f   60 #5f5f87   61 #5f5faf   62 #5f5fdf   63 #5f5fff
  64 #5f8700   65 #5f875f   66 #5f8787   67 #5f87af   68 #5f87df   69 #5f87ff
  70 #5faf00   71 #5faf5f   72 #5faf87   73 #5fafaf   74 #5fafdf   75 #5fafff
  76 #5fdf00   77 #5fdf5f   78 #5fdf87   79 #5fdfaf   80 #5fdfdf   81 #5fdfff
  82 #5fff00   83 #5fff5f   84 #5fff87   85 #5fffaf   86 #5fffdf   87 #5fffff
  88 #870000   89 #87005f   90 #870087   91 #8700af   92 #8700df   93 #8700ff
  94 #875f00   95 #875f5f   96 #875f87   97 #875faf   98 #875fdf   99 #875fff
  100 #878700  101 #87875f  102 #878787  103 #8787af  104 #8787df  105 #8787ff     
  106 #87af00  107 #87af5f  108 #87af87  109 #87afaf  110 #87afdf  111 #87afff
  112 #87df00  113 #87df5f  114 #87df87  115 #87dfaf  116 #87dfdf  117 #87dfff
  118 #87ff00  119 #87ff5f  120 #87ff87  121 #87ffaf  122 #87ffdf  123 #87ffff
  124 #af0000  125 #af005f  126 #af0087  127 #af00af  128 #af00df  129 #af00ff
  130 #af5f00  131 #af5f5f  132 #af5f87  133 #af5faf  134 #af5fdf  135 #af5fff
  136 #af8700  137 #af875f  138 #af8787  139 #af87af  140 #af87df  141 #af87ff 
  142 #afaf00  143 #afaf5f  144 #afaf87  145 #afafaf  146 #afafdf  147 #afafff
  148 #afdf00  149 #afdf5f  150 #afdf87  151 #afdfaf  152 #afdfdf  153 #afdfff
  154 #afff00  155 #afff5f  156 #afff87  157 #afffaf  158 #afffdf  159 #afffff            
  160 #df0000  161 #df005f  162 #df0087  163 #df00af  164 #df00df  165 #df00ff                             
  166 #df5f00  167 #df5f5f  168 #df5f87  169 #df5faf  170 #df5fdf  171 #df5fff          
  172 #df8700  173 #df875f  174 #df8787  175 #df87af  176 #df87df  177 #df87ff
  178 #dfaf00  179 #dfaf5f  180 #dfaf87  181 #dfafaf  182 #dfafdf  183 #dfafff `

**Comment by yhu266** [comment]
Maybe a screenshot instead of list of hex values?

**Comment by lag00n** [comment]
oh sorry

**Comment by lag00n** [comment]
Oh sorry, lemme post a screenshot here... 
![colors](https://user-images.githubusercontent.com/65380127/96513154-0cf84d80-1238-11eb-9ad0-de89ea92538f.png)

better now?

**Comment by yhu266** [comment]
I don't see any issue related to lightline here. You are using a terminal colorscheme that set blue (00, 00, 80) as color 4, but the monitor shows it as pale magenta. Would you check you display color settings?

**Comment by lag00n** [comment]
It's everything on default... I've tried to use it in both urxvt and st, and it has the same problem...

Maybe is something related to pywal?

**Comment by itchyny** [comment]
I see a serious problem here. Your 256 colors output looks unexpected at 21, 46, 51, 201, 226.

**Comment by lag00n** [comment]
I think 196 is weird too... I've done something wrong?

**Comment by itchyny** [comment]
Also note the [selenized light](https://github.com/itchyny/lightline.vim/blob/master/autoload/lightline/colorscheme/selenized_light.vim#L27) colorscheme uses 4 for the background of the first left component, which is blue in most terminal but in your screenshot it looks like purple. Configuring the terminal colors should fix the problem (something like https://addy-dclxvi.github.io/post/configuring-urxvt/).

**Comment by lag00n** [comment]
But i have this problem even on st and gnome-terminal... What's happening?

**Comment by yhu266** [comment]
As I mentioned earlier, your issue is probably unrelated to lightline and terminal settings. Could you reset all system-wide color configurations (e.g. pywal)?

**Comment by lag00n** [comment]
Now it looks like that 
![vimbar](https://user-images.githubusercontent.com/65380127/96805655-7e76fe00-13e8-11eb-8d8a-a81e1e776f23.png)

I can't understand whats happening here.

**Comment by yhu266** [comment]
I believe this is [4-bit color](https://en.wikipedia.org/wiki/ANSI_escape_code#3/4_bit). You did not have 256color in your terminal setting.

**Comment by lag00n** [comment]
![eix](https://user-images.githubusercontent.com/65380127/96894281-ef0e3100-1461-11eb-85af-cd312f977422.png)
it was compiled with 256color support, as you can see in the screenshot

**Comment by lag00n** [comment]
![image](https://user-images.githubusercontent.com/65380127/96940888-44206600-14a7-11eb-8ce7-d2c1e6f15eb4.png)
wombat colorscheme seems to work properly

**Comment by lag00n** [comment]
![vimbar2](https://user-images.githubusercontent.com/65380127/96940906-54384580-14a7-11eb-9586-b4bd6f02b00a.png)
wombat colorscheme seems to work properly
