### ISSUE TITLE
Can I change the color of tabline in my .vimrc?

### ISSUE THREAD

**Issue by gcli7** [itchyny/lightline.vim#518]
Hi, I am looking for a method to change the color of the tabline.

The color scheme of my vim is onedark.vim (https://github.com/joshdick/onedark.vim), and I found lightline.vim in its README.md.

After installing lightline.vim, I made the following changes in my `.vimrc`:

```
let g:lightline = {
    \ 'colorscheme': 'onedark',
    \ }

hi TabLineFill    ctermfg=232 ctermbg=232
hi TabLine        ctermfg=245 ctermbg=234 cterm=none
hi TabLineSel     ctermfg=81  ctermbg=232 cterm=none
```

The status bar has exactly become pretty good!

However, the tabline has not changed, it is still the default color scheme.

I want to know is there any way to do that?

Thanks.

**Comment by yhu266** [comment]
See https://github.com/itchyny/lightline.vim/issues/508#issuecomment-694716949

**Comment by gcli7** [comment]
Thanks a lot. It works!

But in my case, only need to add the following statements in my `.vimrc`:

```
let s:palette = g:lightline#colorscheme#onedark#palette
let s:palette.tabline.tabsel = [['#282C34', '#98C379', 0, 21]]
```

When I add `call lightline#colorscheme()`, it causes an error.

Anyway, thanks a lot for the help.

**Comment by Neur1n** [comment]
> Thanks a lot. It works!
> 
> But in my case, only need to add the following statements in my `.vimrc`:
> 
> ```
> let s:palette = g:lightline#colorscheme#onedark#palette
> let s:palette.tabline.tabsel = [['#282C34', '#98C379', 0, 21]]
> ```
> 
> When I add `call lightline#colorscheme()`, it causes an error.
> 
> Anyway, thanks a lot for the help.

I tried, but failed since `g:lightline#colorscheme#default#palette` (I assign `g:lightline.colorscheme` to 'default') seems to be undefined when I call it. Where do you add those lines? Thanks.

**Comment by itchyny** [comment]
@Neur1n Make sure to add the code after the plugin path is added to `'runtimepath'`. If this doesn't work/make sense, please open a new issue.

**Comment by gcli7** [comment]
@Neur1n

Change the `onedark` to the colorscheme you want to use.

I tried the following revision and it worked for me.

Maybe you can also try it.

```
let s:palette = g:lightline#colorscheme#default#palette
let s:palette.tabline.tabsel = [['#282C34', '#98C379', 235, 114]]
```

**Comment by gcli7** [comment]
By the way, I use `vim-plug` to manage my vim plugins, so remember to add the above two lines as follows:

```
call plug#begin('~/.vim/plugged')
Plug 'itchyny/lightline.vim'
call plug#end()

let s:palette = g:lightline#colorscheme#default#palette
let s:palette.tabline.tabsel = [['#282C34', '#98C379', 235, 114]]
```

**Comment by Neur1n** [comment]
I have a configuration like this:

- `init.vim` sourcing `common.vim`
- `common.vim` sourcing `pluglist.vim` (where I put plug#begin and plug#end)
- `common.vim` sourcing `plugconf.vim` (put after `pluglist.vim`)
- `plugconf.vim` sourcing lightline config file

And when I run `:scriptnames`, it shows that the lightline config file is loaded before lightline itself. Where did I do wrong? Thanks.

**Comment by gcli7** [comment]
Excuse me, what does your lightline config file means?

As I know, if you use any plugin manager, the plugin you install will be auto-loaded and sourced.

Maybe you can try to comment all the lightline config in `plugconf.vim`, and add the above two lines into `plugconf.vim`.

**Comment by Neur1n** [comment]
My fault. I put configurations of lightline into an isolate file. But then I used the following minimal `vimrc` to test:

```vimscript
if has('win32')
  let $VIMCONFIG=$HOME.'/AppData/Local/nvim'
else
  let $VIMCONFIG=$HOME.'/.config/nvim'
endif

call plug#begin('$VIMCONFIG/plugged')
Plug 'itchyny/lightline.vim'
call plug#end()

let g:lightline = {}
let g:lightline['colorscheme'] = 'default'

let s:tmp = get(g:, 'lightline#colorscheme#default#palette', 'DEBUG')
echomsg s:tmp.' TEST'
```

And still have the same issue. I got 'DEBUG TEST' echoed.

**Comment by itchyny** [comment]
The `get()` function does not load the autoload script so that's an expected behavior.

**Comment by Neur1n** [comment]
You are right, thanks a lot.
