### ISSUE TITLE
Use ANSI/cterm colors without `notermguicolors` setting

### ISSUE THREAD

**Issue by Addisonbean** [itchyny/lightline.vim#520]
Is there a way to force lightline to use the cterm colors without setting `notermguicolors`? I want to use `termguicolors` for my neovim colorscheme but use my cterm/ansi colors that are defined by my terminal. Is there a way to do this with lightline, or if not would it be practical to implement? Somethine like a `use_cterm_colors` option would be really helpful to force cterm colors even when neovim has truecolor support enabled.

**Comment by itchyny** [comment]
There's no way to do this and no plan to implement. Sorry.
