### ISSUE TITLE
Is there has a general way to hide the right part when the window size is not enough?

### ISSUE THREAD

**Issue by iwfan** [itchyny/lightline.vim#521]
My vim status line looks like this:

![image](https://user-images.githubusercontent.com/28853200/96358168-ad664900-1136-11eb-95d9-4b2ddbdeb4c0.png)

But I want to hide the right part of lightline when I open the files tree, (only show the mode component).

So Is there has a general way to hide the right part when the window size is not enough or open some special file type?

**Comment by yhu266** [comment]
Based on https://github.com/itchyny/lightline.vim/issues/193#issuecomment-252462678, I believe the best you can do is to use component functions that return empty string for the (assumed) NERDTree buffer.

**Comment by iwfan** [comment]
ok, it's a nice hint. and really appreciate the super-fast response.

**Comment by itchyny** [comment]
https://github.com/itchyny/lightline.vim#can-i-trim-the-file-format-and-encoding-information-on-narrow-windows
