### ISSUE TITLE
Selenized theme has bad colors

### ISSUE THREAD

**Issue by toniz4** [itchyny/lightline.vim#524]
I don't know if it is intended, but the selenized colors looks weird in comparison to the solarized colors for exemple:
 selenized:
![selenized](https://user-images.githubusercontent.com/14265358/97476231-ef5c6f80-192c-11eb-9ee8-dcaa305546df.png)
solarized:
![solarized](https://user-images.githubusercontent.com/14265358/97476255-f71c1400-192c-11eb-8d4d-fb7dc2f8e589.png)

The colors at the left and right extremes looks good, but at the middle it's kinda hard to read.

And other problem that i encountered is the theme naming, selenized has to themes, selenized, and selenized_bw, and in the lightline repos there is selenized_light, selenized_dark, selenized_white and selenized_black. Light/dark and White/Black variants could be just one theme, and determine the bg/fg with the background value, like solarized does, but with selenized and selenized_bw. 

And after comparing the colors in the selenized theme and lightline theme i found that the colors has different hex values.

If you are interested in the proposed changes, can make a pr tomorrow trying to solve those problems.

Thanks for developing this awesome plugin!

**Comment by itchyny** [comment]
Concatinating the background variants makes it difficult to switching them on the fly but it's ok as long as leaving the both variants like PaperColor. Improving the colors is welcome.
