### ISSUE TITLE
Palette for command-mode?

### ISSUE THREAD

**Issue by Galicarnax** [itchyny/lightline.vim#527]
I've tweaked lightline colorscheme to my taste, and noticed, while there are `normal`, `insert`, `visual`, etc. palette components, there seems to be no `command` component. Is it possible to change colors in the command/search mode?

**Comment by itchyny** [comment]
It's definitely possible, you can define your `command` colors in your lightline colorscheme.

**Comment by yhu266** [comment]
Yes it's possible. Use

```
let s:p = {
    \ 'normal': {},
    \ 'inactive': {},
    \ 'insert': {},
    \ 'replace': {},
    \ 'visual': {},
    \ 'tabline': {},
    \ 'command': {},
    \}

let s:p.command.middle = [ [ '#ff0000', '#00ff00', 9, 10 ] ]
```

**Comment by Galicarnax** [comment]
Thanks!
