### ISSUE TITLE
Error detected while processing lightline#enable

### ISSUE THREAD

**Issue by fhofherr** [itchyny/lightline.vim#528]
Hello,

first of all thank you for this great plugin.

Since https://github.com/itchyny/lightline.vim/commit/2d482e82f2e13c6d7bad3a0aabfc44f8aba945ed I'm getting the following error whenever I start neovim:

    Error detected while processing function lightline#enable:
    line   13:                                                                                                                                                       
    E216: No such group or event: lightline-disable

After wrapping the `autocmd! lightline-disable` and `augroup! ligthline-disable` lines of the `lightline#enable` function in a `try-catch` block this does not occur anymore:

```vim
  try
      autocmd! lightline-disable
      augroup! lightline-disable
  catch
  endtry
```

However, I'm not sure if this really fixes the issue or just hides the symptom.

I'm using the version v0.5.0-828-g0a95549d6 of Neovim. Neovim v0.5.0 is not yet released, so there is a possibility that my issue is related to something in Neovim.

**Comment by itchyny** [comment]
Thanks for reporting, I reverted the commit.
