### ISSUE TITLE
lightline not work , when start vim with parametric "--remote-silent-tab" 

### ISSUE THREAD

**Issue by WillDawnlll** [itchyny/lightline.vim#529]
used ":scriptnames" , two ways load same scripts,  cant find diffrent myself , may be u can give me some suggestion.....thank u

**Comment by WillDawnlll** [comment]
ps...win10 gvim

**Comment by yhu266** [comment]
Could you be more specific about the issue? Maybe an example?

**Comment by itchyny** [comment]
This looks like #394. Please confirm your Vim version >= 8.2.0116.

**Comment by WillDawnlll** [comment]
thanks again, is #394, but i didnt searched it before.....i just update 8.1 to 8.2 a week ago form Official website, will try to find another vertion....
