### ISSUE TITLE
Is there a way to display the real time hh:mm:ss in the statusline?

### ISSUE THREAD

**Issue by ndavidpsi** [itchyny/lightline.vim#530]
I want to be able to check the time in my statusline...
Is there some variable we can access to display the time the same way we are able to display say the line number?

I tried the following in my init.vim (or vimrc it works the same):
`let now = strftime('%T')`
I then defined a new lightline component called `timedisplay` and set it equal to `now`.
It displays the time but only the time when you opened the file, it doesn't update.

**Comment by ndavidpsi** [comment]
**Duplicate of #423** 
I just have one question. It seems to only update the statusline when we move or do something in vim (you can test this by adding %S to display the seconds), is there a way to update it every second?

**Comment by itchyny** [comment]
```vim
call timer_start(1000, {->execute('redrawstatus')}, {'repeat': -1})
```

**Comment by ndavidpsi** [comment]
it works but is there a way to only do that if when we are not in the welcome message?
When you open vim you see that welcome message, well causing the redrawstatus to update every second causes the message to disappear after one second.

**Comment by itchyny** [comment]
That's impossible. Please report to [vim_dev](https://github.com/vim/vim/issues/new/choose) if you want an option redrawstatus does not clear the message.

**Comment by ndavidpsi** [comment]
thanks
