### ISSUE TITLE
Is there a way to change the lightline colorscheme colors in my vimrc?

### ISSUE THREAD

**Issue by ndavidpsi** [itchyny/lightline.vim#531]
I am using codedark theme for lightline. I want that grey color to become black so that my statusbar blends better with the background color. Is there an easy way to do that?
![1](https://user-images.githubusercontent.com/73792104/100628721-6ddb7100-3320-11eb-8301-546bb8608bd9.PNG)

**Comment by yhu266** [comment]
See https://github.com/itchyny/lightline.vim/issues/508

**Comment by sp1n0r** [comment]
Thanks! That partially solves the issue. It only changes the middle part where nothing is written. I also want to partially change the left and right parts. I want to change where it says no name, dos, utf8 and no ft. I want to change the background color to black and preserve the colorscheme's foreground color.

Basically some sort of global documentation on how to change the different sections of the statusbar would be highly appreciated, I tried to look into the documentation but I didn't find anything

**Comment by ndavidpsi** [comment]
Thanks! That partially solves the issue. It only changes the middle part where nothing is written. I also want to partially change the left and right parts. I want to change where it says no name, dos, utf8 and no ft. I want to change the background color to black and preserve the colorscheme's foreground color.

Basically some sort of global documentation on how to change the different sections of the statusbar would be highly appreciated, I tried to look into the documentation but I didn't find anything

**Comment by ndavidpsi** [comment]
Figured it out by checking the syntax of one of the colorschemes in lightline repo.
