### ISSUE TITLE
How can I set `bold font` for lightline ?

### ISSUE THREAD

**Issue by uunnxx** [itchyny/lightline.vim#535]
Hi there! Sorry for bothering you guys, Is it possible to make `lightline` font bold?

**Comment by yhu266** [comment]
If you are using `gruvbox`, it has an example here:

https://github.com/morhetz/gruvbox/blob/bf2885a95efdad7bd5e4794dd0213917770d79b7/autoload/lightline/colorscheme/gruvbox.vim#L31

**Comment by uunnxx** [comment]
Thank you!
