### ISSUE TITLE
lightline not working in urxvt on Gentoo

### ISSUE THREAD

**Issue by avdb13** [itchyny/lightline.vim#536]
My statusline is not colored as you can see: https://imgur.com/s7VZojj.png
I added ```set laststatus=2``` to my ```.vimrc``` but without results.
It used to work previously but I don't know what I did differently. ```rxvt-unicode``` is compiled with 256-color support.

**Comment by itchyny** [comment]
Please share your entire `.vimrc`. Also the output of `:echo [&t_Co, &ls, $TERM, &stl]`

**Comment by yhu266** [comment]
From your screenshot, it seems that your config did not load `lightline`, and used the default statusline instead. It doesn't look like a highlighting issue.

**Comment by avdb13** [comment]
`.vimrc`:
```
syntax on
filetype plugin indent on
set guioptions=
set nocompatible
set number
set nowrap
set showmode
set tw=80
set smartcase
set smarttab
set smartindent
set autoindent
set softtabstop=2
set shiftwidth=2
set expandtab
set incsearch
set mouse=a
set history=1000
set clipboard=unnamedplus,autoselect
set completeopt=menuone,menu,longest
set wildignore+=*\\tmp\\*,*.swp,*.swo,*.zip,.git,.cabal-sandbox
set wildmode=longest,list,full
set wildmenu
set completeopt+=longest
set cmdheight=1

call plug#begin('~/.vim/plugged')
" colorschemes
Plug 'bluz71/vim-moonfly-colors'
Plug 'arzg/vim-colors-xcode'
Plug 'ghifarit53/tokyonight-vim'
Plug 'arcticicestudio/nord-vim'
Plug 'ayu-theme/ayu-vim'
Plug 'lewis6991/moonlight.vim'
Plug 'cocopon/iceberg.vim'

Plug 'neovimhaskell/haskell-vim'
Plug 'preservim/nerdtree'
Plug 'dense-analysis/ale'
Plug 'itchyny/lightline.vim'
call plug#end()

set laststatus=2
autocmd VimEnter * NERDTree
" Exit Vim if NERDTree is the only window left.
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() |
    \ quit | endif

map <C-n> :NERDTreeToggle<CR>

colorscheme iceberg
set guifont=rissole\ 10
```

`:echo [&t_Co, &ls, $TERM, &stl]`:
```
['256', 2, 'rxvt-unicode-256color', '%{exists(''b:NERDTree'')?b:NERDTree.root.path.str():''''}']
```

**Comment by itchyny** [comment]
Please disable the statusline of nerdtree.
Reference: https://github.com/preservim/nerdtree/blob/14af89743ac1c31ff9bb43682025eda50333a7d5/doc/NERDTree.txt#L1111-L1122

**Comment by avdb13** [comment]
Did like you said, still no difference except for the output of `:echo [&t_Co, &ls, $TERM, &stl]` which is turned into the following:
```
['256', 2, 'rxvt-unicode-256color', '']

```

**Comment by itchyny** [comment]
Please create minimal vimrc for reproduction.

**Comment by yhu266** [comment]
> Did like you said. Added  `let g:NERDTreeStatusline=-1` to the bottom of my `.vimrc` but still no difference except for the output of `:echo [&t_Co, &ls, $TERM, &stl]` which is turned into the following:
> 
> ```
> 
> ['256', 2, 'rxvt-unicode-256color', '']
> 
> 
> 
> ```

It looks like your results are obtained in the `NERDTree` buffer. Could you open a normal text file and run `echo &stl` again?

**Comment by yhu266** [comment]
Also, if it is a `VimEnter` issue, see https://github.com/itchyny/lightline.vim/issues/487#issuecomment-660380223 for a possible workaround.

**Comment by avdb13** [comment]
Updated my lightline and seems to work right now in both vim and gvim for some reason. Thanks if you changed anything in the main branch.
