### ISSUE TITLE
dont show anything in statusbar if window is below a certain size

### ISSUE THREAD

**Issue by joe23rep** [itchyny/lightline.vim#537]
is there a possibilty to have an empty statusbar if the window is small? like for example the side windows uve when u open coc explorer/ nerd tree or stuff like tagbar?

ive tried a config ive found somewhere else which does this sort of thing but just for one part of the statusbar

```
function! LightlinePercent() abort
    if winwidth(0) < 60
        return ''
    endif

    let l:percent = line('.') * 100 / line('$') . '%'
    return printf('%-4s', l:percent)
endfunction
```

this only shows the percentage when the windowsize is above 60 but with this function the % starts from the left. so when uve 100% it looks like it should but if its 99 or 9 it has 1 or 2 whitespaces next to it. so i stopped using it. 

so is there a possibilty to get rid of all of this via a command or would i need to do this for every component i use in my active statusbar?

and if so- is there a wiki page or something like that which shows how the single modes are configured? like percentage seems to be `line('.') * 100 / line('$') . '%'`. but what is the code for mode, paste, filetype, lineinfo etc etc

**Comment by yhu266** [comment]
See https://github.com/itchyny/lightline.vim#can-i-trim-the-file-format-and-encoding-information-on-narrow-windows

**Comment by itchyny** [comment]
> so is there a possibilty to get rid of all of this via a command or would i need to do this for every component i use in my active statusbar?

There is no way to do this in this plugin.

**Comment by joe23rep** [comment]
so id need to do it for every component i use. is there a list what these components perform?

**Comment by yhu266** [comment]
> so id need to do it for every component i use. is there a list what these components perform?
> 
> id need to know the functions for mode, filetype, lineinfo and percent
> 
> or is there a way to return these directly- like for example:
> 
> ```
> function! LightlinePercent() abort
>     if winwidth(0) < 60
>         return ''
>     endif
> 
>     return 'percent'
> endfunction
> ```

Well, from your config file: https://github.com/joe23rep/neovim/blob/master/config/lightline.vim, you have figured it out :)

**Comment by zhiyuanzhai** [comment]
I'm considering an alternative solution. How about this?
```vim
if winwidth(0) > 60
    let g:lightline = {...} " Your configuration.
else
    let g:lightline = {}
endif
```

**Comment by zhiyuanzhai** [comment]
@yhu266 But he did this separately for each component, which is not an elegant manner. I think it's better to get this done altogether, with a trigger or something...

**Comment by itchyny** [comment]
Repeat the conditional statement in each component functions. Providing a way to control all the components based on the width leads to component allow/denylists or configuration key for the window widths to hide each components. Someone may want to hide components based on the buffer filetypes. Providing such ways to control visibility blows up the configurations of the plugin and sacrifices the performance.
