### ISSUE TITLE
[Help] Is there a way to define a highlight color for `info & hints` from coc.

### ISSUE THREAD

**Issue by AlaaSaadAbdo** [itchyny/lightline.vim#539]
Hi

Thanks for the tool I started using it recently and I got the integration with coc going quite well, my only problem is that I can't display hints and infro that comes from coc diagnostic in a specific color similar to error and warning.

I wanted to know if there's a component_type for them similar to:

```
	let s:p.normal.error = [ [ ... ] ]
	let s:p.normal.warning = [ [ ... ] ]
```

And if not is there a way to specify a color/highlight group just for hints and info?

Cheers!

**Comment by itchyny** [comment]
There is no way to do this officially.

**Comment by yhu266** [comment]
If all you need is a change of colors, could you try modifying:

https://github.com/neoclide/coc.nvim/blob/dda9114c36c6cac3aafbc0e9220c978b8f06da0c/plugin/coc.vim#L332-L333

**Comment by AlaaSaadAbdo** [comment]
@yhu266 

I tried that but it has no effect on the signs shown in lightline. it only works for the signcolumn
