### ISSUE TITLE
lightline not working

### ISSUE THREAD

**Issue by zuluworm** [itchyny/lightline.vim#540]
When following the directions and putting all the necessary files in their respective location...the lightline theme is the only thing not working.  I dont want to use automated script so I have been validating the files and placing them manually. Im using zsh shell and vim 8.2.850

 I attempted to add the following command but it didnt work "set laststatus=2"

Can anyone assist?

**Comment by yhu266** [comment]
Could you share your configuration files and related directory structure?

**Comment by zuluworm** [comment]
Here are the attached config files.  I shared the entire .vim folder. I had to use the command ls -la to view it. Please let me know if you want the files in a different format. Thanks again for the quick response!

[Config files.zip](https://github.com/itchyny/lightline.vim/files/5767820/Config.files.zip)

**Comment by yhu266** [comment]
You did not include either `.vimrc` or `init.vim`. They usually contain information about how you load `lightline` as a plugin.

**Comment by zuluworm** [comment]
Sorry, here is the vimrc file that I have. Thanks in advance for your help!

[vimrc.txt.zip](https://github.com/itchyny/lightline.vim/files/5767939/vimrc.txt.zip)

**Comment by yhu266** [comment]
Well, since you do not use any plugin manager, I think you need to follow https://github.com/itchyny/lightline.vim#vim-packages-since-vim-741528 and install `lightline` in the correct directory.

**Comment by zuluworm** [comment]
Do you mean all I have to do is just cp the file "lightline.vim" in the link you sent into the autoload folder?

**Comment by yhu266** [comment]
It's not about `autoload`. The method (for vim) is described here: https://vimhelp.org/repeat.txt.html#packages

**Comment by rossdotpink** [comment]
Sorry to hijack but I am experiencing the exact same issue.

- vanilla install of macOS 10.15
- bare minimum `.vimrc`

I followed the instructions as per the README, it just doesn't work. My `.vimrc`:

```
set number
set noshowmode
if !has('gui_running')
   set t_Co=256
 endif
```

**Comment by yhu266** [comment]
> Sorry to hijack but I am experiencing the exact same issue.
> 
> 
> 
> - vanilla install of macOS 10.15
> 
> - bare minimum `.vimrc`
> 
> 
> 
> I followed the instructions as per the README, it just doesn't work. My `.vimrc`:
> 
> 
> 
> ```
> 
> set number
> 
> set noshowmode
> 
> if !has('gui_running')
> 
>    set t_Co=256
> 
>  endif
> 
> ```

There is no `set laststatus=2` in your `.vimrc`.

**Comment by itchyny** [comment]
Please use a plugin manager to install Vim plugins. This is not an issue of lightline.vim so closing.
