### ISSUE TITLE
Incorrect counting column number for utf strings

### ISSUE THREAD

**Issue by EvgeniyRRU** [itchyny/lightline.vim#542]
Hello, it seems, I faced with a bug. It incorrect counts column numbers for `UTF` characters. See screenshots:
**itchyny/lightline.vim** - incorrect counting.
<img width="611" alt="vim-lightline-1" src="https://user-images.githubusercontent.com/3672367/104090133-875bcb00-5285-11eb-917b-e2d25c11446b.png">
<img width="278" alt="vim-lightline-2" src="https://user-images.githubusercontent.com/3672367/104090139-8f1b6f80-5285-11eb-989e-c8e1e77d576b.png">

**vim-airline/vim-airline** - works fine.
<img width="619" alt="vim-airline-1" src="https://user-images.githubusercontent.com/3672367/104090146-96db1400-5285-11eb-9736-3b2a1f9811d7.png">
<img width="430" alt="vim-airline-2" src="https://user-images.githubusercontent.com/3672367/104090151-9c385e80-5285-11eb-9ee0-1c078e52bffe.png">

**Comment by itchyny** [comment]
This is an expected behavior, it shows the byte column number by design. It uses `%c` of `:h 'statusline'`.  If you want the virtual offset (note that virtual offset is different from character count), configure as follows.
```vim
let g:lightline = {
      \ 'component': {
      \   'lineinfo': '%3l:%-2v',
      \ }
      \ }
```
