### ISSUE TITLE
Lightline only working after PlugInstall despite being installed

### ISSUE THREAD

**Issue by JohnstonLiu** [itchyny/lightline.vim#543]
Lightline will not work on launch. However, when I call `:PlugInstall` and `:q` out of the new window I will have lightline working in my old window. This is my vimrc.

```
if has('gui_running')
    set guifont=Cascadia_Mono:h11
endif

call plug#begin('c:\Program Files\Vim\Plugins')

Plug 'itchyny/lightline.vim'
Plug 'morhetz/gruvbox'

call plug#end()

" Editor settings
set encoding=utf-8
set relativenumber " Show's relative line numbers
set number         " Show's current line
set signcolumn=no
syntax on
set hidden
set belloff=all
set guicursor=a:blinkon0
colorscheme gruvbox 
set noshowmode
set laststatus=2

" Tabs
set tabstop=4     " Tab characters appear n-spaces-wide
set shiftwidth=4  " The size of an indent
set expandtab

" Lightline

let g:lightline = {
      \ 'colorscheme': 'gruvbox',
      \ }

autocmd filetype cpp nnoremap <F1> :w <bar> exec '!g++ -std=c++14 ' .shellescape('%').' -o '.shellescape('%:r').' && 'shellescape('%:r')<CR>
nnoremap <F2> :%y+ <CR>

au GUIEnter * simalt ~x
```

**Comment by yhu266** [comment]
Would `lightline` work if you remove this line?
```vim
au GUIEnter * simalt ~x
```

It's most likely related to
https://github.com/itchyny/lightline.vim/blob/53176a0b75d6389d775d7bce0d494e58fc654f38/plugin/lightline.vim#L18

**Comment by JohnstonLiu** [comment]
> Would `lightline` work if you remove this line?
> 
> ```viml
> au GUIEnter * simalt ~x
> ```
> 
> It's most likely related to
> https://github.com/itchyny/lightline.vim/blob/53176a0b75d6389d775d7bce0d494e58fc654f38/plugin/lightline.vim#L18

Just tried that didn't work.

**Comment by JohnstonLiu** [comment]
After testing I found that lightline is not automatically enabled for some reason. When I 
`call lightline#init()` it doesn't do anything but when I do `call lightline#enable()` lightline will then show. Regardless, why is it that lightline is not automatically enabled?

**Comment by itchyny** [comment]
Please describe your OS and Vim versions. Also try reinstalling the plugin after removing the directories. Possible reason is permission issues.

**Comment by JohnstonLiu** [comment]
> Please describe your OS and Vim versions. Also try reinstalling the plugin after removing the directories. Possible reason is permission issues.

I'm on Windows 10 and on Vim version 8.2. I have tried reinstalling the plugin to no avail.

**Comment by itchyny** [comment]
Paste the output of `:echo &statusline`.

**Comment by JohnstonLiu** [comment]
> Paste the output of `:echo &statusline`.

There is no output.

**Comment by itchyny** [comment]
Then `:scriptnames`.

**Comment by JohnstonLiu** [comment]
> Then `:scriptnames`.


```
  1: C:\Program Files\Vim\vim82\defaults.vim
  2: C:\Program Files\Vim\vim82\syntax\syntax.vim
  3: C:\Program Files\Vim\vim82\syntax\synload.vim
  4: C:\Program Files\Vim\vim82\syntax\syncolor.vim
  5: C:\Program Files\Vim\vim82\filetype.vim
  6: C:\Program Files\Vim\vim82\menu.vim
  7: C:\Program Files\Vim\vim82\autoload\paste.vim
  8: C:\Program Files\Vim\vim82\ftplugin.vim
  9: C:\Program Files\Vim\vim82\indent.vim
 10: C:\Program Files\Vim\vim82\plugin\getscriptPlugin.vim
 11: C:\Program Files\Vim\vim82\plugin\gzip.vim
 12: C:\Program Files\Vim\vim82\plugin\logiPat.vim
 13: C:\Program Files\Vim\vim82\plugin\manpager.vim
 14: C:\Program Files\Vim\vim82\plugin\matchparen.vim
 15: C:\Program Files\Vim\vim82\plugin\netrwPlugin.vim
 16: C:\Program Files\Vim\vim82\plugin\rrhelper.vim
 17: C:\Program Files\Vim\vim82\plugin\spellfile.vim
 18: C:\Program Files\Vim\vim82\plugin\tarPlugin.vim
 19: C:\Program Files\Vim\vim82\plugin\tohtml.vim
 20: C:\Program Files\Vim\vim82\plugin\vimballPlugin.vim
 21: C:\Program Files\Vim\vim82\plugin\zipPlugin.vim
 22: ~\_gvimrc
 23: ~\vimfiles\autoload\plug.vim
 24: C:\Program Files\Vim\vim82\ftoff.vim
 25: C:\Program Files\Vim\vim82\syntax\nosyntax.vim
 26: c:\Program Files\Vim\Plugins\gruvbox\colors\gruvbox.vim
```

**Comment by yhu266** [comment]
Maybe it's related to https://github.com/junegunn/vim-plug/issues/540#issuecomment-258325522

**Comment by JohnstonLiu** [comment]
> Maybe it's related to [junegunn/vim-plug#540 (comment)](https://github.com/junegunn/vim-plug/issues/540#issuecomment-258325522)
> 
> In short
> 
> > So if you have plug#end() in .gvimrc, &runtimepath is updated after step 4 and plugins will not be correctly loaded.

Yep thank you! I have to put vim plug configuration in my _vimrc instead of my _gvimrc. Sorry for the trouble!

**Comment by Paulario** [comment]
Hi, I have a similar problem. but :echo &statusline yields the following:
![image](https://user-images.githubusercontent.com/44346150/111199485-57081400-85c9-11eb-869d-840ca124ecfe.png)

but nothing I see.

and `:call lightline#enable()` doesn't work.

I'm running Windows Subsystem For Linux (WSL) under Windows 10.

**Comment by itchyny** [comment]
@Paulario `:echo &laststatus`

**Comment by Paulario** [comment]
> @Paulario `:echo &laststatus`

just number 15. I set laststatus=15 in my config file

![image](https://user-images.githubusercontent.com/44346150/111207667-94bd6a80-85d2-11eb-87c3-b01ecac111b0.png)
and it works sometimes. One of the ways it appears is in the vim-plug window. Didn't see it anywhere else

**Comment by itchyny** [comment]
@Paulario Please read `:h laststatus`.
