### ISSUE TITLE
Displaying FugitiveHead with icons

### ISSUE THREAD

**Issue by sp1n0r** [itchyny/lightline.vim#544]
I have the following configuration

```
let g:lightline = {
      \ 'component_function': {
      \   'gitbranch': 'FugitiveHead' },
(...)
      \ 'active': {
      \   'left': [
      \     [ 'mode', 'filesymb', 'paste' ],
      \     [ 'gitbranch', 'readonly', 'filename', 'modified' ] ],
(...)
      \  }
```
It works fine but it doesn't have icons although I have devicons. Do people usually use another function or?

**Comment by itchyny** [comment]
Yes, create a function component and prepend your favorite icon string.

**Comment by sp1n0r** [comment]
Oh ok I thought that there might be some other function with icons, thanks
