### ISSUE TITLE
Under the doc>colorscheme list: 'darcula' means 'dracula', right?

### ISSUE THREAD

**Issue by je-on** [itchyny/lightline.vim#545]
I think there's one minor typo, there.
You can check with
':h g:lightline.colorscheme'.
Thanks

**Comment by yhu266** [comment]
It's not a typo. `darcula` and `dracula` are two colorschemes.

**Comment by je-on** [comment]
Oops, really sorry about that.
I only knew about 'Dracula', sorry again.

**Comment by avdb13** [comment]
I wish I could nominate this for "best Github issue of year" 🤣 
But yeah, common confusion that probably crossed anyone's mind at some point.
