### ISSUE TITLE
Lightline.vim doesn't appear immediatly

### ISSUE THREAD

**Issue by El-Patron-Salan** [itchyny/lightline.vim#546]
I found problem in command:
autocmd VimEnter * NERDTree | wincmd p
Probably it's because it puts cursor from Nerdtree to other window and then lightline doesn't appear, but when we change it to Nerdtree back it shows.
After deleting wincmd p from it, lightline works fine

**Comment by yhu266** [comment]
This is a known issue https://github.com/itchyny/lightline.vim/issues/487#issuecomment-660382253

**Comment by itchyny** [comment]
This is not a a bug of lightline.vim, but expected behavior due to the spec of Vim's auto-commands. Please refer to `:h autocmd`, `:h autocmd-nested`.

**Comment by El-Patron-Salan** [comment]
Okay, thanks for a pointing an answer for this, it helped a lot and sorry for a useless issue.
