### ISSUE TITLE
lightline doesn't appear

### ISSUE THREAD

**Issue by ChavaTI** [itchyny/lightline.vim#549]
I've configured lightline like the image shows, but it doesn't appear.
I'm using neovim 0.5.0

![image](https://user-images.githubusercontent.com/35637860/107895588-8445a180-6ef9-11eb-8d19-82c818701859.png)

**Comment by itchyny** [comment]
Please share your entire init.vim.

**Comment by ChavaTI** [comment]
Nevermind It just appeared !!! I only restarted konsole
