### ISSUE TITLE
I can't make devicons work for lightline

### ISSUE THREAD

**Issue by Godnyx** [itchyny/lightline.vim#550]
I searched everywhere but didn't found anything! They font works for nerdtree but not for lightline. Is there a setting I must enable?

**Comment by yhu266** [comment]
Please refer to https://github.com/itchyny/lightline.vim/issues/541#issuecomment-757618134 and provide more information.

**Comment by itchyny** [comment]
Include your favorite icon characters in components or return value of function components. If it does not work, comment your expectation with your configuration and some screenshots.
