### ISSUE TITLE
Display the correct name of neovim's terminal buffers (term://...)

### ISSUE THREAD

**Issue by camoz** [itchyny/lightline.vim#551]
Neovim has special terminal buffers, which are typically named `term://...`. From `:h terminal-start`:

```
There are several ways to create a terminal buffer:

- Invoke the |:terminal| command.
- Call the |termopen()| function.
- Edit a file with a name matching `term://(.{-}//(\d+:)?)?\zs.*`.
  For example:

    :edit term://bash
    :vsplit term://top
```

As far as I can see, lightline currently uses `%t` for displaying the current filename. I don't know the internals, but `%t` probably strips away anything before (and including) the last slash. This leads to wrong display of the current buffer name in lightline for neovim's terminal buffers.

# Steps to reproduce

Run `:term ls /tmp` inside neovim using lighline.vim.

**Expected behavior**: Displayed buffer name similar to `term://.//32784:ls /tmp`, like it is displayed correctly when run e.g. via `neovim -u NONE`.

**Actual behavior**: Displayed buffer name is `tmp`.

# Possible solution

Maybe test if the current buffer name starts with `term://`, then use `%` for the filename, else use `%t`.

**Comment by itchyny** [comment]
Please configure the filename component.
```vim
let g:lightline = {
      \ 'component_function': {
      \   'filename': 'LightlineFilename',
      \ },
      \ }
function! LightlineFilename()
  if &buftype ==# 'terminal'
    return expand('%:p')
  elseif expand('%:t') !=# ''
    return expand('%:t')
  else
    return '[No Name]'
  endif
endfunction
```

**Comment by camoz** [comment]
Thanks for the snippet.

What do you think about adding this to the "FAQ" section in the README? I don't know if lighline.vim officially supports neovim, but if yes then it seems reasonable to me to display a correct buffer description for terminal buffers, since they are a common part of neovim now. If adding the above snippet to lightline.vim itself is deemed too much custom/bloat (which I can understand), including it in the FAQ seems like a good compromise to me.

Sorry if I'm missing something obvious here, I'm not very familiar with vim plguins or neovim internals.
