### ISSUE TITLE
When the syntax suggestion is shown, suddenly the lightline disappears.

### ISSUE THREAD

**Issue by davidclegg05** [itchyny/lightline.vim#553]
I need a help! I use the `vim-lsp` and `asyncomplete.vim`.
When writing a python code:
![Peek 2021-02-26 16-45](https://user-images.githubusercontent.com/79688091/109271248-9c4ee680-7852-11eb-9029-be607206c07a.gif)
when writing a C lang code:
![Peek 2021-02-26 16-47](https://user-images.githubusercontent.com/79688091/109271270-a375f480-7852-11eb-9d0b-12dfbbc7fbf0.gif)
However, I don't see this issue on other PCs with another OS (linux mint) installed.(same virsion and same init.vim). What could be the cause of this issue? Since it happens in both Python and C, is it related to asyncomplete and not vim-lsp?

Environment:
```
OS: manjaro linux

init.vim: https://github.com/davidclegg05/neovim_config/blob/main/init.vim
scriptnames: https://github.com/davidclegg05/neovim_config/blob/main/script_names.txt
version:
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe
-fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall
-Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wco
nversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong
-fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURC
E -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/con
fig -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/sr
c/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by itchyny** [comment]
This looks like the same issue of #552. The issue will be fixed by upgrading the Neovim version.

**Comment by davidclegg05** [comment]
Thank you!
I installed neovim-nightly(NVIM v0.5.0-dev+1114-g0c7610cf9) and it works fine.
