### ISSUE TITLE
My statusline appears to work incorrectly

### ISSUE THREAD

**Issue by wenbochang888** [itchyny/lightline.vim#557]
I use vim-plug to install

Plug 'itchyny/lightline.vim'  

I install plug and restart the vim

i don't why the statusline appears to work incorrectly

like this:

thank you!

![微信截图_20210323214550.png](https://x.int64ago.org/73349f23-1201-4424-98a2-6184f830baa9.png)

**Comment by itchyny** [comment]
The statusline of your screenshot looks like that of vim-airline. You cannot install both vim-airline and lightline.vim at once.

**Comment by wenbochang888** [comment]
@itchyny 
I try to delete vim-airline.  The lightline works.

thank you very much.
