### ISSUE TITLE
[Question] Tabline

### ISSUE THREAD

**Issue by TornaxO7** [itchyny/lightline.vim#560]
Hello! First of all: Thank you for this plugin! It's very fast and easy to configure :)
But I've got one question: How can I *always* display the tabline? It's only showing up, if I have two tabs but I'd like to see the closed buffers as well like in vim-airline. Do you have an Idea how I can achieve that?

**Comment by itchyny** [comment]
Configure as follows.
```vim
set showtabline=2
```

**Comment by TornaxO7** [comment]
Thank you! It's working now :)
