### ISSUE TITLE
tabline didn't appear correctly, i use gvim

### ISSUE THREAD

**Issue by leo-frank** [itchyny/lightline.vim#561]
first thanks for such a brilliant plugin 

here is problem:
look this picture, there are two tabs, but the tabline looks bad, which is the origin tabline before I install lightline.vim
![image](https://user-images.githubusercontent.com/47302141/112740815-a16a9700-8fb2-11eb-8fa9-52d0db7cd979.png)

i thought lightline.vim will look like this:
![image](https://user-images.githubusercontent.com/47302141/112740933-7f254900-8fb3-11eb-8c38-e754daa38ad8.png)

by the way, i use gvim on windows, thanks!

**Comment by itchyny** [comment]
```vim
set guioptions-=e

set showtabline=2 " if you want to show tabline with one tab
```
