### ISSUE TITLE
Can I colorize characters inline?

### ISSUE THREAD

**Issue by osenvosem** [itchyny/lightline.vim#563]
I have functions that return strings that I use for displaying statuses in the status line (errors, warnings, git statuses). I would like to colorize those statuses. How can I do that? Can I do that inline, inside returning strings?

<img width="448" alt="Screenshot 2021-03-31 at 21 39 30" src="https://user-images.githubusercontent.com/6762673/113194399-c63c6400-9269-11eb-9c7e-ca9fdf7a69bf.png">

**Comment by itchyny** [comment]
This is impossible in this plugin. See `:h lightline-problem-12`.

**Comment by itchyny** [comment]
Learn how to color errors and warnings in `:h lightline-component-expansion`.
