### ISSUE TITLE
Overriding color of ligthline components

### ISSUE THREAD

**Issue by cwlittle** [itchyny/lightline.vim#564]
Is there any way to change the color of the background of the lightline status bar? 
I'm using the apprentice color scheme for the bar along with apprentice as my vim color scheme and the consistent background color between two separate split windows makes it a bit difficult to discern where one starts and the other begins, especially when I have a split terminal open. 
For example: 
![Screen Shot 2021-04-03 at 2 45 00 PM](https://user-images.githubusercontent.com/15937987/113489777-a2586880-948b-11eb-81d4-f5126b853284.png)
It doesn't look too terrible while static, but when things are moving and I'm trying to develop it causes me to have to do double takes to make sure I'm able to reach the correct line.

**Comment by itchyny** [comment]
You can override some colors in the palette, see https://github.com/itchyny/lightline.vim/issues/168#issuecomment-569881983.
