### ISSUE TITLE
Show full file name in tabline for active tab

### ISSUE THREAD

**Issue by xianshuli** [itchyny/lightline.vim#566]
When opening multiple tabs with long file name, the filename in tabline will be truncated. Is there any setting to always show full filename in tabline for active tab? For instance, in the screenshot `tab1`'s name got truncated from `some_long_long_long_long_long_long_long_name_file` to `g_long_long_long_long_name_file`, is there anyway to make `tab1` showing `some_long_long_long_long_long_long_long_name_file` while leaving `tab2` truncated? I think it makes more sense to have the current active tab showing full file name.

![Screen Shot 2021-04-21 at 12 39 45 AM](https://user-images.githubusercontent.com/13989515/115620975-bc2ae580-a2aa-11eb-9360-44fdff726c93.png)

**Comment by itchyny** [comment]
Here's an example of overwriting the tabs component, truncate them if you like.
```vim
let g:lightline = {
      \   'component_expand': {
      \     'tabs': 'LightlineTabs'
      \   },
      \ }

function! LightlineTabs() abort
  let [x, y, z] = [[], [], []]
  let nr = tabpagenr()
  let cnt = tabpagenr('$')
  for i in range(1, cnt)
    call add(i < nr ? x : i == nr ? y : z, (i > nr ? '%<' : '') . '%' . i . 'T%{lightline#onetab(' . i . ',' . (i == nr) . ')}' . (i == cnt ? '%T' : ''))
  endfor
  " truncate x here
  return [x, y, z]
endfunction
```

**Comment by xianshuli** [comment]
Hi itchyny,

The feature I requested is to focus on the current active tab. If the current active tab is `tab1`, then it makes more sense for the tabline to focus on `tab1`. For example, if current active tab is `tab1`, then we can let the tabline starting with `1 some_long_long_long_long_long_long_long_name_file` and truncate some part of `tab2` if the screen is not wide enough. And if the current active tab is `tab2`, then we can let the tabline starting with `2 some_long_long_long_long_long_long_long_name_file` and doesn't show `tab1`. May I ask do you have any idea about how to implement that?

Thanks,
Xianshu

**Comment by itchyny** [comment]
If you want to display the name of the active tab, you need to truncate the left tab names or right tab names.
