### ISSUE TITLE
Middle Component

### ISSUE THREAD

**Issue by Shadorain** [itchyny/lightline.vim#569]
Hello! I was just trying to play around with my bar more and have a middle component be centered, would be my modes, but just noticed that there is no support for this.
I thought there was because there are a lot of `.middle` settings for the color scheme itself but not usable as a component it seems. 

I believe it would be a very nice thing to add if you added a `'middle'` ability that is just like the `'left'` and `'right'` when configuring to have components centered in the bar.

Thank you!

**Comment by itchyny** [comment]
Unfortunately it is not possible to align some text in `statusline`, this is limitation of Vim. But if you add to the `left` component with carefully calculated spacing, and the lightline colorscheme does not have enough colors, it is displayed by the middle colors. For example, the [`wombat`](https://github.com/itchyny/lightline.vim/blob/master/autoload/lightline/colorscheme/wombat.vim) colorscheme has only two colors for `normal.left` so the third components in your config will displayed by the `middle` colors.

**Comment by Shadorain** [comment]
> Unfortunately it is not possible to align some text centering in `statusline`, this is limitation of Vim. But if you add to the `left` component with carefully calculated spacing, and the lightline colorscheme does not have enough colors, it is displayed by the middle colors. For example, the [`wombat`](https://github.com/itchyny/lightline.vim/blob/master/autoload/lightline/colorscheme/wombat.vim) colorscheme has only two colors for `normal.left` so the third components in your config will displayed by the `middle` colors.

okay interesting, yeh that is what I thought of doing with the spacing, I just was lazy I guess and didn't want to go to the work of calculating it. Yeah I made my own scheme so I'd figure that part out. Thanks man!
