### ISSUE TITLE
Adding the Gruvbox colorscheme

### ISSUE THREAD

**Issue by imranZERO** [itchyny/lightline.vim#570]
Hi, I've noticed that lightline doesn't come the gruvbox theme by default. It's loved by a lot of people including me.

https://github.com/shinchu/lightline-gruvbox.vim

This repo already has the theme implemented, so adding it won't be difficult at all. I can even open a PR if anyone's interested.

**Comment by itchyny** [comment]
The [gruvbox colorscheme](https://github.com/morhetz/gruvbox) already provides lightline colorscheme. Isn't that enough?
