### ISSUE TITLE
My status doesn't show lightline's colours

### ISSUE THREAD

**Issue by suhas-bn-1412** [itchyny/lightline.vim#572]
![image](https://user-images.githubusercontent.com/52152465/118121231-c73ae680-b40e-11eb-844d-032f668f2cfa.png)

**Comment by suhas-bn-1412** [comment]
The given picture is the complete vimrc file I have written

**Comment by itchyny** [comment]
Please share your entire vimrc in text so that I can test.

**Comment by suhas-bn-1412** [comment]
" install vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
 silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
   \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
 autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

"------------------------------------------------------------------------------
" Plug installed plugins

call plug#begin('~/.vim/plugged')
" Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'preservim/nerdtree'
Plug 'itchyny/lightline.vim'
call plug#end()
"------------------------------------------------------------------------------

" Turn on syntax highlighting
syntax on

" Show line numbers
set number

" tab uses this many spaces
set tabstop=8

" Status bar
set laststatus=2

" " Last line
set showmode
set showcmd

"------------------------------------------------------------------------------
" NERDtree
nnoremap <F1> :NERDTreeToggle<CR>
nnoremap <F2> :NERDTree<CR>
let g:NERDTreeDirArrowExpandable = '>'
let g:NERDTreeDirArrowCollapsible = '^'

"------------------------------------------------------------------------------
" lightline -> status bar
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ }
"------------------------------------------------------------------------------

**Comment by itchyny** [comment]
I can see the lightline colours with your vimrc. Please describe more information; Vim version, OS version, terminal version, `:echo [$TERM, &t_Co]`.

**Comment by suhas-bn-1412** [comment]
I actually login through ssh to this machine

Vim version: version 7.4.160
OS : Linux
:echo [$TERM, &t_Co] output -> ['screen', '8']

**Comment by itchyny** [comment]
Here's some solutions.

- Add `term "screen-256color"` to screenrc.
- Add `export TERM=xterm-256color` to bashrc.
- Add `set t_Co=256` to your vimrc.

**Comment by suhas-bn-1412** [comment]
After setting t_Co as 256 I'm getting the colours
