### ISSUE TITLE
devicons not showing

### ISSUE THREAD

**Issue by rudrab** [itchyny/lightline.vim#577]
Hi, 
First thing first: Thanks for this essential plugin.
I want you use devicons and I have added patched nerd-fonts for that purpose.
Unfortunately I am not getting the filetype icons in lightline. Attached is a sample screenshot of my lightline. 

![Screenshot from 2021-06-07 20-41-21](https://user-images.githubusercontent.com/4639447/121042303-2b17bb80-c7d1-11eb-9cce-e80faaf84f22.png)

My corresponding vimrc is:
```
colorscheme vimgnome
if has('gui_running')
  if has('gui_gtk3')
    set textwidth=99
    set colorcolumn=100
    set lines=55 columns=155
    set guioptions-=a
    set guioptions-=T
    set guioptions-=e
    set t_Co=256
    set guitablabel=%M\ %t
    set guifont=Source\ Code\ Pro\ 10
    set guifontwide=SauceCodePro\ Nerd\ Font\ Mono\ 10
  endif
endif

" lightline{{{
let g:lightline = {
      \ 'colorscheme': 'solarized',
      \ }
"}}}

```

Kindly help.

**Comment by itchyny** [comment]
You need to configure. For example, following configuration will show the icon on the left of the file name component.
```vim
let g:lightline = {
    \ 'component': {
    \ 'filename': '[icon] %t',
    \ },
    \ }
```

**Comment by rudrab** [comment]
Dear @itchyny 
Thanks for your response. Now my lightline is like:
```
" lightline{{{
let g:lightline = {
      \ 'colorscheme': 'solarized',
      \ 'component': {
        \ 'filename': '[icon] %t',
        \ },
        \ }
"}}}
```
But, in lightline, I am getting `[icon] foo.py` literally, as text
![Screenshot from 2021-06-08 10-14-04](https://user-images.githubusercontent.com/4639447/121124378-71f1c980-c842-11eb-90e2-3eb8db3306ea.png)
Please help.

**Comment by itchyny** [comment]
Replace the `[icon]` with the icon you want.

**Comment by rudrab** [comment]
Sir, I am confused. Can you please show an example?

**Comment by zys5945** [comment]
from :h devicons-lightline-setup

```
  let g:lightline = {
        \ 'component_function': {
        \   'filetype': 'MyFiletype',
        \   'fileformat': 'MyFileformat',
        \ }
        \ }
  
  function! MyFiletype()
    return winwidth(0) > 70 ? (strlen(&filetype) ? &filetype . ' ' . WebDevIconsGetFileTypeSymbol() : 'no ft') : ''
  endfunction
  
  function! MyFileformat()
    return winwidth(0) > 70 ? (&fileformat . ' ' . WebDevIconsGetFileFormatSymbol()) : ''
  endfunction
```

**Comment by rudrab** [comment]
I have tried that, but I am getting the error ": is missing after ?"
