### ISSUE TITLE
Live refreshing of status bar (and everything else)?

### ISSUE THREAD

**Issue by zhiyuanzhai** [itchyny/lightline.vim#578]
It seems that the contents on the status bar can not refresh in real time. They can only refresh when hitting a key by default. Is it possible to real-time refresh the status bar like what we do in other editors, e.g., VSCode?

**Comment by itchyny** [comment]
It is possible to redraw the statusline using timer.
```vim
call timer_start(1000, {->execute('redrawstatus!')}, #{repeat: -1})
```
