### ISSUE TITLE
Colorscheme didn't show up when configured .vimrc

### ISSUE THREAD

**Issue by waynezhangw** [itchyny/lightline.vim#579]
My whole .vimrc is:
" Comments in Vimscript start with a `"`.

" If you open this file in Vim, it'll be syntax highlighted for you.

" Vim is based on Vi. Setting `nocompatible` switches from the default
" Vi-compatibility mode and enables useful Vim functionality. This
" configuration option turns out not to be necessary for the file named
" '~/.vimrc', because Vim automatically enters nocompatible mode if that file
" is present. But we're including it here just in case this config file is
" loaded some other way (e.g. saved as `foo`, and then Vim started with
" `vim -u foo`).

" ------------------plugins-----------------
" 1.lightline.vim
let g:lightline = { 'colorscheme': 'wombat' }

" 2.easy-motion
" map <Space> <Plug>(easymotion-prefix)

" 3.ctrlp
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'

set nocompatible
set hlsearch

" Turn on syntax highlighting.
syntax on

" Disable the default Vim startup message.
set shortmess+=I

" Show line numbers.
set number

" Turn of automated
set paste

" This enables relative line numbering mode. With both number and
" relativenumber enabled, the current line shows the true line number, while
" all other lines (above and below) are numbered relative to the current line.
" This is useful because you can tell, at a glance, what count is needed to
" jump up or down to a particular line, by {count}k to go up or {count}j to go
" down.
set relativenumber

" Always show the status line at the bottom, even if you only have one window open.
set laststatus=2

" The backspace key has slightly unintuitive behavior by default. For example,
" by default, you can't backspace before the insertion point set with 'i'.
" This configuration makes backspace behave more reasonably, in that you can
" backspace over anything.
set backspace=indent,eol,start

" By default, Vim doesn't let you hide a buffer (i.e. have a buffer that isn't
" shown in any window) that has unsaved changes. This is to prevent you from "
" forgetting about unsaved changes and then quitting e.g. via `:qa!`. We find
" hidden buffers helpful enough to disable this protection. See `:help hidden`
" for more information on this.
set hidden

" This setting makes search case-insensitive when all characters in the string
" being searched are lowercase. However, the search becomes case-sensitive if
" it contains any capital letters. This makes searching more convenient.
set ignorecase
set smartcase

" Enable searching as you type, rather than waiting till you press enter.
set incsearch

" Unbind some useless/annoying default key bindings.
nmap Q <Nop> " 'Q' in normal mode enters Ex mode. You almost never want this.

" Disable audible bell because it's annoying.
set noerrorbells visualbell t_vb=

" Enable mouse support. You should avoid relying on this too much, but it can
" sometimes be convenient.
set mouse+=a

" Try to prevent bad habits like using the arrow keys for movement. This is
" not the only possible bad habit. For example, holding down the h/j/k/l keys
" for movement, rather than using more efficient movement commands, is also a
" bad habit. The former is enforceable through a .vimrc, while we don't know
" how to prevent the latter.
" Do this in normal mode...
nnoremap <Left>  :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up>    :echoe "Use k"<CR>
nnoremap <Down>  :echoe "Use j"<CR>
" ...and in insert mode
inoremap <Left>  <ESC>:echoe "Use h"<CR>
inoremap <Right> <ESC>:echoe "Use l"<CR>
inoremap <Up>    <ESC>:echoe "Use k"<CR>
inoremap <Down>  <ESC>:echoe "Use j"<CR>
![image](https://user-images.githubusercontent.com/42730998/121783775-285b0300-cbe3-11eb-8c49-294ddbc94cc5.png)

**Comment by waynezhangw** [comment]
I am using zsh (5.0.2) in centos (7.9) on Alibaba Cloud Elastic Compute Service

**Comment by itchyny** [comment]
Can you `call lightline#enable()`? How do you install lightline?

**Comment by waynezhangw** [comment]
Where should I put call lightline#enable()? 
I install lightline by git clone it to ~/.vim/pack/vendor/start/ by following the suggestion from https://missing.csail.mit.edu/2020/editors/
![image](https://user-images.githubusercontent.com/42730998/121793239-b9f06200-cc2f-11eb-8834-77a18001577a.png)

**Comment by itchyny** [comment]
Your screenshot looks like you don't install lightline plugin. Make sure to install it and confirm with `:call lightline#enable()` command (this is NOT a command to put into vimrc).

**Comment by waynezhangw** [comment]
```:call lightline#enable()``` get E117 unknown function lightline#enable
I even install it in ~/.vim/bundle and ~/.vim/autoload, still didn't work. But it works on my mac.

**Comment by itchyny** [comment]
Make sure `:echo &rtp` includes the directory of lightline plugin you cloned.

**Comment by waynezhangw** [comment]
```:echo &rtp``` shows : /root/.vim,/usr/share/vim/vimfiles,/usr/share/vim/vim74,/usr/share/vim/vimfiles/after,/root/.vim/after,
I add ```set runtimepath+=~/.vim/pack/vendor/start/lightline.vim``` to vimrc, the Colorscheme finally shows up!
But how can I automatically set the runtimepath of each vim plugin everytime I install it?

**Comment by itchyny** [comment]
What's your Vim version BTW? You don't need to add the pack directory to runtimepath.

**Comment by waynezhangw** [comment]
Vim version is 7.4, is this version having some issues with runtimepath of vim plugin?

**Comment by itchyny** [comment]
That's too old. The package feature was implemented in 7.4.1528 (in 2016) so make sure to update Vim.

**Comment by waynezhangw** [comment]
It works after I upgraded vim to 8.2.
Thanks a lot!!!
