### ISSUE TITLE
nvim: text inserting line is highlighted with the same color defined by LightlineRight_insert_0

### ISSUE THREAD

**Issue by JohnRama** [itchyny/lightline.vim#580]
Thank you for the great plugin.                                               
However, I have one problem.                                                  
                                                                              
- Problem                                                                     
	- when trying to input Japanese Language, the line is               
		highlighted the same color which is defined in highlight group            
		"LightlineRight_insert_0".  (See attached png file below)                           

- Expected Behavior
	- No highlight is expected for the line.
                                                                              
- Fact                                                                        
	- Highlighted color is same as the LightlineRight_insert_0.                  
		If we change the setting for LightlineRight_insert_0, then the            
		highlighted color changed accordingly.                                      
	- The problem happens when trying to input Japanese language in insert mode 
		No problem when trying to input alphabet.                                 
	- The problem happens when using nvim.                                      
		no problem with vim (8.2)                                                 
	- The problem does not happen when the window size is half                  
		by using vsplit                                                           
	- The problem happens on mac, not windows.                                  
	- The problem does not happens with the small line files(5 lines or so).    
		The problem happens with [hoge.txt](https://github.com/itchyny/lightline.vim/files/6647801/hoge.txt) which has more than 180 lines.                                
	- tmux is not related.                                                      
		The problem happens even when tmux is not used.                           
                                                                              
- version                                                                     
	$ nvim --version                                                            
	NVIM v0.4.4                                                                 
	Build type: Release                                                         
	LuaJIT 2.1.0-beta3                                                          
                                                                              
	$ cd ~/.config/nvim/dein/repos/github.com/itchyny/lightline.vim/plugin      
	$ git log                                                                   
		commit 8a712365f9708044667589d9fffd87a4825d29f6 (HEAD -> master)          
		Author: itchyny <itchyny@hatena.ne.jp>                                    
		Date:   Sun Mar 21 17:29:18 2021 +0900                                    
                   add screenshot of apprentice to colorscheme.md     
                   
Thanks for the help !!
John

[hoge.txt](https://github.com/itchyny/lightline.vim/files/6647805/hoge.txt)
![Pasted Graphic 5](https://user-images.githubusercontent.com/6152843/121882142-245fdb80-ccde-11eb-87e7-05d77267460a.png)

**Comment by itchyny** [comment]
I'm Japanese and tried to reproduce the issue but it doesn't. But anyway this looks like a rendering bug of NeoVim. Can you create a reproducible steps without lightline? I don't think there is some workaround to do in this plugin.

**Comment by JohnRama** [comment]
Thanks for the quick response. 

> Can you create a reproducible steps without lightline?
I tried couple of times before, but could not reproduce it. 

Question is why it's highlighted as LightlineRight_insert_0 ?
Do you have any idea on this ?
>Highlighted color is same as the LightlineRight_insert_0.
>If we change the setting for LightlineRight_insert_0, then the
>highlighted color changed accordingly.

I put my config files just for your reference.


```
# init.vim

" -----------------------
" dein
" -----------------------

	let g:dein#auto_recache = 1

	" pluin install dir
	let s:nvim_config_dir = expand('~/.config/nvim')

	let s:dein_dir = s:nvim_config_dir . '/dein'
	let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
	let s:toml = s:nvim_config_dir . '/dein.toml'
	let s:lazy_toml = s:nvim_config_dir . '/dein_lazy.toml'

	" Download from github if there is no dein.vim
	if &runtimepath !~# '/dein.vim'
		if !isdirectory(s:dein_repo_dir)
			execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
		endif
		execute 'set runtimepath^=' . fnamemodify(s:dein_repo_dir, ':p')
	endif

	if dein#load_state(s:dein_dir)
		call dein#begin(s:dein_dir)

		call dein#load_toml(s:toml, {'lazy': 0})

		call dein#end()
		call dein#save_state()
	endif

	filetype plugin indent on

"-----------------------
"   colorscheme
"-----------------------
	colorscheme solarized
	let g:solarized_termcolors=256
	"set background=dark
	"highlight Normal ctermfg=none ctermbg=none
	"highlight Normal ctermbg=none
	"highlight CursorLine cterm=underline ctermfg=NONE ctermbg=NONE


```

```
# dein.toml

[[plugins]]
repo = 'Shougo/dein.vim'

# -----------------------
# colorscheme
# -----------------------
[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_add = '''
	"echo "hello"
'''
```

**Comment by JohnRama** [comment]
>>  Can you create a reproducible steps without lightline?
>
> I tried couple of times before, but could not reproduce it.

I tried again, and you are right.  I could reproduce it without lightline.
I could not notice before that because the highlighted color is different. 

This is definitely not a problem of lightline. So, I'll close it. 
Thank you for your time.
