### ISSUE TITLE
NERDTreee err

### ISSUE THREAD

**Issue by Dolfost** [itchyny/lightline.vim#581]
When I open the vim, on the left I have an open NERDTree window, when I hide it with a combination of ctrl-t, the lightline disappears. Probably the lightline is tied to one window of vim. How to repair it?
https://drive.google.com/drive/folders/1_kFMc-z24Qd7GmTkrPdVJpZN1XA-G5Mk?usp=sharing

**Comment by itchyny** [comment]
How about `set laststatus=2` as described in [README.md#introduction](https://github.com/itchyny/lightline.vim#introduction)?

**Comment by Dolfost** [comment]
> How about `set laststatus=2` as described in [README.md#introduction](https://github.com/itchyny/lightline.vim#introduction)?

Yes, it helped. sorry for bothering ... This is because everything looked as it should, and then I discovered this error and forgot about this advice which is described in the way.
