### ISSUE TITLE
How can I highlight the tabline?

### ISSUE THREAD

**Issue by Photonico** [itchyny/lightline.vim#582]
This is my tabline
![](https://raw.githubusercontent.com/Photonico/Problems/master/2021/Screenshot_20210706_193702.png)

I want a highlight tabline: highlight the "filetype" and "tabs" like the "mode" in statusline.

**Comment by itchyny** [comment]
Officially I recommend to create a new colorscheme of lightline (see `:h lightline-colorscheme`). But you can overwrite the `s:palette.tabline.right` of the lightline colorscheme palette. See #431 for reference.

```vim
let s:palette = g:lightline#colorscheme#{g:lightline.colorscheme}#palette
let s:palette.tabline.right = [['#ff0000', '#121212', 196, 233]]
call lightline#highlight('tabline')
```

**Comment by Photonico** [comment]
> Officially I recommend to create a new colorscheme of lightline (see `:h lightline-colorscheme`). But you can overwrite the `s:palette.tabline.right` of the lightline colorscheme palette. See #431 for reference.
> 
> ```viml
> let s:palette = g:lightline#colorscheme#{g:lightline.colorscheme}#palette
> let s:palette.tabline.right = [['#ff0000', '#121212', 196, 233]]
> call lightline#highlight('tabline')
> ```

I overwrite the colorscheme in `.vimrc`. It works, thank you.
