### ISSUE TITLE
Is it possible to get the evaluated component value in a component function?

### ISSUE THREAD

**Issue by MIvanchev** [itchyny/lightline.vim#583]
Basically what the title says. I need a component function which does:

if <condition> take value that would've been put without the function otherwise do something else.

Is it currently possible?

**Comment by itchyny** [comment]
I can't understand what you want. Any example?

**Comment by MIvanchev** [comment]
Yes! For example,

```
let g:lightline.component_function = {
  'filename': 'foo'
}

function foo()
    return <some condition> ? evaluated_value_for_filename_component : ''
endfunction
```

My motivation is to specify empty values for all components for NERDTree.

**Comment by itchyny** [comment]
Unfortunately it's impossible to evaluate (non-functional) components in Vim script. Use `expand('%:t')` for filename, `line('.')` for line number, etc.

**Comment by MIvanchev** [comment]
Yeah I saw this however the plugin performs significant post-processing on the values, this is why I wanted to use the originals :(
