### ISSUE TITLE
Hide the statusline on a file tree?

### ISSUE THREAD

**Issue by iRealistiX** [itchyny/lightline.vim#588]
Hello! I am a happy user of lightline, but, there's one problem for me.

Since in my config, i want to mimic vscode, i really want to hide the statusline on the tree side.

For info, i use nvim-tree.lua, I tried used `if !has()` but didn't work.

**Comment by itchyny** [comment]
You cannot hide the statusline, nor disable lightline only for some specific window. Instead, I recommend to truncate components based on the window width, or file type as described in [README.md](https://github.com/itchyny/lightline.vim#can-i-trim-the-file-format-and-encoding-information-on-narrow-windows).

**Comment by iRealistiX** [comment]
Thanks for replying, I think this will work since I define a specific width for the file tree.

**Comment by Flo-Slv** [comment]
> Thanks for replying, I think this will work since I define a specific width for the file tree.

Hi, can you share your code ?!
