### ISSUE TITLE
Breaks tab highlighting

### ISSUE THREAD

**Issue by Integralist** [itchyny/lightline.vim#589]
Hello, I've noticed that this plugin is preventing the following configuration from working:

```viml
autocmd VimEnter * hi TabLineSel ctermfg=Red ctermbg=Yellow
```

If I disable the plugin then I'll see the correct behaviour:

<img width="205" alt="Screenshot 2021-07-26 at 12 55 49" src="https://user-images.githubusercontent.com/180050/126984866-873a77bd-3570-4554-9c72-0813d212d9ea.png">

Otherwise, with the plugin enabled I see:

<img width="226" alt="Screenshot 2021-07-26 at 12 56 38" src="https://user-images.githubusercontent.com/180050/126984906-0c9d94c1-f49f-43cd-b813-426e66bbb862.png">

I have only two lines of plugin related configuration:

```viml
set noshowmode
let g:lightline = {'colorscheme': 'powerlineish'}
```

**Comment by itchyny** [comment]
This plugin has own colorscheme for tab colors. If you want to use the default tabline, disable the tabline of this plugin.

```vim
let g:lightline.enable = {
    \ 'tabline': 0
    \ }
```

**Comment by Integralist** [comment]
Thank you, that works great 🙂
