### ISSUE TITLE
Avoid "floating"/"wobbling" tabline by always including the separator (with the background color for the selected buffer)

### ISSUE THREAD

**Issue by MIvanchev** [itchyny/lightline.vim#590]
Hey, I'm using `lightline` with `lightline-bufferline` and came across this IMHO annoying effect. Because the separators are not rendered for the selected buffer, the width of the tabline changes when the selection changes. This is especially noticeable if one buffer is on the edge of the tabline and another in the middle. Perhaps a solution would be to always render the separator but change the color to the background color for the selected entry.

**Comment by itchyny** [comment]
Please share screenshots, reproducible steps to understand what is the exact problem.

**Comment by MIvanchev** [comment]
[Here](https://raw.githubusercontent.com/MIvanchev/images/109905a3-3c00-4bcb-9d49-2eeca38fbfd2/tabline1.png) and [here](https://raw.githubusercontent.com/MIvanchev/images/109905a3-3c00-4bcb-9d49-2eeca38fbfd2/tabline2.png) are to screenshots showing how the length of the tabline changes by 1 whole character (I've enabled colorcolumn for demonstration purposes)

**Comment by itchyny** [comment]
How about setting same separators as seb-separators?
￼￼￼```vim
let g:lightline.tabline_separator = { 'left': '|', 'right': '|' }
```
ref: https://github.com/itchyny/lightline.vim/blob/b06d921023cf6536bcbee5754071d122296e8942/doc/lightline.txt#L281

**Comment by MIvanchev** [comment]
No, this doesn't look good at all sadly:

![tabline3](https://raw.githubusercontent.com/MIvanchev/images/109905a3-3c00-4bcb-9d49-2eeca38fbfd2/tabline3.png)
![tabline4](https://raw.githubusercontent.com/MIvanchev/images/109905a3-3c00-4bcb-9d49-2eeca38fbfd2/tabline4.png)

**Comment by itchyny** [comment]
It looks working, avoiding wobbling by 1 characters.

**Comment by itchyny** [comment]
If you don't like unmatching colors in the edge of selected tab, set the separators empty. There's no other way to work around this issue.

```vim
let g:lightline.tabline_separator = { 'left': '', 'right': '' }
let g:lightline.tabline_subseparator = { 'left': '', 'right': '' }
```

**Comment by MIvanchev** [comment]
Yes, thank you! :) That'll have to do for now!
