### ISSUE TITLE
No Colors Before Switching Between Buffer

### ISSUE THREAD

**Issue by Bo-Ru** [itchyny/lightline.vim#591]
When I'm using nerdtree with lightline, I noticed that no color will be shown in the status bar until I switch between buffer.  Am I missing some steps? (I'm new to vim)
![Problem](https://user-images.githubusercontent.com/65844719/127743368-c876a574-4302-40b2-81aa-00348e973e81.gif)
Here is part of my .vimrc file:
```
"  For NerdTree
autocmd VimEnter * NERDTree | wincmd p
" For Status Line
set laststatus=2
set noshowmode
```

**Comment by itchyny** [comment]
You will need `++nested` flag.
```vim
autocmd VimEnter * ++nested NERDTree | wincmd p
```

**Comment by Bo-Ru** [comment]
> You will need `++nested` flag.
> 
> ```viml
> autocmd VimEnter * ++nested NERDTree | wincmd p
> ```

It worked, thanks a lot.
