### ISSUE TITLE
Display indentation settings in use?

### ISSUE THREAD

**Issue by mrusme** [itchyny/lightline.vim#593]
Hey there!

Is it possible to display the indentation settings that are currently in use, similarly to how e.g. Sublime Text does it in the lower right corner? I'm using editorconfigs and they differ from repo to repo, so I would like to have lightline display something like `"Spaces: 2"` (for two spaces indentation) or `"Tab size: 4"` (for tab indentation that's 4 spaces wide) on the right side, next to where it displays the format and charset.

From what I understood the relevant vim settings are the following:

> *tabstop*
>
>sThe width of a hard tabstop measured in "spaces" -- effectively the (maximum) width of an actual tab character.
>
>
> *shiftwidth*
>
> The size of an "indent". It's also measured in spaces, so if your code base indents with tab characters then you want shiftwidth to equal the number of tab characters times tabstop. This is also used by things like the =, > and < commands.
>
>
> *softtabstop*
>
> Setting this to a non-zero value other than tabstop will make the tab key (in insert mode) insert a combination of spaces (and possibly tabs) to simulate tab stops at this width.
>
>
> *expandtab*
>
> Enabling this will make the tab key (in insert mode) insert spaces instead of tab characters. This also affects the behavior of the retab command.
>
>
> *smarttab*
>
> Enabling this will make the tab key (in insert mode) insert spaces or tabs to go to the next indent of the next tabstop when the cursor is at the beginning of a line (i.e. the only preceding characters are whitespace)

What would be the proper way to display these settings in lightline in a format similar to the one mentioned above?

Thank you!

**Comment by itchyny** [comment]
You have reached to the options you need, what is the problem here? Can you paste your config that didn't work?

**Comment by mrusme** [comment]
@itchyny I am not certain how I would make lightline display these options. I assume it would require writing a `component_function` which reads these variables and returns the proper string output. Is this the way to do it?

**Comment by itchyny** [comment]
Here's example using component which is slightly faster,
```vim
let g:lightline = {
      \ 'active': {
      \   'right': [ [ 'lineinfo' ], [ 'percent' ], [ 'indent', 'fileformat', 'fileencoding', 'filetype' ] ]
      \ },
      \ 'component': {
      \   'indent': '%{&expandtab?"Spaces":"Tab size"}:%{&expandtab?&shiftwidth:&tabstop}',
      \ },
      \ }
```
or function component which is more flexible.
```vim
let g:lightline = {
      \ 'active': {
      \   'right': [ [ 'lineinfo' ], [ 'percent' ], [ 'indent', 'fileformat', 'fileencoding', 'filetype' ] ]
      \ },
      \ 'component_function': {
      \   'indent': 'LightlineIndent',
      \ },
      \ }

function! LightlineIndent() abort
  return (&expandtab ? "Spaces" : "Tab size") . ':' . (&expandtab ? &shiftwidth : &tabstop)
endfunction
```

**Comment by mrusme** [comment]
Thank you very much for that! Just tested the first solution and it works very well, no need for the function then! :-)
