### ISSUE TITLE
How to show git branch icon near git branch information

### ISSUE THREAD

**Issue by SarveshMD** [itchyny/lightline.vim#594]
How can we have git branch icon like this one near the git branch information ?
![image](https://user-images.githubusercontent.com/76893756/131293133-109427fb-9238-49b8-8728-18722e36b723.png)

**Comment by itchyny** [comment]
- Install some fonts including the branch icon to your terminal
- Learn how to configure components in [README.md](https://github.com/itchyny/lightline.vim).
- Add your favorite icon to your branch component.

**Comment by SarveshMD** [comment]
Thanks @itchyny.

**Comment by SarveshMD** [comment]
I added the following snippet to my .vimrc. 
```vim
function! GitBranch() 
    return " " . FugitiveHead()
endfunction
```
Then used `g:lightline.component_function.gitbranch` to be the newly created function `GitBranch`. This solved my problem. Thanks
