### ISSUE TITLE
How to pad the tabline to respect sidebars?

### ISSUE THREAD

**Issue by DevonPeroutky** [itchyny/lightline.vim#595]
Let me start by saying Lightline is great! I'm using it as a tabline and it works well except that I have toggle-able sidebar (coc-explorer). When the sidebar is visible, the tabline does not account for the sidebar.

Without the sidebar
<img width="1792" alt="Screen Shot 2021-09-03 at 12 44 35 PM" src="https://user-images.githubusercontent.com/36947377/132040297-043e051d-3d3a-4ace-adc9-c342796cfad2.png">

With the sidebar
<img width="1792" alt="Screen Shot 2021-09-03 at 12 47 22 PM" src="https://user-images.githubusercontent.com/36947377/132040598-22be6fd4-f712-40fe-ac3a-21c6eef0c396.png">

Is there any way to add padding to the tabline such that it is aligned with the windows when the sidebar is active? Apologies if this is described in the documentation and I missed it. I searched but couldn't find anything.

**Comment by itchyny** [comment]
Lookup the coc-explorer window, and repeat spaces by the window width.
```vim
let g:lightline = {
      \ 'tabline': {
      \   'left': [ [ 'cocspaces', 'tabs' ] ],
      \ },
      \ 'component_function': {
      \   'cocspaces': 'LightlineCocSpaces',
      \ },
      \ 'component_type': {
      \   'cocspaces': 'raw',
      \ },
      \ }

function! LightlineCocSpaces()
  let nr = get(filter(range(winnr()), 'getbufvar(winbufnr(v:val), "&filetype") ==# "coc-explorer"'), 0, -1)
  return nr < 0 ? '' : repeat(' ', winwidth(nr)+1)
endfunction
```
