### ISSUE TITLE
Colors inaccuracy in neovim

### ISSUE THREAD

**Issue by SamuelFe** [itchyny/lightline.vim#596]
Well, i've seen other issues like that but I couldn't solve it.

**Colorscheme = "ayu_mirage"**

## Expected
![image](https://user-images.githubusercontent.com/54598690/132593224-4ea1bbb4-0d6e-4a31-a494-79176d8b0238.png)

## What I got
![image](https://user-images.githubusercontent.com/54598690/132593161-eea97f37-e340-426b-b4b3-1548fb798acc.png)
![image](https://user-images.githubusercontent.com/54598690/132593250-90945724-bdce-450a-8758-e325103d73da.png)
![image](https://user-images.githubusercontent.com/54598690/132593266-73f7219f-ffab-454f-a826-28564c75dca7.png)

*Pretty weird right?*

The same happens with other themes, such as materia and one.

I run nvim with *konsole* as terminal emulatior, but I tried with *alacritty* as well. It didn't changed anything.

`:hi Normal` returns `Normal   xxx cleared`
`:echo lightline#colorscheme#background()` returns `dark`
`:echo &background` returns `dark`
`:echo has('termguicolors')` returns `1`

**Comment by itchyny** [comment]
The screenshot below looks like the cterm colors so not much surprise. So the problem is you're expecting gui colors while termguicolors is on. Maybe set the option on but the terminal does not support. Or you should set `t_8f` and `t_8b (for reference see `:h xterm-true-color`).

**Comment by SamuelFe** [comment]
Inside nvim, I just tiped `:set termguicolors` and suddently everything worked fine. Thank you very very much!

![image](https://user-images.githubusercontent.com/54598690/132609245-b6d41961-fba2-4fbe-a398-12144512870b.png)
![image](https://user-images.githubusercontent.com/54598690/132609311-268d7806-5a9e-40d2-8585-58161f0fffe4.png)
![image](https://user-images.githubusercontent.com/54598690/132609347-79eb4fc8-9efa-4f77-b2c8-c8bcb3fbd065.png)
![image](https://user-images.githubusercontent.com/54598690/132609369-51f09f34-48c6-4a23-8ee9-f601123c028c.png)


## Actual solution
Put `set termguicolors` into `init.vim` (the neovim config file)
