### ISSUE TITLE
Isn't "parent/filename" a better default for tab? 

### ISSUE THREAD

**Issue by tbmreza** [itchyny/lightline.vim#598]
Thank you for the cool plugin. I have a tiny suggestion/question.

Isn't parent/filename a better default for most users? I work like this most of the time.
<img width="579" alt="image" src="https://user-images.githubusercontent.com/17718201/132967341-5302336d-a96a-4fb4-ac27-bc15713cb606.png">
[my fork](https://github.com/tbmreza/lightline.vim/commit/ccd74073412eea685e8c9cf15aa265878b94a2dd)

It was not straightforward to override using component_expand the `lightline#tab#filename` component (at least to my mileage), so I thought changing the default would make sense to other people as well.

**Comment by itchyny** [comment]
I cannot change the default behavior now. Changing the default is not satisfying for all existing users.

**Comment by vhp1360** [comment]
Hello.
could you please provide a way to do it for my vim?
