### ISSUE TITLE
Setting `g:lightline.active.left` in `ginit.vim`

### ISSUE THREAD

**Issue by hangjit-domain** [itchyny/lightline.vim#603]
I have this code in `ginit.vim` but the config doesn't get picked up by lightline.
```
unlet g:lightline.active.left
let g:lightline.active.left = [ ['mode', 'paste'] , ['cocstatus', 'currentfunction', 'fugitive', 'readonly','absolutepath', 'modified']]

```

When I run `echo g:lightline.active.left` I get the output below:
![image](https://user-images.githubusercontent.com/52148253/134831476-6410b014-f461-4c60-8edd-c89dff0ab1fa.png)

**Comment by itchyny** [comment]
The ginit.vim file is sourced after plugin initialization so this is a correct behavior. Consider moving configuration to init.vim.

**Comment by hangjit-domain** [comment]
@itchyny I don't want to show the `absolutepath` in terminal version (init.vim). 

I'm nvim-qt GUI which needs the config to be in ginit.vim due to which I need to 'reset' the array. If there's a way to add `absolutepath` to the array and re-render the status line, that would work too.

**Comment by itchyny** [comment]
If you want to switch the config check `has('gui')`. If you still need to write in gvim.vim, `call lightline#init()` and then `call lightline#update()` would apply the config.

**Comment by hrai** [comment]
Thanks, that worked like a charm!
