### ISSUE TITLE
Devicons on tabs

### ISSUE THREAD

**Issue by sicr0** [itchyny/lightline.vim#605]
I have this function that adds Devicons to filenames (and removes undesired filenames). I wanted to be able to use it with the tabs. How could I do it?

**Comment by itchyny** [comment]
- Implement a function which accepts tab number and returns icon string of the corresponding buffer.
- Add the function to `g:lightline.tab_component_function`.
- Add the tab component to `g:lightline.tab.active` and `g:lightline.tab.inactive`.
