### ISSUE TITLE
Can't change default lightline settings

### ISSUE THREAD

**Issue by cbjuju** [itchyny/lightline.vim#609]
I am not able to change any of the default settings that come with lightline. I tried to change the lightline separators but that did not work. The 'hello world' configuration in the README is not working for me. The wombat colorscheme is not appearing. 

I have set the lightline colorscheme before setting the editor colorscheme as written in the README. I have given the relevant part of my vimrc below. I am running nvim version NVIM v0.5.0-dev+1164-gdc8da7ba4 on Ubuntu 18.04. I have a window manager called Regolith which uses the gnome terminal.

![Screenshot from 2021-10-31 11-00-35](https://user-images.githubusercontent.com/40547464/139592269-4fa29a32-8cbc-43cb-a81e-5102691402c1.png)

**Comment by itchyny** [comment]
Is that file sourced by NeoVim? It often sources init.vim.

**Comment by cbjuju** [comment]
It does source init.vim. However init.vim contains a command for sourcing .vimrc. I have only three lines in my init.vim :

> set runtimepath^=~/.vim runtimepath+=~/.vim/after
>let &packpath = &runtimepath
>source ~/.vimrc

**Comment by itchyny** [comment]
Please create a minimum init.vim so that I can reproduce the problem.
