### ISSUE TITLE
Overriding TabLine/Fill/Sel colors

### ISSUE THREAD

**Issue by rafi** [itchyny/lightline.vim#61]
I've tried setting the highlight colors for TabLine/Fill/Sel in my vimrc, but it would just not work. I've found the option to disable lightline's tabline feature, but is there a way to override the tabline colors without disabling lightline's tabline features?

**Comment by glacambre** [comment]
Hi,
I'm trying to create a colorscheme that leaves the tab bar "transparent" (i.e., no colors) except for the selected tab. What I did in my vim coclor scheme is this : 
`hi TabLineFill  guifg=none     ctermfg=none     guibg=none     ctermbg=none     gui=none    cterm=none`
`hi TabLine	    guifg=none     ctermfg=none     guibg=none     ctermbg=none     gui=none    cterm=none`
`hi TabLineSel   guifg=none     ctermfg=none     guibg=none     ctermbg=none     gui=none    cterm=inverse`
It works without lightline, but with lightline it doesn't. Here's what I tried in the lightline colorscheme :
`let s:p.tabline.left = [ [ 'none', 'none' ] ]`
`let s:p.tabline.tabsel = [ [ 'none', 'none', 'none', 'none', 'inverse' ] ]`
`let s:p.tabline.middle = [ [ 'none', 'none' ] ]`
`let s:p.tabline.right = [ [ 'none', 'none' ] ]`
This turns everything in the tab bar to black.
Am I doing something wrong ? It seems like manually overriding the colors works.

**Comment by itchyny** [comment]
Sorry but lightline does not support inverse attribute because it is too difficult to calculate the separator highlight from them.

**Comment by QMonkey** [comment]
I use highlight command to get all highlight groups which start with 'LightLine', and then I highlight all of them. But I find I still cannot change the color of TabLineFill.
What should I do to change the color of TabLineFille.

**Comment by QMonkey** [comment]
I found the highlight group, that is LighlightMiddle_tabline. It seems it isn't in highlight result.
