### ISSUE TITLE
How can I remove the carets "^^^^^^^^^^^^^^^^^^"

### ISSUE THREAD

**Issue by BenzLeung** [itchyny/lightline.vim#610]
![图片](https://user-images.githubusercontent.com/2764768/139801657-6acfed6b-7562-4cb1-86e9-bc73cc5596db.png)

When there is a sidebar, there is so many caret in the statusline.

How can I remove them?

I used item2 + vim + one light colorscheme.

**Comment by itchyny** [comment]
Configure `set fillchars=stl:\ ,`.

**Comment by BenzLeung** [comment]
> Configure `set fillchars=stl:\ ,`.

I tried. There is no change in the statusline. Still a lot of ^^^^^^ :-(

But I tried `set fillchars=stl:\ ,stlnc:.` and it works. However, the statusline in the inactive column become a lot of ".................."

It seems `stl` and` stlnc` cannot use the same character. I have seen a lot of screenshots, there is no character, I am curious how they did?

**Comment by itchyny** [comment]
`set fillchars=stl:\ ,stlnc:\ ,` works for me

**Comment by BenzLeung** [comment]
`set fillchars=stl:\ ,stlnc:\ ,` doesn't work for me, but I found another solution.

`highlight StatusLineNC ctermfg=bg ctermbg=bg guibg=bg guifg=bg` works for me.

Anyway, Thank you very much for your reply.
