### ISSUE TITLE
Not loading correctly after nvim update

### ISSUE THREAD

**Issue by mrlinuxfish** [itchyny/lightline.vim#612]
I just updated nvim and now I can't get lightline to load correctly
```
Cannot source a directory: "/home/atomsk/.config/nvim/autoload/lightline.vim"
Error detected while processing BufEnter Autocommands for "*":
E117: Unknown function: lightline#update
Press ENTER or type command to continue
```
I've tried reinstalling the plugin but it doesn't seem to help. I'm not sure what I'm doing wrong if anything or if there's just an issue with the plugin

**Comment by itchyny** [comment]
Describe the problem with complete vimrc configuration with installation steps you did.

**Comment by mrlinuxfish** [comment]
[https://github.com/mrlinuxfish/dotfiles/blob/master/.config/nvim/init.vim](vimrc). I installed with plug using the steps on the readme (I have done the PlugUpdate and PlugInstall commands on nvim)

**Comment by itchyny** [comment]
One problem is that you're using `~/.config/nvim/autoload` for plugins directory which can cause various problems when `~/.config/nvim/` is included in `&runtimepath`. Read [vim-plug](https://github.com/junegunn/vim-plug) README.md carefully, it says `Avoid using standard Vim directory names like 'plugin'` (`autoload` is a standard Vim directory as well) so use `call plug#begin(stdpath('data') . '/plugged')`. Make sure to remove all plugin directories and reinstall.

**Comment by mrlinuxfish** [comment]
Thanks for helping me figure out what I was doing wrong :heart:
