### ISSUE TITLE
How to add bold to a part of a component

### ISSUE THREAD

**Issue by SuperCuber** [itchyny/lightline.vim#613]
I looked through a couple issues but couldn't find what I wanted

I want to have a component like `relativepath` but with the file stem in bold. So I wrote something like this:
```vim
function! FileDirAndName()
    let dir = fnamemodify(expand("%:h"), ":~:.")
    if dir == ""
        return "[No Name]"
    endif

    let separator = "/"
    let stem = expand("%:t:r")
    let extension = expand("%:e")

    if extension == ""
        return dir . separator . "%#Bold#" . stem
    else
        return dir . separator . "%#Bold#" . stem . "%#Normal#" . "." . extension
    endif
endfunction

"  ...

component = "%{FileDirAndName()}"
```

Seems like my highlight groups are rendered as normal text, and even if they weren't it would look horrible since highlight groups reset all other styles (and I'm not sure if `Normal` is a thing)

How would I go about doing this? Am I supposed to use a raw component or an expanded component?

**Comment by itchyny** [comment]
This is not supported in this plugin (`:h lightline-problem-12` might be a hint). In order to make components in bold font, create your own colorscheme with `'bold'` in the fifth element of the color.
