### ISSUE TITLE
Show character digraph & related insert mode issues

### ISSUE THREAD

**Issue by vglfr** [itchyny/lightline.vim#614]
Trying to display digraph with something like:

```
let g:lightline = {
  \ 'active': {
  \   'right': [ [ 'lineinfo' ],
  \              [ 'percent' ],
  \              [ 'digraph' ] ],
  \ },
  \ 'component_function': {
  \   'digraph': 'Digraph'
  \ },
  \ }

function! Digraph()
  let c = execute(':ascii')
  let c = execute(':normal ga')
  " TODO pattern match
  " or just show digraph character
  let c = getline('.')[col('.') - 1]
  return c
endfunction
```
Results in a broken status line when current character is digraph (or just non-ascii):

![screen](https://i.imgur.com/nGh0nzW.png)

Moreover, normal mode `A` on lines with ~~non-ascii~~ any characters when `digraph` component is enabled results in cursor appearing before the last character of the line instead of after it. This holds regardless of the number of non-ascii characters on the line. When lightline is hidden with `set laststatus=1` the issue disappears.

**Comment by itchyny** [comment]
How about `return matchstr(getline('.'), '\%' . col('.') . 'c.')` .

**Comment by vglfr** [comment]
Solved, any thanks!
