### ISSUE TITLE
Define lineinfo to encode 3 elements: Column number, Line number, Total number of lines

### ISSUE THREAD

**Issue by rerrabolu** [itchyny/lightline.vim#617]
Macro/Function Definition:

    let g:lightline.component = {
            \ 'lineinfo': "[%{printf('%03d/%03d',line('.'),line('$'))}]"
    }

Currently this definition is printing only two elements: Line number and Total number of lines.

Actual Behavior:  45/1123

Desired Behavior: 23/45/1123

Can someone help me with the definition of lineinfo so that it prints 3 elements:
    - Column number,
    - Line number,
    - Total number of lines in file

How would I extend current definition. Could I request the right definition given here.

**Comment by itchyny** [comment]
You can get the column number by `col('.')`.

**Comment by rerrabolu** [comment]
Thanks for the suggestion. I updated the old definition to the new one given below. Basically added a 3 element to the macro definition and it works.

**The new definition is:**

let g:lightline.component = {
        \  'lineinfo': "[%{printf('%03d/%03d/%03d',col('.'),line('.'),line('$'))}]"
        \}
