### ISSUE TITLE
Right side separator

### ISSUE THREAD

**Issue by phortonssf** [itchyny/lightline.vim#618]
I have lightline, and i have the separators working for the most part with my nerd font. As you can see the left side has the separators working but on the right side the last two separators are not right. 
My lightline settings,
`  
let g:lightline.separator = { 'left': "\ue0b8", 'right': "\ue0be" }
let g:lightline.subseparator = { 'left': "\ue0b9", 'right': "\ue0b9" }
let g:lightline.tabline_separator = { 'left': "\ue0bc", 'right': "\ue0ba" }
 let g:lightline.tabline_subseparator = { 'left': "\ue0bb", 'right': "\ue0bb" }
`
![image](https://user-images.githubusercontent.com/23040285/150186907-b76a5a6e-deda-4080-aeea-aa96fcb3d912.png)

Expected to look like this:
[correct](https://i.redd.it/wir0l0kywkb31.png)
The source code for that is from [here](https://github.com/sainnhe/dotfiles/blob/06f3529930ed545972eef5f73ea8c856c13dd015/.config/nvim/init.vim#:~:text=let%20g%3Alightline%20%3D%20%7B%7D,ale%23indicator_ok%20%3D%20%22%5Cuf00c%22)

**Comment by itchyny** [comment]
How does `:echo "\ue0be"` look like?

**Comment by phortonssf** [comment]
![image](https://user-images.githubusercontent.com/23040285/150264627-224ff5f6-11d6-49cf-a6d8-1ffdae29eed4.png)

**Comment by phortonssf** [comment]
it just gives me the triangle, that wider tan bar on top is the tabline.

**Comment by itchyny** [comment]
How about :echo "\ue0beM"?

**Comment by phortonssf** [comment]
![image](https://user-images.githubusercontent.com/23040285/150265013-47fc8e31-4668-461f-a4fd-55ca47c93a47.png)

**Comment by phortonssf** [comment]
It doesn't like that one as much

**Comment by itchyny** [comment]
This is likely an issue of font and terminal rendering and there's nothing I can do in the plugin. Probably `set ambiwidth=double` or another terminal option for ambiguous width characters might help you.

**Comment by phortonssf** [comment]
I was working on my icons for powerlevel10k and someone mentioned leaving a space for the codes. Turn out that was the solution here:
"\ue0be" vs "\ue0be "
