### ISSUE TITLE
Different settings in ftplugin for different filetypes don't work with buffers

### ISSUE THREAD

**Issue by Bharath-Hegde** [itchyny/lightline.vim#619]
For illustration of my issue I have created 2 files in `~/.config/nvim/ftplugin/`  which are `python.vim` and `cpp.vim`, which have different themes and the 'sayhello' component displays different messages.

Contents of `python.vim`:
```Vim
function! Func()
	return "Hello Python!"
endfunction
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'cocstatus', 'currentfunction', 'sayhello', 'readonly', 'filename', 'modified' ] ]
      \ },
	  \ 'component': {
		  \ 'sayhello':'%{Func()}'
	  \ },
      \ 'component_function': {
      \   'cocstatus': 'coc#status',
      \   'currentfunction': 'CocCurrentFunction',
      \ },
      \ }
```

Contents of `cpp.vim`:
```Vim
function! Func()
	return "Hello cpp!"
endfunction
let g:lightline = {
      \ 'colorscheme': 'solarized',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'cocstatus', 'currentfunction', 'sayhello', 'readonly', 'filename', 'modified' ] ]
      \ },
	  \ 'component': {
		  \ 'sayhello':'%{Func()}'
	  \ },
      \ 'component_function': {
      \   'cocstatus': 'coc#status',
      \   'currentfunction': 'CocCurrentFunction',
      \ },
      \ }
```

These settings work as expected when I open a .py file or a .cpp file.

But the problem occurs when I open a .py file with an open .cpp buffer or vice versa.
1. The theme of the _first opened_ file is applied to all subsequently opened buffers.
2. The sayhello message of the _last opened_ file is applied to all open buffers.

So if I open a .cpp file the theme would be 'wombat' and the message would be 'Hello cpp!'. Now if I open a .py file from within nvim, the theme remains 'wombat' while the message changes to 'Hello Python!' for both the open buffers.

I'd like to have each open buffer to separately load the filetype configs.

**Comment by itchyny** [comment]
This is not supported by lightline.vim by design. The `g:lightline` variable is global and you cannot configure separately per filetypes. Instead, change the return value of the component functions, like;
```vim
function! Func()
	return "Hello " . &filetype . "!"
endfunction
```
