### ISSUE TITLE
Whitespace warnings

### ISSUE THREAD

**Issue by rafi** [itchyny/lightline.vim#62]
The feature I'm missing from airline is the whitespace warning for "trailing" and "mixed-indent", here is the [screenshot](https://github.com/bling/vim-airline#whitespace) of how it looks.

Is there a way to mimic this feature in lightline?

**Comment by deponian** [comment]
This is comment for people who came here from search engine with query "lightline whitespace". I have ported vim-airline's whitespace extension to lighline, so you can add it to your lightline config.

You can get plugin here: https://github.com/deponian/vim-lightline-whitespace
