### ISSUE TITLE
Suggestion: support for icon colors with nvim-web-devicons

### ISSUE THREAD

**Issue by MIvanchev** [itchyny/lightline.vim#620]
I'm totally loving your plugin and use it all the time but it'd be great if it had support for icon colors (e.g. in the tabline).

**Comment by itchyny** [comment]
This issue has less information and can't tell what you want. Less likely there's nothing I can help.

**Comment by MIvanchev** [comment]
I'm sorry, it was indeed quite brief. The plugin https://github.com/kyazdani42/nvim-web-devicons provides icons as well as pre-defined color for the icons, like green for Vim's V icon. It would be nice if lightline is able to display those colors for icons embedded in the components' texts.

**Comment by itchyny** [comment]
I haven't test it but maybe displaying icons is easy if you're familiar with the api of that plugin. Coloring specific part of component is difficult in lightline by design decision (see `:h lightline-problem-12`), so you shouldn't try to do that.
