### ISSUE TITLE
How to add separate icon and icon for git branch in lightline.vim

### ISSUE THREAD

**Issue by HungPham3112** [itchyny/lightline.vim#621]
I tried to use `vim-airline` but it makes vim slow so I decided to use `lightline.vim`. Airline have some feature I really like but don't know how to do it in lightline.

Airline:

![image](https://user-images.githubusercontent.com/75968004/150902148-8cb75ec7-6f0a-4a0d-bb8f-f5ccbfbb5511.png)

Currently my lightline:

![image](https://user-images.githubusercontent.com/75968004/150902111-84dc8ec8-98b3-439f-abd6-bbe3fae8e369.png)

My settings:
```
let g:lightline = {
\ 'colorscheme': 'edge',
\ 'active': {
\   'left': [ [ 'mode', 'paste' ],
\             [ 'cocstatus', 'readonly' ],
\             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ],
\ },
\ 'component': {
\   'filename': '%F',
\ },
\ 'component_function': {
\   'cocstatus': 'coc#status',
\   'filetype': 'MyFiletype',
\   'fileformat': 'MyFileformat',
\   'gitbranch': 'gitbranch#name'
\ },
\ }
function! MyFiletype()
    return winwidth(0) > 70 ? (strlen(&filetype) ? &filetype . ' ' . WebDevIconsGetFileTypeSymbol() : 'no ft') : ''
endfunction

function! MyFileformat()
    return winwidth(0) > 70 ? (&fileformat . ' ' . WebDevIconsGetFileFormatSymbol()) : ''
endfunction

"Use autocmd to force lightline update.
autocmd User CocStatusChange,CocDiagnosticChange call lightline#update()
```

How to add icon for git branch like above, make separate line '|' become '>'.  Is it compatible if I use both `coc-nvim` settings and `fugitive` settings in lightline, and how to config?. Thanks a lot.

**Comment by itchyny** [comment]
Create your own coc status function,
```vim
function! MyCocStatus()
    return '[icon] ' . coc#status()
endfunction
```
And update the `component_function`.
```vim
\ 'component_function': {
\   'cocstatus': 'MyCocStatus',
```
In order to change the separator, configure `g:lightline.separator` and `g:lightline.subseparator`.
