### ISSUE TITLE
Column number is shown as byte offset instead of display column.

### ISSUE THREAD

**Issue by wjl** [itchyny/lightline.vim#623]
The default lineinfo component shows line and column, which is great. However, it by default uses the byte number of the line, instead of the display column. While there may occasionally be a reason to wants to see the actual byte offset in the status line, this is very rarely what anybody wants in modern times where Unicode is the default encoding.

The root cause is using %c for column number, which is a byte offset, instead of %v for the display column number, which takes into account Unicode EGCs and Vim's character width settings like the rest of the editor.

Here is a quick patch (it's literally just a one character change, from %c to %v):

```diff
diff --git a/autoload/lightline.vim b/autoload/lightline.vim
index e1f09ca..ed065ec 100644
--- a/autoload/lightline.vim
+++ b/autoload/lightline.vim
@@ -110,7 +110,7 @@ let s:_lightline = {
       \     'paste': '%{&paste?"PASTE":""}', 'readonly': '%R', 'charvalue': '%b', 'charvaluehex': '%B',
       \     'spell': '%{&spell?&spelllang:""}', 'fileencoding': '%{&fenc!=#""?&fenc:&enc}', 'fileformat': '%{&ff}',
       \     'filetype': '%{&ft!=#""?&ft:"no ft"}', 'percent': '%3p%%', 'percentwin': '%P',
-      \     'lineinfo': '%3l:%-2c', 'line': '%l', 'column': '%c', 'close': '%999X X ', 'winnr': '%{winnr()}'
+      \     'lineinfo': '%3l:%-2v', 'line': '%l', 'column': '%c', 'close': '%999X X ', 'winnr': '%{winnr()}'
       \   },
       \   'component_visible_condition': {
       \     'modified': '&modified||!&modifiable', 'readonly': '&readonly', 'paste': '&paste', 'spell': '&spell'
```

Due to the nice design of lightline, it is of course possible to work around this at a user level by redefining the display of lineinfo, but for someone that isn't already customizing lightline, this is a lot to go through to just get a good default for column numbers.

Lightline ought to make displaying the actual display column number the default.

Thanks!

**Comment by itchyny** [comment]
This is an expected behavior, it shows the byte column number by design. It uses `%c` of `:h 'statusline'`.  If you want the virtual offset (note that virtual offset is different from character count), configure as follows.
```vim
let g:lightline = {
      \ 'component': {
      \   'lineinfo': '%3l:%-2v',
      \ }
      \ }
```
#542,  #558

**Comment by itchyny** [comment]
As my self a Japanese with 3-byte characters (in UTF-8), I prefer counting by bytes because it calculates the real data size.
