### ISSUE TITLE
feature: neovim global statusline support 

### ISSUE THREAD

**Issue by deathmaz** [itchyny/lightline.vim#627]
hi, is it possible to add support for https://github.com/neovim/neovim/pull/17266 ?

**Comment by itchyny** [comment]
I tested with `NVIM v0.7.0-dev+1280-gf2e5f509d` (revision [`f2e5f50`](https://github.com/neovim/neovim/commit/f2e5f509d995b291e4b9e05a0c059e83490a18e1)) and it looks working as intended.
![screenshot](https://user-images.githubusercontent.com/375258/159102250-97917f5f-0f8a-4a94-9512-012b7eee0cb8.gif)
init.vim
```vim
set runtimepath+=~/path/to/lightline
set laststatus=3
```
If it does not work, please describe the behavior with complete configuration and reproduction steps with screenshot and expectations.

**Comment by deathmaz** [comment]
Works as expected. I think when i tried it initially i was using outdated version of neovim. Sorry for noise and thank you for your work.
