### ISSUE TITLE
Is it possible to have lightline overlap the command line?

### ISSUE THREAD

**Issue by evprkr** [itchyny/lightline.vim#628]
I love lightline, excellent work. So much easier than the alternatives.

I know this isn't specific to lightline, but I figured someone here may know. I'm wondering if, when the command line (where you enter `:` commands, not sure if it has a name) is not in use, lightline can be printed in that space, and then moved upwards one row when the command line is in use.

If that's not possible, an acceptable alternative would be to have lightline disappear when the command line is in use.

Fig. 1 - _command line closed_
```
1 Line one!
2 Line two!
3 Line three!
| NORMAL | .vimrc |                                                 unix | utf-8 | vim | 0% | 1:1 |
```

Fig. 2 - _command line opened (`:` pressed)
```
1 Line one!
2 Line two!
| NORMAL | .vimrc |                                                 unix | utf-8 | vim | 0% | 1:1 |
: _
```

Notice line 3 is obscured by lightline moving upwards one row.

**Comment by itchyny** [comment]
This is impossible. See https://github.com/vim/vim/issues/940, https://github.com/neovim/neovim/issues/1004. As pointed out, the cmdline is also used for `:echo`, `:echoerr`, so these messages will flicker the statusline at unexpected timing.

**Comment by evprkr** [comment]
> This is impossible. See [vim/vim#940](https://github.com/vim/vim/issues/940), [neovim/neovim#1004](https://github.com/neovim/neovim/issues/1004). As pointed out, the cmdline is also used for `:echo`, `:echoerr`, so these messages will flicker the statusline at unexpected timing.

I kind of figured it would be. Thank you for explaining it!
