### ISSUE TITLE
What does the percentage represent?

### ISSUE THREAD

**Issue by TechWiz-3** [itchyny/lightline.vim#632]
On the lightline bar, I don't understand what the percent number on the right side represents, it's obviously not battery but I'm not sure what it could be?

Any guidance is appreciated.

**Comment by itchyny** [comment]
It shows the percentage of the current line over the line count of the file. It is the same value as the percentage shown by <kbd>CTRL-g</kbd>.

**Comment by TechWiz-3** [comment]
Wow thank you for the quick response. Love this tool :)
