### ISSUE TITLE
strange space on the right

### ISSUE THREAD

**Issue by call-me-anything-you-want** [itchyny/lightline.vim#637]
I find space on the right of the lightline which looks like this:
![image](https://user-images.githubusercontent.com/70688565/188312215-388873f5-40ae-424c-a9b5-8c405947c455.png)

here is my related setting:
let g:lightline.separator={'left': "\ue0b8", 'right': "\ue0be"}

the character "\ue0be" looks like this:
![image](https://user-images.githubusercontent.com/70688565/188312807-bb863b85-1b74-4207-b0d9-2c5eb1834816.png)

I'm pretty sure there is no extra space in this setting. And I have tried deleting other settings that I thought related to it in my vimrc as well but the problem is still not solved. So I can't figure what's wrong with it. 

I'm using gVim 8.2 under windows 11.

**Comment by itchyny** [comment]
This looks like a font issue. Try `:echo "M\ue0beM"` to see how it is rendered.

**Comment by call-me-anything-you-want** [comment]
it looks like this:
![image](https://user-images.githubusercontent.com/70688565/188314175-165fa148-c269-42c6-a179-f068319cc1be.png)

the font I'm using is DejaVuSansMono_NF

**Comment by itchyny** [comment]
Maybe setcellwidth will help.

**Comment by call-me-anything-you-want** [comment]
Thank you for your help. I just found out how to solve it.
I deleted "set ambiwidth=double" in my vimrc and the space disappeared

**Comment by call-me-anything-you-want** [comment]
I tried your suggestion as well.
:call setcellwidths([[0xe0be, 0xe0be, 1]]) can also solve the problem
Thanks
