### ISSUE TITLE
How to change the colour of 'ShowTime' component

### ISSUE THREAD

**Issue by dr-costas** [itchyny/lightline.vim#641]
Hi, 

I have `lightline` and `lightline_buffer`, and I have the following configuration: 

```vim
    \ 'tabline': {
    \   'left': [ [ 'bufferinfo' ],
    \             [ 'separator' ],
    \             [ 'bufferbefore', 'buffercurrent', 'bufferafter' ], ],
    \   'right': [ [ 'clock' ], ]
    \ },
```

where the `clock` is:

```vim
	\ 'component_function': {
	\	'clock': 'ShowTime',
	\ },
```

and the `ShowTime` is: 

```vim
function! ShowTime()
	return strftime('%c')
endfunction
```

I do have: 

```vim
    \ 'component_type': {
    \   'buffercurrent': 'tabsel',
    \   'bufferbefore': 'raw',
    \   'bufferafter': 'raw',
    \	'clock': 'tabsel',
    \ }
```

but the clock colouring is not working. How can I set a custom colour to the `clock` component?

**Comment by itchyny** [comment]
Note that `component_type` is not applied to `component_function` by design.
```vim
let g:lightline = {
      \ 'tabline': {
      \   'right': [ [ 'clock' ] ],
      \ },
      \ 'component_expand': {
      \   'clock': 'ShowTime',
      \ },
      \ 'component_type': {
      \   'clock': 'tabsel',
      \ },
      \ }
function! ShowTime()
  return strftime('%c')
endfunction
```

**Comment by dr-costas** [comment]
Got it! Thnx! It works.

Can you please tell me what is the difference between `component_expand` and `component_function`? When one is preferred over the other?

**Comment by itchyny** [comment]
These are different features. The golden rule of lightline components is that components in a group such as `g:lightline.active.left[0]` and `g:lightline.tabline.left[0]` have the same color. But within this rule, it is difficult to color the current tab in the `tabs` component. Component expansion is the phase to evaluate components, and create a component group if the component type is configured. This feature is introduced to implement the `tabs` component, but can be used to show the warning messages of syntactic tools. Note that expansion components in `'statusline'` are evaluated only when the active window is switched (you can force update by `call lightline#update()`), but when used in `'tabline'`, there are no such optimization and less performant.
