### ISSUE TITLE
statusline in white and black not colored

### ISSUE THREAD

**Issue by Mederim** [itchyny/lightline.vim#645]
OS: Gentoo Linux
Terminal: Foot
Session: Wayland

I tried using the `set laststatus=2` and the other solution:

```
if !has('gui_running')
    set t_Co=256
endif
```
and still have this same result: 

![20221224_19h50m41s_grim](https://user-images.githubusercontent.com/68717975/209453503-7031cf79-51fb-40e4-ac1f-5d3900705e8d.png)

**Comment by itchyny** [comment]
Make sure to install this plugin properly, and report with your entire Vim configuration for reproducibility.
