### ISSUE TITLE
How to change the color of the mode indicator and the separator

### ISSUE THREAD

**Issue by MIvanchev** [itchyny/lightline.vim#647]
I'm using solarized with a > separator and the contrast is really low to the point my eyes hurt trying to distinguish the left triangle

![screenshot](https://raw.githubusercontent.com/MIvanchev/images/ea4f4d9d17da1608028701966c66601b5f19bacb/low-contrast.png)

How can I change the color itself without touching the colorscheme settings?

**Comment by itchyny** [comment]
Changing some colors without changing the colorscheme is asked several times before (e.x. https://github.com/itchyny/lightline.vim/issues/381#issuecomment-523529581).
```vim
autocmd VimEnter * call SetupLightlineColors()
function SetupLightlineColors() abort
  let l:pallete = lightline#palette()
  let l:pallete.normal.left[0][3] = 196
  call lightline#colorscheme()
endfunction
```

**Comment by MIvanchev** [comment]
Thanks, I did search but not for long enough it seems, sorry! Is it also possible to set the separator color that way or is it derived from the normal color?

**Comment by itchyny** [comment]
The separator colors are automatically derived.
