### ISSUE TITLE
Failing automatic commands make lightline move upwards

### ISSUE THREAD

**Issue by attjo** [itchyny/lightline.vim#648]
## System
Distro: Ubuntu 22.04, Debian 10
Vim: 8.1.5126

## Problem
I noted on a new machine that I sometimes got a behaviour where lightline was printing a message in the bottom line, just under the statusline when I saved the file with `:x`, and if I saved again it got stacked like this

```sh
NORMAL | main | test.py
"test.py" [noeol] 3L, 36C written/bin/bash: ctags: command not found                                                  
"test.py" [noeol] 3L, 36C written/bin/bash: ctags: command not found
```

and tabs had moved out of the terminal window and so on. With `Ctrl + l` I could clean the window and get back.

Looking in to why this happened I realised that I didn't have ctags installed on my new machine which together with an automatic command to update ctags file for relevant filetypes in my `vimrc` creates this behaviour.

```vim
autocmd BufWritePost *.c,*.h,*.cpp,*.hpp,*.py silent! !ctags . &
```

## Solution

Install the missing package, in this case `ctags`.

## For lightline

I thought I let you know in case you see a way to make lightline not jump due to error messages from automatic commands like `BufWritePost`.

**Comment by itchyny** [comment]
This is an expected behavior of error messages of Vim and there is nothing we can do as a status plugin.
