### ISSUE TITLE
NORMAL word missing!

### ISSUE THREAD

**Issue by smokeyhallow** [itchyny/lightline.vim#649]
The word "NORMAL" isn't showing in normal mode! I thought it was an issue with colours, but when I selected the text, there is no text there! Insert mode works as expected!

I am trying this in Neovim 0.6.1 through a container inside WSL. There are a few errors in checkhealth related with encoding but since the word itself is missing I guess its something else?

![normal](https://user-images.githubusercontent.com/97153432/218246417-b3d1e55f-c3b2-461d-b998-7822266b2a92.png)

**Comment by itchyny** [comment]
Looks hard for me to reproduce the issue, but report more information as much as possible; OS, terminal, `:version`, minimal vimrc especially the lightline configuration, `:echo &statusline`, and `:echo lightline#mode()`.

**Comment by clach04** [comment]
I **think** I hit this too. Copy/paste with the mouse shows the text NORMAL is present; it's just the same color text as the background, so NORMAL appears to be invisible (certainly not readable 🙈  ).

I'm ONLY seeing this in GNU Screen, using raw (putty) terminal is fine. I've not tested with tmux, etc.

My workaround (whilst still using screen) is to NOT use the default lightline color scheme "powerline" nor "powerlineish", I was lazy and went for darcula (wombat also seems OK), I've not tested this properly but in case anyone else hits this, it hopefully leaves a breadcrumb trail/hint:

```vimrc
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ }
```

or:

```vimrc
" Workaround https://github.com/itchyny/lightline.vim/issues/649
let g:lightline = {'colorscheme': 'darcula',}
```

## potential diags

:echo &statusline
```
%{lightline#link()}%#LightlineLeft_active_0#%( %{lightline#mode()} %)%{(&paste)?"|":""}%( %{&paste?"PASTE":""} %)%#LightlineLeft_active_0_1#%#LightlineLeft_active_1#%( %R %)%{(&readonly
)&&(1||(&modified||!&modifiable))?"|":""}%( %t %)%{(&modified||!&modifiable)?"|":""}%( %M %)%#LightlineLeft_active_1_2#%#LightlineMiddle_active#%=%#LightlineRight_active_2_3#%#Lightline
Right_active_2#%( %{&ff} %)%{1||1?"|":""}%( %{&fenc!=#""?&fenc:&enc} %)%{1?"|":""}%( %{&ft!=#""?&ft:"no ft"} %)%#LightlineRight_active_1_2#%#LightlineRight_active_1#%( %3p%% %)%#Lightli
neRight_active_0_1#%#LightlineRight_active_0#%( %3l:%-2c %)

```

:echo lightline#mode()
```
NORMAL
```

I don't have any idea what version of lightline I have, git log (latest commit) shows:

```git
commit f11645cc6d37871244f2ea0ae972d3f6af9c8f73 (HEAD -> master, origin/master, origin/HEAD)
Merge: b1e91b4 3d10b50
Author: itchyny <itchyny@cybozu.co.jp>
Date:   Sun Sep 3 19:09:07 2023 +0900

    Merge pull request #659 from 4513ECHO/fix/neovim-floatwin

    fix: Make not to skip floatwin if it is focusable
```

I just needed this to work without digging too deep.

@itchyny thanks for this project! This was super easy to install with essentially no config (other than the workaround).

**Comment by clach04** [comment]
Confirmed still an issue with headrevs:

```
commit e358557e1a9f9fc860416c8eb2e34c0404078155 (HEAD -> master, origin/master, origin/HEAD)
Author: itchyny <itchyny@cybozu.co.jp>
Date:   Mon Dec 30 22:13:52 2024 +0900

    optimize evaluating expanding components
```
