### ISSUE TITLE
Error when installing new plugins with lazy.nvim

### ISSUE THREAD

**Issue by brycepg** [itchyny/lightline.vim#654]
The error is:

    ColorScheme Autocommands for "*"..function lightline#highlight, line 1: Vim(let):E121: Undefined
    variable: s:lightline

This error occurs when installing a new plugin when neovim opens with https://github.com/folke/lazy.nvim    
I'm using Windows Powershell as a terminal.

No file is opened I'm simply calling `nvim`

I removed all lightline configuration and the error still appears. Lmk and I'd be happy to open a lazy.nvim issue

**Comment by itchyny** [comment]
That sounds like an issue of session. Or plugin cache files. Please create a minimal vimrc for reproduction.

**Comment by brycepg** [comment]
Not sure why you closed this

**Comment by itchyny** [comment]
I closed because no further description was given. Given some reproducible setup, I'll look into this.

**Comment by brycepg** [comment]
It's all good. I've moved over to https://github.com/nvim-lualine/lualine.nvim which doesn't produce the error
