### ISSUE TITLE
bug : Undefined variable: g:lightline

### ISSUE THREAD

**Issue by archershan** [itchyny/lightline.vim#660]
![image](https://github.com/itchyny/lightline.vim/assets/126007455/885ceee4-c510-4da0-8cfe-1867abb562e6)
when I have wrote the `let g:lightline.colorscheme='default'` to the `init.vim` in neovim
and I confirm that I have installed the lightline by vim-plug

**Comment by itchyny** [comment]
Add `let g:lightline = {}` before that configuration.

**Comment by archershan** [comment]
thankyou，it has been solved
