### ISSUE TITLE
Lineinfo column doesn't match cursor column position

### ISSUE THREAD

**Issue by Aq32** [itchyny/lightline.vim#664]
Is there a way to show what the column number is when you exceed the written line column? 
For example your line might be 60 characters long but if you move your cursor beyond that then the lineinfo will still say lineNumber:60.

**Comment by itchyny** [comment]
Here's a configuration, for virtual editing users.
```vim
let g:lightline = {
      \ 'component': {
      \   'lineinfo': '%3l:%-2v',
      \ },
      \ }
```

**Comment by Aq32** [comment]
Nice! Thanks it works!
