### ISSUE TITLE
incorrect branch name on Gsplit

### ISSUE THREAD

**Issue by rkochar** [itchyny/lightline.vim#665]
```
let g:lightline = {
  \ 'active': {
  \ 'left': [['mode', 'paste'],
  \    ['gitbranch', 'readonly', 'filename', 'modified']],
  \ 'right': [['lineinfo'],
  \    ['percent'],
  \    ['fileformat', 'fileencoding']]
  \ },
  \ 'component_function': {
  \   'gitbranch': 'FugitiveHead'
  \ },
  \ }
```

Open a file in a git repository in branch 1, `:Gsplit <branch 2>` opens a new tab with same file in branch 2. Bottom left corner branch name is branch 1 (should be branch 2).

Thanks!

**Comment by itchyny** [comment]
The `FugitiveHead` function returns the current branch, but the `Gsplit` command does not checkout to the specified branch, so that's understandable behavior.

**Comment by rkochar** [comment]
Do you have a suggestion to get branch 2? Thanks!

**Comment by itchyny** [comment]
Would you ask to fugitive.vim devs? I'm not familiar with fugitive APIs.

**Comment by rkochar** [comment]
Thanks. I have made a [ticket with them](https://github.com/tpope/vim-fugitive/issues/2247).
