### ISSUE TITLE
extra spaces from lightline-problem-12

### ISSUE THREAD

**Issue by elig0n** [itchyny/lightline.vim#669]
Trying the example from `lightline-problem-12` the normal status line shows up like this:

![image](https://github.com/itchyny/lightline.vim/assets/31196036/f44e2576-24fd-48e4-b292-3bd71fa0148b)

One problem that is noticeable here is that there is an extra space/s before `filename`  component

Removing the `modified` component altogether gets it back to normal:

![image](https://github.com/itchyny/lightline.vim/assets/31196036/5b4c00bb-acdb-43af-a44e-5785fb6485ba)

I then found out that if I remove the highlight string `%#ModifiedColor#` from the component the extra spaces would be gone.

Since the returned line is 

```		  return &modified ? '+' : &modifiable ? '' : '-' ```

it does not make sense that the spacing comes from it.

**Comment by itchyny** [comment]
Setting the type of the component to raw will rid the spaces.
```
      \ 'component_type': {
      \   'modified': 'raw',
      \ },
```
