### ISSUE TITLE
All Highlighted/Selected Character Count?

### ISSUE THREAD

**Issue by Aq32** [itchyny/lightline.vim#671]
Is there a component that we can add onto lightline that shows the highlighted text character count as you select less/more text? 

Right now it looks like you can only see the native vim select character count and that changes from characters to line count if you select multiple lines. I'm looking to see my total character count when I select multiple lines.

**Comment by itchyny** [comment]
What do you mean by highlighted? Selected in the visual mode?

**Comment by Aq32** [comment]
Yes like: v[hjkl]
You can select/highlight characters and/or lines.  

I'm looking for something similar to [word count](https://github.com/itchyny/lightline.vim/issues/295) but for character counting.

**Comment by itchyny** [comment]
You can use some methods shared in [this page](https://stackoverflow.com/q/1533565/1363488). But note that the `'<` and `'>` positions are not updated often, this is a limitation of Vim.

**Comment by Aq32** [comment]
I'm not sure I understand what to do with this information.

**Comment by itchyny** [comment]
The solutions in the link shows how to get the selected text, you can count the bytes with `len(str)`, or you can accumulate the count for better performance.

**Comment by Aq32** [comment]
Thanks for your hint.

A lazy approach I used (for anyone else interested) from the link itchyny provided was to copy the Get_Visual_Selection() function (credit to xolox in the link) and then create a CharCount() wrapper function in the .vimrc file. (You could edit the Get_Visual_Selection function itself to be the CharCount() one to make the code shorter.) Then just added the lines necessary to format into lightline (still .vimrc file).
`
function! Get_Visual_Selection()
    let [line_start, column_start] = getpos("'<")[1:2]
    let [line_end, column_end] = getpos("'>")[1:2]
    let lines = getline(line_start, line_end)
    if len(lines) == 0
        return ''
    endif
    let lines[-1] = lines[-1][: column_end - (&selection == 'inclusive' ? 1 : 2)]
    let lines[0] = lines[0][column_start - 1:]
    return join(lines, "\n")
endfunction

function! CharCount()
    return len(Get_Visual_Selection())
endfunction
`

then in the lightline configuration section edit in where in the bar you want it eg.:
`
...
\   'active' : {
...
\       'right': [
\             [ 'lineinfo' ],
\               [ 'wordcount' ],
\               [ 'charcount' ],
...
\   },
`
and the component function part:
`
\   'component_function': {
\           'charcount': 'CharCount',
\           'wordcount': 'WordCount',
\   },
`
