### ISSUE TITLE
middle active/inactive items missing from statusline

### ISSUE THREAD

**Issue by elig0n** [itchyny/lightline.vim#672]
Items I set at `g:lightline.active.middle` or `g:lightline.inactive.middle` don't show up in the  final statusline.

> echo lightline#statusline(0)

shows no items after the middle highlight group, i.e.:

> ... %#LightlineLeft_active_1_2#%#LightlineMiddle_active#%=%#LightlineRight_active_2_3 ...

I see that several `LightlineMiddle_*` highlight groups were made available by the script .

https://github.com/itchyny/lightline.vim/blob/58c97bc21c6f657d3babdd4eefce7593e30e75ce/autoload/lightline.vim#L415

Source shows indeed that nothing is parsed for being added to the LightlineMiddle_ highlight in s:line

**Comment by itchyny** [comment]
There is no place to show, so this is simply not supposed. What's your expectation?

**Comment by elig0n** [comment]
> There is no place to show, so this is simply not supposed. What's your expectation?
What's wrong with how ti is ? just show it anyway ...

**Comment by itchyny** [comment]
You can add components to the left group, it will be rendered in the middle colors if the array size is bigger than that of the color list of the colorscheme pallete.

**Comment by elig0n** [comment]
I don't like that behavior.

**Comment by itchyny** [comment]
Please describe the reason.

**Comment by elig0n** [comment]
I want to keep the styles of the 'left' group intact for what is defined for them regardless of current colorscheme which I change often.

Also please consider adding a source comment or documentation for what happens with middle just like you explained for the sake of others

**Comment by itchyny** [comment]
I don't think I'm going to accept this proposal, closing the issue.
