### ISSUE TITLE
How do I ignore certain filetypes?

### ISSUE THREAD

**Issue by fent** [itchyny/lightline.vim#677]
I'd like to not have lightline enabled on terminal buffers? I didn't see anything looking through the docs. Can this be configured?

**Comment by itchyny** [comment]
This is not supported in this plugin by design. However, for terminal buffers, you can use the `TerminalWinOpen` event to override the local statusline (`autocmd TerminalWinOpen * setlocal statusline=`). I don't recommend this way though.
