### ISSUE TITLE
Changing the color of modified file symbol

### ISSUE THREAD

**Issue by heliotech** [itchyny/lightline.vim#678]
It would be quite convenient, if the symbol for modified file (+), was in a different colour, say red. Is it possible to implement that?

(If it is already possible to change that, I apologize --  I simply don't know how to do that. I've been asking ChatGPT for a solution, but to no avail. If it is the case, this change could be described in the documentation (I haven't found it)).

**Comment by itchyny** [comment]
Please refer to the help; `:h lightline-problem-12`.

**Comment by heliotech** [comment]
Thanks! It worked, sorry I didn't search enough. It looks quite complicated. It might be against the spirit of _lightline_, though it is a bit easier to spot the symbol.
(And how to change the red color for another, I wonder…)
Thanks again, I greatly appreciate your help and prompt response.
