### ISSUE TITLE
Switching background (set bg=dark vs set bg=light)

### ISSUE THREAD

**Issue by mahush** [itchyny/lightline.vim#680]
I am using PaperColor color scheme. In this regard my vimrc looks as follows:
 ```
set background=light
colorscheme PaperColor

let g:lightline.colorscheme = 'PaperColor'
```

The issue is that when I switch from light to dark within a vim session by putting the `set bg=dark` command, vim itself changes, but   lightline does not. 

I am aware of `:h lightline-problem-13` which didn't helped here, maybe because PaperColor is not considered in the following statement `if g:colors_name =~# 'wombat\|solarized\|landscape\|jellybeans\|seoul256\|Tomorrow'`?

Also [the approach you suggested here](https://github.com/itchyny/lightline.vim/issues/650#issuecomment-1493331855) has no effect. 

So, how can I switch between light and dark without restarting vim? Any help is appreciated 🙏 

By the way, thanks a lot for the great plugin!

**Comment by itchyny** [comment]
Did you try this?
```vim
autocmd OptionSet background
      \ execute 'source' globpath(&rtp, 'autoload/lightline/colorscheme/PaperColor.vim')
      \ | call lightline#colorscheme() | call lightline#update()
```

**Comment by mahush** [comment]
Thank you @itchyny. Indeed, the provided auto command solves the issue!

Would it be possible to include a generic form of this within the plugin itself?

**Comment by itchyny** [comment]
No, not all user want to switch the lightline colorscheme based on the background, and not all colorscheme have both variants. Switching something automatically is surprising for most users, and there's a simple way of configuration here, that is enough.
