### ISSUE TITLE
Lightline themes doesn't work with Neovim 0.10.1 and newer versions

### ISSUE THREAD

**Issue by Hund** [itchyny/lightline.vim#682]
This is what my Lightline with the Solarized theme looks like know. They changed things with the colours or something, which broke pretty much every colour scheme out there. Lightline seems to be affected as well.

![2024-09-17-112334_1920x1080_scrot](https://github.com/user-attachments/assets/626a8a84-bf19-46e7-a1fe-a0c0ef41e6dc)

Is there any way to fix this?

**Comment by itchyny** [comment]
Could you identify which change in neovim causes the regression?

**Comment by Hund** [comment]
> Could you identify which change in neovim causes the regression?

Checking `:h news` shows me this:

```
  • Default color scheme has been updated to be "Nvim branded" and accessible.
    Use `:colorscheme vim` to revert to the old legacy color scheme.
    • These Nvim specific highlight groups are now defined in a meaningfully
      different way and might need an update:
      • |hl-FloatBorder| is linked to |hl-NormalFloat| instead of |hl-WinSeparator|.
      • |hl-NormalFloat| is not linked to |hl-Pmenu|.
      • |hl-WinBar| has different background.
      • |hl-WinBarNC| is similar to |hl-WinBar| but not bold.
      • |hl-WinSeparator| is linked to |hl-Normal| instead of |hl-VertSplit|.
    • This also might result into some color schemes looking differently due
      to them relying on implicit assumptions about how highlight groups are
      defined by default. To account for this, define all attributes of
      highlight groups explicitly. Alternatively, use `:colorscheme vim` or
      `:source $VIMRUNTIME/colors/vim.lua` to restore previous definitions.
```

There's been a few complaints about this as well, like this one: https://github.com/neovim/neovim/issues/29013

**Comment by itchyny** [comment]
What's the result of `:echo [get(g:, 'solarized_termcolors', -1), &t_Co]`? Both with Neovim 0.10.1 and with the Neovim version worked before.

**Comment by itchyny** [comment]
<img width="719" alt="Screenshot 2024-09-18 at 15 13 50" src="https://github.com/user-attachments/assets/cbb0c6d1-d8ee-430a-9ee7-bb711694bd64">
I cannot reproduce the issue yet, so please describe the reproducing steps as in detail as possible.
Here's the init.lua I used when I took screenshot above.
```lua
vim.o.runtimepath = '/path/to/lightline,' .. vim.o.runtimepath
vim.g.lightline = {
  colorscheme = 'solarized',
}

vim.o.laststatus = 3
```

**Comment by Hund** [comment]
> What's the result of `:echo [get(g:, 'solarized_termcolors', -1), &t_Co]`? Both with Neovim 0.10.1 and with the Neovim version worked before.

I get the same message with version 0.9.5 and 0.10.1: `[-1, '256']`


> <img alt="Screenshot 2024-09-18 at 15 13 50" width="719" src="https://private-user-images.githubusercontent.com/375258/368442112-cbb0c6d1-d8ee-430a-9ee7-bb711694bd64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDkxNTksIm5iZiI6MTcyNjY0ODg1OSwicGF0aCI6Ii8zNzUyNTgvMzY4NDQyMTEyLWNiYjBjNmQxLWQ4ZWUtNDMwYS05ZWU3LWJiNzExNjk0YmQ2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwODQwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDAwNDUyOTdhNzc2NGZkMjU4M2ViNDMxMWI5YTE3MjFhODc0YTc0NTkxNGJmMzBmMmVkODIxNGNkNGE5MTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W_C9E8b6D_DkInfKt7q-nuq45cFu_1Z9TdVM31OZWDc">
> 
> I cannot reproduce the issue yet, so please describe the reproducing steps as in detail as possible. Here's the init.lua I used when I took screenshot above.
> 
> ```lua
> vim.o.runtimepath = '/path/to/lightline,' .. vim.o.runtimepath
> vim.g.lightline = {
>   colorscheme = 'solarized',
> }
> 
> vim.o.laststatus = 3
> ```

1. I upgraded to the newer version of Neovim 0.10.1.
2. Themes and Lightline are broken.
3. Replacing old theme [vim-colors-solarized](https://github.com/altercation/vim-colors-solarized) with newer NeoVim theme [neosolarized.nvim](https://github.com/svrana/neosolarized.nvim).

If I want to get everything to 'work', I have to downgrade to version 0.9.5 and go back to the old theme with the old syntax of how themes now work.

My wild guess would be that the Solarized theme for Lightline relies on the old way how themes work in version 0.9.5 and earlier versions. :)

**Comment by Hund** [comment]
> Please share your Neovim configuration file to reproduce the issue, and the screenshot how it looks with 0.9.5.

I can give you the relevant parts of my config:

```
call plug#begin('~/.config/nvim/plugged')
Plug 'overcache/NeoSolarized'
Plug 'itchyny/lightline.vim'
call plug#end()

let g:lightline = { 'colorscheme': 'solarized', }
set laststatus=2

colorscheme NeoSolarized
set background=dark
```
I included a screenshot in the first post. :)

**Comment by itchyny** [comment]
What do you mean by broken?

**Comment by Hund** [comment]
They changed how things work with themes, which broke old themes. They simply doesn't work anymore. I could solve it by using a new theme explicitly written for newer version of Neovim (not Vim). This seems to have broken Lightline as well, as it seems to be relying on how themes worked in the past.

**Comment by itchyny** [comment]
Sorry but I can't still understand what you're talking. What do you mean by old/new themes? The colors of lightline is not related to the pre-defined highlight groups. For me, Neovim 0.10.0 working well with lightline colors perfectly. You still don't describe how you expect to see; the screenshot in the first post looks lightline working.

**Comment by Hund** [comment]
The affected version is 0.10.1. Not 0.10.0. See my previous reply with the `:h news` part.

The first image in the first shows me when I have the theme Solarized. I'm sorry if that wasn't clear. It's broken in the sense that it uses some other colours than the Solarized ones.

**Comment by itchyny** [comment]
Do you think it works or not in the screenshot in https://github.com/itchyny/lightline.vim/issues/682#issuecomment-2357592462?

**Comment by Hund** [comment]
I forgot about this. I gave up on Neovim and went back to Vim. I had too much issues with Neovim. They seem to follow the philosophy of Mark: "Move fast, break things".

Thank you for your time, trying to help me with this issue.

**Comment by Hund** [comment]
I'm back with Neovim again. :)

> Also, what's the result of `:hi LightlineMiddle_command` and `:hi LightlineLeft_normal_0` ?

```
:hi LightlineMiddle_command                                                                                  
LightlineMiddle_command xxx ctermfg=245 ctermbg=236 guifg=#8a8a8a guibg=#303030
```
```
:hi LightlineLeft_normal_0
LightlineLeft_normal_0 xxx cterm=bold ctermfg=22 ctermbg=148 gui=bold guifg=#005f00 guibg=#afdf00
```

I hope this is of any help?

**Comment by itchyny** [comment]
Could you share a minimal (less than 10 lines) and complete (not part of) configuration file to reproduce the issue.

**Comment by Hund** [comment]
> Could you share a minimal (less than 10 lines) and complete (not part of) configuration file to reproduce the issue.

Sure!

```vim
call plug#begin('~/.config/nvim/plugged')

Plug 'overcache/NeoSolarized'
Plug 'itchyny/lightline.vim'

call plug#end()

let g:lightline = { 'colorscheme': 'solarized', }
```

This is with Neovim 0.9.5 in Linux Mint.

**Comment by MIvanchev** [comment]
I don't know why this issue is closed because the problem is very much still there. NeoVim 0.11.0 on Void Linux, solarized8 theme and the colors in the status line are all wrong. Lualine works without issues.

**Comment by jchnkl** [comment]
This worked for me:
```
vim.api.nvim_set_hl(0, "StatusLine", { reverse = false })
vim.api.nvim_set_hl(0, "StatusLineNC", { reverse = false })
```
Apparently the new highlight groups are reversed by default now.
