### ISSUE TITLE
Separator triangle looks perfect on the left side but has a small gap on the right side

### ISSUE THREAD

**Issue by harrypotterIUP** [itchyny/lightline.vim#683]
![screenshot11](https://github.com/user-attachments/assets/bcb7f8c3-a506-44e4-a1bf-5d5287c4b379)

The gap looks just like the screenshot above: perfect on the left side, but a little bit of a gap on the right side. Is there anything that lightline can do to fix this issue or is this completely dependent on font and terminal emulator rendering?

**Comment by itchyny** [comment]
Yes, this is rendering issue of the terminal and the font, lightline plugin cannot handle it. About the font repo link, could you send a PR for it. I can't recommend using patched fonts anyways.
