### ISSUE TITLE
Is it possible to add colorscheme to vimrc or change colors from inside vimrc?

### ISSUE THREAD

**Issue by harrypotterIUP** [itchyny/lightline.vim#684]
Great plugin! :heart: Quick question: I want to change only a few color settings. Do I have to create a whole new colorscheme file or can I modify linelight colors from inside vimrc, too? Thanks!

**Comment by itchyny** [comment]
Please check https://github.com/itchyny/lightline.vim/issues/168#issuecomment-569881983.
