### ISSUE TITLE
Statusline normal mode doesn't automatically adjust to colorscheme change

### ISSUE THREAD

**Issue by harrypotterIUP** [itchyny/lightline.vim#686]
I have to load my vim colorscheme like this:

    autocmd VimEnter * colorscheme onedark

(Due to issues with its plugin path.) This seems to result in lightline colors not working for normal mode. (Independent from chosen lightline colorscheme.) If I switch to any other mode (insert, visual, ...), coloring of lightline works in that mode. However, switching back to normal mode, lightline colors stop working again.

`:redrawstatus` doesn't help. However, if I run `:colorscheme onedark` manually again, lightline coloring works in normal mode, too. Running `:call lightline#colorscheme()` doesn't work right away, but after switching to any other mode (insert, visual, ...) and back - now normal mode works, too.

Unfortunately, adding another autocmd doesn't seem to help, either:

    autocmd VimEnter * call lightline#colorscheme()

I couldn't find any mentions of a similar issue in previous threads. Maybe you can see what's wrong right away. I tried to describe the issue, but please let me know if I should go more into detail or post a screenrecording or steps how to reproduce.

Thank you very much in advance.

**Comment by itchyny** [comment]
Try `autocmd VimEnter * ++nested colorscheme onedark`.

**Comment by itchyny** [comment]
Delaying setting colorscheme to VimEnter is non-standard usage (you don't need to do if you properly configure runtime paths), so it can cause some unexpected side effects like that.
