### ISSUE TITLE
ctermbg for whole line of lightline

### ISSUE THREAD

**Issue by arozehnal** [itchyny/lightline.vim#688]
I use lightline on Windows (gvim GUI) 
![image](https://github.com/user-attachments/assets/d3850f02-c0e1-4db5-914e-8087e379b38f)

and on AIX (term vim).
![image](https://github.com/user-attachments/assets/5851a21f-d5ec-4323-a7fb-c877914bd5fd)

I would like to have in the terminal  the whole background of the lightline  colored in case of the editing mode similar to the gui on win.

**Comment by itchyny** [comment]
Do you enable `termguicolors` on?

**Comment by itchyny** [comment]
Oops, sorry (I noticed I was responding to different issue). What does `:hi LightlineMiddle_normal` print?

**Comment by arozehnal** [comment]
Win
![image](https://github.com/user-attachments/assets/520dea4c-f7fc-4ec9-b360-fa87bfb9d558)


AIX
![image](https://github.com/user-attachments/assets/22c40558-22c0-4ec1-85b6-3d5e6db4cb4d)

**Comment by itchyny** [comment]
You seem to configure the lightline colorsheme. Did you check how you set `g:lightline` in vimrc?

**Comment by arozehnal** [comment]
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ], [ 'readonly', 'absolutepath', 'modified' ] ],
      \   'right': [ [ 'lineinfo' ], [ 'charvaluehex', 'fileencoding', 'fileformat', 'filetype' ] ]
      \ },
      \ 'component': {
      \   'charvaluehex': '%b'
      \ },
      \ }

**Comment by arozehnal** [comment]
Great, problem solved :-), issue can be closed,.
Thank you very much for your help.
