### ISSUE TITLE
lightline.vim covering vim-ctrlspace tabline message

### ISSUE THREAD

**Issue by pihao** [itchyny/lightline.vim#73]
vim-ctrlspace is working well when use default statusline
![use_default](https://cloud.githubusercontent.com/assets/3308394/3534646/8641b24e-07ef-11e4-8e5f-c9cbe45d8a1b.png)

Can't see the vim-ctrlspace special statusline characters when use lightline.vim plugin. Covered by lightline.vim?
![use_lightline](https://cloud.githubusercontent.com/assets/3308394/3534663/c2f59430-07ef-11e4-8486-a79cecc95959.png)

the two screenshots are vim-ctrlspace Search Mode.
Windows 8.1
gvim 7.4

vim-ctrlspace: [https://github.com/szw/vim-ctrlspace](https://github.com/szw/vim-ctrlspace)
lightline.vim: [https://github.com/itchyny/lightline.vim](https://github.com/itchyny/lightline.vim)

**Comment by biotician** [comment]
Could you give me a few more clues about how to get this:
![lightline+CtrlSpace](https://cloud.githubusercontent.com/assets/3308394/3534663/c2f59430-07ef-11e4-8486-a79cecc95959.png)
The CtrlSpace plugin override the lightline:
![2015-06-01-020442_1366x768_scrot](https://cloud.githubusercontent.com/assets/7250745/7904600/bb045766-0802-11e5-8728-6fc9c58968d5.png)
In my `.vimrc`, I have, in this order:
```
set nocompatible
execute pathogen#infect()
set laststatus=2
let g:airline_exclude_preview = 1
```

I have read [CtrlSpace](https://github.com/szw/vim-ctrlspace) API page, and seen every results for `"lightline" "ctrlspace"`, but I didn't find any solution. 

It isn't a big issue at all but a minor adjustment.

Thank you for your attention!
ありがとうございました
