### ISSUE TITLE
Syntastic only works for *.c and *.cpp

### ISSUE THREAD

**Issue by esn89** [itchyny/lightline.vim#77]
As per your example that you provided, there is only the two file types that it checks for.

Adding a *.py and a *.sh does not seem to work.  I purposely made python/shell scripts with errors and syntastic only picks up *.cpp and *.c errors.

I even tried setting a wildcard in there:

http://i.imgur.com/QF8JEJY.png

As per line 30.

Any advice?

**Comment by jordwalke** [comment]
I see this issue too, but if it is a problem with syntastic, why do I not have the same problem with Airline?
