### ISSUE TITLE
Toggle Lightline when using Goyo

### ISSUE THREAD

**Issue by obxhdx** [itchyny/lightline.vim#83]
I have [Goyo.vim](https://github.com/junegunn/goyo.vim) installed, which provides a distraction-free mode.

I want to temporarily disable Lightline when Goyo gets enabled, just like Goyo already does for some other plugins: https://github.com/junegunn/goyo.vim/blob/master/plugin/goyo.vim#L150.

I tried calling `lightline#disable()` but Lightline always comes back after a few seconds.

**Comment by yous** [comment]
You can modify your `autocmd` to update lightline.vim only when it's enabled.

``` vim
autocmd CursorHold,BufWritePost,InsertLeave * call s:component_expand()
function! s:component_expand()
  call TrailingSpaceWarning()
  call MixedIndentSpaceWarning()
  if exists('#lightline')
    call lightline#update()
  endif
endfunction
```
