### ISSUE TITLE
Path to file?

### ISSUE THREAD

**Issue by adamski** [itchyny/lightline.vim#87]
Is there a way to show the path to a file if outside the current working dir?
Thanks

**Comment by biotician** [comment]
It worked for me, thank you for all these tips.

from this [thread](http://stackoverflow.com/questions/4525261/getting-relative-paths-in-vim), I've seen that `fnamemodify(expand("%"), ":~:.")` let me "reduce the path relative to the home folder if possible":
```
:pwd
/home/josuah/Downloads
```
> filename: `~/.vim/colors/molokai.vim`

```
:cd ~/.vim
:pwd
/home/josuah/.vim
```
> filename: `colors/molokai.vim`

Wish it helps someone.

I love lightline design allowing very fine tuning with ease. Thank you for your work!

**Comment by itchyny** [comment]
You're welcome. When I started to work on lightline, I tried to find the design with maximum configurability with minimum core scripts. Enjoy improving your configuration better for you.

**Comment by biotician** [comment]
Thank you. So will I.

**Comment by krzkrzkrz** [comment]
Hmmm, so what exactly needs to go in `.vimrc` to display the path and filename in the lightline status bar?

**Comment by itchyny** [comment]
Absolute path
```vim
let g:lightline = {
      \ 'component_function': {
      \   'filename': 'LightLineFilename'
      \ }
      \ }
function! LightLineFilename() abort
  return expand('%:p:h')
endfunction
```

Relative path
```vim
let g:lightline = {
      \ 'component_function': {
      \   'filename': 'LightLineFilename'
      \ }
      \ }
function! LightLineFilename() abort
  return expand('%')
endfunction
```

**Comment by krzkrzkrz** [comment]
That's strange. That doesn't change anything... Do I need additional configuration?

**Comment by itchyny** [comment]
No.

**Comment by krzkrzkrz** [comment]
Ahh I see, shinchu/lightline-gruvbox.vim seemed to have override the setting

**Comment by aktau** [comment]
If I'm seeing this right, instead of redefining the filename component function, one could also just use the `relativepath` component. At least that seems to work for me.

It does make overriding in different scripts more difficult to handle, though.

**Comment by itchyny** [comment]
Ah, yes... `relativepath` component will work enough...

**Comment by nothingelsematters7** [comment]
@aktau can you please provide an example of how to do it without overriding?

**Comment by itchyny** [comment]
```vim
let g:lightline.active = {
    \ 'left': [ [ 'mode', 'paste' ], [ 'readonly', 'relativepath', 'modified' ] ]
    \ }
```

**Comment by nothingelsematters7** [comment]
@itchyny Thank you :+1:

**Comment by akarki15** [comment]
I use something like this for nicely abbreviated path-

```
let g:lightline = {
      \ 'component_function': {
      \   'filename': 'LightLineFilename'
      \ }
      \ }
function! LightLineFilename()
	let name = ""
	let subs = split(expand('%'), "/") 
	let i = 1
	for s in subs
		let parent = name
		if  i == len(subs)
			let name = parent . '/' . s
		elseif i == 1
			let name = s
		else
			let name = parent . '/' . strpart(s, 0, 2)
		endif
		let i += 1
	endfor
  return name
endfunction
```

Outputs:
![image](https://user-images.githubusercontent.com/3751173/29725574-99dda792-899a-11e7-8439-3b8946922bbc.png)

**Comment by her** [comment]
Thanks for the tips everyone. 

What I did was set `expand('%:p:h')` in the filename component and then also added `relativepath` to lightline's `active` hash.

<img width="392" alt="screen shot 2017-09-06 at 10 39 34 am" src="https://user-images.githubusercontent.com/10278096/30126093-b772de72-92ef-11e7-88b3-df656b3b7312.png">

this is working well so far! cheers <3

**Comment by carusog** [comment]
Thanks you all for the above replies.

Thanks to them, I was able to solve an issue I am having with a codebase lastly where all main files in a component folder are called `index.xyz`. As you can imagine, it's very confusing having a lot of index files open a trying to understand who is who.

So, I wrote (my very first) VimL function to solve the issue, by showing, in case of an index file, also its latest folder like `folderName/index.xyz`.

I hope it can be useful for other people having the same issue. 

About that, if @itchyny thinks it's a good configuration option to have for the plugin, I can try to make a PR for integrating it. 

Finally, that't my first time writing a VimL function, please, feel free to give me feedback about it, I would really appreciate it. I hope it makes sense 😄 . 

```viml
let g:lightline = {
\    'colorscheme': 'dracula',
\    'active': {
\        'left': [ [ 'mode', 'paste' ], [ 'gitbranch', 'readonly', 'filenameOrLastFolderOfIndex', 'modified' ] ]
\    },
\    'component_function': {
\        'gitbranch': 'fugitive#head',
\        'filenameOrLastFolderOfIndex': 'LightLineFixIndexFiles'
\    },
\}
function! LightLineFixIndexFiles()
    let filenameonly = expand('%:t:r')
    if filenameonly ==? "index"
        return remove(split(expand("%:h"), "/"), -1) . "/" . expand("%:t")
    else 
        return expand("%:t")
    endif
endfunction
```

**Comment by Nitrodist** [comment]
@itchyny these snippets should be in the readme
