### ISSUE TITLE
Showing Full Length of file

### ISSUE THREAD

**Issue by indiesquidge** [itchyny/lightline.vim#92]
Is there a way for me to show the current line as well as the total number of lines in the current buffer? I would love for it to say `023/106` if I was on line 23 and the file was 106 lines long.

Thanks!

**Comment by itchyny** [comment]
Use `line('.') . '/' . line('$')`.

**Comment by indiesquidge** [comment]
Would I have to add that manually somewhere? Is there no way to add it directly within the lightline config? As such:
```
'left': [ [ 'mode', ], [ 'fugitive', 'readonly', 'filename' ] ],
'right': [ [ 'syntastic', 'lineinfo', "line('.') . '/' . line('$')" ], [ 'filetype' ] ]
```

I'm fairly new to editing my vimrc files, so I'm a bit confused where I should be adding this. Any help would be much appreciated.

**Comment by itchyny** [comment]
Please read README or doc. The following examples should work for you. Choose the one you like.
```vim
let g:lightline = {
      \ 'component': {
      \   'lineinfo': "%{line('.') . '/' . line('$')}",
      \ },
      \ }
```
```vim
let g:lightline = {
      \ 'component': {
      \   'lineinfo': "%{printf('%03d/%03d', line('.'),  line('$'))}",
      \ },
      \ }
```
```vim
let g:lightline = {
      \ 'component_function': {
      \   'lineinfo': "MyLineinfo",
      \ },
      \ }
function! MyLineinfo() abort
  return line('.') . '/' . line('$')
endfunction
```
```vim
let g:lightline = {
      \ 'component_function': {
      \   'lineinfo': "MyLineinfo",
      \ },
      \ }
function! MyLineinfo() abort
  return printf('%03d/%03d', line('.'),  line('$'))
endfunction
```
```vim
let g:lightline = {
      \ 'active': {
      \   'right': [ [ 'syntastic', 'mylineinfo' ], [ 'filetype' ] ],
      \ },
      \ 'component_function': {
      \   'mylineinfo': "MyLineinfo",
      \ },
      \ }
function! MyLineinfo() abort
  return line('.') . '/' . line('$')
endfunction
```

**Comment by indiesquidge** [comment]
I did, in fact, read the whole README. Sometimes its just difficult to not only know where to write what you want, but how to format it, correct syntax, etc. Especially if you're a beginner. Thank you for your help though, I really appreciate it.
