### ISSUE TITLE
color16 theme colors hard to read

### ISSUE THREAD

**Issue by heidar** [itchyny/lightline.vim#94]
I decided to use color16 as my colorscheme and I find it almost impossible to read with default settings. See screenshot (the blue fg on green bg on the right):

![screen shot 2015-02-15 at 8 05 38 pm](https://cloud.githubusercontent.com/assets/1471406/6203190/b860a3e0-b54e-11e4-822c-518b3f19a1bb.png)

I'm using base16-default dark as my colorscheme. I thought color16 would be the same but it seems the colors are different? Would it make sense to have base16-default in there instead of color16?

Thanks :)

**Comment by itchyny** [comment]
The `color16` colorscheme uses the colors from 0 to 15 and associated colors are determined by the terminal settings. Unfortunately, `lightline` cannot detect what the 16 colors look like. The appearance changes due to the connections between the 16 numbers to the real colors.

**Comment by heidar** [comment]
Ahh, ok. Got it, thanks.
