### ISSUE TITLE
Question: how to define custom precent/lineinfo

### ISSUE THREAD

**Issue by bitterjug** [itchyny/lightline.vim#95]
Hi I'm enjoying lightline.
In my vimfiler explorer sidebar I want to hide the line info and percent indicators to leave more space for the current path on the left. I've tried `component_function` and ` component_expand` functions, but when I provide the default string, e.g. '%3p%%' that's what I see in the status line instead of the expanded version. I can't figure out from the code when the `%3p` gets expanded. What am I missing?

**Comment by itchyny** [comment]
Try setting in the `g:lightline.component`.

**Comment by bitterjug** [comment]
`g:lightline.component` sets the base strings, right? I can use it to change the format of the percent and line-info segments, but it doesn't seem to accept a function (I see the function name, not its return value, in the component).  

I guess what I really want is for the line-info and percent components, and their groups, to not show up at all in my vimfiler window. Is that possible? I have tried
``` viml
g:lightline.component_visible_condition[ 'percent'] = 0
```
to check if I could turn off the component that way, but it doesn't work. 

Failing that, I'd settle for making the percent and line-info's component groups small (empty). Which was my first strategy:

``` viml
g:lightline.component_function['percent'] = 'MyPercent'
function! MyPercent()
    return &ft =~? 'vimfiler' ? '' : '%3p%%'
endfunction
```

This empties the component group in vimfiler windows, but, like I said, the `%3p%%` doesn't get expanded by vim for other windows.

I'm finding the source code pretty dense. Which is why I'm asking for your help.

**Comment by itchyny** [comment]
Try
```vim
function! MyPercent()
    return &ft =~? 'vimfiler' ? '' : 100 * line('.') / line('$')
endfunction
```

**Comment by bitterjug** [comment]
OK that nailed it. Thanks for your quick answers.

**Comment by horseinthesky** [comment]
I have a question. If I have this:
```
  \ 'component': {
  \   'lineinfo': ' %3l:%-2v%<',
  \ },
```
![image](https://user-images.githubusercontent.com/19948672/71574813-77020380-2afb-11ea-859f-4972f7a22d7c.png)


How to make it look like `<line_num>/<max_line_num>:<char_num>`?

**Comment by itchyny** [comment]
@horseinthesky Try `%3l/%L:${line2byte(line("$")+1)-1}`.

**Comment by horseinthesky** [comment]
@itchyny This worked to the component:
```
  \ 'component': {
  \   'lineinfo': ' %3l/%L:%-2v%<',
```
And this worked for a function you wrote for me:
```
function! LightlineLineInfo()
  return expand('%:t') =~# g:viewplugins ? '' : printf(' %d/%d:%-2d', line('.'), line('$'), col('.'))
endfunction
```

Thanks =)
