### ISSUE TITLE
Lightline, fugitive and sshfs

### ISSUE THREAD

**Issue by kiryph** [itchyny/lightline.vim#96]
I have added the fugitive branch info to the lightline. I have noticed that scrolling became quite slow when I was viewing a file mounted through sshfs. I could resolve this issue by removing fugitive status from lightline.

Can you confirm this?

I think this information is helpful for user of your plugin and a note could be added to the Troubleshooting section of your helpfile

see also https://github.com/seletskiy/vim-refugi for the problem of fugitive or more precisely git with sshfs

**Comment by itchyny** [comment]
Please paste your configuration.

**Comment by kiryph** [comment]
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
    "                             Plugin: Lightline                              "
    """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
    let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'fugitive', 'readonly', 'filename', 'modified', 'spell', 'syntastic' ] ],
      \   'right': [ [ 'lineinfo' ], ['percent'], [ 'fileformat', 'fileencoding', 'filetype' ] ]
      \ },
      \ 'component': {
      \   'spell': '%{&spell?&spelllang:"no spell"}',
      \   'modified': '%{&filetype=="help"?"":&modified?"+":&modifiable?"":"-"}',
      \   'fugitive': '%{&filetype=="help"?"":exists("*fugitive#head")?fugitive#head():""}'
      \ },
      \ 'component_visible_condition': {
      \   'readonly': '(&filetype!="help"&& &readonly)',
      \   'modified': '(&filetype!="help"&&(&modified||!&modifiable))',
      \   'fugitive': '(&filetype!="help"&&exists("*fugitive#head") && ""!=fugitive#head())'
      \ },
      \ 'component_expand': {
      \   'syntastic': 'SyntasticStatuslineFlag',
      \ },
      \ 'component_type': {
      \   'syntastic': 'error',
      \ }
      \ }

**Comment by itchyny** [comment]
How about the following config?
```vim
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                             Plugin: Lightline                              "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:lightline = {
  \ 'active': {
  \   'left': [ [ 'mode', 'paste' ],
  \             [ 'fugitive', 'readonly', 'filename', 'modified', 'spell', 'syntastic' ] ],
  \   'right': [ [ 'lineinfo' ], ['percent'], [ 'fileformat', 'fileencoding', 'filetype' ] ]
  \ },
  \ 'component': {
  \   'spell': '%{&spell?&spelllang:"no spell"}',
  \   'modified': '%{&filetype=="help"?"":&modified?"+":&modifiable?"":"-"}',
  \ },
  \ 'component_visible_condition': {
  \   'readonly': '(&filetype!="help"&& &readonly)',
  \   'modified': '(&filetype!="help"&&(&modified||!&modifiable))',
  \ },
  \ 'component_function': {
  \   'fugitive': 'LightlineFugitive',
  \ },
  \ 'component_expand': {
  \   'syntastic': 'SyntasticStatuslineFlag',
  \ },
  \ 'component_type': {
  \   'syntastic': 'error',
  \ }
  \ }

function! LightlineFugitive() abort
  if &filetype ==# 'help'
    return ''
  endif
  if has_key(b:, 'lightline_fugitive') && reltimestr(reltime(b:lightline_fugitive_)) =~# '^\s*0\.[0-3]'
    return b:lightline_fugitive
  endif
  try
    if exists('*fugitive#head')
      let head = fugitive#head()
    else
      return ''
    endif
    let b:lightline_fugitive = head
    let b:lightline_fugitive_ = reltime()
    return b:lightline_fugitive
  catch
  endtry
  return ''
endfunction
```

**Comment by kiryph** [comment]
Looks good. Thanks for that.

I have encountered a problem testing different `vimrc`'s by invoking vim with `$ vim -u ~/.vim/vimrc` and `$ vim -u ~/.vim/vimrc2`. Maybe you can help me out here as well.

It actually drives me nuts. I have boiled it down by creating an empty .vim directory and almost empty vimrc:
```
$ tree .vim
.vim
└── vimrc

0 directories, 1 file

$ cat .vim/vimrc
let g:lightline = {
  \ }

$ vim # just fine
$ vim -u .vim/vimrc
Error detected while processing /Users/kiryph/.vim/vimrc:
line    1:
E15: Invalid expression:
E15: Invalid expression: {
line    2:
```

I was trying to test your suggestion in parallel with my old one.

**Comment by kiryph** [comment]
I have figured it out with the help of `http://stackoverflow.com/questions/6696079/vimrc-causes-error-e10-should-be-followed-by-or`. adding `-N` was required.

**Comment by kiryph** [comment]
Can you explain these piece of code
`reltimestr(reltime(b:lightline_fugitive_)) =~# '^\s*0\.[0-5]'`

It looks like as long as the last update time is smaller than 0.5s, the branch is not reloaded.
Is this correct?

**Comment by itchyny** [comment]
Right, you have to `set nocompatible` if you source your vimrc with `-u`. And correct, that code checks the time after the last update time.
