### ISSUE TITLE
Can't figure out how to not display 'unix', 'utf-8' and 'html'

### ISSUE THREAD

**Issue by joetemp** [itchyny/lightline.vim#97]
How can I get rid of these things? I don't really need to see them. Thanks!

**Comment by itchyny** [comment]
Have you see the README? Remove the third element from `g:lightline.active.right`.

**Comment by joetemp** [comment]
Cool, thanks. I didn't see that.

**Comment by GaelanVenturi** [comment]
I've been looking at the README and I see the `g:lightline.active.right`, but I'm still not able to get the correct code to remove the `unix` and `utf-8` from lightline.

**Comment by itchyny** [comment]
```vim
let g:lightline = {
      \ 'active': {
      \   'right': [['lineinfo'], ['percent'], ['filetype']] },
      \ }
```

**Comment by itchyny** [comment]
```vim
let g:lightline = {
      \ 'active': {
      \   'right': [['lineinfo'], ['percent'], ['filetype']],
      \ },
      \ }
```

**Comment by GaelanVenturi** [comment]
Sorry, I tried both versions of the code you typed above and neither removed them from the line.

![Screenshot from 2022-03-01 08-24-58](https://user-images.githubusercontent.com/21958164/156177316-c6d72f5c-760e-4291-aa32-fe875c64bdcb.png)
![Screenshot from 2022-03-01 08-25-29](https://user-images.githubusercontent.com/21958164/156177317-5327ce84-eb1f-43b3-bf0a-926ba8689932.png)

**Comment by itchyny** [comment]
You are overwriting the `g:lightline` value again by `= {}` so remove that line.

**Comment by GaelanVenturi** [comment]
Awesome! Got it

Thank you!
